/*
* FileName "config.js"
* Version: 1.0.0
* Copyright (c) 2023 Pandafirm LLC
* Distributed under the terms of the GNU Lesser General Public License.
* https://opensource.org/licenses/LGPL-2.1
*/
var $jscomp=$jscomp||{};$jscomp.scope={};$jscomp.arrayIteratorImpl=function(f){var d=0;return function(){return d<f.length?{done:!1,value:f[d++]}:{done:!0}}};$jscomp.arrayIterator=function(f){return{next:$jscomp.arrayIteratorImpl(f)}};$jscomp.makeIterator=function(f){var d="undefined"!=typeof Symbol&&Symbol.iterator&&f[Symbol.iterator];if(d)return d.call(f);if("number"==typeof f.length)return $jscomp.arrayIterator(f);throw Error(String(f)+" is not an iterable or ArrayLike");};
$jscomp.arrayFromIterator=function(f){for(var d,b=[];!(d=f.next()).done;)b.push(d.value);return b};$jscomp.arrayFromIterable=function(f){return f instanceof Array?f:$jscomp.arrayFromIterator($jscomp.makeIterator(f))};
window.KintoneBoosterConfig=function(f){var d=this;this.app=location.href.match(/\/m\//g)?kintone.mobile.app.getId():kintone.app.getId();this.subdomain=location.host.split(".")[0];this.cache=null;this.config={size:function(b){return[].concat($jscomp.arrayFromIterable(b)).reduce(function(a,c,e,g){c=c.charCodeAt(0);127>=c?a+=1:2047>=c?a+=2:55296<=c&&57343>=c?(g[e+1]="",a+=4):a+=65535>c?3:4;return a},0)},clear:function(){return new Promise(function(b,a){fetch("https://api.kintone-booster.com/config?id="+
f+"&subdomain="+d.subdomain+"&app="+d.app,{method:"DELETE",headers:{"X-Requested-With":"XMLHttpRequest"}}).then(function(c){c.json().then(function(e){switch(c.status){case 200:b();break;default:kb.alert(kb.error.parse(e)),a()}})})["catch"](function(c){console.log("Failed to connect to the server.");a()})})},get:function(){return new Promise(function(b,a){try{d.cache?b(d.cache):function(c){if(Object.keys(c).exceeded){var e=function(g){fetch("https://api.kintone-booster."+g+"/config?id="+f+"&subdomain="+
d.subdomain+"&app="+d.app,{method:"GET",headers:{"X-Requested-With":"XMLHttpRequest"}}).then(function(k){k.json().then(function(h){switch(k.status){case 200:d.cache="result"in h?"string"===typeof h.result?{}:h.result:{};b(d.cache);break;default:"com"==g?e("net"):(kb.alert(kb.error.parse(h)),a())}})})["catch"](function(k){"com"==g?e("net"):(console.log("Failed to connect to the server."),a())})};e("com")}else d.cache=c,b(d.cache)}(kintone.plugin.app.getConfig(f))}catch(c){kb.alert(kb.error.parse(c)),
a()}})},set:function(b){try{255E3<d.config.size(JSON.stringify(b))?fetch("https://api.kintone-booster.com/config",{method:"PUT",headers:{"X-Requested-With":"XMLHttpRequest"},body:JSON.stringify({id:f,subdomain:d.subdomain,app:d.app,datas:b})}).then(function(a){a.json().then(function(c){switch(a.status){case 200:kintone.plugin.app.setConfig({exceeded:!0});break;default:kb.alert(kb.error.parse(c))}})})["catch"](function(a){console.log("Failed to connect to the server.")}):kintone.plugin.app.setConfig(b)}catch(a){kb.alert(kb.error.parse(a))}}};
this.ui={fields:{conditions:{get:function(b){return{condition:{code:"condition",type:"CONDITION",label:"",required:!1,noLabel:!0,app:{id:kintone.app.getId(),fields:b.parallelize}},device:{code:"device",type:"RADIO_BUTTON",label:"",required:!0,noLabel:!0,options:[{index:0,label:"both"},{index:1,label:"pc"},{index:2,label:"mobile"}]}}},set:function(b,a){return b.append(kb.create("h1").html(kb.constants.config.caption.conditions[kb.operator.language])).append(kb.create("section").append(kb.create("p").html(kb.constants.config.caption.conditions.condition[kb.operator.language])).append(kb.field.activate(kb.field.create(a.fields.condition).css({width:"100%"}),
a))).append(kb.create("section").append(kb.field.activate(function(c){c.elms("[data-name="+a.fields.device.code+"]").each(function(e,g){e.closest("label").elm("span").html(kb.constants.config.caption.conditions.device[e.val()][kb.operator.language])});return c}(kb.field.create(a.fields.device).css({width:"100%"})),a)))}},users:{get:function(b){return{user:{code:"user",type:"USER_SELECT",label:"",required:!1,noLabel:!0,guestuser:!0},organization:{code:"organization",type:"ORGANIZATION_SELECT",label:"",
required:!1,noLabel:!0},group:{code:"group",type:"GROUP_SELECT",label:"",required:!1,noLabel:!0}}},set:function(b,a){return b.append(kb.create("h1").html(kb.constants.config.caption.users[kb.operator.language])).append(kb.create("section").append(kb.create("p").html(kb.constants.config.caption.users.user[kb.operator.language])).append(kb.field.activate(kb.field.create(a.fields.user).css({width:"100%"}),a))).append(kb.create("section").append(kb.create("p").html(kb.constants.config.caption.users.organization[kb.operator.language])).append(kb.field.activate(kb.field.create(a.fields.organization).css({width:"100%"}),
a))).append(kb.create("section").append(kb.create("p").html(kb.constants.config.caption.users.group[kb.operator.language])).append(kb.field.activate(kb.field.create(a.fields.group).css({width:"100%"}),a)))}}},options:{fields:function(b,a,c,e){var g=[{code:"",label:""}];a&&(g=g.concat(Object.values(b.placed).reduce(a,[])));c&&(g=g.concat(Object.values(b.tables).map(function(k){return{code:k.code,label:k.label}})));e&&(g=g.concat(Object.values(b.groups).map(function(k){return{code:k.code,label:k.label}})));
return g}}}};
window.KintoneBoosterConfig.prototype.build=function(f,d,b){var a=this;try{(function(c){c&&(c.parentNode.css({width:"calc(100% - "+c.parentNode.siblings().reduce(function(e,g){return e+g.outerWidth()},16)+"px)"}),c.append(function(e){return c.main=e}(kb.create("main").addClass("kb-config-main"))).append(function(e){return c.footer=e}(kb.create("footer").addClass("kb-config-footer"))),f.submit&&c.footer.append(function(e){switch(kb.operator.language){case "en":e.text("Save");break;case "ja":e.text("\u4fdd\u5b58\u3059\u308b");break;
case "zh":e.text("\u4fdd\u5b58")}return e}(kb.create("button").addClass("kb-config-footer-button kb-config-footer-button-submit").on("click",function(){(function(e){e&&kb.confirm(kb.constants.common.message.confirm.save[kb.operator.language],function(){a.config.set(e)})})(f.submit(c,{}))}))).append(function(e){switch(kb.operator.language){case "en":e.text("Cancel");break;case "ja":e.text("\u30ad\u30e3\u30f3\u30bb\u30eb");break;case "zh":e.text("\u53d6\u6d88")}return e}(kb.create("button").addClass("kb-config-footer-button kb-config-footer-button-cancel").on("click",
function(e){return history.back()}))).append(function(e){switch(kb.operator.language){case "en":e.text("Export configuration file");break;case "ja":e.text("\u8a2d\u5b9a\u30d5\u30a1\u30a4\u30eb\u66f8\u304d\u51fa\u3057");break;case "zh":e.text("\u5bfc\u51fa\u914d\u7f6e\u6587\u4ef6")}return e}(kb.create("button").addClass("kb-config-footer-button kb-config-footer-button-export").on("click",function(e){a.config.get().then(function(g){return kb.downloadText(JSON.stringify(g),"config.json")})["catch"](function(g){})}))).append(function(e){switch(kb.operator.language){case "en":e.text("Import configuration file");
break;case "ja":e.text("\u8a2d\u5b9a\u30d5\u30a1\u30a4\u30eb\u8aad\u307f\u8fbc\u307f");break;case "zh":e.text("\u5bfc\u5165\u914d\u7f6e\u6587\u4ef6")}return e}(kb.create("button").addClass("kb-config-footer-button kb-config-footer-button-import").on("click",function(e){(function(g){kb.elm("body").append(g.on("change",function(k){if(k.currentTarget.files){var h=new FileReader;h.onload=function(l){var m={};try{m=JSON.parse(l.target.result)}catch(n){m={}}finally{a.build(f,d,m)}};h.readAsText(k.currentTarget.files.first())}else document.body.removeChild(g)}));
g.click()})(kb.create("input").attr("type","file").attr("accept",".json").css({display:"none"}))}))),b?d(c,b):a.config.get().then(function(e){return d(c,e)})["catch"](function(e){}))})(kb.elm(".kb-config-container").empty())}catch(c){kb.alert(kb.error.parse(c))}};
window.KintoneBoosterConfigTabbed=function(f,d){var b=this;this.tabs=[];this.callback=d;this.container=f;this.container.main.append(kb.create("div").addClass("kb-hidden kb-config-tabbed-tab-scroller")).append(function(a){b.container.tabs=a;return a.append(kb.create("div").addClass("kb-hidden kb-config-tabbed-tab-guide"))}(kb.create("div").addClass("kb-config-tabbed-tabs"))).append(function(a){return b.container.panels=a}(kb.create("div").addClass("kb-config-tabbed-panels")));(function(a,c){(function(e){var g=
null;g=null;var k=function(h){h=void 0===h?0:h;a.scrollWidth>a.clientWidth?(0<a.scrollLeft+h?e.prev.removeAttr("disabled"):e.prev.attr("disabled","disabled"),a.scrollLeft+h<a.scrollWidth-a.clientWidth?e.next.removeAttr("disabled"):e.next.attr("disabled","disabled"),c.removeClass("kb-hidden")):c.addClass("kb-hidden")};g=new MutationObserver(function(){return k()});g.disconnect();g.observe(a,{childList:!0});g=new ResizeObserver(function(){return k()});g.disconnect();g.observe(a);c.append(e.prev.on("click",
function(h){h=Math.floor(a.clientWidth/-2);k(h);a.scrollBy({left:h})})).append(e.next.on("click",function(h){h=Math.ceil(a.clientWidth/2);k(h);a.scrollBy({left:h})}))})({prev:kb.create("button").addClass("kb-icon kb-icon-arrow kb-icon-arrow-left"),next:kb.create("button").addClass("kb-icon kb-icon-arrow kb-icon-arrow-right")})})(this.container.elm(".kb-config-tabbed-tabs"),this.container.elm(".kb-config-tabbed-tab-scroller"));kb.event.on("kb.drag.start",function(a){var c=a.element,e=b.container.tabs.elm(".kb-config-tabbed-tab-guide"),
g={move:function(k){var h=document.elementFromPoint(k.pageX,k.pageY);if(h&&h!=e){var l=h.getBoundingClientRect();h.hasClass("kb-config-tabbed-tab")&&h.parentNode.insertBefore(e.removeClass("kb-hidden"),k.pageX<l.left+.5*l.width?h:h.nextElementSibling)}},end:function(k){e.visible()?e.parentNode.insertBefore(c.removeClass("kb-hidden"),e.addClass("kb-hidden").nextElementSibling):c.removeClass("kb-hidden");b.tabs=b.container.tabs.elms(".kb-config-tabbed-tab").map(function(h,l){h.removeClass("kb-dragging").index=
l;return h});window.off("mousemove,touchmove",g.move);window.off("mouseup,touchend",g.end);k.stopPropagation();k.preventDefault()}};(function(k){e.css({width:k.width.toString()+"px"});c.addClass("kb-hidden").parentNode.insertBefore(e.removeClass("kb-hidden"),c.nextElementSibling)})(c.getBoundingClientRect());b.tabs.each(function(k,h){k.addClass("kb-dragging")});window.on("mousemove,touchmove",g.move);window.on("mouseup,touchend",g.end)})};
window.KintoneBoosterConfigTabbed.prototype.activate=function(f){this.tabs.each(function(d,b){b==f.index?(d.addClass("kb-activate"),d.panel.show()):(d.removeClass("kb-activate"),d.panel.hide())});return f};
window.KintoneBoosterConfigTabbed.prototype.add=function(f){var d=this;return function(b){var a=function(c){c=c.changedTouches?Array.from(c.changedTouches).first():c;kb.event.call("kb.drag.start",{element:b,page:{x:c.pageX,y:c.pageY}});window.off("touchmove,mousemove",a)};d.container.panels.append(b.panel);kb.isNumeric(f)?(d.container.tabs.insertBefore(b,d.tabs[f].nextElementSibling),d.tabs.splice(f+1,0,b)):(d.container.tabs.append(b),d.tabs.push(b));d.tabs.each(function(c,e){c.index=e});d.callback.add(function(){b.label.html(function(){var c=
"";switch(kb.operator.language){case "en":c="Setting";break;case "ja":c="\u8a2d\u5b9a";break;case "zh":c="\u8bbe\u7f6e"}return c+(d.tabs.filter(function(e){return e.label.html().match(new RegExp("^"+c+"[1-9]{1}[0-9]*$","g"))}).length+1).toString()}());return b}());d.activate(b);b.on("touchstart,mousedown",function(c){window.on("touchmove,mousemove",a);c.stopPropagation();c.preventDefault()}).on("touchend,mouseup",function(c){window.off("touchmove,mousemove",a);d.activate(b);c.stopPropagation();c.preventDefault()});
return b}(function(){var b=kb.create("div").addClass("kb-config-tabbed-tab").append(kb.create("span").addClass("kb-config-tabbed-tab-label").on("dblclick",function(a){a.currentTarget.parentNode.elm(".kb-config-tabbed-tab-prompt").val(a.currentTarget.html()).show("inline-block").focus();a.currentTarget.hide();a.stopPropagation();a.preventDefault()})).append(kb.create("input").attr("type","text").addClass("kb-config-tabbed-tab-prompt").hide().on("touchstart,mousedown",function(a){a.stopPropagation()}).on("blur",
function(a){a.currentTarget.parentNode.elm(".kb-config-tabbed-tab-label").html(a.currentTarget.val()).show("inline-block");a.currentTarget.hide();a.stopPropagation();a.preventDefault()})).append(kb.create("button").addClass("kb-icon kb-icon-add").on("touchstart,mousedown",function(a){a.stopPropagation()}).on("click",function(a){d.add(b.index);a.stopPropagation();a.preventDefault()})).append(kb.create("button").addClass("kb-icon kb-icon-copy").on("touchstart,mousedown",function(a){a.stopPropagation()}).on("click",
function(a){d.add(b.index);switch(kb.operator.language){case "en":d.tabs[b.index+1].label.html(d.tabs[b.index].label.html()+" Copy");break;case "ja":d.tabs[b.index+1].label.html(d.tabs[b.index].label.html()+" \u30b3\u30d4\u30fc");break;case "zh":d.tabs[b.index+1].label.html(d.tabs[b.index].label.html()+" \u590d\u5236")}d.copy(b.index,b.index+1);a.stopPropagation();a.preventDefault()})).append(kb.create("button").addClass("kb-icon kb-icon-del").on("touchstart,mousedown",function(a){a.stopPropagation()}).on("click",
function(a){kb.confirm(kb.constants.common.message.confirm["delete"][kb.operator.language],function(){d.del(b.index)});a.stopPropagation();a.preventDefault()}));b.label=b.elm(".kb-config-tabbed-tab-label");b.panel=kb.create("div").addClass("kb-config-tabbed-panel");return b}())};window.KintoneBoosterConfigTabbed.prototype.copy=function(f,d){this.callback.copy(this.tabs[f],this.tabs[d])};
window.KintoneBoosterConfigTabbed.prototype.del=function(f){var d=this;(function(b){d.container.panels.removeChild(b.panel);d.container.tabs.removeChild(b);d.tabs.splice(f,1);d.tabs.each(function(a,c){a.index=c});d.callback.del(f);0==d.tabs.length?d.add():d.activate(d.tabs[d.tabs.length>f?f:f-1])})(this.tabs[f])};"undefined"===typeof kb.config&&(kb.config={});kb.config[kintone.$PLUGIN_ID]=new KintoneBoosterConfig(kintone.$PLUGIN_ID);
kb.constants=kb.extend({config:{caption:{conditions:{en:"Conditions for operation",ja:"\u52d5\u4f5c\u6761\u4ef6",zh:"\u64cd\u4f5c\u7684\u6761\u4ef6",condition:{en:"Please specify the conditions for the record to be executable with the set content.",ja:"\u8a2d\u5b9a\u3057\u305f\u5185\u5bb9\u3092\u5b9f\u884c\u51fa\u6765\u308b\u30ec\u30b3\u30fc\u30c9\u306e\u6761\u4ef6\u3092\u6307\u5b9a\u3057\u3066\u4e0b\u3055\u3044\u3002",zh:"\u8bf7\u6307\u5b9a\u5177\u6709\u6240\u8bbe\u7f6e\u5185\u5bb9\u7684\u8bb0\u5f55\u7684\u53ef\u6267\u884c\u6761\u4ef6\u3002"},
device:{both:{en:"Execute on both PC and mobile versions",ja:"PC\u7248\u3068\u30e2\u30d0\u30a4\u30eb\u7248\u306e\u4e21\u65b9\u3067\u5b9f\u884c",zh:"\u5728PC\u548c\u79fb\u52a8\u7248\u672c\u4e0a\u90fd\u6267\u884c"},mobile:{en:"Execute on mobile version only",ja:"\u30e2\u30d0\u30a4\u30eb\u7248\u306e\u307f\u3067\u5b9f\u884c",zh:"\u4ec5\u5728\u79fb\u52a8\u7248\u672c\u4e0a\u6267\u884c"},pc:{en:"Execute on PC version only",ja:"PC\u7248\u306e\u307f\u3067\u5b9f\u884c",zh:"\u4ec5\u5728PC\u7248\u672c\u4e0a\u6267\u884c"}}},
users:{en:"Authorized users",ja:"\u8a31\u53ef\u30e6\u30fc\u30b6\u30fc",zh:"\u83b7\u5f97\u6388\u6743\u7684\u7528\u6237",group:{en:"In addition to the operational conditions, if you want to determine the execution permission based on the group the logged-in user belongs to, please specify the group to be permitted.",ja:"\u52d5\u4f5c\u6761\u4ef6\u306b\u52a0\u3048\u3001\u30ed\u30b0\u30a4\u30f3\u30e6\u30fc\u30b6\u30fc\u304c\u6240\u5c5e\u3059\u308b\u30b0\u30eb\u30fc\u30d7\u3092\u5b9f\u884c\u8a31\u53ef\u306e\u5224\u65ad\u3068\u3057\u305f\u3044\u5834\u5408\u306f\u3001\u8a31\u53ef\u3059\u308b\u30b0\u30eb\u30fc\u30d7\u3092\u6307\u5b9a\u3057\u3066\u4e0b\u3055\u3044\u3002",
zh:"\u9664\u4e86\u64cd\u4f5c\u6761\u4ef6\u5916\uff0c\u5982\u679c\u60a8\u60f3\u6839\u636e\u767b\u5f55\u7528\u6237\u6240\u5c5e\u7684\u7ec4\u6765\u51b3\u5b9a\u6267\u884c\u6743\u9650\uff0c\u8bf7\u6307\u5b9a\u5141\u8bb8\u7684\u7ec4\u3002"},organization:{en:"In addition to the operational conditions, if you want to determine the execution permission based on the organization the logged-in user belongs to, please specify the organization to be permitted.",ja:"\u52d5\u4f5c\u6761\u4ef6\u306b\u52a0\u3048\u3001\u30ed\u30b0\u30a4\u30f3\u30e6\u30fc\u30b6\u30fc\u304c\u6240\u5c5e\u3059\u308b\u7d44\u7e54\u3092\u5b9f\u884c\u8a31\u53ef\u306e\u5224\u65ad\u3068\u3057\u305f\u3044\u5834\u5408\u306f\u3001\u8a31\u53ef\u3059\u308b\u7d44\u7e54\u3092\u6307\u5b9a\u3057\u3066\u4e0b\u3055\u3044\u3002",
zh:"\u9664\u4e86\u64cd\u4f5c\u6761\u4ef6\u5916\uff0c\u5982\u679c\u60a8\u60f3\u6839\u636e\u767b\u5f55\u7528\u6237\u6240\u5c5e\u7684\u7ec4\u7ec7\u6765\u51b3\u5b9a\u6267\u884c\u6743\u9650\uff0c\u8bf7\u6307\u5b9a\u5141\u8bb8\u7684\u7ec4\u7ec7\u3002"},user:{en:"In addition to the operational conditions, if you want to determine the execution permission based on the logged-in user, please specify the user to be permitted.",ja:"\u52d5\u4f5c\u6761\u4ef6\u306b\u52a0\u3048\u3001\u30ed\u30b0\u30a4\u30f3\u30e6\u30fc\u30b6\u30fc\u3092\u5b9f\u884c\u8a31\u53ef\u306e\u5224\u65ad\u3068\u3057\u305f\u3044\u5834\u5408\u306f\u3001\u8a31\u53ef\u3059\u308b\u30e6\u30fc\u30b6\u30fc\u3092\u6307\u5b9a\u3057\u3066\u4e0b\u3055\u3044\u3002",
zh:"\u9664\u4e86\u64cd\u4f5c\u6761\u4ef6\u5916\uff0c\u5982\u679c\u60a8\u60f3\u6839\u636e\u767b\u5f55\u7528\u6237\u6765\u51b3\u5b9a\u6267\u884c\u6743\u9650\uff0c\u8bf7\u6307\u5b9a\u5141\u8bb8\u7684\u7528\u6237\u3002"}}}}},kb.constants);