/*
* FileName "plugins.cascade.js"
* Version: 1.0.0
* Copyright (c) 2023 Pandafirm LLC
* Distributed under the terms of the GNU Lesser General Public License.
* https://opensource.org/licenses/LGPL-2.1
*/
'use strict';(B=>{var a={handlers:{}},E=(h,f,F,w="record",z="detail")=>{var r=(()=>{var n={},A=0;if("record"==w)for(var t in f)t in a.fieldInfos.tables&&f[t].value.each((c,m)=>{null==c.id&&(A++,c.id=A);n[c.id]=m},{});return n})();return new Promise((n,A)=>{var t=(c,m)=>{var v=l=>(b=>new Kuc.Dropdown({className:"control-gaia",items:[{label:"-----",value:""}].concat(Object.values(b.options).reduce((d,u)=>{d[u.index]=u;return d},Array(Object.values(b.options).length).fill("")).map(d=>({label:d.label,value:d.label}))),
label:b.noLabel||b.tableCode?"":b.label,requiredIcon:b.required}))(a.fieldInfos.parallelize[l.child.value]),C=(l,b)=>{var d=Object.keys(a.fieldInfos.parallelize[l.child.value].options);if(Array.isArray(b[l.parent.value].value)?0!=b[l.parent.value].value.length:b[l.parent.value].value)d=(Array.isArray(b[l.parent.value].value)?b[l.parent.value].value:[b[l.parent.value].value]).reduce((u,p)=>u=[...(new Set([...u,...l.relation.value[p]]))],[]);return d},G=l=>null==l||!1===l?"":String(l),x=l=>Array.from(l.childNodes).map(b=>
b.nodeType===Node.TEXT_NODE?b.nodeValue.trim():b.nodeType===Node.ELEMENT_NODE?x(b):"").join("");(l=>{(b=>{switch(w){case "record":b.parent.tableCode?b.parent.tableCode in f&&(d=>{(u=>{if(kb.elms(u).length!=f[b.parent.tableCode].value.length){let p=new MutationObserver(()=>{kb.elms(u).length==f[b.parent.tableCode].value.length&&(d(),p.disconnect())});p.observe(kb.elm(".subtable-"+a.fieldInfos.tables[b.parent.tableCode].id),{childList:!0,subtree:!0})}else d()})(".subtable-"+a.fieldInfos.tables[b.parent.tableCode].id+
(a.mobile?" .subtable-row-gaia":" tbody tr"))})(()=>{f[b.parent.tableCode].value.each((d,u)=>{b.parent.code in d.value&&(p=>{p&&(e=>{var k="";switch(a.fieldInfos.parallelize[b.child.code].type){case "CHECK_BOX":k=a.mobile?".checkbox-gaia":".input-checkbox-item-cybozu";break;case "DROP_DOWN":a.mobile?k="option":(g=>{if(!g.nextSibling||!g.nextSibling.tagName.toLowerCase().startsWith("kuc")){g.hide().insertAdjacentElement("afterend",v(l));let q=new MutationObserver(()=>{g.nextSibling.elms("[role=option]").each((y,
D)=>{y.attr("value")&&!e.includes(x(y))&&y.addClass("kb-cascade-disabled")});kb.event.call("kb.style.color.call",{field:g});kb.event.call("kb.style.display.call",{field:g});kb.event.call("kb.style.editable.call",{field:g});q.disconnect()});q.observe(g.nextSibling,{childList:!0,subtree:!0})}(q=>{q.handler&&q.removeEventListener("change",q.handler);q.handler=y=>{var D=(a.mobile?kintone.mobile.app.record:kintone.app.record).get();D.record[b.parent.tableCode].value[r[d.id]].value[b.child.code].value=
y.detail.value;(a.mobile?kintone.mobile.app.record:kintone.app.record).set(D)};q.addEventListener("change",q.handler);q.elms("[role=option]").each((y,D)=>{y.attr("value")&&!e.includes(x(y))&&y.addClass("kb-cascade-disabled")});q.value=G(f[b.parent.tableCode].value[r[d.id]].value[b.child.code].value)})(g.nextSibling)})(p[r[d.id]]);break;case "MULTI_SELECT":k=a.mobile?"option":".goog-menuitem";break;case "RADIO_BUTTON":k=a.mobile?".radio-gaia":".input-radio-item-cybozu"}k&&("option"==k?(p[r[d.id]].value.elms(k).each((g,
q)=>{"span"==g.parentNode.tagName.toLowerCase()&&(q=g.parentNode,g.closest("select").insertBefore(g,q),g.closest("select").removeChild(q))}),p[r[d.id]].value.elms(k).each((g,q)=>{g.attr("value")&&!e.includes(x(g))&&"span"!=g.parentNode.tagName.toLowerCase()&&(q=kb.create("span").addClass("kb-cascade-disabled"),g.parentNode.insertBefore(q,g),q.append(g))})):p[r[d.id]].value.elms(k).each((g,q)=>{e.includes(x(g))||g.addClass("kb-cascade-disabled")}))})(C(l,d.value))})(kb.field.get(b.child,a.mobile,a.type||
z))})}):b.parent.code in f&&(d=>{d&&(u=>{var p="";switch(a.fieldInfos.parallelize[b.child.code].type){case "CHECK_BOX":p=a.mobile?".checkbox-gaia":".input-checkbox-item-cybozu";break;case "DROP_DOWN":if(a.mobile)p="option";else{if(!d.nextSibling||!d.nextSibling.tagName.toLowerCase().startsWith("kuc")){d.hide().insertAdjacentElement("afterend",v(l));let e=new MutationObserver(()=>{d.nextSibling.elms("[role=option]").each((k,g)=>{k.attr("value")&&!u.includes(x(k))&&k.addClass("kb-cascade-disabled")});
e.disconnect()});e.observe(d.nextSibling,{childList:!0,subtree:!0})}(e=>{e.handler&&e.removeEventListener("change",e.handler);e.handler=k=>{var g=(a.mobile?kintone.mobile.app.record:kintone.app.record).get();g.record[b.child.code].value=k.detail.value;(a.mobile?kintone.mobile.app.record:kintone.app.record).set(g)};e.addEventListener("change",e.handler);e.elms("[role=option]").each((k,g)=>{k.attr("value")&&!u.includes(x(k))&&k.addClass("kb-cascade-disabled")});e.value=G(f[b.child.code].value)})(d.nextSibling)}break;
case "MULTI_SELECT":p=a.mobile?"option":".goog-menuitem";break;case "RADIO_BUTTON":p=a.mobile?".radio-gaia":".input-radio-item-cybozu"}p&&("option"==p?(d.value.elms(p).each((e,k)=>{"span"==e.parentNode.tagName.toLowerCase()&&(k=e.parentNode,e.closest("select").insertBefore(e,k),e.closest("select").removeChild(k))}),d.value.elms(p).each((e,k)=>{e.attr("value")&&!u.includes(x(e))&&"span"!=e.parentNode.tagName.toLowerCase()&&(k=kb.create("span").addClass("kb-cascade-disabled"),e.parentNode.insertBefore(k,
e),k.append(e))})):d.value.elms(p).each((e,k)=>{u.includes(x(e))||e.addClass("kb-cascade-disabled")}))})(C(l,f))})(kb.field.get(b.child,a.mobile,a.type||z));break;case "view":b.parent.tableCode?b.parent.tableCode in f&&f[b.parent.tableCode].value.each((d,u)=>{b.parent.code in d.value&&(d.value[b.child.code].options=C(l,d.value))}):b.parent.code in f&&(f[b.child.code].options=C(l,f))}})({parent:a.fieldInfos.parallelize[l.parent.value],child:a.fieldInfos.parallelize[l.child.value]});c++;c<h.length?
t(c,m):m()})(h[c])};"record"==w&&kb.elms(".kb-cascade-disabled").each((c,m)=>{c.removeClass("kb-cascade-disabled")});t(0,()=>n())})};kintone.events.on(["app.record.create.show","app.record.edit.show","mobile.app.record.create.show","mobile.app.record.edit.show"],h=>new Promise((f,F)=>{((w,z)=>{a.mobile=w;a.type=z;for(var r in a.handlers)a.handlers[r].each((n,A)=>{kintone.events.off(r,n)});kb.config[B].config.get().then(n=>{0!=Object.keys(n).length?kb.field.load(kb.config[B].app,!0).then(A=>{a.app=
{id:kb.config[B].app,fields:A.origin};a.fieldInfos=A;try{(t=>{0!=t.length&&(((c,m)=>{kintone.events.on(c,m);c.each((v,C)=>{v in a.handlers||(a.handlers[v]=[]);a.handlers[v].push(m)})})(t.reduce((c,m)=>{c.push("app.record.create.change."+m.parent.value);c.push("app.record.edit.change."+m.parent.value);c.push("mobile.app.record.create.change."+m.parent.value);c.push("mobile.app.record.edit.change."+m.parent.value);var v=a.fieldInfos.parallelize[m.parent.value].tableCode;v&&(c.push("app.record.create.change."+
v),c.push("app.record.edit.change."+v),c.push("mobile.app.record.create.change."+v),c.push("mobile.app.record.edit.change."+v));switch(a.fieldInfos.parallelize[m.child.value].type){case "DROP_DOWN":c.push("app.record.create.change."+m.child.value),c.push("app.record.edit.change."+m.child.value),c.push("mobile.app.record.create.change."+m.child.value),c.push("mobile.app.record.edit.change."+m.child.value)}return[...(new Set([...c]))]},[]),c=>{kb.event.call("kb.action.installed.change",{installed:!1,
mobile:a.mobile}).then(m=>{m.installed||E(t,c.record,kb.elm("body"),"record").then(v=>{}).catch(()=>{})});return c}),kb.event.call("kb.action.installed.show",{installed:!1,mobile:a.mobile}).then(c=>{c.installed?f(h):E(t,h.record,kb.elm("body"),"record").then(m=>f(h)).catch(()=>{})}))})(JSON.parse(n.tab).map((t,c)=>kb.extend({sIndex:{value:c.toString()}},t.setting)).reduce((t,c)=>{(a.mobile?["all","both","mobile"]:["all","both","pc"]).includes(c.device.value)&&c.parent.value in a.fieldInfos.parallelize&&
c.child.value in a.fieldInfos.parallelize&&(c.relation.value=JSON.parse(c.relation.value),t.push(c));return t},[]))}catch(t){kb.alert(kb.error.parse(t)),f(h)}}).catch(A=>f(h)):f(h)}).catch(n=>f(h))})("mobile"==h.type.split(".").first(),h.type.split(".").slice(-2).first())}));kb.event.on("kb.cascade.call",h=>new Promise((f,F)=>{["create","edit"].includes(h.pattern)?kb.config[B].config.get().then(w=>{0!=Object.keys(w).length?kb.field.load(kb.config[B].app,!0).then(z=>{a.app={id:kb.config[B].app,fields:z.origin};
a.fieldInfos=z;a.mobile="mobile"in a?a.mobile:h.mobile;try{(r=>{0!=r.length?E(r,h.record,h.container,h.workplace?h.workplace:"record",h.pattern).then(n=>f(h)).catch(()=>f(h)):f(h)})(JSON.parse(w.tab).map((r,n)=>kb.extend({sIndex:{value:n.toString()}},r.setting)).reduce((r,n)=>{(h.mobile?["all","both","mobile"]:["all","both","pc"]).includes(n.device.value)&&n.parent.value in a.fieldInfos.parallelize&&n.child.value in a.fieldInfos.parallelize&&(n.relation.value=JSON.parse(n.relation.value),r.push(n));
return r},[]))}catch(r){kb.alert(kb.error.parse(r)),f(h)}}).catch(z=>f(h)):f(h)}).catch(w=>f(h)):f(h)}))})(kintone.$PLUGIN_ID);
