/*
* FileName "plugins.style.js"
* Version: 1.0.0
* Copyright (c) 2023 Pandafirm LLC
* Distributed under the terms of the GNU Lesser General Public License.
* https://opensource.org/licenses/LGPL-2.1
*/
(function(u){var c={},z=function(e,h,n){n=void 0===n?"record":n;var r=!1,q=function(){var k={},l=0;if("record"==n)for(var m in h)m in c.fieldInfos.tables&&h[m].value.each(function(f,p){null==f.id&&(l++,f.id=l);k[f.id]=p},{});return k}();return new Promise(function(k,l){var m=function(f,p){var A=function(){f++;f<e.length?m(f,p):p()};(function(t){var g=kb.filter.scan(c.app,h,t.condition.value);g?kb.filter.auth(t.user.value,t.organization.value,t.group.value).then(function(x){x&&(t.color.value.map(function(b){return b.value}).each(function(b,
y){b.field.value in c.fieldInfos.parallelize&&function(a){switch(n){case "record":a.tableCode?a.tableCode in g&&function(d){if(c.mobile)d();else if(kb.elms(".subtable-"+c.fieldInfos.tables[a.tableCode].id+" tbody tr").length!=h[a.tableCode].value.length){var v=new MutationObserver(function(){kb.elms(".subtable-"+c.fieldInfos.tables[a.tableCode].id+" tbody tr").length==h[a.tableCode].value.length&&(d(),v.disconnect())});v.observe(kb.elm(".subtable-"+c.fieldInfos.tables[a.tableCode].id),{childList:!0,
subtree:!0})}else d()}(function(){g[a.tableCode].value.each(function(d,v){if(a.code in d.value){var w=kb.field.get(a,c.mobile,c.type);w&&(w[q[d.id]].value.css({backgroundColor:b.backcolor.value,color:b.forecolor.value}),b.backcolor.value?w[q[d.id]].value.addClass("kb-inherit-backcolor"):w[q[d.id]].value.removeClass("kb-inherit-backcolor"),b.forecolor.value?w[q[d.id]].value.addClass("kb-inherit-forecolor"):w[q[d.id]].value.removeClass("kb-inherit-forecolor"))}})}):a.code in g&&function(d){d&&(d.value.css({backgroundColor:b.backcolor.value,
color:b.forecolor.value}),b.backcolor.value?d.value.addClass("kb-inherit-backcolor"):d.value.removeClass("kb-inherit-backcolor"),b.forecolor.value?d.value.addClass("kb-inherit-forecolor"):d.value.removeClass("kb-inherit-forecolor"))}(kb.field.get(a,c.mobile,c.type));break;case "view":a.tableCode?a.tableCode in g&&g[a.tableCode].value.each(function(d,v){a.code in d.value&&(d.value[a.code].backcolor=b.backcolor.value,d.value[a.code].forecolor=b.forecolor.value)}):a.code in g&&(g[a.code].backcolor=b.backcolor.value,
g[a.code].forecolor=b.forecolor.value)}}(c.fieldInfos.parallelize[b.field.value])}),t.display.value.map(function(b){return b.value}).each(function(b,y){switch(n){case "record":(c.mobile?kintone.mobile.app.record:kintone.app.record).setFieldShown(b.field.value,"show"==b.state.value);break;case "view":b.field.value in c.fieldInfos.groups?c.fieldInfos.groups[b.field.value].fields.map(function(a){return a.code}).each(function(a,d){a in c.fieldInfos.parallelize&&a in g&&(g[a].hidden="hide"==b.state.value)}):
b.field.value in c.fieldInfos.tables?b.field.value in g&&(g[b.field.value].hidden="hide"==b.state.value):function(a){a.tableCode?a.tableCode in g&&g[a.tableCode].value.each(function(d,v){a.code in d.value&&(d.value[a.code].hidden="hide"==b.state.value)}):a.code in g&&(g[a.code].hidden="hide"==b.state.value)}(c.fieldInfos.parallelize[b.field.value])}}),t.toggle.value.map(function(b){return b.value}).each(function(b,y){switch(n){case "record":(c.mobile?kintone.mobile.app.record:kintone.app.record).setGroupFieldOpen(b.field.value,
"open"==b.state.value)}}),["create","edit"].includes(c.type)&&t.editable.value.map(function(b){return b.value}).each(function(b,y){b.field.value in c.fieldInfos.parallelize&&function(a){c.fieldInfos.disables.includes(a.code)||(a.tableCode?a.tableCode in g&&g[a.tableCode].value.each(function(d,v){a.code in d.value&&(d.value[a.code].disabled="disable"==b.state.value,"record"==n&&(r=!0))}):a.code in g&&(g[a.code].disabled="disable"==b.state.value,"record"==n&&(r=!0)))}(c.fieldInfos.parallelize[b.field.value])}));
A()})["catch"](function(x){return kb.alert(kb.error.parse(x))}):A()})(e[f])};m(0,function(){return k({performed:r})})})};kintone.events.on("app.record.create.show app.record.detail.show app.record.edit.show app.record.print.show mobile.app.record.create.show mobile.app.record.detail.show mobile.app.record.edit.show".split(" "),function(e){return new Promise(function(h,n){(function(r,q){c.mobile=r;c.type=q;kb.config[u].config.get().then(function(k){0!=Object.keys(k).length?(e.reuse&&function(l){"reusecolor"in
l&&l.reusecolor.value&&kintone.app.record.getHeaderMenuSpaceElement().nextSibling.firstElementChild.css({backgroundColor:l.reusecolor.value})}(JSON.parse(k.flat)),kb.field.load(kb.config[u].app,!0).then(function(l){c.app={id:kb.config[u].app,fields:l.origin};c.fieldInfos=l;try{(function(m){if(0!=m.length){if(["create","edit"].includes(c.type))kintone.events.on(l.changes.reduce(function(f,p){f.push("app.record.create.change."+p);f.push("app.record.edit.change."+p);f.push("mobile.app.record.create.change."+
p);f.push("mobile.app.record.edit.change."+p);return f},[]),function(f){z(m,f.record,"record").then(function(p){p.performed&&(c.mobile?kintone.mobile.app.record:kintone.app.record).set(f)});return f});z(m,e.record,"record").then(function(f){return h(e)})}else h(e)})(JSON.parse(k.tab).reduce(function(m,f){(c.mobile?["both","mobile"]:["both","pc"]).includes(f.setting.device.value)&&f.setting.page.value.includes(c.type)&&m.push(f.setting);return m},[]))}catch(m){kb.alert(kb.error.parse(m)),h(e)}})["catch"](function(l){return h(e)})):
h(e)})["catch"](function(k){return h(e)})})("mobile"==e.type.split(".").first(),e.type.split(".").slice(-2).first())})});kb.event.on("kb.style.call",function(e){return new Promise(function(h,n){kb.config[u].config.get().then(function(r){0!=Object.keys(r).length?kb.field.load(kb.config[u].app,!0).then(function(q){c.app={id:kb.config[u].app,fields:q.origin};c.fieldInfos=q;try{(function(k){0!=k.length?z(k,e.record,e.workplace?e.workplace:"record").then(function(l){return h(e)}):h(e)})(JSON.parse(r.tab).reduce(function(k,
l){(e.mobile?["both","mobile"]:["both","pc"]).includes(l.setting.device.value)&&l.setting.page.value.includes(e.pattern)&&k.push(l.setting);return k},[]))}catch(k){kb.alert(kb.error.parse(k)),h(e)}})["catch"](function(q){return h(e)}):h(e)})["catch"](function(r){return h(e)})})})})(kintone.$PLUGIN_ID);