/*
* FileName "plugins.linkage.js"
* Version: 1.0.0
* Copyright (c) 2023 Pandafirm LLC
* Distributed under the terms of the GNU Lesser General Public License.
* https://opensource.org/licenses/LGPL-2.1
*/
'use strict';(G=>{var c={handlers:{}},J=(l,y)=>new Promise((H,B)=>{kb.field.load(l.app.value).then(t=>{(A=>{l.criteria.value.some(p=>!(p.value.external.value in A.external&&p.value.internal.value in A.internal))?(kb.alert("No field to linkage was found"),B()):l.mapping.value.some(p=>!(p.value.external.value in A.external))?(kb.alert("No field to linkage was found"),B()):(p=>{kb.view.records.get(l.app.value,p).then(u=>{u.length!=0?((m,r)=>{H((w=>{w.records.sort((e,a)=>{var q=0;l.sort.value.each((b,
d)=>{switch(t.parallelize[b.value.field.value].type){case "CALC":switch(t.parallelize[b.value.field.value].format){case "NUMBER":case "NUMBER_DIGIT":d=e[b.value.field.value].value?parseFloat(e[b.value.field.value].value):0;var h=a[b.value.field.value].value?parseFloat(a[b.value.field.value].value):0;break;default:d=e[b.value.field.value].value,h=a[b.value.field.value].value}break;case "CATEGORY":case "CHECK_BOX":case "CREATOR":case "FILE":case "GROUP_SELECT":case "MODIFIER":case "MULTI_SELECT":case "ORGANIZATION_SELECT":case "STATUS_ASSIGNEE":case "USER_SELECT":d=
JSON.stringify(e[b.value.field.value].value);h=JSON.stringify(a[b.value.field.value].value);break;case "NUMBER":d=e[b.value.field.value].value?parseFloat(e[b.value.field.value].value):0;h=a[b.value.field.value].value?parseFloat(a[b.value.field.value].value):0;break;default:d=e[b.value.field.value].value,h=a[b.value.field.value].value}switch(b.value.order.value){case "asc":d>h&&(q=1);d<h&&(q=-1);break;case "desc":d>h&&(q=-1),d<h&&(q=1)}if(q)return KB_BREAK});return q});return w})(m.reduce((w,e)=>{Array(r?
e[r].value.length:1).fill().map(()=>({})).each((a,q)=>{a.$id=e.$id;for(var b in t.parallelize)t.parallelize[b].tableCode?t.parallelize[b].tableCode==r&&(a[b]=e[r].value[q].value[b]):a[b]=e[b];w.records.push(a)});return w},{offset:0,records:[]})))})(u.reduce((m,r)=>{(r=kb.filter.scan({fields:t.origin},r,p))&&m.push(r);return m},[]),Array.from(new Set(l.mapping.value.map(m=>t.parallelize[m.value.external.value].tableCode))).join("")):H({offset:0,records:[]})}).catch(u=>{kb.alert(kb.error.parse(u));
B()})})(l.criteria.value.reduce((p,u)=>{p.push(kb.filter.query.create(A.external[u.value.external.value],u.value.operator.value,y[u.value.internal.value]));return p},kb.filter.query.parse.expand({id:l.app.value,fields:t.origin},l.filter.value).map(p=>p.field+" "+p.operator+" "+p.value)).join(" and "))})({external:t.parallelize,internal:c.fieldInfos.parallelize})}).catch(t=>{kb.alert(kb.error.parse(t));B()})});kintone.events.on("app.record.create.show app.record.detail.show app.record.edit.show app.record.index.show mobile.app.record.create.show mobile.app.record.detail.show mobile.app.record.edit.show mobile.app.record.index.show".split(" "),
l=>new Promise((y,H)=>{((B,t)=>{c.mobile=B;c.type=t;for(var A in c.handlers)c.handlers[A].each((p,u)=>{kintone.events.off(A,p)});kb.config[G].config.get().then(p=>{Object.keys(p).length!=0?kb.field.load(kb.config[G].app,!0).then(u=>{c.app={id:kb.config[G].app,fields:u.origin};c.fieldInfos=u;try{(m=>{if(m.length!=0){var r=(e,a,q)=>{var b=(d=>Array.from(new Set(d.map(h=>c.fieldInfos.parallelize[h.value.internal.value].tableCode))).reduce((h,k)=>{a[k].value=[];h[k]={fields:d.filter(f=>c.fieldInfos.parallelize[f.value.internal.value].tableCode==
k),row:kb.record.create(c.fieldInfos.origin[k],!1)};return h},{}))(e.mapping.value.reduce((d,h)=>{h.value.internal.value in c.fieldInfos.parallelize&&d.push(h);return d},[]));q.each((d,h)=>{for(var k in b)a[k].value.push((f=>{b[k].fields.each((x,z)=>{if(x.value.internal.value in c.fieldInfos.parallelize)switch(c.fieldInfos.parallelize[x.value.internal.value].type){case "lookup":z=d[x.value.external.value];f[x.value.internal.value]={lookup:!0,search:"search"in z?z.search:"",value:z.value};break;default:f[x.value.internal.value].value=
d[x.value.external.value].value}});return{value:f}})(kb.extend({},b[k].row)))});return a};c.mobile&&kb.elm("body").addClass("kb-mobile");switch(c.type){case "create":case "edit":case "detail":var w=e=>{(a=>{(q=>{q&&kb.field.load(a.app.value).then(b=>{(d=>{((h,k)=>{var f={},x=kb.create("button").addClass("kb-linkage-container-button").html(a.label.value).on("click",n=>{kb.confirm(a.message.value,()=>{kb.event.call("kb.action.call",{container:kb.elm("body"),record:r(a,(c.mobile?kintone.mobile.app.record:
kintone.app.record).get().record,f.records),mobile:c.mobile,pattern:"change",fields:(g=>g.reduce((v,D)=>v=v.concat(Object.keys(c.fieldInfos.tables[D].fields)),g))(a.mapping.value.reduce((g,v)=>{v.value.internal.value in c.fieldInfos.parallelize&&g.push(c.fieldInfos.parallelize[v.value.internal.value].tableCode);return g},[])),stopPropagation:!0,workplace:"record"}).then(g=>{kb.event.call("kb.style.call",{container:g.container,record:g.record,mobile:g.mobile,pattern:"$id"in g.record?g.record.$id.value?
"edit":"create":"create",workplace:g.workplace}).then(v=>{(c.mobile?kintone.mobile.app.record:kintone.app.record).set({record:v.record})}).catch(()=>{})}).catch(()=>{})})}),z=kb.create("button").addClass("kb-icon kb-icon-arrow kb-icon-arrow-left").on("click",n=>{f.offset-=k;E()}),F=kb.create("button").addClass("kb-icon kb-icon-arrow kb-icon-arrow-right").on("click",n=>{f.offset+=k;E()}),K=kb.create("button").addClass("kb-icon kb-icon-reload").on("click",n=>{I((c.mobile?kintone.mobile.app.record:kintone.app.record).get().record)}),
C=kb.create("span").addClass("kb-linkage-container-monitor").html(""),E=()=>{var n=f.records.slice(f.offset,f.offset+k);h.clearRows();n.each((g,v)=>{(D=>{kb.record.set(D.elm("[form-id=form_"+d.id+"]"),d,g).then(()=>{D.elm(".kb-view-row-edit").attr("href",kb.record.page.detail(c.mobile,d.id,g.$id.value)).attr("target","_blank");v==n.length-1&&q.parentNode.show()})})(h.addRow())});switch(kb.operator.language){case "en":C.html(f.records.length.toString()+"records in total");break;case "ja":C.html("\u7dcf"+
f.records.length.toString()+"\u884c");break;case "zh":C.html("\u5171"+f.records.length.toString()+"\u6761\u8bb0\u5f55");break;case "zh-TW":C.html("\u5171"+f.records.length.toString()+"\u7b46\u8a18\u9304")}f.offset>0?z.removeAttr("disabled"):z.attr("disabled","disabled");f.offset+(k==n.length?k:n.length)<f.records.length?F.removeAttr("disabled"):F.attr("disabled","disabled")},I=n=>{J(a,n).then(g=>{f=g;E()}).catch(()=>{f={offset:0,records:[]};E()})};switch(c.type){case "create":case "edit":q.append(kb.create("div").addClass("kb-linkage-container-footer").append(C).append(K).append(z).append(F).append(x));
break;case "detail":q.append(kb.create("div").addClass("kb-linkage-container-footer").append(C).append(K).append(z).append(F))}((n,g)=>{kintone.events.on(n,g);n.each((v,D)=>{v in c.handlers||(c.handlers[v]=[]);c.handlers[v].push(g)})})(a.criteria.value.reduce((n,g)=>{n.push("app.record.create.change."+g.value.internal.value);n.push("app.record.edit.change."+g.value.internal.value);n.push("mobile.app.record.create.change."+g.value.internal.value);n.push("mobile.app.record.edit.change."+g.value.internal.value);
return n},[]),n=>I(n.record));I(l.record)})(kb.view.create(q.addClass("kb-linkage-container"),d,d.view.id,c.mobile).elm(".kb-view"),parseInt(a.limit.value))})({id:a.app.value,disables:[],fields:b.parallelize,view:{id:"linkage_"+a.app.value+"_"+a.container.value,buttons:["delete"],fields:a.mapping.value.map(d=>d.value.external.value),mode:"viewer"}})}).catch(()=>{})})((c.mobile?kintone.mobile.app.record:kintone.app.record).getSpaceElement(a.container.value));e++;e<m.length&&w(e)})(m[e])};w(0);y(l);
break;case "index":w=e=>{(a=>{kb.filter.auth(a.user.value,a.organization.value,a.group.value).then(q=>{q&&(a.view.value&&a.view.value!=l.viewId.toString()||kb.button.create(c.mobile,c.type,"kb-linkage-button"+e.toString(),a.label.value,a.message.value,()=>{kb.view.records.get(c.app.id,(c.mobile?kintone.mobile.app:kintone.app).getQueryCondition()).then(b=>{var d=[];let h=(k,f)=>{J(a,b[k]).then(x=>{d.push(kb.view.records.transform(r(a,b[k],x.records)));kb.progressUpdate();k++;k<b.length?h(k,f):f()}).catch(()=>
{})};b.length!=0?(kb.progressStart(b.length),h(0,()=>{kb.view.records.set(c.app.id,{put:d}).then(k=>kb.alert("Done!",()=>window.location.reload(!0))).catch(k=>kb.alert(kb.error.parse(k)))})):kb.alert("There are no records.")}).catch(b=>kb.alert(kb.error.parse(b)))}));e++;e<m.length&&w(e)}).catch(q=>{e++;e<m.length&&w(e)})})(m[e])},w(0),y(l)}}else y(l)})(JSON.parse(p.tab).map((m,r)=>kb.extend({sIndex:{value:r.toString()}},m.setting)).reduce((m,r)=>{switch(c.type){case "index":r.bulk.value.includes("bulk")&&
m.push(r);break;default:m.push(r)}return m},[]))}catch(m){kb.alert(kb.error.parse(m)),y(l)}}).catch(u=>y(l)):y(l)}).catch(p=>y(l))})(l.type.split(".").first()=="mobile",l.type.split(".").slice(-2).first())}))})(kintone.$PLUGIN_ID);