/*
* FileName "plugins.mail.js"
* Version: 1.0.0
* Copyright (c) 2023 Pandafirm LLC
* Distributed under the terms of the GNU Lesser General Public License.
* https://opensource.org/licenses/LGPL-2.1
*/
(function(n){var q,g,h,k=function(a,c){return new Promise(function(r,e){r()})};kintone.events.on("app.record.create.submit.success app.record.detail.process.proceed app.record.detail.show app.record.edit.submit.success app.record.index.show mobile.app.record.create.submit.success mobile.app.record.detail.process.proceed mobile.app.record.detail.show mobile.app.record.edit.submit.success mobile.app.record.index.show".split(" "),function(a){return new Promise(function(c,r){(function(e,v){g=e;h=v;kb.config[n].config.get().then(function(p){0!=
Object.keys(p).length?kb.field.load(kb.config[n].app,!0).then(function(w){q=kb.config[n].app;try{(function(d){if(0!=d.length)switch(h){case "create":case "edit":k(d,a.record).then(function(b){return c(a)});break;case "process":(function(b){0!=b.length?k(b,a.record).then(function(l){return c(a)}):c(a)})(d.filter(function(b){return b.action.value==a.action.value+":"+a.status.value+":"+a.nextStatus.value}));break;case "detail":d.each(function(b,l){kb.button.create(g,h,"kb-upsert-button"+l.toString(),
b.label.value,b.message.value,function(){return k([b],a.record).then(function(f){return kb.alert("Done!")})})});c(a);break;case "index":d.each(function(b,l){b.view.value&&b.view.value!=a.viewId.toString()||kb.button.create(g,h,"kb-upsert-button"+l.toString(),b.label.value,b.message.value,function(){kb.view.records.get(q,(g?kintone.mobile.app:kintone.app).getQueryCondition()).then(function(f){var u=function(m,t){k([b],f[m]).then(function(x){m++;m<f.length?u(m,t):t()})};0!=f.length?u(0,function(){return kb.alert("Done!")}):
kb.alert("There are no records.")})["catch"](function(f){return kb.alert(kb.error.parse(f))})})}),c(a)}else c(a)})(JSON.parse(p.tab).reduce(function(d,b){(g?["both","mobile"]:["both","pc"]).includes(b.setting.device.value)&&b.setting.event.value.includes(h)&&d.push(b.setting);return d},[]))}catch(d){kb.alert(kb.error.parse(d)),c(a)}})["catch"](function(w){return c(a)}):c(a)})["catch"](function(p){return c(a)})})("mobile"==a.type.split(".").first(),function(e){switch(e){case "submit":e=a.type.split(".").slice(-3).first()}return e}(a.type.split(".").slice(-2).first()))})})})(kintone.$PLUGIN_ID);