/*
* FileName "plugins.upsert.js"
* Version: 1.0.0
* Copyright (c) 2023 Pandafirm LLC
* Distributed under the terms of the GNU Lesser General Public License.
* https://opensource.org/licenses/LGPL-2.1
*/
'use strict';(I=>{var p={},L=(e,l,J=!1)=>new Promise((z,v)=>{var t=(u,m)=>{var n=()=>{u++;u<e.length?t(u,m):m()};(b=>{var f=kb.filter.scan(p.app,l,b.condition.value);f?kb.filter.auth(b.user.value,b.organization.value,b.group.value).then(B=>{B?kb.field.load(b.app.value).then(w=>{var D={id:b.app.value,fields:w.origin};(q=>{var F=[],M=[],P=[],G={},C=1,N=1,E=0,K=0,O=()=>{var g=[],r={field:(d,c)=>{c=d.tableCode?f[d.tableCode].value.length>c?f[d.tableCode].value[c].value[d.code]:kb.record.create({fields:{empty:mapping.internal}}).empty:
f[d.code];return kb.extend({type:d.type},c)},record:d=>{N.each(c=>{var y=(a=>{var k=kb.filter.scan(D,d,a.query);if(!k&&b.pattern.value=="upsert"){for(var h in a.rows)kb.filter.result[h].value.length==0&&(d[h].value.push({value:kb.extend({},a.rows[h])}),kb.filter.result[h]={value:[d[h].value.last()]});k=kb.filter.result}return k})((()=>{var a={rows:{},query:[]};K=c;F.each((k,h)=>{k.external.tableCode&&(k.external.tableCode in a.rows||(a.rows[k.external.tableCode]=kb.record.create(D.fields[k.external.tableCode],
!1)),a.rows[k.external.tableCode][k.external.code]=x(k.external,r.field(k.internal,K)),a.query.push(kb.filter.query.create(k.external,k.operator,r.field(k.internal,K))))});M.each((k,h)=>{k.field.tableCode&&a.query.push(k.field.code+" "+k.operator+" "+k.value)});a.query=a.query.join(" and ");return a})());y&&P.each((a,k)=>{a.external.tableCode?a.external.tableCode in G?(d[a.external.tableCode]={value:G[a.external.tableCode]},G[a.external.tableCode].each((h,H)=>{h.value[a.external.code]=x(a.external,
r.field(a.internal,H));a.external.type=="FILE"&&h.value[a.external.code].value&&Array.prototype.push.apply(g,h.value[a.external.code].value)})):y[a.external.tableCode].value.each((h,H)=>{h.value[a.external.code]=x(a.external,r.field(a.internal,K));a.external.type=="FILE"&&h.value[a.external.code].value&&Array.prototype.push.apply(g,h.value[a.external.code].value)}):(d[a.external.code]=x(a.external,r.field(a.internal,E)),a.external.type=="FILE"&&d[a.external.code].value&&Array.prototype.push.apply(g,
d[a.external.code].value))})});return d}},x=(d,c)=>{switch(d.type){case "CHECK_BOX":case "FILE":case "GROUP_SELECT":case "MULTI_SELECT":case "ORGANIZATION_SELECT":case "USER_SELECT":Array.isArray(c.value)||(c.value=[c.value])}c.type=d.type;return d.lookup?kb.extend({lookup:!0},c):c},A=d=>{d.each((c,y)=>{b.formula.value.each((a,k)=>{a.value.field.value in q.external&&(h=>{h.tableCode?c[h.tableCode].value.each((H,Q)=>{H.value[h.code].value=kb.formula.calculate(a.value,H.value,c,c,q.external);h.lookup&&
(H.value[h.code].lookup=!0)}):(c[h.code].value=kb.formula.calculate(a.value,c,c,c,q.external),h.lookup&&(c[h.code].lookup=!0))})(q.external[a.value.field.value])})});return d};b.pattern.value=="insert"?(d=>{kb.file.clone(g,!0).then(()=>{kb.view.records.set(b.app.value,{post:d},J).then(c=>{E++;E<C?O():n()}).catch(c=>{kb.alert(kb.error.parse(c));v()})})})(A([r.record(kb.record.create(D))])):kb.view.records.get(b.app.value,(()=>{var d=[];F.each((c,y)=>{c.external.tableCode||d.push(kb.filter.query.create(c.external,
c.operator,r.field(c.internal,E)))});M.each((c,y)=>{c.field.tableCode||d.push(c.field.code+" "+c.operator+" "+c.value)});return d.join(" and ")})()).then(d=>{d=(c=>{var y=[];c.length!=0?y=c.map(a=>r.record(a)):b.pattern.value=="upsert"&&(a=>{y.push(r.record((()=>{var k=kb.record.create(D);a.each((h,H)=>{h.external.tableCode?k[h.external.tableCode]={value:[]}:k[h.external.code]=x(h.external,r.field(h.internal,E))});return k})()))})(F.filter(a=>!kb.field.reserved.includes(a.external.type)));return A(y)})(d);
kb.file.clone(g,!0).then(()=>{kb.view.records.set(b.app.value,{post:d.filter(c=>!c.$id.value),put:d.reduce((c,y)=>{y.$id.value&&c.push(kb.view.records.transform(y));return c},[])},J).then(c=>{E++;E<C?O():n()}).catch(c=>{kb.alert(kb.error.parse(c));v()})})}).catch(d=>{kb.alert(kb.error.parse(d));v()})};b.mapping.value.some(g=>!(g.value.external.value in q.external&&g.value.internal.value in q.internal))?(kb.alert("No field to transfer was found"),v()):b.criteria.value.some(g=>!(g.value.external.value in
q.external&&g.value.internal.value in q.internal))?(kb.alert("No field to transfer was found"),v()):(b.mapping.value.each((g,r)=>{((x,A)=>{x.tableCode?G[x.tableCode]=(d=>{d=d?d.length:1;A.tableCode&&(d=d<f[A.tableCode].value.length?f[A.tableCode].value.length:d);return Array(d).fill().map(()=>({value:kb.record.create(D.fields[x.tableCode],!1)}))})(G[x.tableCode]):A.tableCode&&(C=f[A.tableCode].value.length==0?0:C<f[A.tableCode].value.length?f[A.tableCode].value.length:C);P.push({external:x,internal:A})})(q.external[g.value.external.value],
q.internal[g.value.internal.value])}),b.criteria.value.each((g,r)=>{r=q.external[g.value.external.value];var x=g.value.operator.value;g=q.internal[g.value.internal.value];r.tableCode?(r.tableCode in G&&delete G[r.tableCode],g.tableCode&&(N=N<f[g.tableCode].value.length?f[g.tableCode].value.length:N)):g.tableCode&&(C=f[g.tableCode].value.length==0?0:C<f[g.tableCode].value.length?f[g.tableCode].value.length:C);F.push({external:r,operator:x,internal:g})}),kb.filter.query.parse.expand({id:b.app.value,
fields:w.origin},b.filter.value).each((g,r)=>{M.push({field:q.external[g.field],operator:g.operator,value:g.value})}),C!=0?(K=E=0,O()):n())})({external:w.parallelize,internal:p.fieldInfos.parallelize})}).catch(w=>{kb.alert(kb.error.parse(w));v()}):n()}).catch(B=>{kb.alert(kb.error.parse(B));v()}):n()})(e[u])};J||kb.loadStart();t(0,()=>{J||kb.loadEnd();z()})});kintone.events.on("app.record.create.submit.success app.record.detail.process.proceed app.record.detail.show app.record.edit.submit.success app.record.index.show mobile.app.record.create.submit.success mobile.app.record.detail.process.proceed mobile.app.record.detail.show mobile.app.record.edit.submit.success mobile.app.record.index.show".split(" "),
e=>new Promise((l,J)=>{((z,v)=>{p.mobile=z;p.type=v;kb.config[I].config.get().then(t=>{Object.keys(t).length!=0?kb.field.load(kb.config[I].app,!0).then(u=>{p.app={id:kb.config[I].app,fields:u.origin};p.fieldInfos=u;try{(m=>{if(m.length!=0)switch(p.type){case "create":case "edit":L(m,e.record).then(b=>l(e)).catch(()=>{});break;case "process":(b=>{b.length!=0?L(b,e.record).then(f=>l(e)).catch(()=>{}):l(e)})(m.filter(b=>b.action.value==e.action.value+":"+e.status.value+":"+e.nextStatus.value));break;
case "detail":var n=b=>{(f=>{kb.filter.scan(p.app,e.record,f.condition.value)?kb.filter.auth(f.user.value,f.organization.value,f.group.value).then(B=>{B&&kb.button.create(p.mobile,p.type,"kb-upsert-button"+b.toString(),f.label.value,f.message.value,()=>L([f],e.record).then(w=>kb.alert("Done!")).catch(()=>{}));b++;b<m.length&&n(b)}).catch(B=>{b++;b<m.length&&n(b)}):(b++,b<m.length&&n(b))})(m[b])};n(0);l(e);break;case "index":n=b=>{(f=>{kb.filter.auth(f.user.value,f.organization.value,f.group.value).then(B=>
{B&&(f.view.value&&f.view.value!=e.viewId.toString()||kb.button.create(p.mobile,p.type,"kb-upsert-button"+b.toString(),f.label.value,f.message.value,()=>{kb.view.records.get(p.app.id,(p.mobile?kintone.mobile.app:kintone.app).getQueryCondition()).then(w=>{let D=(q,F)=>{L([f],w[q],!0).then(M=>{kb.progressUpdate();q++;q<w.length?D(q,F):F()}).catch(()=>{})};w.length!=0?(kb.progressStart(w.length),D(0,()=>kb.alert("Done!"))):kb.alert("There are no records.")}).catch(w=>kb.alert(kb.error.parse(w)))}));
b++;b<m.length&&n(b)}).catch(B=>{b++;b<m.length&&n(b)})})(m[b])},n(0),l(e)}else l(e)})(JSON.parse(t.tab).map((m,n)=>kb.extend({sIndex:{value:n.toString()}},m.setting)).reduce((m,n)=>{(p.mobile?["all","both","mobile"]:["all","both","pc"]).includes(n.device.value)&&n.event.value.includes(p.type)&&m.push(n);return m},[]))}catch(m){kb.alert(kb.error.parse(m)),l(e)}}).catch(u=>l(e)):l(e)}).catch(t=>l(e))})(e.type.split(".").first()=="mobile",(z=>{switch(z){case "submit":z=e.type.split(".").slice(-3).first()}return z})(e.type.split(".").slice(-2).first()))}));
kb.event.on("kb.upsert.call",e=>new Promise((l,J)=>{kb.config[I].config.get().then(z=>{Object.keys(z).length!=0?kb.field.load(kb.config[I].app,!0).then(v=>{p.app={id:kb.config[I].app,fields:v.origin};p.fieldInfos=v;try{(t=>{t.length!=0?L(t,e.record,!0).then(u=>l(e)).catch(()=>l(e)):l(e)})(JSON.parse(z.tab).map((t,u)=>kb.extend({sIndex:{value:u.toString()}},t.setting)).reduce((t,u)=>{(e.mobile?["all","both","mobile"]:["all","both","pc"]).includes(u.device.value)&&u.event.value.includes(e.pattern)&&
t.push(u);return t},[]))}catch(t){kb.alert(kb.error.parse(t)),l(e)}}).catch(v=>l(e)):l(e)}).catch(z=>l(e))}))})(kintone.$PLUGIN_ID);