/*
* FileName "plugins.omail.js"
* Version: 1.0.0
* Copyright (c) 2023 Pandafirm LLC
* Distributed under the terms of the GNU Lesser General Public License.
* https://opensource.org/licenses/LGPL-2.1
*/
'use strict';(y=>{var c={},B=(b,g,C=!1)=>new Promise((r,p)=>{var l="",q=(f,h)=>{var d=()=>{f++;f<b.length?q(f,h):h()};(a=>{var n=kb.filter.scan(c.app,g,a.condition.value);n?kb.filter.auth(a.user.value,a.organization.value,a.group.value).then(t=>{if(t){var x=(k,m,w)=>{a.format.value=="HTML"&&(k=k.replace(/\r/g,"").replace(/\n/g,"<br>"));for(var e in m){var u=m[e].value;e in c.fieldInfos.parallelize&&(a.format.value=="HTML"&&c.fieldInfos.parallelize[e].type=="MULTI_LINE_TEXT"&&(u=u.replace(/\r/g,"").replace(/\n/g,
"<br>")),k=k.replace(new RegExp("%"+e+"%","g"),kb.field.stringify(c.fieldInfos.parallelize[e],u," / ",!0)))}for(e in w)u=w[e].value,e in c.fieldInfos.parallelize&&(a.format.value=="HTML"&&c.fieldInfos.parallelize[e].type=="MULTI_LINE_TEXT"&&(u=u.replace(/\r/g,"").replace(/\n/g,"<br>")),k=k.replace(new RegExp("%"+e+"%","g"),kb.field.stringify(c.fieldInfos.parallelize[e],u," / ",!0)));return k};(k=>{var m=w=>{(e=>{var u=(v,z)=>{e.attachment.length!=0?kb.file.download(e.attachment[v],!0).then(A=>{kb.field.blobToBase64(A,
D=>{e.attachment[v].data=D;v++;v<e.attachment.length?u(v,z):z()})}).catch(A=>{kb.alert(kb.error.parse(A));p()}):z()};u(0,()=>{kb.encrypt(JSON.stringify(e.data),l).then(v=>{var z=fetch,A="https://api.kintone-booster.com/mail/oauth/"+kb.operator.language,D=JSON,F=D.stringify;e.data=v.data;e.iv=v.iv;e.tag=v.tag;z(A,{method:"POST",headers:{"X-Requested-With":"XMLHttpRequest"},body:F.call(D,e)}).then(E=>{E.json().then(G=>{switch(E.status){case 200:w++;w<k.length?m(w):d();break;default:kb.alert(kb.error.parse(G)),
p()}})}).catch(E=>{kb.alert(kb.error.parse(E));p()})}).catch(v=>{p()})})})(k[w])};k.length!=0?m(0):d()})((()=>{var k=[];(c.fieldInfos.parallelize[a.to.value].tableCode?n[c.fieldInfos.parallelize[a.to.value].tableCode].value:[{value:n}]).each((m,w)=>{m.value[a.to.value].value&&k.push({data:{client_id:a.client_id.value,client_secret:a.client_secret.value,author:a.author.value,sender:a.sender.value,subdomain:location.host.split(".")[0],provider:(e=>{e="";switch(a.provider.value){case "GMail":e="google";
break;case "Exchange Online":e="microsoft"}return e})(a.provider.value),to:m.value[a.to.value].value,cc:x(a.cc.value,n,c.fieldInfos.parallelize[a.to.value].tableCode?m.value:{}),bcc:x(a.bcc.value,n,c.fieldInfos.parallelize[a.to.value].tableCode?m.value:{}),html:a.format.value=="HTML"},subject:x(a.subject.value,n,c.fieldInfos.parallelize[a.to.value].tableCode?m.value:{}),body:x(a.body.value,n,c.fieldInfos.parallelize[a.to.value].tableCode?m.value:{}),attachment:(()=>{var e=[];a.attachment.value&&a.attachment.value in
c.fieldInfos.parallelize&&(e=(c.fieldInfos.parallelize[a.attachment.value].tableCode?m.value:n)[a.attachment.value].value);return e})()})});return k})())}else d()}).catch(t=>{kb.alert(kb.error.parse(t));p()}):d()})(b[f])};fetch("https://api.kintone-booster.com/mail/oauth/"+kb.operator.language,{method:"GET",headers:{"X-Requested-With":"XMLHttpRequest"}}).then(f=>{f.json().then(h=>{switch(f.status){case 200:l=h.passphrase;C||kb.loadStart();q(0,()=>{C||kb.loadEnd();r()});break;default:kb.alert(kb.error.parse(h)),
p()}})}).catch(f=>{kb.alert(kb.error.parse(f));p()})});kintone.events.on("app.record.create.submit.success app.record.detail.process.proceed app.record.detail.show app.record.edit.submit.success app.record.index.show mobile.app.record.create.submit.success mobile.app.record.detail.process.proceed mobile.app.record.detail.show mobile.app.record.edit.submit.success mobile.app.record.index.show".split(" "),b=>new Promise((g,C)=>{((r,p)=>{c.mobile=r;c.type=p;kb.config[y].config.get().then(l=>{Object.keys(l).length!=
0?kb.field.load(kb.config[y].app,!0).then(q=>{c.app={id:kb.config[y].app,fields:q.origin};c.fieldInfos=q;try{(f=>{if(f.length!=0)switch(c.type){case "create":case "edit":B(f,b.record).then(d=>g(b)).catch(()=>{});break;case "process":(d=>{d.length!=0?B(d,b.record).then(a=>g(b)).catch(()=>{}):g(b)})(f.filter(d=>d.action.value==b.action.value+":"+b.status.value+":"+b.nextStatus.value));break;case "detail":var h=d=>{(a=>{kb.filter.scan(c.app,b.record,a.condition.value)?kb.filter.auth(a.user.value,a.organization.value,
a.group.value).then(n=>{n&&kb.button.create(c.mobile,c.type,"kb-mail-button"+d.toString(),a.label.value,a.message.value,()=>B([a],b.record).then(t=>kb.alert("Done!")).catch(()=>{}));d++;d<f.length&&h(d)}).catch(n=>{d++;d<f.length&&h(d)}):(d++,d<f.length&&h(d))})(f[d])};h(0);g(b);break;case "index":h=d=>{(a=>{kb.filter.auth(a.user.value,a.organization.value,a.group.value).then(n=>{n&&(a.view.value&&a.view.value!=b.viewId.toString()||kb.button.create(c.mobile,c.type,"kb-mail-button"+d.toString(),a.label.value,
a.message.value,()=>{kb.view.records.get(c.app.id,(c.mobile?kintone.mobile.app:kintone.app).getQueryCondition()).then(t=>{let x=(k,m)=>{B([a],t[k],!0).then(w=>{kb.progressUpdate();k++;k<t.length?x(k,m):m()}).catch(()=>{})};t.length!=0?(kb.progressStart(t.length),x(0,()=>kb.alert("Done!"))):kb.alert("There are no records.")}).catch(t=>kb.alert(kb.error.parse(t)))}));d++;d<f.length&&h(d)}).catch(n=>{d++;d<f.length&&h(d)})})(f[d])},h(0),g(b)}else g(b)})(JSON.parse(l.tab).map((f,h)=>kb.extend({sIndex:{value:h.toString()}},
f.setting)).reduce((f,h)=>{(c.mobile?["all","both","mobile"]:["all","both","pc"]).includes(h.device.value)&&h.event.value.includes(c.type)&&f.push(h);return f},[]))}catch(f){kb.alert(kb.error.parse(f)),g(b)}}).catch(q=>g(b)):g(b)}).catch(l=>g(b))})(b.type.split(".").first()=="mobile",(r=>{switch(r){case "submit":r=b.type.split(".").slice(-3).first()}return r})(b.type.split(".").slice(-2).first()))}));kb.event.on("kb.omail.call",b=>new Promise((g,C)=>{kb.config[y].config.get().then(r=>{Object.keys(r).length!=
0?kb.field.load(kb.config[y].app,!0).then(p=>{c.app={id:kb.config[y].app,fields:p.origin};c.fieldInfos=p;try{(l=>{l.length!=0?B(l,b.record,!0).then(q=>g(b)).catch(()=>g(b)):g(b)})(JSON.parse(r.tab).map((l,q)=>kb.extend({sIndex:{value:q.toString()}},l.setting)).reduce((l,q)=>{(b.mobile?["all","both","mobile"]:["all","both","pc"]).includes(q.device.value)&&q.event.value.includes(b.pattern)&&l.push(q);return l},[]))}catch(l){kb.alert(kb.error.parse(l)),g(b)}}).catch(p=>g(b)):g(b)}).catch(r=>g(b))}))})(kintone.$PLUGIN_ID);