/*
* FileName "plugins.cascade.js"
* Version: 1.0.0
* Copyright (c) 2023 Pandafirm LLC
* Distributed under the terms of the GNU Lesser General Public License.
* https://opensource.org/licenses/LGPL-2.1
*/
'use strict';(B=>{var a={handlers:{}},E=(g,f,F,w="record",z="detail")=>{var q=(()=>{var n={},A=0;if("record"==w)for(var r in f)r in a.fieldInfos.tables&&f[r].value.each((c,m)=>{null==c.id&&(A++,c.id=A);n[c.id]=m},{});return n})();return new Promise((n,A)=>{var r=(c,m)=>{var v=l=>(b=>new Kuc.Dropdown({className:"control-gaia kb-cascade-dropdown",items:[{label:"-----",value:""}].concat(Object.values(b.options).reduce((d,u)=>{d[u.index]=u;return d},Array(Object.values(b.options).length).fill("")).map(d=>({label:d.label,
value:d.label}))),label:b.noLabel||b.tableCode?"":b.label,requiredIcon:b.required}))(a.fieldInfos.parallelize[l.child.value]),C=(l,b)=>{var d=Object.keys(a.fieldInfos.parallelize[l.child.value].options);if(Array.isArray(b[l.parent.value].value)?0!=b[l.parent.value].value.length:b[l.parent.value].value)d=(Array.isArray(b[l.parent.value].value)?b[l.parent.value].value:[b[l.parent.value].value]).reduce((u,t)=>u=[...(new Set([...u,...l.relation.value[t]]))],[]);return d},G=l=>null==l||!1===l?"":String(l),
x=l=>Array.from(l.childNodes).map(b=>b.nodeType===Node.TEXT_NODE?b.nodeValue.trim():b.nodeType===Node.ELEMENT_NODE?x(b):"").join("");(l=>{(b=>{switch(w){case "record":b.parent.tableCode?b.parent.tableCode in f&&(d=>{if(a.mobile)d();else if(kb.elms(".subtable-"+a.fieldInfos.tables[b.parent.tableCode].id+" tbody tr").length!=f[b.parent.tableCode].value.length){let u=new MutationObserver(()=>{kb.elms(".subtable-"+a.fieldInfos.tables[b.parent.tableCode].id+" tbody tr").length==f[b.parent.tableCode].value.length&&
(d(),u.disconnect())});u.observe(kb.elm(".subtable-"+a.fieldInfos.tables[b.parent.tableCode].id),{childList:!0,subtree:!0})}else d()})(()=>{f[b.parent.tableCode].value.each((d,u)=>{b.parent.code in d.value&&(t=>{t&&(e=>{var h="";switch(a.fieldInfos.parallelize[b.child.code].type){case "CHECK_BOX":h=a.mobile?".checkbox-gaia":".input-checkbox-item-cybozu";break;case "DROP_DOWN":a.mobile?h="option":(k=>{if(!k.nextSibling||!k.nextSibling.hasClass("kb-cascade-dropdown")){k.hide().insertAdjacentElement("afterend",
v(l));let p=new MutationObserver(()=>{k.nextSibling.elms("[role=option]").each((y,D)=>{y.attr("value")&&!e.includes(x(y))&&y.addClass("kb-cascade-disabled")});p.disconnect()});p.observe(k.nextSibling,{childList:!0,subtree:!0})}(p=>{p.handler&&p.removeEventListener("change",p.handler);p.handler=y=>{var D=(a.mobile?kintone.mobile.app.record:kintone.app.record).get();D.record[b.parent.tableCode].value[q[d.id]].value[b.child.code].value=y.detail.value;(a.mobile?kintone.mobile.app.record:kintone.app.record).set(D)};
p.addEventListener("change",p.handler);p.elms("[role=option]").each((y,D)=>{y.attr("value")&&!e.includes(x(y))&&y.addClass("kb-cascade-disabled")});p.value=G(f[b.parent.tableCode].value[q[d.id]].value[b.child.code].value)})(k.nextSibling)})(t[q[d.id]]);break;case "MULTI_SELECT":h=a.mobile?"option":".goog-menuitem";break;case "RADIO_BUTTON":h=a.mobile?".radio-gaia":".input-radio-item-cybozu"}h&&("option"==h?(t[q[d.id]].value.elms(h).each((k,p)=>{"span"==k.parentNode.tagName.toLowerCase()&&(p=k.parentNode,
k.closest("select").insertBefore(k,p),k.closest("select").removeChild(p))}),t[q[d.id]].value.elms(h).each((k,p)=>{k.attr("value")&&!e.includes(x(k))&&"span"!=k.parentNode.tagName.toLowerCase()&&(p=kb.create("span").addClass("kb-cascade-disabled"),k.parentNode.insertBefore(p,k),p.append(k))})):t[q[d.id]].value.elms(h).each((k,p)=>{e.includes(x(k))||k.addClass("kb-cascade-disabled")}))})(C(l,d.value))})(kb.field.get(b.child,a.mobile,a.type||z))})}):b.parent.code in f&&(d=>{d&&(u=>{var t="";switch(a.fieldInfos.parallelize[b.child.code].type){case "CHECK_BOX":t=
a.mobile?".checkbox-gaia":".input-checkbox-item-cybozu";break;case "DROP_DOWN":if(a.mobile)t="option";else{if(!d.nextSibling||!d.nextSibling.hasClass("kb-cascade-dropdown")){d.hide().insertAdjacentElement("afterend",v(l));let e=new MutationObserver(()=>{d.nextSibling.elms("[role=option]").each((h,k)=>{h.attr("value")&&!u.includes(x(h))&&h.addClass("kb-cascade-disabled")});e.disconnect()});e.observe(d.nextSibling,{childList:!0,subtree:!0})}(e=>{e.handler&&e.removeEventListener("change",e.handler);
e.handler=h=>{var k=(a.mobile?kintone.mobile.app.record:kintone.app.record).get();k.record[b.child.code].value=h.detail.value;(a.mobile?kintone.mobile.app.record:kintone.app.record).set(k)};e.addEventListener("change",e.handler);e.elms("[role=option]").each((h,k)=>{h.attr("value")&&!u.includes(x(h))&&h.addClass("kb-cascade-disabled")});e.value=G(f[b.child.code].value)})(d.nextSibling)}break;case "MULTI_SELECT":t=a.mobile?"option":".goog-menuitem";break;case "RADIO_BUTTON":t=a.mobile?".radio-gaia":
".input-radio-item-cybozu"}t&&("option"==t?(d.value.elms(t).each((e,h)=>{"span"==e.parentNode.tagName.toLowerCase()&&(h=e.parentNode,e.closest("select").insertBefore(e,h),e.closest("select").removeChild(h))}),d.value.elms(t).each((e,h)=>{e.attr("value")&&!u.includes(x(e))&&"span"!=e.parentNode.tagName.toLowerCase()&&(h=kb.create("span").addClass("kb-cascade-disabled"),e.parentNode.insertBefore(h,e),h.append(e))})):d.value.elms(t).each((e,h)=>{u.includes(x(e))||e.addClass("kb-cascade-disabled")}))})(C(l,
f))})(kb.field.get(b.child,a.mobile,a.type||z));break;case "view":b.parent.tableCode?b.parent.tableCode in f&&f[b.parent.tableCode].value.each((d,u)=>{b.parent.code in d.value&&(d.value[b.child.code].options=C(l,d.value))}):b.parent.code in f&&(f[b.child.code].options=C(l,f))}})({parent:a.fieldInfos.parallelize[l.parent.value],child:a.fieldInfos.parallelize[l.child.value]});c++;c<g.length?r(c,m):m()})(g[c])};"record"==w&&kb.elms(".kb-cascade-disabled").each((c,m)=>{c.removeClass("kb-cascade-disabled")});
r(0,()=>n())})};kintone.events.on(["app.record.create.show","app.record.edit.show","mobile.app.record.create.show","mobile.app.record.edit.show"],g=>new Promise((f,F)=>{((w,z)=>{a.mobile=w;a.type=z;for(var q in a.handlers)a.handlers[q].each((n,A)=>{kintone.events.off(q,n)});kb.config[B].config.get().then(n=>{0!=Object.keys(n).length?kb.field.load(kb.config[B].app,!0).then(A=>{a.app={id:kb.config[B].app,fields:A.origin};a.fieldInfos=A;try{(r=>{0!=r.length&&(((c,m)=>{kintone.events.on(c,m);c.each((v,
C)=>{v in a.handlers||(a.handlers[v]=[]);a.handlers[v].push(m)})})(r.reduce((c,m)=>{c.push("app.record.create.change."+m.parent.value);c.push("app.record.edit.change."+m.parent.value);c.push("mobile.app.record.create.change."+m.parent.value);c.push("mobile.app.record.edit.change."+m.parent.value);var v=a.fieldInfos.parallelize[m.parent.value].tableCode;v&&(c.push("app.record.create.change."+v),c.push("app.record.edit.change."+v),c.push("mobile.app.record.create.change."+v),c.push("mobile.app.record.edit.change."+
v));switch(a.fieldInfos.parallelize[m.child.value].type){case "DROP_DOWN":c.push("app.record.create.change."+m.child.value),c.push("app.record.edit.change."+m.child.value),c.push("mobile.app.record.create.change."+m.child.value),c.push("mobile.app.record.edit.change."+m.child.value)}return[...(new Set([...c]))]},[]),c=>{kb.event.call("kb.action.installed.change",{installed:!1,mobile:a.mobile}).then(m=>{m.installed||E(r,c.record,kb.elm("body"),"record").then(v=>{}).catch(()=>{})});return c}),kb.event.call("kb.action.installed.show",
{installed:!1,mobile:a.mobile}).then(c=>{c.installed?f(g):E(r,g.record,kb.elm("body"),"record").then(m=>f(g)).catch(()=>{})}))})(JSON.parse(n.tab).map((r,c)=>kb.extend({sIndex:{value:c.toString()}},r.setting)).reduce((r,c)=>{(a.mobile?["all","both","mobile"]:["all","both","pc"]).includes(c.device.value)&&c.parent.value in a.fieldInfos.parallelize&&c.child.value in a.fieldInfos.parallelize&&(c.relation.value=JSON.parse(c.relation.value),r.push(c));return r},[]))}catch(r){kb.alert(kb.error.parse(r)),
f(g)}}).catch(A=>f(g)):f(g)}).catch(n=>f(g))})("mobile"==g.type.split(".").first(),g.type.split(".").slice(-2).first())}));kb.event.on("kb.cascade.call",g=>new Promise((f,F)=>{["create","edit"].includes(g.pattern)?kb.config[B].config.get().then(w=>{0!=Object.keys(w).length?kb.field.load(kb.config[B].app,!0).then(z=>{a.app={id:kb.config[B].app,fields:z.origin};a.fieldInfos=z;a.mobile="mobile"in a?a.mobile:g.mobile;try{(q=>{0!=q.length?E(q,g.record,g.container,g.workplace?g.workplace:"record",g.pattern).then(n=>
f(g)).catch(()=>f(g)):f(g)})(JSON.parse(w.tab).map((q,n)=>kb.extend({sIndex:{value:n.toString()}},q.setting)).reduce((q,n)=>{(g.mobile?["all","both","mobile"]:["all","both","pc"]).includes(n.device.value)&&n.parent.value in a.fieldInfos.parallelize&&n.child.value in a.fieldInfos.parallelize&&(n.relation.value=JSON.parse(n.relation.value),q.push(n));return q},[]))}catch(q){kb.alert(kb.error.parse(q)),f(g)}}).catch(z=>f(g)):f(g)}).catch(w=>f(g)):f(g)}))})(kintone.$PLUGIN_ID);
