/*
* FileName "plugins.spread.js"
* Version: 1.0.0
* Copyright (c) 2023 Pandafirm LLC
* Distributed under the terms of the GNU Lesser General Public License.
* https://opensource.org/licenses/LGPL-2.1
*/
(function(v){var p,f;kintone.events.on(["app.record.index.show","mobile.app.record.index.show"],function(m){return new Promise(function(r,z){(function(A,B){p=A;kb.config[v].config.get().then(function(w){0!=Object.keys(w).length?kb.field.load(kb.config[v].app,!0).then(function(t){f={id:kb.config[v].app,disables:t.disables.reduce(function(b,d){d in t.parallelize&&b.push(t.parallelize[d]);return b},[]),fields:function(b,d){var q={},k;for(k in b){var e=b[k];e.tableCode?e.tableCode in q||(q[e.tableCode]=
d[e.tableCode]):q[k]=e}return q}(t.parallelize,t.tables),view:{}};try{(function(b){b?function(d){var q=function(){d.elm(".kb-view").elms("[unsaved=unsaved]").each(function(k,e){k.removeAttr("unsaved").removeClass("kb-unsaved")});window.location.reload(!0)};p&&kb.elm("body").addClass("kb-mobile");d.append(kb.create("div").addClass("kb-spread-toolbar").append(kb.create("button").addClass("kb-spread-toolbar-button kb-spread-toolbar-button-submit").html(kb.constants.common.caption.button.submit[kb.operator.language]).on("click",
function(k){(function(e,u){var g={post:[],put:[]},l={submit:function(c,a){if(0!=e.length){var n=kb.record.get(e[c],f);n.error?a(!0):kb.event.call("kb.submit.call",{record:n.record,mobile:p,numbering:u,pattern:n.record.$id.value?"edit":"create",workplace:"view"}).then(function(h){h.error?(kb.record.set(e[c],f,h.record),a(!0)):(h.record.$id.value?g.put.push({id:h.record.$id.value,record:h.record}):g.post.push(h.record),c++,c<e.length?l.submit(c,a):a())})["catch"](function(){})}else a()},success:function(c,
a,n,h){var y=function(){c++;c<g[a].length?l.success(c,a,n,h):"post"==a?l.success(0,"put",n,h):h()};0!=g[a].length?kb.event.call("kb."+n+".call",{record:"post"==a?g[a][c]:g[a][c].record,mobile:p,pattern:"post"==a?"create":"edit",workplace:"view"}).then(function(x){x.error||("post"==a?g[a][c]=x.record:g[a][c].record=x.record,y())})["catch"](function(){}):y()}};l.submit(0,function(c){c||(0!=g.post.length+g.put.length?(kb.loadStart(),kb.event.call("kb.view.submit",{container:d.elm(".kb-view"),records:g,
viewId:b.view.value}).then(function(a){a.error||kb.confirm(kb.constants.common.message.confirm.submit[kb.operator.language],function(){kb.loadStart();kb.view.records.set(f.id,a.records,!0,!0).then(function(n){kb.event.call("kb.view.submit.success",{container:a.container,records:a.records,viewId:a.viewId}).then(function(h){h.error||l.success(0,"post","mail",function(){l.success(0,"post","upsert",function(){kb.alert("Done!",function(){return q()})})})})})["catch"](function(n){kb.alert(kb.error.parse(n));
z()})})})):kb.alert(kb.constants.common.message.invalid.submit[kb.operator.language]))})})(d.elm(".kb-view").elms("[unsaved=unsaved]"),{})})).append(kb.create("button").addClass("kb-spread-toolbar-button").html(kb.constants.common.caption.button.cancel[kb.operator.language]).on("click",function(k){0!=d.elm(".kb-view").elms("[unsaved=unsaved]").length&&kb.confirm(kb.constants.common.message.confirm.cancel[kb.operator.language],function(){return q()})})));kb.view.load(f.id).then(function(k){f.view=
{buttons:b.buttons.value,fields:k.list.reduce(function(e,u){return u.id==b.view.value?u.fields:e},[]),mode:b.mode.value};(function(e){m.records.each(function(u,g){(function(l){kb.event.call("kb.action.call",{container:l.elm("[form-id=form_"+f.id+"]"),record:u,mobile:p,pattern:"editor"==b.mode.value?"edit":"dummy",workplace:"view"}).then(function(c){kb.event.call("kb.style.call",{container:l.elm("[form-id=form_"+f.id+"]"),record:c.record,mobile:c.mobile,pattern:"editor"==b.mode.value?"edit":"detail",
workplace:c.workplace}).then(function(a){kb.record.set(l.elm("[form-id=form_"+f.id+"]"),f,a.record).then(function(){l.elm(".kb-view-row-edit").attr("href",kb.record.page.detail(p,f.id,a.record.$id.value));d.parentNode.show()})})["catch"](function(){})})["catch"](function(){})})(e.addRow())})})(kb.view.create(d,f,b.view.value,p).elm(".kb-view"));r(m)});window.on("beforeunload",function(k){0!=d.elm(".kb-view").elms("[unsaved=unsaved]").length&&(k.returnValue=kb.constants.common.message.confirm.changed[kb.operator.language])})}(kb.elm(p?
".gaia-mobile-v2-indexviewpanel-tableview":"#view-list-data-gaia").addClass("kb-view-container").empty()):r(m)})(JSON.parse(w.flat).setting.value.reduce(function(b,d){d.value.view.value==m.viewId.toString()&&(b=d.value);return b},null))}catch(b){kb.alert(kb.error.parse(b)),r(m)}})["catch"](function(t){return r(m)}):r(m)})["catch"](function(w){return r(m)})})("mobile"==m.type.split(".").first(),m.type.split(".").slice(-2).first())})})})(kintone.$PLUGIN_ID);