/*
* FileName "plugins.submit.js"
* Version: 1.0.0
* Copyright (c) 2023 Pandafirm LLC
* Distributed under the terms of the GNU Lesser General Public License.
* https://opensource.org/licenses/LGPL-2.1
*/
'use strict';(z=>{var b={},A=(c,g,v=!1,w={},y="record")=>new Promise((p,m)=>{var r=[],t=(d,k)=>{var u=()=>{d++;d<c.length?t(d,k):k()};(e=>{kb.filter.scan(b.app,g,e.condition.value)?kb.filter.auth(e.user.value,e.organization.value,e.group.value).then(x=>{if(x){var q={duplicate:l=>{try{e.duplicateCriteria.value.some(a=>!(a.value.external.value in b.fieldInfos.parallelize&&a.value.internal.value in b.fieldInfos.parallelize))?(kb.alert("No field to lookup was found"),m()):(a=>{a&&r.push(a);l()})(e.duplicateCriteria.value.reduce((a,
f)=>{a.push(kb.filter.query.create(b.fieldInfos.parallelize[f.value.external.value],f.value.operator.value,g[b.fieldInfos.parallelize[f.value.internal.value].code]));return a},[]).join(" and "))}catch(a){kb.alert(kb.error.parse(a)),m()}},error:l=>{try{if(e.errorMessage.value||e.errorField.value.length!=0){var a=kb.filter.scan(b.app,g,e.errorFilter.value);a?(e.errorField.value.each((f,h)=>{f.value.field.value in b.fieldInfos.parallelize&&(n=>{n.tableCode?a[n.tableCode].value.each((B,C)=>{B.value[f.value.field.value].error=
f.value.message.value}):g[f.value.field.value].error=f.value.message.value})(b.fieldInfos.parallelize[f.value.field.value])}),v||kb.loadEnd(),p({error:!0,message:e.errorMessage.value})):l()}else l()}catch(f){kb.alert(kb.error.parse(f)),m()}},numbering:l=>{try{if(e.numberingField.value in b.fieldInfos.parallelize)if(g[e.numberingField.value].value)l();else{var a="",f=e.numberingGroup.value.reduce((h,n)=>{if(n.value.field.value in b.fieldInfos.parallelize)switch(a+=g[n.value.field.value].value,b.fieldInfos.parallelize[n.value.field.value].type){case "DROP_DOWN":case "RADIO_BUTTON":h.push(n.value.field.value+
' in ("'+g[n.value.field.value].value+'")');break;default:h.push(n.value.field.value+'="'+g[n.value.field.value].value+'"')}return h},"$id"in g?['$id!="'+g.$id.value+'"']:[]);a in w?(w[a]++,g[e.numberingField.value].value=a+w[a].toString().lpad("0",parseInt(e.numberingDigits.value)),l()):kintone.api(kintone.api.url("/k/v1/records",!0),"GET",{app:b.app.id,query:f.join(" and ")+" order by "+e.numberingField.value+" desc limit 1 offset 0"}).then(h=>{h=h.records;var n=0;h.length!=0&&(n=parseInt((h.first()[e.numberingField.value].value||
" ").replace(/[ ]+/g,"").replace(new RegExp("^"+a,"g"),"")),kb.isNumeric(n)||(n=0));n++;h=n;w[a]=h;g[e.numberingField.value].value=a+h.toString().lpad("0",parseInt(e.numberingDigits.value));l()}).catch(h=>{kb.alert(kb.error.parse(h));m()})}else l()}catch(h){kb.alert(kb.error.parse(h)),m()}},prompt:l=>{try{(a=>{a.length!=0?(f=>{a.each((h,n)=>{f.append(kb.field.activate(kb.field.create(h).css({width:"100%"}),b.app,!1))});v||kb.loadEnd();(new KintoneBoosterPopupform(f,600,"full",{ok:()=>{var h=kb.record.get(f,
b.app,!0);a.each((n,B)=>{g[n.code].value=h.record[n.code].value});v||kb.loadStart();l()},cancel:()=>{v||kb.loadStart();l()}})).show()})(kb.create("div").addClass("kb-scope").attr("form-id","form_"+b.app.id)):l()})(e.promptField.value.reduce((a,f)=>{f.value.field.value in b.fieldInfos.parallelize&&(e.promptOverwrite.value.includes("overwrite")?a.push(b.fieldInfos.parallelize[f.value.field.value]):kb.field.isEmpty(g[f.value.field.value].value)&&a.push(b.fieldInfos.parallelize[f.value.field.value]));
return a},[]))}catch(a){kb.alert(kb.error.parse(a)),m()}},verify:l=>{try{(a=>{a.length!=0?(f=>{a.each((h,n)=>{f.append(kb.field.activate(kb.field.create(h).addClass("kb-readonly").css({width:"100%"}),b.app,!1))});kb.record.set(f,b.app,g);v||kb.loadEnd();(new KintoneBoosterPopupform(f,600,"full",{ok:()=>{v||kb.loadStart();l()},cancel:()=>{v||kb.loadEnd();p({error:!0})}})).show()})(kb.create("div").addClass("kb-scope kb-verify").attr("form-id","form_"+b.app.id).append(kb.create("p").html(e.verifyMessage.value))):
l()})(e.verifyField.value.reduce((a,f)=>{f.value.field.value in b.fieldInfos.parallelize&&a.push(b.fieldInfos.parallelize[f.value.field.value]);return a},[]))}catch(a){kb.alert(kb.error.parse(a)),m()}}};q.numbering(()=>{y!="saved"?q.prompt(()=>{q.verify(()=>{q.error(()=>{q.duplicate(()=>{u()})})})}):u()})}else u()}).catch(x=>{kb.alert(kb.error.parse(x));m()}):u()})(c[d])};v||kb.loadStart();t(0,()=>{v||kb.loadEnd();r.length!=0?kintone.api(kintone.api.url("/k/v1/records",!0),"GET",{app:b.app.id,query:((d,
k)=>(k?"$id!="+k+" and ("+d+")":d)+" order by $id asc limit 5 offset 0")(r.map(d=>"("+d+")").join(" or "),"$id"in g?g.$id.value:"")}).then(d=>{d.records.length!=0?kb.confirm((k=>{d.records.each(u=>{k.append(kb.create("p").css({margin:"0"}).append(kb.create("a").attr("href",kb.record.page.detail(b.mobile,b.app.id,u.$id.value)).attr("target","_blank").html("Record No: "+u.$id.value)))});return k})(kb.create("div").append(kb.create("p").css({margin:"0"}).html(kb.constants.submit.message.duplicate[kb.operator.language]))),
k=>{p({error:k})},!0):p({error:!1})}).catch(d=>{kb.alert(kb.error.parse(d),()=>{p({error:!1})})}):p({error:!1})})});kintone.events.on("app.record.create.submit app.record.detail.process.proceed app.record.edit.submit app.record.index.show mobile.app.record.create.submit mobile.app.record.detail.process.proceed mobile.app.record.edit.submit mobile.app.record.index.show".split(" "),c=>new Promise((g,v)=>{((w,y)=>{b.mobile=w;b.type=y;kb.config[z].config.get().then(p=>{Object.keys(p).length!=0?kb.field.load(kb.config[z].app,
!0).then(m=>{b.app={id:kb.config[z].app,fields:m.origin};b.fieldInfos=m;try{(r=>{if(r.length!=0)switch(b.type){case "create":case "edit":A(r,c.record).then(d=>{d.error&&(c.error="message"in d?d.message:kb.constants.submit.message.cancel.submit[kb.operator.language]);g(c)}).catch(()=>{c.error=kb.constants.submit.message.cancel.submit[kb.operator.language];g(c)});(d=>{if(d.length!=0)kintone.events.on((b.mobile?"mobile.":"")+"app.record."+b.type+".submit.success",k=>new Promise((u,e)=>{var x=q=>{(l=>
{kb.filter.scan(b.app,k.record,l.condition.value)?kb.filter.auth(l.user.value,l.organization.value,l.group.value).then(a=>{if(a){a=l.url.value;var f=k.record,h;for(h in f)a=a.replace(new RegExp("%"+h+"%","g"),kb.field.stringify(b.fieldInfos.parallelize[h],f[h].value," / "));k.url=a}q++;q<d.length&&x(q)}).catch(a=>{q++;q<d.length&&x(q)}):(q++,q<d.length&&x(q))})(d[q])};x(0);u(k)}))})(r.filter(d=>d.url.value));break;case "process":(d=>{d.length!=0?A(d,c.record).then(k=>{k.error&&(c.error="message"in
k?k.message:kb.constants.submit.message.cancel.submit[kb.operator.language]);g(c)}).catch(()=>{c.error=kb.constants.submit.message.cancel.submit[kb.operator.language];g(c)}):g(c)})(r.filter(d=>d.action.value==c.action.value+":"+c.status.value+":"+c.nextStatus.value));break;case "index":var t=d=>{(k=>{kb.filter.auth(k.user.value,k.organization.value,k.group.value).then(u=>{u&&(k.view.value&&k.view.value!=c.viewId.toString()||kb.button.create(b.mobile,b.type,"kb-submit-button"+d.toString(),k.label.value,
k.message.value,()=>{kb.view.records.get(b.app.id,(b.mobile?kintone.mobile.app:kintone.app).getQueryCondition(),(e=>{e=e.match(/order by/g)?e.replace(/^.*order by/g,""):"";return(e=e.replace(/limit [0-9]+/g,"").replace(/ offset [0-9]+/g,"").replace(/^[ ]+/g,"").replace(/[ ]+$/g,""))?e:"$id asc"})((b.mobile?kintone.mobile.app:kintone.app).getQuery())).then(e=>{var x={},q=[];let l=(a,f)=>{A([k],e[a],!0,x,"saved").then(h=>{h.error?f(!0):(q.push(kb.view.records.transform(e[a])),kb.progressUpdate(),a++,
a<e.length?l(a,f):f())}).catch(()=>{})};e.length!=0?(kb.progressStart(e.length),l(0,a=>{a||kb.view.records.set(b.app.id,{put:q}).then(f=>kb.alert("Done!",()=>window.location.reload(!0))).catch(f=>kb.alert(kb.error.parse(f)))})):kb.alert("There are no records.")}).catch(e=>kb.alert(kb.error.parse(e)))}));d++;d<r.length&&t(d)}).catch(u=>{d++;d<r.length&&t(d)})})(r[d])};t(0);g(c)}else g(c)})(JSON.parse(p.tab).map((r,t)=>kb.extend({sIndex:{value:t.toString()}},r.setting)).reduce((r,t)=>{(b.mobile?["all",
"both","mobile"]:["all","both","pc"]).includes(t.device.value)&&t.event.value.includes(b.type)&&r.push(t);return r},[]))}catch(r){kb.alert(kb.error.parse(r)),g(c)}}).catch(m=>g(c)):g(c)}).catch(p=>g(c))})(c.type.split(".").first()=="mobile",c.type.split(".").slice(-2).first())}));kb.event.on("kb.submit.call",c=>new Promise((g,v)=>{kb.config[z].config.get().then(w=>{Object.keys(w).length!=0?kb.field.load(kb.config[z].app,!0).then(y=>{b.app={id:kb.config[z].app,fields:y.origin};b.fieldInfos=y;try{(p=>
{p.length!=0?A(p,c.record,!0,c.numbering).then(m=>{m.error?(c.error=!0,m.message?kb.alert(m.message,()=>g(c)):g(c)):g(c)}).catch(()=>{c.error=!0;g(c)}):g(c)})(JSON.parse(w.tab).map((p,m)=>kb.extend({sIndex:{value:m.toString()}},p.setting)).reduce((p,m)=>{(c.mobile?["all","both","mobile"]:["all","both","pc"]).includes(m.device.value)&&m.event.value.includes(c.pattern)&&p.push(m);return p},[]))}catch(p){kb.alert(kb.error.parse(p)),g(c)}}).catch(y=>g(c)):g(c)}).catch(w=>g(c))}))})(kintone.$PLUGIN_ID);
kb.constants=kb.extend({submit:{message:{cancel:{process:{en:"The process action was canceled.",ja:"\u30d7\u30ed\u30bb\u30b9\u30a2\u30af\u30b7\u30e7\u30f3\u304c\u30ad\u30e3\u30f3\u30bb\u30eb\u3055\u308c\u307e\u3057\u305f\u3002",zh:"\u8fdb\u7a0b\u64cd\u4f5c\u5df2\u88ab\u53d6\u6d88\u3002","zh-TW":"\u8655\u7406\u64cd\u4f5c\u5df2\u88ab\u53d6\u6d88\u3002"},submit:{en:"The submit was canceled.",ja:"\u4fdd\u5b58\u304c\u30ad\u30e3\u30f3\u30bb\u30eb\u3055\u308c\u307e\u3057\u305f\u3002",zh:"\u4fdd\u5b58\u5df2\u88ab\u53d6\u6d88\u3002",
"zh-TW":"\u63d0\u4ea4\u5df2\u88ab\u53d6\u6d88\u3002"}},duplicate:{en:"A similar record already exists. Would you like to proceed with the registration anyway?",ja:"\u985e\u4f3c\u30ec\u30b3\u30fc\u30c9\u304c\u65e2\u306b\u767b\u9332\u3055\u308c\u3066\u3044\u307e\u3059\u304c\u3001\u3053\u306e\u307e\u307e\u767b\u9332\u3057\u3066\u3082\u5b9c\u3057\u3044\u3067\u3059\u304b\uff1f",zh:"\u5df2\u7ecf\u6709\u7c7b\u4f3c\u7684\u8bb0\u5f55\u5b58\u5728\u4e86\uff0c\u60a8\u8fd8\u8981\u7ee7\u7eed\u6ce8\u518c\u5417\uff1f",
"zh-TW":"\u5df2\u7d93\u6709\u985e\u4f3c\u7684\u8a18\u9304\u5b58\u5728\u4e86\uff0c\u60a8\u9084\u8981\u7e7c\u7e8c\u8a3b\u518a\u55ce\uff1f"}}}},kb.constants);