/*
* FileName "plugins.imap.js"
* Version: 1.0.0
* Copyright (c) 2023 Pandafirm LLC
* Distributed under the terms of the GNU Lesser General Public License.
* https://opensource.org/licenses/LGPL-2.1
*/
'use strict';(y=>{var e={},A=b=>new Promise((q,m)=>{((k,t)=>{t.append(kb.create("div").addClass("kb-row").append(kb.field.activate(kb.field.create(k.fields.from).css({width:"50%"}),k,!1)).append(kb.field.activate(kb.field.create(k.fields.to).css({width:"50%"}),k,!1))).append(kb.create("div").addClass("kb-row").append(kb.field.activate(kb.field.create(k.fields.sender).css({width:"100%"}),k,!1)));kb.record.set(t,k,e.filter?e.filter:{from:{value:(new Date).format("Y-m-d")},to:{value:(new Date).format("Y-m-d")},
sender:{value:""}});(new KintoneBoosterPopupform(t,600,null,{ok:()=>{e.filter=kb.record.get(t,k,!0).record;fetch("https://api.kintone-booster.com/mail/rv",{method:"GET",headers:{"X-Requested-With":"XMLHttpRequest"}}).then(n=>{n.json().then(u=>{switch(n.status){case 200:(c=>{kb.loadStart();kb.encrypt(JSON.stringify(c),u.passphrase).then(g=>{fetch("https://api.kintone-booster.com/mail/rv",{method:"POST",headers:{"X-Requested-With":"XMLHttpRequest"},body:JSON.stringify({data:g.data,iv:g.iv,tag:g.tag})}).then(h=>
{h.json().then(a=>{switch(h.status){case 200:var r=[],v=[],p=(d,f)=>{0!=r.length?kb.file.upload((l=>{var w=atob(l.binary),x=new Uint8Array(w.length);w.length.each(z=>x[z]=w.charCodeAt(z));return new File([new Blob([x.buffer],{type:l.contentType})],l.filename,{type:l.contentType})})(r[d]),!0).then(l=>{a[v[d].json].attachment[v[d].attachment]=l;d++;d<r.length?p(d,f):f()}).catch(l=>{kb.alert(kb.error.parse(l));m()}):f()};r=a.reduce((d,f,l)=>{0!=f.attachment.length&&f.attachment.each((w,x)=>{d.push(w);
v.push({json:l,attachment:x})});return d},[]);p(0,()=>q(a));break;default:kb.alert(kb.error.parse(a)),m()}})}).catch(h=>{kb.alert(kb.error.parse(h));m()})}).catch(g=>{kb.loadEnd();m()})})({host:b.host.value,port:b.port.value,option:b.option.value?b.option.value:"/imap/ssl",mailbox:b.mailbox.value?b.mailbox.value:"INBOX",author:b.author.value,pwd:b.pwd.value,criteria:(()=>{var c='SINCE "'+e.filter.from.value+'" BEFORE "'+(new Date(e.filter.to.value)).calc("1 day").format("Y-m-d")+'"';e.filter.sender.value&&
(c+=' FROM "'+e.filter.sender.value+'"');return c})()});break;default:kb.alert(kb.error.parse(u)),m()}})}).catch(n=>{kb.alert(kb.error.parse(n));m()})},cancel:()=>m()})).show()})({id:"IMAP_filter",fields:{from:{code:"from",type:"DATE",label:kb.constants.imap.caption.from[kb.operator.language],required:!0,noLabel:!1},to:{code:"to",type:"DATE",label:kb.constants.imap.caption.to[kb.operator.language],required:!0,noLabel:!1},sender:{code:"sender",type:"SINGLE_LINE_TEXT",label:kb.constants.imap.caption.sender[kb.operator.language],
required:!0,noLabel:!1,format:"mail"}}},kb.create("div").addClass("kb-scope").attr("form-id","form_IMAP_filter"))});kintone.events.on(["app.record.index.show","mobile.app.record.index.show"],b=>new Promise((q,m)=>{((k,t)=>{e.mobile=k;e.type=t;kb.config[y].config.get().then(n=>{0!=Object.keys(n).length?kb.field.load(kb.config[y].app,!0).then(u=>{e.app={id:kb.config[y].app,fields:u.origin};e.fieldInfos=u;try{(c=>{if(0!=c.length){var g=h=>{(a=>{kb.filter.auth(a.user.value,a.organization.value,a.group.value).then(r=>
{r&&(a.view.value&&a.view.value!=b.viewId.toString()||kb.button.create(e.mobile,e.type,"kb-imap-button"+h.toString(),a.label.value,a.message.value,()=>{A(a).then(v=>{0!=v.length?kb.view.records.set(e.app.id,{post:v.reduce((p,d)=>{var f={};f[a.uid.value]={value:d.uid};f[a.from.value]={value:d.from};f[a.date.value]={value:(new Date(d.date)).format("ISO")};f[a.subject.value]={value:d.subject};f[a.body.value]={value:d.body};f[a.attachment.value]={value:d.attachment};p.push(f);return p},[])},!0).then(p=>
kb.alert("Done!",()=>window.location.reload(!0))).catch(p=>kb.alert(kb.error.parse(p))):kb.alert("There are no emails.")}).catch(()=>{})}));h++;h<c.length&&g(h)}).catch(r=>{h++;h<c.length&&g(h)})})(c[h])};g(0)}q(b)})(JSON.parse(n.tab).map((c,g)=>kb.extend({sIndex:{value:g.toString()}},c.setting)).reduce((c,g)=>{(e.mobile?["both","mobile"]:["both","pc"]).includes(g.device.value)&&c.push(g);return c},[]))}catch(c){kb.alert(kb.error.parse(c)),q(b)}}).catch(u=>q(b)):q(b)}).catch(n=>q(b))})("mobile"==
b.type.split(".").first(),b.type.split(".").slice(-2).first())}))})(kintone.$PLUGIN_ID);kb.constants=kb.extend({imap:{caption:{from:{en:"Since",ja:"\u4ee5\u964d",zh:"\u4ee5\u540e"},sender:{en:"Sender",ja:"\u5dee\u51fa\u4eba",zh:"\u53d1\u4ef6\u4eba"},to:{en:"Before",ja:"\u4ee5\u524d",zh:"\u4ee5\u524d"}}}},kb.constants);