/*
* FileName "plugins.style.js"
* Version: 1.0.0
* Copyright (c) 2023 Pandafirm LLC
* Distributed under the terms of the GNU Lesser General Public License.
* https://opensource.org/licenses/LGPL-2.1
*/
'use strict';(w=>{var b={handlers:{}},z=(f,h,v,t="record")=>{var u=(()=>{var p={},l=0;if("record"==t)for(var q in h)q in b.fieldInfos.tables&&h[q].value.each((n,d)=>{null==n.id&&(l++,n.id=l);p[n.id]=d},{});return p})();return new Promise((p,l)=>{var q={},n=(d,k)=>{(m=>{var g=kb.filter.scan(b.app,h,m.condition.value);g?kb.filter.auth(m.user.value,m.organization.value,m.group.value).then(x=>{x&&(m.color.value.map(c=>c.value).each((c,y)=>{c.field.value in b.fieldInfos.parallelize&&(a=>{switch(t){case "record":a.tableCode?
a.tableCode in g&&(e=>{if(b.mobile)e();else if(kb.elms(".subtable-"+b.fieldInfos.tables[a.tableCode].id+" tbody tr").length!=h[a.tableCode].value.length){let r=new MutationObserver(()=>{kb.elms(".subtable-"+b.fieldInfos.tables[a.tableCode].id+" tbody tr").length==h[a.tableCode].value.length&&(e(),r.disconnect())});r.observe(kb.elm(".subtable-"+b.fieldInfos.tables[a.tableCode].id),{childList:!0,subtree:!0})}else e()})(()=>{g[a.tableCode].value.each((e,r)=>{a.code in e.value&&(r=kb.field.get(a,b.mobile,
b.type))&&(r[u[e.id]].value.css({backgroundColor:c.backcolor.value,color:c.forecolor.value}),c.backcolor.value?r[u[e.id]].value.addClass("kb-inherit-backcolor"):r[u[e.id]].value.removeClass("kb-inherit-backcolor"),c.forecolor.value?r[u[e.id]].value.addClass("kb-inherit-forecolor"):r[u[e.id]].value.removeClass("kb-inherit-forecolor"))})}):a.code in g&&(e=>{e&&(e.value.css({backgroundColor:c.backcolor.value,color:c.forecolor.value}),c.backcolor.value?e.value.addClass("kb-inherit-backcolor"):e.value.removeClass("kb-inherit-backcolor"),
c.forecolor.value?e.value.addClass("kb-inherit-forecolor"):e.value.removeClass("kb-inherit-forecolor"))})(kb.field.get(a,b.mobile,b.type));break;case "view":a.tableCode?a.tableCode in g&&g[a.tableCode].value.each((e,r)=>{a.code in e.value&&(e.value[a.code].backcolor=c.backcolor.value,e.value[a.code].forecolor=c.forecolor.value)}):a.code in g&&(g[a.code].backcolor=c.backcolor.value,g[a.code].forecolor=c.forecolor.value)}})(b.fieldInfos.parallelize[c.field.value])}),m.display.value.map(c=>c.value).each((c,
y)=>{switch(t){case "record":(b.mobile?kintone.mobile.app.record:kintone.app.record).setFieldShown(c.field.value,"show"==c.state.value);break;case "view":c.field.value in b.fieldInfos.groups?b.fieldInfos.groups[c.field.value].fields.map(a=>a.code).each((a,e)=>{a in b.fieldInfos.parallelize&&a in g&&(g[a].hidden="hide"==c.state.value)}):c.field.value in b.fieldInfos.tables?c.field.value in g&&(g[c.field.value].hidden="hide"==c.state.value):(a=>{a.tableCode?a.tableCode in g&&g[a.tableCode].value.each((e,
r)=>{a.code in e.value&&(e.value[a.code].hidden="hide"==c.state.value)}):a.code in g&&(g[a.code].hidden="hide"==c.state.value)})(b.fieldInfos.parallelize[c.field.value])}}),m.toggle.value.map(c=>c.value).each((c,y)=>{switch(t){case "record":(b.mobile?kintone.mobile.app.record:kintone.app.record).setGroupFieldOpen(c.field.value,"open"==c.state.value)}}),(["create","edit"].includes(b.type)||"view"==t)&&m.editable.value.map(c=>c.value).each((c,y)=>{c.field.value in b.fieldInfos.parallelize&&(a=>{b.fieldInfos.disables.includes(a.code)||
(a.tableCode?a.tableCode in g&&(g[a.tableCode].value.each((e,r)=>{a.code in e.value&&(e.value[a.code].disabled="disable"==c.state.value)}),q[a.code]=h[a.tableCode].value.map(e=>e.value[a.code].disabled?"disabled":"")):a.code in g&&(g[a.code].disabled="disable"==c.state.value,q[a.code]=h[a.code].disabled?"disabled":""))})(b.fieldInfos.parallelize[c.field.value])}));d++;d<f.length?n(d,k):k()}).catch(x=>{kb.alert(kb.error.parse(x));l()}):(d++,d<f.length?n(d,k):k())})(f[d])};n(0,()=>{v.latest?v.latest.style||
(v.latest.style="{}"):v.latest={style:"{}"};var d=JSON.stringify(q),k="{}"!=d?v.latest.style!=d:!1;k&&(v.latest.style=d);p({performed:k})})})};kintone.events.on("app.record.create.show app.record.detail.show app.record.edit.show app.record.print.show mobile.app.record.create.show mobile.app.record.detail.show mobile.app.record.edit.show".split(" "),f=>new Promise((h,v)=>{((t,u)=>{b.mobile=t;b.type=u;for(var p in b.handlers)b.handlers[p].each((l,q)=>{kintone.events.off(p,l)});kb.config[w].config.get().then(l=>
{0!=Object.keys(l).length?(f.reuse&&(q=>{"reusecolor"in q&&q.reusecolor.value&&kintone.app.record.getHeaderMenuSpaceElement().nextSibling.firstElementChild.css({backgroundColor:q.reusecolor.value})})(JSON.parse(l.flat)),kb.field.load(kb.config[w].app,!0).then(q=>{b.app={id:kb.config[w].app,fields:q.origin};b.fieldInfos=q;try{(n=>{0!=n.length?(["create","edit"].includes(b.type)&&((d,k)=>{kintone.events.on(d,k);d.each((m,g)=>{m in b.handlers||(b.handlers[m]=[]);b.handlers[m].push(k)})})(q.changes.reduce((d,
k)=>{d.push("app.record.create.change."+k);d.push("app.record.edit.change."+k);d.push("mobile.app.record.create.change."+k);d.push("mobile.app.record.edit.change."+k);return d},[]),d=>{if((()=>{var k=!0;["DATETIME","TIME"].includes(d.changes.field.type)&&(m=>{m&&(Array.isArray(m)?m:[m]).each((g,x)=>{g.elm(".control-errors-content-gaia")&&(k=!1)})})(kb.field.get(b.fieldInfos.parallelize[d.type.split(".").last()],b.mobile,b.type));return k})())return kb.event.call("kb.action.installed",{installed:!1,
mobile:b.mobile}).then(k=>{k.installed||z(n,d.record,kb.elm("body"),"record").then(m=>{m.performed&&(b.mobile?kintone.mobile.app.record:kintone.app.record).set(d)}).catch(()=>{})}),d}),kb.event.call("kb.action.installed",{installed:!1,mobile:b.mobile}).then(d=>{d.installed||z(n,f.record,kb.elm("body"),"record").then(k=>h(f)).catch(()=>{})})):h(f)})(JSON.parse(l.tab).map((n,d)=>kb.extend({sIndex:{value:d.toString()}},n.setting)).reduce((n,d)=>{(b.mobile?["all","both","mobile"]:["all","both","pc"]).includes(d.device.value)&&
d.page.value.includes(b.type)&&n.push(d);return n},[]))}catch(n){kb.alert(kb.error.parse(n)),h(f)}}).catch(q=>h(f))):h(f)}).catch(l=>h(f))})("mobile"==f.type.split(".").first(),f.type.split(".").slice(-2).first())}));kb.event.on("kb.style.call",f=>new Promise((h,v)=>{kb.config[w].config.get().then(t=>{0!=Object.keys(t).length?kb.field.load(kb.config[w].app,!0).then(u=>{b.app={id:kb.config[w].app,fields:u.origin};b.fieldInfos=u;try{(p=>{0!=p.length?z(p,f.record,f.container,f.workplace?f.workplace:
"record").then(l=>{f.performed=l.performed;h(f)}).catch(()=>h(f)):h(f)})(JSON.parse(t.tab).map((p,l)=>kb.extend({sIndex:{value:l.toString()}},p.setting)).reduce((p,l)=>{(f.mobile?["all","both","mobile"]:["all","both","pc"]).includes(l.device.value)&&l.page.value.includes(f.pattern)&&p.push(l);return p},[]))}catch(p){kb.alert(kb.error.parse(p)),h(f)}}).catch(u=>h(f)):h(f)}).catch(t=>h(f))}))})(kintone.$PLUGIN_ID);
