/*
* FileName "plugins.omail.js"
* Version: 1.0.0
* Copyright (c) 2023 Pandafirm LLC
* Distributed under the terms of the GNU Lesser General Public License.
* https://opensource.org/licenses/LGPL-2.1
*/
'use strict';(z=>{var d={},B=(b,g,C=!1)=>new Promise((t,q)=>{var l="",r=(f,h)=>{var e=()=>{f++;f<b.length?r(f,h):h()};(a=>{var p=kb.filter.scan(d.app,g,a.condition.value);p?kb.filter.auth(a.user.value,a.organization.value,a.group.value).then(u=>{if(u){var x=(k,m,w)=>{"HTML"==a.format.value&&(k=k.replace(/\r/g,"").replace(/\n/g,"<br>"));for(var c in m){var v=m[c].value;c in d.fieldInfos.parallelize&&("HTML"==a.format.value&&"MULTI_LINE_TEXT"==d.fieldInfos.parallelize[c].type&&(v=v.replace(/\r/g,"").replace(/\n/g,
"<br>")),k=k.replace(new RegExp("%"+c+"%","g"),kb.field.stringify(d.fieldInfos.parallelize[c],v," / ",!0)))}for(c in w)v=w[c].value,c in d.fieldInfos.parallelize&&("HTML"==a.format.value&&"MULTI_LINE_TEXT"==d.fieldInfos.parallelize[c].type&&(v=v.replace(/\r/g,"").replace(/\n/g,"<br>")),k=k.replace(new RegExp("%"+c+"%","g"),kb.field.stringify(d.fieldInfos.parallelize[c],v," / ",!0)));return k};(k=>{var m=w=>{(c=>{var v=(n,y)=>{if(0!=c.attachment.length){var D=!1;window.hasOwnProperty("kb_report_temp")&&
c.attachment[n].fileKey in window.kb_report_temp&&(D=!0);D?(c.attachment[n].data=window.kb_report_temp[c.attachment[n].fileKey],n++,n<c.attachment.length?v(n,y):y()):kb.file.download(c.attachment[n],!0).then(A=>{kb.field.blobToBase64(A,F=>{c.attachment[n].data=F;n++;n<c.attachment.length?v(n,y):y()})}).catch(A=>{kb.alert(kb.error.parse(A));q()})}else y()};v(0,()=>{kb.encrypt(JSON.stringify(c.data),l).then(n=>{var y=fetch,D="https://api.kintone-booster.com/mail/oauth/"+kb.operator.language,A=JSON,
F=A.stringify;c.data=n.data;c.iv=n.iv;c.tag=n.tag;y(D,{method:"POST",headers:{"X-Requested-With":"XMLHttpRequest"},body:F.call(A,c)}).then(E=>{E.json().then(G=>{switch(E.status){case 200:w++;w<k.length?m(w):e();break;default:kb.alert(kb.error.parse(G)),q()}})}).catch(E=>{kb.alert(kb.error.parse(E));q()})}).catch(n=>{q()})})})(k[w])};0!=k.length?m(0):e()})((()=>{var k=[];(d.fieldInfos.parallelize[a.to.value].tableCode?p[d.fieldInfos.parallelize[a.to.value].tableCode].value:[{value:p}]).each((m,w)=>
{m.value[a.to.value].value&&k.push({data:{client_id:a.client_id.value,client_secret:a.client_secret.value,author:a.author.value,sender:a.sender.value,subdomain:location.host.split(".")[0],provider:(c=>{c="";switch(a.provider.value){case "GMail":c="google";break;case "Exchange Online":c="microsoft"}return c})(a.provider.value),to:m.value[a.to.value].value,cc:x(a.cc.value,p,d.fieldInfos.parallelize[a.to.value].tableCode?m.value:{}),bcc:x(a.bcc.value,p,d.fieldInfos.parallelize[a.to.value].tableCode?
m.value:{}),html:"HTML"==a.format.value},subject:x(a.subject.value,p,d.fieldInfos.parallelize[a.to.value].tableCode?m.value:{}),body:x(a.body.value,p,d.fieldInfos.parallelize[a.to.value].tableCode?m.value:{}),attachment:(()=>{var c=[];a.attachment.value&&a.attachment.value in d.fieldInfos.parallelize&&(c=(d.fieldInfos.parallelize[a.attachment.value].tableCode?m.value:p)[a.attachment.value].value);return c})()})});return k})())}else e()}).catch(u=>{kb.alert(kb.error.parse(u));q()}):e()})(b[f])};fetch("https://api.kintone-booster.com/mail/oauth/"+
kb.operator.language,{method:"GET",headers:{"X-Requested-With":"XMLHttpRequest"}}).then(f=>{f.json().then(h=>{switch(f.status){case 200:l=h.passphrase;C||kb.loadStart();r(0,()=>{C||kb.loadEnd();t()});break;default:kb.alert(kb.error.parse(h)),q()}})}).catch(f=>{kb.alert(kb.error.parse(f));q()})});kintone.events.on("app.record.create.submit.success app.record.detail.process.proceed app.record.detail.show app.record.edit.submit.success app.record.index.show mobile.app.record.create.submit.success mobile.app.record.detail.process.proceed mobile.app.record.detail.show mobile.app.record.edit.submit.success mobile.app.record.index.show".split(" "),
b=>new Promise((g,C)=>{((t,q)=>{d.mobile=t;d.type=q;kb.config[z].config.get().then(l=>{0!=Object.keys(l).length?kb.field.load(kb.config[z].app,!0).then(r=>{d.app={id:kb.config[z].app,fields:r.origin};d.fieldInfos=r;try{(f=>{if(0!=f.length)switch(d.type){case "create":case "edit":B(f,b.record).then(e=>g(b)).catch(()=>{});break;case "process":(e=>{0!=e.length?B(e,b.record).then(a=>g(b)).catch(()=>{}):g(b)})(f.filter(e=>e.action.value==b.action.value+":"+b.status.value+":"+b.nextStatus.value));break;
case "detail":var h=e=>{(a=>{kb.filter.scan(d.app,b.record,a.condition.value)?kb.filter.auth(a.user.value,a.organization.value,a.group.value).then(p=>{p&&kb.button.create(d.mobile,d.type,"kb-mail-button"+e.toString(),a.label.value,a.message.value,()=>B([a],b.record).then(u=>kb.alert("Done!")).catch(()=>{}));e++;e<f.length&&h(e)}).catch(p=>{e++;e<f.length&&h(e)}):(e++,e<f.length&&h(e))})(f[e])};h(0);g(b);break;case "index":h=e=>{(a=>{kb.filter.auth(a.user.value,a.organization.value,a.group.value).then(p=>
{p&&(a.view.value&&a.view.value!=b.viewId.toString()||kb.button.create(d.mobile,d.type,"kb-mail-button"+e.toString(),a.label.value,a.message.value,()=>{kb.view.records.get(d.app.id,(d.mobile?kintone.mobile.app:kintone.app).getQueryCondition()).then(u=>{let x=(k,m)=>{B([a],u[k],!0).then(w=>{kb.progressUpdate();k++;k<u.length?x(k,m):m()}).catch(()=>{})};0!=u.length?(kb.progressStart(u.length),x(0,()=>kb.alert("Done!"))):kb.alert("There are no records.")}).catch(u=>kb.alert(kb.error.parse(u)))}));e++;
e<f.length&&h(e)}).catch(p=>{e++;e<f.length&&h(e)})})(f[e])},h(0),g(b)}else g(b)})(JSON.parse(l.tab).map((f,h)=>kb.extend({sIndex:{value:h.toString()}},f.setting)).reduce((f,h)=>{(d.mobile?["all","both","mobile"]:["all","both","pc"]).includes(h.device.value)&&h.event.value.includes(d.type)&&f.push(h);return f},[]))}catch(f){kb.alert(kb.error.parse(f)),g(b)}}).catch(r=>g(b)):g(b)}).catch(l=>g(b))})("mobile"==b.type.split(".").first(),(t=>{switch(t){case "submit":t=b.type.split(".").slice(-3).first()}return t})(b.type.split(".").slice(-2).first()))}));
kb.event.on("kb.omail.call",b=>new Promise((g,C)=>{kb.config[z].config.get().then(t=>{0!=Object.keys(t).length?kb.field.load(kb.config[z].app,!0).then(q=>{d.app={id:kb.config[z].app,fields:q.origin};d.fieldInfos=q;try{(l=>{0!=l.length?B(l,b.record,!0).then(r=>g(b)).catch(()=>g(b)):g(b)})(JSON.parse(t.tab).map((l,r)=>kb.extend({sIndex:{value:r.toString()}},l.setting)).reduce((l,r)=>{(b.mobile?["all","both","mobile"]:["all","both","pc"]).includes(r.device.value)&&r.event.value.includes(b.pattern)&&
l.push(r);return l},[]))}catch(l){kb.alert(kb.error.parse(l)),g(b)}}).catch(q=>g(b)):g(b)}).catch(t=>g(b))}))})(kintone.$PLUGIN_ID);
