/*
* FileName "plugins.restore.js"
* Version: 1.0.0
* Copyright (c) 2023 Pandafirm LLC
* Distributed under the terms of the GNU Lesser General Public License.
* https://opensource.org/licenses/LGPL-2.1
*/
(function(r){var p,t,u;kintone.events.on(["app.record.detail.show","mobile.app.record.detail.show"],function(b){return new Promise(function(k,C){(function(y,z){p=y;t=z;kb.config[r].config.get().then(function(q){0!=Object.keys(q).length?kb.field.load(kb.config[r].app,!0).then(function(v){u=v;try{(function(g){(function(l,w,e){l&&"comments"in e&&"record"in e&&kb.button.create(p,t,"kb-restore-button",function(){var c="";switch(kb.operator.language){case "en":c="Restore the record";break;case "ja":c="\u30ec\u30b3\u30fc\u30c9\u3092\u5fa9\u5143\u3059\u308b";
break;case "zh":c="\u6062\u590d\u8bb0\u5f55"}return c}(),function(){var c="";switch(kb.operator.language){case "en":c="May I restore the record?";break;case "ja":c="\u30ec\u30b3\u30fc\u30c9\u3092\u5fa9\u5143\u3057\u3066\u3082\u3044\u3044\u3067\u3059\u304b\uff1f";break;case "zh":c="\u6211\u53ef\u4ee5\u6062\u590d\u8bb0\u5f55\u5417\uff1f"}return c}(),function(){kb.field.load(l).then(function(c){(function(A){(function(m){kb.loadStart();kb.file.clone(m,!0).then(function(){kb.view.records.set(l,{post:[kb.view.records.transform(e.record,
"POST")]},!0).then(function(a){(function(f){kb.record.comments.set(l,a,e.comments,!0).then(function(d){return kb.alert("Done!",function(){return window.open(f)})})["catch"](function(d){return kb.alert(kb.error.parse(d))})})(kb.record.page.detail(p,l,a))})["catch"](function(a){return kb.alert(kb.error.parse(a))})})})(Object.values(A.external).reduce(function(m,a){"FILE"==a.type&&(a.tableCode?e.record[a.tableCode].value.each(function(f,d){f.value[a.code].value&&(f.value[a.code].value=f.value[a.code].value.reduce(function(n,
h){var x=w.filter(function(B){return B.name==h.name});0!=x.length&&(h.fileKey=x.first().fileKey,h.name=h.keepName,delete h.keepName,n.push(h));return n},[]),Array.prototype.push.apply(m,f.value[a.code].value))}):e.record[a.code].value&&(e.record[a.code].value=e.record[a.code].value.reduce(function(f,d){var n=w.filter(function(h){return h.name==d.name});0!=n.length&&(d.fileKey=n.first().fileKey,d.name=d.keepName,delete d.keepName,f.push(d));return f},[]),Array.prototype.push.apply(m,e.record[a.code].value)));
return m},[]))})({external:c.parallelize,internal:u.parallelize})})["catch"](function(c){return kb.alert(kb.error.parse(c))})})})(g.backupID.value in b.record?b.record[g.backupID.value].value:"",g.backupFile.value in b.record?b.record[g.backupFile.value].value:[],g.backupRecord.value in b.record?JSON.parse(b.record[g.backupRecord.value].value):{})})(JSON.parse(q.flat)),k(b)}catch(g){kb.alert(kb.error.parse(g)),k(b)}})["catch"](function(v){return k(b)}):k(b)})["catch"](function(q){return k(b)})})("mobile"==
b.type.split(".").first(),b.type.split(".").slice(-2).first())})})})(kintone.$PLUGIN_ID);