/*
* FileName "plugins.style.js"
* Version: 1.0.0
* Copyright (c) 2023 Pandafirm LLC
* Distributed under the terms of the GNU Lesser General Public License.
* https://opensource.org/licenses/LGPL-2.1
*/
(function(v){var b={},A=function(e,h,p){p=void 0===p?"record":p;var t=!1,q=function(){var l={},k=0;if("record"==p)for(var m in h)m in b.fieldInfos.tables&&h[m].value.each(function(f,n){null==f.id&&(k++,f.id=k);l[f.id]=n},{});return l}();return new Promise(function(l,k){var m=function(f,n){var u=function(){f++;f<e.length?m(f,n):n()};(function(r){var g=kb.filter.scan(b.app,h,r.condition.value);g?kb.filter.auth(r.user.value,r.organization.value,r.group.value).then(function(y){y&&(r.color.value.map(function(c){return c.value}).each(function(c,
z){c.field.value in b.fieldInfos.parallelize&&function(a){switch(p){case "record":a.tableCode?a.tableCode in g&&function(d){if(b.mobile)d();else if(kb.elms(".subtable-"+b.fieldInfos.tables[a.tableCode].id+" tbody tr").length!=h[a.tableCode].value.length){var w=new MutationObserver(function(){kb.elms(".subtable-"+b.fieldInfos.tables[a.tableCode].id+" tbody tr").length==h[a.tableCode].value.length&&(d(),w.disconnect())});w.observe(kb.elm(".subtable-"+b.fieldInfos.tables[a.tableCode].id),{childList:!0,
subtree:!0})}else d()}(function(){g[a.tableCode].value.each(function(d,w){if(a.code in d.value){var x=kb.field.get(a,b.mobile,b.type);x&&(x[q[d.id]].value.css({backgroundColor:c.backcolor.value,color:c.forecolor.value}),c.backcolor.value?x[q[d.id]].value.addClass("kb-inherit-backcolor"):x[q[d.id]].value.removeClass("kb-inherit-backcolor"),c.forecolor.value?x[q[d.id]].value.addClass("kb-inherit-forecolor"):x[q[d.id]].value.removeClass("kb-inherit-forecolor"))}})}):a.code in g&&function(d){d&&(d.value.css({backgroundColor:c.backcolor.value,
color:c.forecolor.value}),c.backcolor.value?d.value.addClass("kb-inherit-backcolor"):d.value.removeClass("kb-inherit-backcolor"),c.forecolor.value?d.value.addClass("kb-inherit-forecolor"):d.value.removeClass("kb-inherit-forecolor"))}(kb.field.get(a,b.mobile,b.type));break;case "view":a.tableCode?a.tableCode in g&&g[a.tableCode].value.each(function(d,w){a.code in d.value&&(d.value[a.code].backcolor=c.backcolor.value,d.value[a.code].forecolor=c.forecolor.value)}):a.code in g&&(g[a.code].backcolor=c.backcolor.value,
g[a.code].forecolor=c.forecolor.value)}}(b.fieldInfos.parallelize[c.field.value])}),r.display.value.map(function(c){return c.value}).each(function(c,z){switch(p){case "record":(b.mobile?kintone.mobile.app.record:kintone.app.record).setFieldShown(c.field.value,"show"==c.state.value);break;case "view":c.field.value in b.fieldInfos.groups?b.fieldInfos.groups[c.field.value].fields.map(function(a){return a.code}).each(function(a,d){a in b.fieldInfos.parallelize&&a in g&&(g[a].hidden="hide"==c.state.value)}):
c.field.value in b.fieldInfos.tables?c.field.value in g&&(g[c.field.value].hidden="hide"==c.state.value):function(a){a.tableCode?a.tableCode in g&&g[a.tableCode].value.each(function(d,w){a.code in d.value&&(d.value[a.code].hidden="hide"==c.state.value)}):a.code in g&&(g[a.code].hidden="hide"==c.state.value)}(b.fieldInfos.parallelize[c.field.value])}}),r.toggle.value.map(function(c){return c.value}).each(function(c,z){switch(p){case "record":(b.mobile?kintone.mobile.app.record:kintone.app.record).setGroupFieldOpen(c.field.value,
"open"==c.state.value)}}),["create","edit"].includes(b.type)&&r.editable.value.map(function(c){return c.value}).each(function(c,z){c.field.value in b.fieldInfos.parallelize&&function(a){b.fieldInfos.disables.includes(a.code)||(a.tableCode?a.tableCode in g&&g[a.tableCode].value.each(function(d,w){a.code in d.value&&(d.value[a.code].disabled="disable"==c.state.value,"record"==p&&(t=!0))}):a.code in g&&(g[a.code].disabled="disable"==c.state.value,"record"==p&&(t=!0)))}(b.fieldInfos.parallelize[c.field.value])}));
u()})["catch"](function(y){kb.alert(kb.error.parse(y));k()}):u()})(e[f])};m(0,function(){return l({performed:t})})})};kintone.events.on("app.record.create.show app.record.detail.show app.record.edit.show app.record.print.show mobile.app.record.create.show mobile.app.record.detail.show mobile.app.record.edit.show".split(" "),function(e){return new Promise(function(h,p){(function(t,q){b.mobile=t;b.type=q;kb.config[v].config.get().then(function(l){0!=Object.keys(l).length?(e.reuse&&function(k){"reusecolor"in
k&&k.reusecolor.value&&kintone.app.record.getHeaderMenuSpaceElement().nextSibling.firstElementChild.css({backgroundColor:k.reusecolor.value})}(JSON.parse(l.flat)),kb.field.load(kb.config[v].app,!0).then(function(k){b.app={id:kb.config[v].app,fields:k.origin};b.fieldInfos=k;try{(function(m){if(0!=m.length){if(["create","edit"].includes(b.type))kintone.events.on(k.changes.reduce(function(f,n){f.push("app.record.create.change."+n);f.push("app.record.edit.change."+n);f.push("mobile.app.record.create.change."+
n);f.push("mobile.app.record.edit.change."+n);return f},[]),function(f){if(function(){var n=!0;["DATETIME","TIME"].includes(f.changes.field.type)&&function(u){u&&(Array.isArray(u)?u:[u]).each(function(r,g){r.elm(".control-errors-content-gaia")&&(n=!1)})}(kb.field.get(b.fieldInfos.parallelize[f.type.split(".").last()],b.mobile,b.type));return n}())return kb.event.call("kb.action.installed",{installed:!1,mobile:b.mobile}).then(function(n){n.installed||A(m,f.record,"record").then(function(u){u.performed&&
(b.mobile?kintone.mobile.app.record:kintone.app.record).set(f)})["catch"](function(){})}),f});A(m,e.record,"record").then(function(f){return h(e)})["catch"](function(){})}else h(e)})((b.config?b.config:b.config=JSON.parse(l.tab)).reduce(function(m,f){(b.mobile?["both","mobile"]:["both","pc"]).includes(f.setting.device.value)&&f.setting.page.value.includes(b.type)&&m.push(f.setting);return m},[]))}catch(m){kb.alert(kb.error.parse(m)),h(e)}})["catch"](function(k){return h(e)})):h(e)})["catch"](function(l){return h(e)})})("mobile"==
e.type.split(".").first(),e.type.split(".").slice(-2).first())})});kb.event.on("kb.style.call",function(e){return new Promise(function(h,p){kb.config[v].config.get().then(function(t){0!=Object.keys(t).length?kb.field.load(kb.config[v].app,!0).then(function(q){b.app={id:kb.config[v].app,fields:q.origin};b.fieldInfos=q;try{(function(l){0!=l.length?A(l,e.record,e.workplace?e.workplace:"record").then(function(k){e.performed=k.performed;h(e)})["catch"](function(){return h(e)}):h(e)})((b.config?b.config:
b.config=JSON.parse(t.tab)).reduce(function(l,k){(e.mobile?["both","mobile"]:["both","pc"]).includes(k.setting.device.value)&&k.setting.page.value.includes(e.pattern)&&l.push(k.setting);return l},[]))}catch(l){kb.alert(kb.error.parse(l)),h(e)}})["catch"](function(q){return h(e)}):h(e)})["catch"](function(t){return h(e)})})})})(kintone.$PLUGIN_ID);