/*
* FileName "plugins.mail.js"
* Version: 1.0.0
* Copyright (c) 2023 Pandafirm LLC
* Distributed under the terms of the GNU Lesser General Public License.
* https://opensource.org/licenses/LGPL-2.1
*/
(function(E){var c={},D=function(d,l,u){u=void 0===u?!1:u;return new Promise(function(v,q){var x="",y=function(e,h){var b=function(){e++;u||kb.progressUpdate();e<d.length?y(e,h):h()};(function(a){var m=kb.filter.scan(c.app,l,a.condition.value);m?kb.filter.auth(a.user.value,a.organization.value,a.group.value).then(function(p){if(p){var z=function(f,k,r){"HTML"==a.format.value&&(f=f.replace(/\r/g,"").replace(/\n/g,"<br>"));for(var g in k)f=f.replace(new RegExp("%"+g+"%","g"),kb.field.stringify(c.fieldInfos.parallelize[g],
k[g].value," / "));for(g in r)f=f.replace(new RegExp("%"+g+"%","g"),kb.field.stringify(c.fieldInfos.parallelize[g],r[g].value," / "));return f};(function(f){var k=function(r){(function(g){var B=function(n,w){0!=g.attachment.length?kb.file.download(g.attachment[n],!0).then(function(t){kb.field.blobToBase64(t,function(A){g.attachment[n].data=A;n++;n<g.attachment.length?B(n,w):w()})})["catch"](function(t){kb.alert(kb.error.parse(t));q()}):w()};B(0,function(){kb.encrypt(JSON.stringify(g.data),x).then(function(n){var w=
fetch,t="https://api.kintone-booster.com/mail/"+kb.operator.language,A=JSON,F=A.stringify;g.data=n.data;g.iv=n.iv;g.tag=n.tag;w(t,{method:"POST",headers:{"X-Requested-With":"XMLHttpRequest"},body:F.call(A,g)}).then(function(C){C.json().then(function(G){switch(C.status){case 200:r++;r<f.length?k(r):b();break;default:kb.alert(kb.error.parse(G)),q()}})})["catch"](function(C){kb.alert(kb.error.parse(C));q()})})["catch"](function(n){q()})})})(f[r])};0!=f.length&&k(0)})(function(){var f=[];(c.fieldInfos.parallelize[a.to.value].tableCode?
m[c.fieldInfos.parallelize[a.to.value].tableCode].value:[m]).each(function(k,r){if(k[a.to.value].value){var g=f.push,B={mail:a.mail.value,sender:a.sender.value,host:a.host.value,port:a.port.value,author:a.author.value,pwd:a.pwd.value,secure:a.secure.value,to:k[a.to.value].value,cc:a.cc.value,bcc:a.bcc.value,html:"HTML"==a.format.value},n=z(a.subject.value,m,c.fieldInfos.parallelize[a.to.value].tableCode?k:{}),w=z(a.body.value,m,c.fieldInfos.parallelize[a.to.value].tableCode?k:{}),t=[];a.attachment.value&&
a.attachment.value in c.fieldInfos.parallelize&&(t=(c.fieldInfos.parallelize[a.attachment.value].tableCode?k:m)[a.attachment.value].value);g.call(f,{data:B,subject:n,body:w,attachment:t})}});return f}())}else b()})["catch"](function(p){kb.alert(kb.error.parse(p));q()}):b()})(d[e])};fetch("https://api.kintone-booster.com/mail/"+kb.operator.language,{method:"GET",headers:{"X-Requested-With":"XMLHttpRequest"}}).then(function(e){e.json().then(function(h){switch(e.status){case 200:x=h.passphrase;u||kb.progressStart(d.length);
y(0,function(){u||kb.progressEnd();v()});break;default:kb.alert(kb.error.parse(h)),q()}})})["catch"](function(e){kb.alert(kb.error.parse(e));q()})})};kintone.events.on("app.record.create.submit.success app.record.detail.process.proceed app.record.detail.show app.record.edit.submit.success app.record.index.show mobile.app.record.create.submit.success mobile.app.record.detail.process.proceed mobile.app.record.detail.show mobile.app.record.edit.submit.success mobile.app.record.index.show".split(" "),
function(d){return new Promise(function(l,u){(function(v,q){c.mobile=v;c.type=q;kb.config[E].config.get().then(function(x){0!=Object.keys(x).length?kb.field.load(kb.config[E].app,!0).then(function(y){c.app={id:kb.config[E].app,fields:y.origin};c.fieldInfos=y;try{(function(e){if(0!=e.length)switch(c.type){case "create":case "edit":D(e,d.record).then(function(b){return l(d)})["catch"](function(){});break;case "process":(function(b){0!=b.length?D(b,d.record).then(function(a){return l(d)})["catch"](function(){}):
l(d)})(e.filter(function(b){return b.action.value==d.action.value+":"+d.status.value+":"+d.nextStatus.value}));break;case "detail":var h=function(b){(function(a){kb.filter.scan(c.app,d.record,a.condition.value)?kb.filter.auth(a.user.value,a.organization.value,a.group.value).then(function(m){m&&kb.button.create(c.mobile,c.type,"kb-mail-button"+b.toString(),a.label.value,a.message.value,function(){return D([a],d.record).then(function(p){return kb.alert("Done!")})["catch"](function(){})});b++;b<e.length&&
h(b)})["catch"](function(m){b++;b<e.length&&h(b)}):(b++,b<e.length&&h(b))})(e[b])};h(0);l(d);break;case "index":h=function(b){(function(a){kb.filter.auth(a.user.value,a.organization.value,a.group.value).then(function(m){m&&(a.view.value&&a.view.value!=d.viewId.toString()||kb.button.create(c.mobile,c.type,"kb-mail-button"+b.toString(),a.label.value,a.message.value,function(){kb.view.records.get(c.app.id,(c.mobile?kintone.mobile.app:kintone.app).getQueryCondition()).then(function(p){var z=function(f,
k){D([a],p[f],!0).then(function(r){kb.progressUpdate();f++;f<p.length?z(f,k):k()})["catch"](function(){})};0!=p.length?(kb.progressStart(p.length),z(0,function(){return kb.alert("Done!")})):kb.alert("There are no records.")})["catch"](function(p){return kb.alert(kb.error.parse(p))})}));b++;b<e.length&&h(b)})["catch"](function(m){b++;b<e.length&&h(b)})})(e[b])},h(0),l(d)}else l(d)})((c.config?c.config:c.config=JSON.parse(x.tab)).reduce(function(e,h){(c.mobile?["both","mobile"]:["both","pc"]).includes(h.setting.device.value)&&
h.setting.event.value.includes(c.type)&&e.push(h.setting);return e},[]))}catch(e){kb.alert(kb.error.parse(e)),l(d)}})["catch"](function(y){return l(d)}):l(d)})["catch"](function(x){return l(d)})})("mobile"==d.type.split(".").first(),function(v){switch(v){case "submit":v=d.type.split(".").slice(-3).first()}return v}(d.type.split(".").slice(-2).first()))})})})(kintone.$PLUGIN_ID);