/*
* FileName "plugins.mail.js"
* Version: 1.0.0
* Copyright (c) 2023 Pandafirm LLC
* Distributed under the terms of the GNU Lesser General Public License.
* https://opensource.org/licenses/LGPL-2.1
*/
(function(E){var d={},D=function(c,h,u){u=void 0===u?!1:u;return new Promise(function(v,m){var x="",y=function(e,b){var p=function(){e++;u||kb.progressUpdate();e<c.length?y(e,b):b()};(function(a){var n=kb.filter.scan(d.app,h,a.condition.value);n?kb.filter.auth(a.user.value,a.organization.value,a.group.value).then(function(q){if(q){var z=function(g,l,r){"HTML"==a.format.value&&(g=g.replace(/\r/g,"").replace(/\n/g,"<br>"));for(var f in l)g=g.replace(new RegExp("%"+f+"%","g"),kb.field.stringify(d.fieldInfos.parallelize[f],
l[f].value," / "));for(f in r)g=g.replace(new RegExp("%"+f+"%","g"),kb.field.stringify(d.fieldInfos.parallelize[f],r[f].value," / "));return g};(function(g){var l=function(r){(function(f){var B=function(k,w){0!=f.attachment.length?kb.file.download(f.attachment[k],!0).then(function(t){kb.field.blobToBase64(t,function(A){f.attachment[k].data=A;k++;k<f.attachment.length?B(k,w):w()})})["catch"](function(t){kb.alert(kb.error.parse(t));m()}):w()};B(0,function(){kb.encrypt(JSON.stringify(f.data),x).then(function(k){var w=
fetch,t="https://api.kintone-booster.com/mail/"+kb.operator.language,A=JSON,F=A.stringify;f.data=k.data;f.iv=k.iv;f.tag=k.tag;w(t,{method:"POST",headers:{"X-Requested-With":"XMLHttpRequest"},body:F.call(A,f)}).then(function(C){C.json().then(function(G){switch(C.status){case 200:r++;r<g.length?l(r):p();break;default:kb.alert(kb.error.parse(G)),m()}})})["catch"](function(C){kb.alert(kb.error.parse(C));m()})})["catch"](function(k){m()})})})(g[r])};0!=g.length&&l(0)})(function(){var g=[];(d.fieldInfos.parallelize[a.to.value].tableCode?
n[d.fieldInfos.parallelize[a.to.value].tableCode].value:[n]).each(function(l,r){if(l[a.to.value].value){var f=g.push,B={mail:a.mail.value,sender:a.sender.value,host:a.host.value,port:a.port.value,author:a.author.value,pwd:a.pwd.value,secure:a.secure.value,to:l[a.to.value].value,cc:a.cc.value,bcc:a.bcc.value,html:"HTML"==a.format.value},k=z(a.subject.value,n,d.fieldInfos.parallelize[a.to.value].tableCode?l:{}),w=z(a.body.value,n,d.fieldInfos.parallelize[a.to.value].tableCode?l:{}),t=[];a.attachment.value&&
a.attachment.value in d.fieldInfos.parallelize&&(t=(d.fieldInfos.parallelize[a.attachment.value].tableCode?l:n)[a.attachment.value].value);f.call(g,{data:B,subject:k,body:w,attachment:t})}});return g}())}else p()})["catch"](function(q){kb.alert(kb.error.parse(q));m()}):p()})(c[e])};fetch("https://api.kintone-booster.com/mail/"+kb.operator.language,{method:"GET",headers:{"X-Requested-With":"XMLHttpRequest"}}).then(function(e){e.json().then(function(b){switch(e.status){case 200:x=b.passphrase;u||kb.progressStart(c.length);
y(0,function(){u||kb.progressEnd();v()});break;default:kb.alert(kb.error.parse(b)),m()}})})["catch"](function(e){kb.alert(kb.error.parse(e));m()})})};kintone.events.on("app.record.create.submit.success app.record.detail.process.proceed app.record.detail.show app.record.edit.submit.success app.record.index.show mobile.app.record.create.submit.success mobile.app.record.detail.process.proceed mobile.app.record.detail.show mobile.app.record.edit.submit.success mobile.app.record.index.show".split(" "),
function(c){return new Promise(function(h,u){(function(v,m){d.mobile=v;d.type=m;kb.config[E].config.get().then(function(x){0!=Object.keys(x).length?kb.field.load(kb.config[E].app,!0).then(function(y){d.app={id:kb.config[E].app,fields:y.origin};d.fieldInfos=y;try{(function(e){if(0!=e.length)switch(d.type){case "create":case "edit":D(e,c.record).then(function(b){return h(c)})["catch"](function(){});break;case "process":(function(b){0!=b.length?D(b,c.record).then(function(p){return h(c)})["catch"](function(){}):
h(c)})(e.filter(function(b){return b.action.value==c.action.value+":"+c.status.value+":"+c.nextStatus.value}));break;case "detail":e.each(function(b,p){kb.button.create(d.mobile,d.type,"kb-upsert-button"+p.toString(),b.label.value,b.message.value,function(){return D([b],c.record).then(function(a){return kb.alert("Done!")})["catch"](function(){})})});h(c);break;case "index":e.each(function(b,p){b.view.value&&b.view.value!=c.viewId.toString()||kb.button.create(d.mobile,d.type,"kb-upsert-button"+p.toString(),
b.label.value,b.message.value,function(){kb.view.records.get(d.app.id,(d.mobile?kintone.mobile.app:kintone.app).getQueryCondition()).then(function(a){var n=function(q,z){D([b],a[q],!0).then(function(g){kb.progressUpdate();q++;q<a.length?n(q,z):z()})["catch"](function(){})};0!=a.length?(kb.progressStart(a.length),n(0,function(){return kb.alert("Done!")})):kb.alert("There are no records.")})["catch"](function(a){return kb.alert(kb.error.parse(a))})})}),h(c)}else h(c)})(JSON.parse(x.tab).reduce(function(e,
b){(d.mobile?["both","mobile"]:["both","pc"]).includes(b.setting.device.value)&&b.setting.event.value.includes(d.type)&&e.push(b.setting);return e},[]))}catch(e){kb.alert(kb.error.parse(e)),h(c)}})["catch"](function(y){return h(c)}):h(c)})["catch"](function(x){return h(c)})})("mobile"==c.type.split(".").first(),function(v){switch(v){case "submit":v=c.type.split(".").slice(-3).first()}return v}(c.type.split(".").slice(-2).first()))})})})(kintone.$PLUGIN_ID);