/*
* FileName "plugins.delete.js"
* Version: 1.0.0
* Copyright (c) 2023 Pandafirm LLC
* Distributed under the terms of the GNU Lesser General Public License.
* https://opensource.org/licenses/LGPL-2.1
*/
(function(t){var l={},y=function(b,e){return new Promise(function(w,u){var n={suspend:function(f){try{var g=function(c,d){var m=function(){c++;c<b.length?g(c,d):d(!1)};(function(a){kb.filter.scan(l.app,e,a.condition.value)?kb.filter.auth(a.user.value,a.organization.value,a.group.value).then(function(p){p?a.suspendMessage.value?kb.filter.scan(l.app,e,a.suspendFilter.value)?a.suspendContinue.value.includes("continue")?kb.confirm(a.suspendMessage.value,function(v){v?d(v):m()},!0):kb.alert(a.suspendMessage.value,
function(){return d(!0)}):m():m():m()})["catch"](function(p){kb.alert(kb.error.parse(p));d(!0)}):m()})(b[c])};g(0,function(c){return f(c)})}catch(c){kb.alert(kb.error.parse(c)),f(!0)}},backup:function(f){try{var g=function(c,d){var m=function(){c++;c<b.length?g(c,d):d(!1)};(function(a){kb.filter.scan(l.app,e,a.condition.value)?kb.filter.auth(a.user.value,a.organization.value,a.group.value).then(function(p){p?a.backupApp.value?kintone.api(kintone.api.url("/k/v1/app",!0),"GET",{id:l.app.id}).then(function(v){kb.field.load(a.backupApp.value).then(function(x){(function(q){a.backupID.value in
q.external?a.backupName.value in q.external?a.backupUser.value in q.external?a.backupDatetime.value in q.external?a.backupFile.value in q.external?a.backupRecord.value in q.external?function(r){r.each(function(h,k){h.keepName=h.name;h.name="file_"+k.toString()+"."+h.name.split(".").last()});kb.file.clone(r,!0).then(function(){kb.record.comments.get(l.app.id,e.$id.value).then(function(h){kb.view.records.set(a.backupApp.value,{post:function(){var k={};k[a.backupID.value]={value:l.app.id};k[a.backupName.value]=
{value:v.name};k[a.backupUser.value]={value:[{code:kb.operator.code}]};k[a.backupDatetime.value]={value:(new Date).format("ISO")};k[a.backupFile.value]={value:r};k[a.backupRecord.value]={value:JSON.stringify({comments:h,record:e})};return[k]}()},!0).then(function(k){return m()})["catch"](function(k){kb.alert(kb.error.parse(k));d(!0)})})["catch"](function(h){kb.alert(kb.error.parse(h));d(!0)})})}(Object.values(q.internal).reduce(function(r,h){"FILE"==h.type&&(h.tableCode?e[h.tableCode].value.each(function(k,
z){k.value[h.code].value&&Array.prototype.push.apply(r,k.value[h.code].value)}):e[h.code].value&&Array.prototype.push.apply(r,e[h.code].value));return r},[])):(kb.alert("No field to backup was found"),d(!0)):(kb.alert("No field to backup was found"),d(!0)):(kb.alert("No field to backup was found"),d(!0)):(kb.alert("No field to backup was found"),d(!0)):(kb.alert("No field to backup was found"),d(!0)):(kb.alert("No field to backup was found"),d(!0))})({external:x.parallelize,internal:l.fieldInfos.parallelize})})["catch"](function(x){kb.alert(kb.error.parse(x));
d(!0)})})["catch"](function(v){kb.alert(kb.error.parse(v));d(!0)}):m():m()})["catch"](function(p){kb.alert(kb.error.parse(p));d(!0)}):m()})(b[c])};g(0,function(c){return f(c)})}catch(c){kb.alert(kb.error.parse(c)),f(!0)}}};n.suspend(function(f){f?w({error:f}):b.some(function(g){return g.backupApp.value})&&(kb.loadStart(),n.backup(function(g){kb.loadEnd();w({error:g})}))})})};kintone.events.on(["app.record.detail.delete.submit","app.record.index.delete.submit","mobile.app.record.detail.delete.submit"],
function(b){return new Promise(function(e,w){(function(u,n){l.mobile=u;l.type=n;kb.config[t].config.get().then(function(f){0!=Object.keys(f).length?kb.field.load(kb.config[t].app,!0).then(function(g){l.app={id:kb.config[t].app,fields:g.origin};l.fieldInfos=g;try{(function(c){0!=c.length?y(c,b.record).then(function(d){e(d.error?!1:b)})["catch"](function(){e(resp.error?!1:b)}):e(b)})(JSON.parse(f.tab).map(function(c,d){return kb.extend({sIndex:{value:d.toString()}},c.setting)}).reduce(function(c,d){(l.mobile?
["both","mobile"]:["both","pc"]).includes(d.device.value)&&c.push(d);return c},[]))}catch(c){kb.alert(kb.error.parse(c)),e(b)}})["catch"](function(g){return e(b)}):e(b)})["catch"](function(f){return e(b)})})("mobile"==b.type.split(".").first(),b.type.split(".").slice(-2).first())})});kb.event.on("kb.view.delete",function(b){return new Promise(function(e,w){kb.config[t].config.get().then(function(u){0!=Object.keys(u).length?kb.field.load(kb.config[t].app,!0).then(function(n){l.app={id:kb.config[t].app,
fields:n.origin};l.fieldInfos=n;try{(function(f){0!=f.length?y(f,b.record).then(function(g){b.error=g.error;e(b)})["catch"](function(){b.error=!0;e(b)}):e(b)})(JSON.parse(u.tab).map(function(f,g){return kb.extend({sIndex:{value:g.toString()}},f.setting)}).reduce(function(f,g){(b.mobile?["both","mobile"]:["both","pc"]).includes(g.device.value)&&f.push(g);return f},[]))}catch(f){kb.alert(kb.error.parse(f)),e(b)}})["catch"](function(n){return e(b)}):e(b)})["catch"](function(u){return e(b)})})})})(kintone.$PLUGIN_ID);