/*
* FileName "plugins.upsert.js"
* Version: 1.0.0
* Copyright (c) 2023 Pandafirm LLC
* Distributed under the terms of the GNU Lesser General Public License.
* https://opensource.org/licenses/LGPL-2.1
*/
(function(L){var p={},K=function(f,v,P){return new Promise(function(C,D){var F=function(z,r){var g=function(){z++;kb.progressStart(f.length);z<f.length?F(z,r):r()};(function(h){var m=kb.filter.scan(p.app,v,h.condition.value);m?kb.filter.auth(h.user.value,h.organization.value,h.group.value).then(function(G){G?kb.field.load(h.app.value).then(function(x){var A={id:h.app.value,fields:x.origin};(function(q){var I=[],M=[],O=[],E={},y=1,J=1,B=0,H=0,N=function(){var k=[],t={field:function(b,c){var l=null;
if(b.tableCode)if(m[b.tableCode].value.length>c)l=m[b.tableCode].value[c].value[b.code];else switch(b.type){case "CHECK_BOX":case "FILE":case "GROUP_SELECT":case "MULTI_SELECT":case "ORGANIZATION_SELECT":case "USER_SELECT":l={value:[]};break;case "RADIO_BUTTON":(function(a){l={value:0!=a.length?a.reduce(function(e,d){e[d.index]=d;return e},Array(a.length).fill("")).first().label:""}})(Object.values(b.options));break;default:l={value:""}}else l=m[b.code];return kb.extend({type:b.type},l)},record:function(b){J.each(function(c){var l=
function(a){var e=kb.filter.scan(A,b,a.query);if(!e&&"upsert"==h.pattern.value){for(var d in a.rows)0==kb.filter.result[d].value.length&&(b[d].value.push({value:kb.extend({},a.rows[d])}),kb.filter.result[d]={value:[b[d].value.last()]});e=kb.filter.result}return e}(function(){var a={rows:{},query:[]};H=c;I.each(function(e,d){e.external.tableCode&&(e.external.tableCode in a.rows||(a.rows[e.external.tableCode]=kb.record.create(A.fields[e.external.tableCode],!1)),a.rows[e.external.tableCode][e.external.code]=
n(e.external,t.field(e.internal,H)),a.query.push(kb.filter.query.create(e.external,e.operator,t.field(e.internal,H))))});M.each(function(e,d){e.field.tableCode&&a.query.push(e.field.code+" "+e.operator+" "+e.value)});a.query=a.query.join(" and ");return a}());l&&O.each(function(a,e){a.external.tableCode?a.external.tableCode in E?(b[a.external.tableCode]={value:E[a.external.tableCode]},E[a.external.tableCode].each(function(d,w){d.value[a.external.code]=n(a.external,t.field(a.internal,w));"FILE"==a.external.type&&
d.value[a.external.code].value&&Array.prototype.push.apply(k,d.value[a.external.code].value)})):l[a.external.tableCode].value.each(function(d,w){d.value[a.external.code]=n(a.external,t.field(a.internal,H));"FILE"==a.external.type&&d.value[a.external.code].value&&Array.prototype.push.apply(k,d.value[a.external.code].value)}):(b[a.external.code]=n(a.external,t.field(a.internal,B)),"FILE"==a.external.type&&b[a.external.code].value&&Array.prototype.push.apply(k,b[a.external.code].value))})});return b}},
n=function(b,c){return b.lookup?kb.extend({lookup:!0},c):c},u=function(b){b.each(function(c,l){h.formula.value.each(function(a,e){a.value.field.value in q.external&&function(d){d.tableCode?c[d.tableCode].value.each(function(w,Q){w.value[d.code].value=kb.formula.calculate(a.value,w.value,c,c,q.external);d.lookup&&(w.value[d.code].lookup=!0)}):(c[d.code].value=kb.formula.calculate(a.value,c,c,c,q.external),d.lookup&&(c[d.code].lookup=!0))}(q.external[a.value.field.value])})});return b};"insert"==h.pattern.value?
function(b){kb.file.clone(k,!0).then(function(){kb.view.records.set(h.app.value,{post:b},!0).then(function(c){B++;B<y?N():g()})["catch"](function(c){kb.alert(c.message);D()})})}(u([t.record(kb.record.create(A))])):kb.view.records.get(h.app.value,function(){var b=[];I.each(function(c,l){c.external.tableCode||b.push(kb.filter.query.create(c.external,c.operator,t.field(c.internal,B)))});M.each(function(c,l){c.field.tableCode||b.push(c.field.code+" "+c.operator+" "+c.value)});return b.join(" and ")}()).then(function(b){b=
function(c){var l=[];0!=c.length?l=c.map(function(a){return t.record(a)}):"upsert"==h.pattern.value&&function(a){l.push(t.record(function(){var e=kb.record.create(A);a.each(function(d,w){d.external.tableCode?e[d.external.tableCode]={value:[]}:e[d.external.code]=n(d.external,t.field(d.internal,B))});return e}()))}(I.filter(function(a){return!kb.field.reserved.includes(a.external.type)}));return u(l)}(b);kb.file.clone(k,!0).then(function(){kb.view.records.set(h.app.value,{post:b.filter(function(c){return!c.$id.value}),
put:b.reduce(function(c,l){if(l.$id.value){var a=c.push,e=l.$id.value,d={},w;for(w in l)kb.field.reserved.includes(l[w].type)||(d[w]=l[w]);a.call(c,{id:e,record:d})}return c},[])}).then(function(c){B++;B<y?N():g()})["catch"](function(c){kb.alert(c.message);D()})})})["catch"](function(b){kb.alert(kb.error.parse(b));D()})};h.mapping.value.some(function(k){return!(k.value.external.value in q.external&&k.value.internal.value in q.internal)})?(kb.alert("No field to transfer was found"),D()):h.criteria.value.some(function(k){return!(k.value.external.value in
q.external&&k.value.internal.value in q.internal)})?(kb.alert("No field to transfer was found"),D()):(h.mapping.value.each(function(k,t){(function(n,u){n.tableCode?E[n.tableCode]=function(b){b=b?b.length:1;u.tableCode&&(b=b<m[u.tableCode].value.length?m[u.tableCode].value.length:b);return Array(b).fill().map(function(){return{value:kb.record.create(A.fields[n.tableCode],!1)}})}(E[n.tableCode]):u.tableCode&&(y=0==m[u.tableCode].value.length?0:y<m[u.tableCode].value.length?m[u.tableCode].value.length:
y);O.push({external:n,internal:u})})(q.external[k.value.external.value],q.internal[k.value.internal.value])}),h.criteria.value.each(function(k,t){var n=q.external[k.value.external.value],u=k.value.operator.value,b=q.internal[k.value.internal.value];n.tableCode?(n.tableCode in E&&delete E[n.tableCode],b.tableCode&&(J=J<m[b.tableCode].value.length?m[b.tableCode].value.length:J)):b.tableCode&&(y=0==m[b.tableCode].value.length?0:y<m[b.tableCode].value.length?m[b.tableCode].value.length:y);I.push({external:n,
operator:u,internal:b})}),kb.filter.query.parse(h.filter.value).each(function(k,t){M.push({field:q.external[k.field],operator:k.operator,value:k.value})}),0!=y?(H=B=0,N()):g())})({external:x.parallelize,internal:p.fieldInfos.parallelize})})["catch"](function(x){return kb.alert(kb.error.parse(x))}):g()})["catch"](function(G){return kb.alert(kb.error.parse(G))}):g()})(f[z])};kb.progressStart(f.length);F(0,function(){kb.progressEnd();C()})})};kintone.events.on("app.record.create.submit.success app.record.detail.process.proceed app.record.detail.show app.record.edit.submit.success app.record.index.show mobile.app.record.create.submit.success mobile.app.record.detail.process.proceed mobile.app.record.detail.show mobile.app.record.edit.submit.success mobile.app.record.index.show".split(" "),
function(f){return new Promise(function(v,P){(function(C,D){p.mobile=C;p.type=D;kb.config[L].config.get().then(function(F){0!=Object.keys(F).length?kb.field.load(kb.config[L].app,!0).then(function(z){p.app={id:kb.config[L].app,fields:z.origin};p.fieldInfos=z;try{(function(r){if(0!=r.length)switch(p.type){case "create":case "edit":K(r,f.record).then(function(g){return v(f)});break;case "process":(function(g){0!=g.length?K(g,f.record).then(function(h){return v(f)}):v(f)})(r.filter(function(g){return g.action.value==
f.action.value+":"+f.status.value+":"+f.nextStatus.value}));break;case "detail":r.each(function(g,h){kb.button.create(p.mobile,p.type,"kb-upsert-button"+h.toString(),g.label.value,g.message.value,function(){return K([g],f.record).then(function(m){return kb.alert("Done!")})})});v(f);break;case "index":r.each(function(g,h){g.view.value&&g.view.value!=f.viewId.toString()||kb.button.create(p.mobile,p.type,"kb-upsert-button"+h.toString(),g.label.value,g.message.value,function(){kb.view.records.get(p.app.id,
(p.mobile?kintone.mobile.app:kintone.app).getQueryCondition()).then(function(m){var G=function(x,A){K([g],m[x]).then(function(q){x++;x<m.length?G(x,A):A()})};0!=m.length?G(0,function(){return kb.alert("Done!")}):kb.alert("There are no records.")})["catch"](function(m){return kb.alert(kb.error.parse(m))})})}),v(f)}else v(f)})(JSON.parse(F.tab).reduce(function(r,g){(p.mobile?["both","mobile"]:["both","pc"]).includes(g.setting.device.value)&&g.setting.event.value.includes(p.type)&&r.push(g.setting);
return r},[]))}catch(r){kb.alert(kb.error.parse(r)),v(f)}})["catch"](function(z){return v(f)}):v(f)})["catch"](function(F){return v(f)})})("mobile"==f.type.split(".").first(),function(C){switch(C){case "submit":C=f.type.split(".").slice(-3).first()}return C}(f.type.split(".").slice(-2).first()))})})})(kintone.$PLUGIN_ID);