/*
* FileName "plugins.linkage.js"
* Version: 1.0.0
* Copyright (c) 2023 Pandafirm LLC
* Distributed under the terms of the GNU Lesser General Public License.
* https://opensource.org/licenses/LGPL-2.1
*/
'use strict';(K=>{var d={handlers:{},stats:{}},O=(w,D)=>new Promise((L,H)=>{kb.field.load(w.app.value).then(A=>{(E=>{w.criteria.value.some(t=>!(t.value.external.value in E.external&&t.value.internal.value in E.internal))?(kb.alert("No field to linkage was found"),H()):w.mapping.value.some(t=>!(t.value.external.value in E.external))?(kb.alert("No field to linkage was found"),H()):(t=>{t.api=t.api.join(" and ");t.url=t.url.join(" and ");kb.view.records.get(w.app.value,t.api).then(x=>{0!=x.length?((v,z,B)=>{L((p=>
{p.records.sort((e,u)=>{var n=0;w.sort.value.each((c,q)=>{switch(A.parallelize[c.value.field.value].type){case "CALC":switch(A.parallelize[c.value.field.value].format){case "NUMBER":case "NUMBER_DIGIT":q=e[c.value.field.value].value?parseFloat(e[c.value.field.value].value):0;var g=u[c.value.field.value].value?parseFloat(u[c.value.field.value].value):0;break;default:q=e[c.value.field.value].value,g=u[c.value.field.value].value}break;case "CATEGORY":case "CHECK_BOX":case "CREATOR":case "FILE":case "GROUP_SELECT":case "MODIFIER":case "MULTI_SELECT":case "ORGANIZATION_SELECT":case "STATUS_ASSIGNEE":case "USER_SELECT":q=
JSON.stringify(e[c.value.field.value].value);g=JSON.stringify(u[c.value.field.value].value);break;case "NUMBER":q=e[c.value.field.value].value?parseFloat(e[c.value.field.value].value):0;g=u[c.value.field.value].value?parseFloat(u[c.value.field.value].value):0;break;default:q=e[c.value.field.value].value,g=u[c.value.field.value].value}switch(c.value.order.value){case "asc":q>g&&(n=1);q<g&&(n=-1);break;case "desc":q>g&&(n=-1),q<g&&(n=1)}if(n)return KB_BREAK});return n});return p})(v.reduce((p,e)=>{Array(B?
e[B].value.length:1).fill().map(()=>({})).each((u,n)=>{u.$id=e.$id;for(var c in A.parallelize)A.parallelize[c].tableCode?A.parallelize[c].tableCode==B&&(u[c]=e[B].value[n].value[c]):"$rowId"!=c?u[c]=e[c]:u.$rowId=B?{value:e[B].value[n].id}:{value:""};p.records.push(u)});return p},{offset:0,origin:z,query:t.url,records:[]})))})(x.reduce((v,z)=>{(z=kb.filter.scan({fields:A.origin},z,t.api))&&v.push(z);return v},[]),x,Array.from(new Set(w.mapping.value.map(v=>A.parallelize[v.value.external.value].tableCode))).join("")):
L({offset:0,records:[]})}).catch(x=>{kb.alert(kb.error.parse(x));H()})})(w.criteria.value.reduce((t,x)=>{t.api.push(kb.filter.query.create(E.external[x.value.external.value],x.value.operator.value,D[x.value.internal.value]));E.external[x.value.external.value].tableCode||t.url.push(t.api.last());return t},kb.filter.query.parse.expand({id:w.app.value,fields:A.origin},w.filter.value).reduce((t,x)=>{t.api.push(x.field+" "+x.operator+" "+x.value);E.external[x.field].tableCode||t.url.push(t.api.last());
return t},{api:[],url:[]})))})({external:A.parallelize,internal:d.fieldInfos.parallelize})}).catch(A=>{kb.alert(kb.error.parse(A));H()})});kintone.events.on("app.record.create.show app.record.detail.show app.record.edit.show app.record.index.show mobile.app.record.create.show mobile.app.record.detail.show mobile.app.record.edit.show mobile.app.record.index.show".split(" "),w=>new Promise((D,L)=>{((H,A)=>{d.mobile=H;d.type=A;for(var E in d.handlers)d.handlers[E].each((t,x)=>{kintone.events.off(E,t)});
kb.config[K].config.get().then(t=>{0!=Object.keys(t).length?kb.field.load(kb.config[K].app,!0).then(x=>{d.app={id:kb.config[K].app,fields:x.origin};d.fieldInfos=x;try{(v=>{if(0!=v.length){var z=(p,e,u)=>{var n=(c=>Array.from(new Set(c.map(q=>d.fieldInfos.parallelize[q.value.internal.value].tableCode))).reduce((q,g)=>{e[g].value=[];q[g]={fields:c.filter(k=>d.fieldInfos.parallelize[k.value.internal.value].tableCode==g),row:kb.record.create(d.fieldInfos.origin[g],!1)};return q},{}))(p.mapping.value.reduce((c,
q)=>{q.value.internal.value in d.fieldInfos.parallelize&&c.push(q);return c},[]));u.each((c,q)=>{for(var g in n)e[g].value.push((k=>{n[g].fields.each((b,y)=>{if(b.value.internal.value in d.fieldInfos.parallelize)switch(d.fieldInfos.parallelize[b.value.internal.value].type){case "lookup":y=c[b.value.external.value];k[b.value.internal.value]={lookup:!0,search:"search"in y?y.search:"",value:y.value};break;default:k[b.value.internal.value].value=c[b.value.external.value].value}});return{value:k}})(kb.extend({},
n[g].row)))});return e};d.mobile&&kb.elm("body").addClass("kb-mobile");switch(d.type){case "create":case "edit":case "detail":var B=p=>{(e=>{(u=>{u&&kb.field.load(e.app.value).then(n=>{(c=>{((q,g)=>{var k={},b={copy:kb.create("button").addClass("kb-linkage-container-button").html(e.label.value).on("click",m=>{kb.confirm(e.message.value,()=>{kb.event.call("kb.action.call",{container:kb.elm("body"),record:z(e,(d.mobile?kintone.mobile.app.record:kintone.app.record).get().record,k.records),mobile:d.mobile,
pattern:"change",fields:(a=>a.reduce((l,f)=>l=l.concat(Object.keys(d.fieldInfos.tables[f].fields)),a))(e.mapping.value.reduce((a,l)=>{l.value.internal.value in d.fieldInfos.parallelize&&a.push(d.fieldInfos.parallelize[l.value.internal.value].tableCode);return a},[])),stopPropagation:!0,workplace:"record"}).then(a=>{kb.event.call("kb.style.call",{container:a.container,record:a.record,mobile:a.mobile,pattern:"$id"in a.record?a.record.$id.value?"edit":"create":"create",workplace:a.workplace}).then(l=>
{kb.event.call("kb.cascade.call",l).then(f=>{(d.mobile?kintone.mobile.app.record:kintone.app.record).set({record:f.record})}).catch(()=>{})}).catch(()=>{})}).catch(()=>{})})}),edit:kb.create("button").addClass("kb-icon kb-icon-edit").on("click",m=>{[b.total,b.reload,b.open,b.edit,b.prev,b.next,b.copy].each((a,l)=>a.addClass("kb-hidden"));[b.submit,b.cancel].each((a,l)=>a.removeClass("kb-hidden"));q.elms(".kb-field").each((a,l)=>a.removeClass("kb-readonly"));(a=>{a=kb.elm(".kb_spread_style_"+CSS.escape(a));
a.parentNode.removeChild(a)})("view_"+c.id+"_"+c.view.id+"_"+location.host.split(".").first());u.parentNode.show()}),submit:kb.create("button").addClass("kb-linkage-container-button").on("click",m=>{var a=q.tr.reduce((f,r,h)=>{f.error||"unsaved"!=r.elm(".kb-scope").attr("unsaved")||(r=kb.record.get(r.elm(".kb-scope"),c),r.error?f.error=!0:f.records["row"+h.toString()]=r.record);return f},{error:!1,records:{}}),l=(f=!1)=>{[b.total,b.reload,b.open,b.edit,b.prev,b.next,b.copy].each((r,h)=>r.removeClass("kb-hidden"));
[b.submit,b.cancel].each((r,h)=>r.addClass("kb-hidden"));f?J((d.mobile?kintone.mobile.app.record:kintone.app.record).get().record):y()};a.error||0==Object.keys(a.records).length?l():kb.confirm(kb.constants.common.message.confirm.submit[kb.operator.language],f=>{if(f)l();else{var r={},h;for(h in a.records)((G,R)=>{var I=G.$id.value,S=G.$rowId.value,M=JSON.parse(JSON.stringify(k.origin.find(C=>C.$id.value==I)||{}));0!=Object.keys(M)&&(I in r||(r[I]=(C=>{var F={id:I,record:{$id:M.$id}};C&&(F.record[C]=
M[C]);return F})(Array.from(new Set(e.mapping.value.map(C=>n.parallelize[C.value.external.value].tableCode))).join(""))),r[I].record=c.view.fields.reduce((C,F)=>{q.tr[R].elm('[field-id="'+CSS.escape(F)+'"]').hasAttribute("edited")&&(P=>{P?C[P].value.each((Q,T)=>{Q.id==S&&(Q.value[F]=G[F])}):C[F]=G[F]})(c.fields[F].tableCode);return C},r[I].record))})(a.records[h],h.replace(/^row/g,""));kb.view.records.set(c.id,{put:Object.values(r)},!1,!0).then(G=>{l(!0)}).catch(G=>{kb.alert(kb.error.parse(G));l()})}},
!0)}).html(kb.constants.common.caption.button.submit[kb.operator.language]).addClass("kb-hidden"),cancel:kb.create("button").addClass("kb-linkage-container-button").on("click",m=>{[b.total,b.reload,b.open,b.edit,b.prev,b.next,b.copy].each((a,l)=>a.removeClass("kb-hidden"));[b.submit,b.cancel].each((a,l)=>a.addClass("kb-hidden"));y()}).html(kb.constants.common.caption.button.cancel[kb.operator.language]).addClass("kb-hidden"),open:kb.create("button").addClass("kb-icon kb-icon-open").on("click",m=>
{window.open(kb.record.page.view(d.mobile,c.id,"20",k.query))}),prev:kb.create("button").addClass("kb-icon kb-icon-arrow kb-icon-arrow-left").on("click",m=>{k.offset-=g;y()}),next:kb.create("button").addClass("kb-icon kb-icon-arrow kb-icon-arrow-right").on("click",m=>{k.offset+=g;y()}),reload:kb.create("button").addClass("kb-icon kb-icon-reload").on("click",m=>{J((d.mobile?kintone.mobile.app.record:kintone.app.record).get().record)}),total:kb.create("span").addClass("kb-linkage-container-monitor").html("")},
y=()=>{var m=k.records.slice(k.offset,k.offset+g);q.clearRows();m.each((a,l)=>{(f=>{kb.record.set(f.elm("[form-id=form_"+c.id+"]"),c,a).then(()=>{f.elm(".kb-view-row-edit").attr("href",kb.record.page.detail(d.mobile,c.id,a.$id.value)).attr("target","_blank");l==m.length-1&&u.parentNode.show()})})(q.addRow())});switch(kb.operator.language){case "en":b.total.html(k.records.length.toString()+"records in total");break;case "ja":b.total.html("\u7dcf"+k.records.length.toString()+"\u884c");break;case "zh":b.total.html("\u5171"+
k.records.length.toString()+"\u6761\u8bb0\u5f55");break;case "zh-TW":b.total.html("\u5171"+k.records.length.toString()+"\u7b46\u8a18\u9304")}0<k.offset?b.prev.removeAttr("disabled"):b.prev.attr("disabled","disabled");k.offset+(g==m.length?g:m.length)<k.records.length?b.next.removeAttr("disabled"):b.next.attr("disabled","disabled")},N=()=>{var m={},a=e.mapping.value.reduce((f,r)=>{switch(n.parallelize[r.value.external.value].type){case "CREATED_TIME":case "DATE":case "DATETIME":case "UPDATED_TIME":f[r.value.external.value]=
{max:"",min:""};break;case "NUMBER":f[r.value.external.value]={count:0,sum:"",avg:"",max:"",min:""}}return f},{});k.records.each((f,r)=>{for(var h in f)if(h in n.parallelize)switch(n.parallelize[h].type){case "CREATED_TIME":case "DATE":case "DATETIME":case "UPDATED_TIME":if(h in a&&f[h].value){if(!a[h].max||f[h].value>a[h].max)a[h].max=f[h].value;if(!a[h].min||f[h].value<a[h].min)a[h].min=f[h].value}break;case "NUMBER":if(h in a&&kb.isNumeric(f[h].value)){if(!kb.isNumeric(a[h].max)||Number(f[h].value)>
a[h].max)a[h].max=Number(f[h].value);if(!kb.isNumeric(a[h].min)||Number(f[h].value)<a[h].min)a[h].min=Number(f[h].value);kb.isNumeric(a[h].sum)||(a[h].sum=0);a[h].sum+=Number(f[h].value);a[h].count++}}});for(var l in a)a[l].count&&(a[l].avg=a[l].sum/a[l].count),Object.values(d.stats).filter(f=>f.source==l).each((f,r)=>{r=f.destination;m[r]={type:d.fieldInfos.origin[r].type,value:f.value=a[l][f.method]}});if(["create","edit"].includes(d.type))(f=>{try{f()}catch(h){var r=setInterval(()=>{try{f(),clearInterval(r)}catch(G){}},
500)}})(()=>{0!=Object.keys(m).length&&(d.mobile?kintone.mobile.app.record:kintone.app.record).set({record:m})});else for(l in m)(f=>{var r=kb.field.stringify(f,m[l].value," / ");d.mobile?kb.field.get(f,d.mobile,d.type).value.html(r):kb.field.get(f,d.mobile,d.type).value.elm("span").html(r)})(d.fieldInfos.parallelize[l])},J=m=>{O(e,m).then(a=>{k=a;y();N()}).catch(()=>{k={offset:0,records:[]};y();N()})};switch(d.type){case "create":case "edit":u.append(kb.create("div").addClass("kb-linkage-container-footer").append(b.total).append(b.reload).append(b.open).append(b.edit).append(b.prev).append(b.next).append(b.copy).append(b.submit).append(b.cancel));
break;case "detail":u.append(kb.create("div").addClass("kb-linkage-container-footer").append(b.total).append(b.reload).append(b.open).append(b.edit).append(b.prev).append(b.next).append(b.submit).append(b.cancel))}e.editable.value.includes("editable")||b.edit.addClass("kb-hidden");((m,a)=>{kintone.events.on(m,a);m.each((l,f)=>{l in d.handlers||(d.handlers[l]=[]);d.handlers[l].push(a)})})(e.criteria.value.reduce((m,a)=>{m.push("app.record.create.change."+a.value.internal.value);m.push("app.record.edit.change."+
a.value.internal.value);m.push("mobile.app.record.create.change."+a.value.internal.value);m.push("mobile.app.record.edit.change."+a.value.internal.value);return m},[]),m=>{J(m.record);return m});c.view.fields.each((m,a)=>{kb.event.on("kb.change."+m,l=>{l.container.elm('[field-id="'+CSS.escape(m)+'"]').attr("edited","edited");return l})});J(w.record)})(kb.view.create(u.addClass("kb-linkage-container"),c,c.view.id,d.mobile).elm(".kb-view"),parseInt(e.limit.value))})({id:e.app.value,disables:[],fields:(c=>
{c.$rowId={code:"$rowId",type:"SINGLE_LINE_TEXT",label:"",required:!1,noLabel:!0,placeholder:""};return c})(n.parallelize),view:{id:"linkage_"+e.app.value+"_"+e.container.value,buttons:["delete"],fields:e.mapping.value.map(c=>c.value.external.value),mode:"viewer"}})}).catch(()=>{})})((d.mobile?kintone.mobile.app.record:kintone.app.record).getSpaceElement(e.container.value).css({width:"max-content"}));p++;p<v.length&&B(p)})(v[p])};v.first().mapping.value.some(p=>!("stats"in p.value))&&(kb.alert(kb.error.config.update("Boost! Linkage")),
v=v.map(p=>{p.mapping.value=p.mapping.value.map(e=>{e.value.stats={value:""};return e});return p}));d.stats={};v.each((p,e)=>{p.mapping.value.each((u,n)=>{n=JSON.parse(u.value.stats.value||"{}");for(var c in n)((q,g)=>{g.value in d.fieldInfos.origin&&(g.value in d.stats||((k,b)=>{kintone.events.on(k,b);k.each((y,N)=>{y in d.handlers||(d.handlers[y]=[]);d.handlers[y].push(b)})})(["app.record.create.change."+g.value,"app.record.edit.change."+g.value,"mobile.app.record.create.change."+g.value,"mobile.app.record.edit.change."+
g.value],k=>{k.record[g.value].value!=d.stats[g.value].value&&(k.record[g.value].value=d.stats[g.value].value);return k}),d.stats[g.value]={destination:g.value,method:q,source:u.value.external.value,value:""})})(c,n[c])})});B(0);D(w);break;case "index":B=p=>{(e=>{kb.filter.auth(e.user.value,e.organization.value,e.group.value).then(u=>{u&&(e.view.value&&e.view.value!=w.viewId.toString()||kb.button.create(d.mobile,d.type,"kb-linkage-button"+p.toString(),e.label.value,e.message.value,()=>{kb.view.records.get(d.app.id,
(d.mobile?kintone.mobile.app:kintone.app).getQueryCondition()).then(n=>{var c=[];let q=(g,k)=>{O(e,n[g]).then(b=>{c.push(kb.view.records.transform(z(e,n[g],b.records)));kb.progressUpdate();g++;g<n.length?q(g,k):k()}).catch(()=>{})};0!=n.length?(kb.progressStart(n.length),q(0,()=>{kb.view.records.set(d.app.id,{put:c}).then(g=>kb.alert("Done!",()=>window.location.reload(!0))).catch(g=>kb.alert(kb.error.parse(g)))})):kb.alert("There are no records.")}).catch(n=>kb.alert(kb.error.parse(n)))}));p++;p<
v.length&&B(p)}).catch(u=>{p++;p<v.length&&B(p)})})(v[p])},B(0),D(w)}}else D(w)})(JSON.parse(t.tab).map((v,z)=>kb.extend({sIndex:{value:z.toString()}},v.setting)).reduce((v,z)=>{switch(d.type){case "index":z.bulk.value.includes("bulk")&&v.push(z);break;default:v.push(z)}return v},[]))}catch(v){kb.alert(kb.error.parse(v)),D(w)}}).catch(x=>D(w)):D(w)}).catch(t=>D(w))})("mobile"==w.type.split(".").first(),w.type.split(".").slice(-2).first())}))})(kintone.$PLUGIN_ID);
