/*
* FileName "plugins.submit.js"
* Version: 1.0.0
* Copyright (c) 2023 Pandafirm LLC
* Distributed under the terms of the GNU Lesser General Public License.
* https://opensource.org/licenses/LGPL-2.1
*/
(function(w){var d={},y=function(a,c,q,r){q=void 0===q?!1:q;r=void 0===r?{}:r;return new Promise(function(u,m){var p=function(n,e){var t=function(){n++;n<a.length?p(n,e):e()};(function(h){kb.filter.scan(d.app,c,h.condition.value)?kb.filter.auth(h.user.value,h.organization.value,h.group.value).then(function(x){if(x){var v={error:function(f){try{h.errorMessage.value||0!=h.errorField.value.length?kb.filter.scan(d.app,c,h.errorFilter.value)?(h.errorField.value.each(function(b,g){b.value.field.value in
d.fieldInfos.parallelize&&(c[b.value.field.value].error=b.value.message.value)}),q||kb.loadEnd(),u({error:!0,message:h.errorMessage.value})):f():f()}catch(b){kb.alert(kb.error.parse(b)),m()}},numbering:function(f){try{if(h.numberingField.value in d.fieldInfos.parallelize)if(c[h.numberingField.value].value)f();else{var b="",g=h.numberingGroup.value.reduce(function(k,l){if(l.value.field.value in d.fieldInfos.parallelize)switch(b+=c[l.value.field.value].value,d.fieldInfos.parallelize[l.value.field.value].type){case "DROP_DOWN":case "RADIO_BUTTON":k.push(l.value.field.value+
' in ("'+c[l.value.field.value].value+'")');break;default:k.push(l.value.field.value+'="'+c[l.value.field.value].value+'"')}return k},"$id"in c?['$id!="'+c.$id.value+'"']:[]);b in r?(r[b]++,c[h.numberingField.value].value=b+r[b].toString().lpad("0",parseInt(h.numberingDigits.value)),f()):kintone.api(kintone.api.url("/k/v1/records",!0),"GET",{app:d.app.id,query:g.join(" and ")+" order by "+h.numberingField.value+" desc limit 1 offset 0"}).then(function(k){k=k.records;var l=0;0!=k.length&&(l=parseInt((k.first()[h.numberingField.value].value||
" ").replace(/[ ]+/g,"").replace(new RegExp("^"+b,"g"),"")));l++;k=l;r[b]=k;c[h.numberingField.value].value=b+k.toString().lpad("0",parseInt(h.numberingDigits.value));f()})["catch"](function(k){kb.alert(kb.error.parse(k));m()})}else f()}catch(k){kb.alert(kb.error.parse(k)),m()}},prompt:function(f){try{(function(b){0!=b.length?function(g){b.each(function(k,l){g.append(kb.field.activate(kb.field.create(k).css({width:"100%"}),d.app,!1))});q||kb.loadEnd();(new KintoneBoosterPopupform(g,600,"full",{ok:function(){var k=
kb.record.get(g,d.app,!0);b.each(function(l,z){c[l.code].value=k.record[l.code].value});q||kb.loadStart();f()},cancel:function(){q||kb.loadStart();f()}})).show()}(kb.create("div").addClass("kb-scope").attr("form-id","form_"+d.app.id)):f()})(h.promptField.value.reduce(function(b,g){g.value.field.value in d.fieldInfos.parallelize&&(h.promptOverwrite.value.includes("overwrite")?b.push(d.fieldInfos.parallelize[g.value.field.value]):kb.field.isEmpty(c[g.value.field.value].value)&&b.push(d.fieldInfos.parallelize[g.value.field.value]));
return b},[]))}catch(b){kb.alert(kb.error.parse(b)),m()}},verify:function(f){try{(function(b){0!=b.length?function(g){b.each(function(k,l){g.append(kb.field.activate(kb.field.create(k).addClass("kb-readonly").css({width:"100%"}),d.app,!1))});kb.record.set(g,d.app,c);q||kb.loadEnd();(new KintoneBoosterPopupform(g,600,"full",{ok:function(){q||kb.loadStart();f()},cancel:function(){q||kb.loadEnd();u({error:!0})}})).show()}(kb.create("div").addClass("kb-scope kb-verify").attr("form-id","form_"+d.app.id).append(kb.create("p").html(h.verifyMessage.value))):
f()})(h.verifyField.value.reduce(function(b,g){g.value.field.value in d.fieldInfos.parallelize&&b.push(d.fieldInfos.parallelize[g.value.field.value]);return b},[]))}catch(b){kb.alert(kb.error.parse(b)),m()}}};v.numbering(function(){v.prompt(function(){v.verify(function(){v.error(function(){t()})})})})}else t()})["catch"](function(x){kb.alert(kb.error.parse(x));m()}):t()})(a[n])};q||kb.loadStart();p(0,function(){q||kb.loadEnd();u({error:!1})})})};kintone.events.on("app.record.create.submit app.record.detail.process.proceed app.record.edit.submit mobile.app.record.create.submit mobile.app.record.detail.process.proceed mobile.app.record.edit.submit".split(" "),
function(a){return new Promise(function(c,q){(function(r,u){d.mobile=r;d.type=u;kb.config[w].config.get().then(function(m){0!=Object.keys(m).length?kb.field.load(kb.config[w].app,!0).then(function(p){d.app={id:kb.config[w].app,fields:p.origin};d.fieldInfos=p;try{(function(n){if(0!=n.length)switch(d.type){case "create":case "edit":y(n,a.record).then(function(e){e.error&&(a.error="message"in e?e.message:kb.constants.submit.message.cancel.submit[kb.operator.language]);c(a)})["catch"](function(){a.error=
kb.constants.submit.message.cancel.submit[kb.operator.language];c(a)});(function(e){if(0!=e.length)kintone.events.on((d.mobile?"mobile.":"")+"app.record."+d.type+".submit.success",function(t){return new Promise(function(h,x){var v=function(f){(function(b){kb.filter.scan(d.app,t.record,b.condition.value)?kb.filter.auth(b.user.value,b.organization.value,b.group.value).then(function(g){if(g){g=b.url.value;var k=t.record,l;for(l in k)g=g.replace(new RegExp("%"+l+"%","g"),kb.field.stringify(d.fieldInfos.parallelize[l],
k[l].value," / "));t.url=g}f++;f<e.length&&v(f)})["catch"](function(g){f++;f<e.length&&v(f)}):(f++,f<e.length&&v(f))})(e[f])};v(0);h(t)})})})(n.filter(function(e){return e.url.value}));break;case "process":(function(e){0!=e.length?y(e,a.record).then(function(t){t.error&&(a.error="message"in t?t.message:kb.constants.submit.message.cancel.submit[kb.operator.language]);c(a)})["catch"](function(){a.error=kb.constants.submit.message.cancel.submit[kb.operator.language];c(a)}):c(a)})(n.filter(function(e){return e.action.value==
a.action.value+":"+a.status.value+":"+a.nextStatus.value}))}else c(a)})(JSON.parse(m.tab).map(function(n,e){return kb.extend({sIndex:{value:e.toString()}},n.setting)}).reduce(function(n,e){(d.mobile?["both","mobile"]:["both","pc"]).includes(e.device.value)&&e.event.value.includes(d.type)&&n.push(e);return n},[]))}catch(n){kb.alert(kb.error.parse(n)),c(a)}})["catch"](function(p){return c(a)}):c(a)})["catch"](function(m){return c(a)})})("mobile"==a.type.split(".").first(),a.type.split(".").slice(-2).first())})});
kb.event.on("kb.submit.call",function(a){return new Promise(function(c,q){kb.config[w].config.get().then(function(r){0!=Object.keys(r).length?kb.field.load(kb.config[w].app,!0).then(function(u){d.app={id:kb.config[w].app,fields:u.origin};d.fieldInfos=u;try{(function(m){0!=m.length?y(m,a.record,!0,a.numbering).then(function(p){p.error?(a.error=!0,p.message?kb.alert(p.message,function(){return c(a)}):c(a)):c(a)})["catch"](function(){a.error=!0;c(a)}):c(a)})(JSON.parse(r.tab).map(function(m,p){return kb.extend({sIndex:{value:p.toString()}},
m.setting)}).reduce(function(m,p){(a.mobile?["both","mobile"]:["both","pc"]).includes(p.device.value)&&p.event.value.includes(a.pattern)&&m.push(p);return m},[]))}catch(m){kb.alert(kb.error.parse(m)),c(a)}})["catch"](function(u){return c(a)}):c(a)})["catch"](function(r){return c(a)})})})})(kintone.$PLUGIN_ID);
kb.constants=kb.extend({submit:{message:{cancel:{process:{en:"The process action was canceled.",ja:"\u30d7\u30ed\u30bb\u30b9\u30a2\u30af\u30b7\u30e7\u30f3\u304c\u30ad\u30e3\u30f3\u30bb\u30eb\u3055\u308c\u307e\u3057\u305f\u3002",zh:"\u8fdb\u7a0b\u64cd\u4f5c\u5df2\u88ab\u53d6\u6d88\u3002"},submit:{en:"The submit was canceled.",ja:"\u4fdd\u5b58\u304c\u30ad\u30e3\u30f3\u30bb\u30eb\u3055\u308c\u307e\u3057\u305f\u3002",zh:"\u4fdd\u5b58\u5df2\u88ab\u53d6\u6d88\u3002"}}}}},kb.constants);