/*
* FileName "plugins.imap.js"
* Version: 1.0.0
* Copyright (c) 2023 Pandafirm LLC
* Distributed under the terms of the GNU Lesser General Public License.
* https://opensource.org/licenses/LGPL-2.1
*/
'use strict';(y=>{var f={},A=c=>new Promise((q,m)=>{((k,t)=>{t.append(kb.create("div").addClass("kb-row").append(kb.field.activate(kb.field.create(k.fields.from).css({width:"50%"}),k,!1)).append(kb.field.activate(kb.field.create(k.fields.to).css({width:"50%"}),k,!1))).append(kb.create("div").addClass("kb-row").append(kb.field.activate(kb.field.create(k.fields.sender).css({width:"100%"}),k,!1)));kb.record.set(t,k,f.filter?f.filter:{from:{value:(new Date).format("Y-m-d")},to:{value:(new Date).format("Y-m-d")},
sender:{value:""}});(new KintoneBoosterPopupform(t,600,null,{ok:()=>{f.filter=kb.record.get(t,k,!0).record;fetch("https://api.kintone-booster.com/mail/rv",{method:"GET",headers:{"X-Requested-With":"XMLHttpRequest"}}).then(n=>{n.json().then(u=>{switch(n.status){case 200:(d=>{kb.loadStart();kb.encrypt(JSON.stringify(d),u.passphrase).then(g=>{fetch("https://api.kintone-booster.com/mail/rv",{method:"POST",headers:{"X-Requested-With":"XMLHttpRequest"},body:JSON.stringify({data:g.data,iv:g.iv,tag:g.tag})}).then(h=>
{h.json().then(a=>{switch(h.status){case 200:var r=[],v=[],p=(b,e)=>{0!=r.length?kb.file.upload((l=>{var w=atob(l.binary),x=new Uint8Array(w.length);w.length.each(z=>x[z]=w.charCodeAt(z));return new File([new Blob([x.buffer],{type:l.contentType})],l.filename,{type:l.contentType})})(r[b]),!0).then(l=>{a[v[b].json].attachment[v[b].attachment]=l;b++;b<r.length?p(b,e):e()}).catch(l=>{kb.alert(kb.error.parse(l));m()}):e()};r=a.reduce((b,e,l)=>{0!=e.attachment.length&&e.attachment.each((w,x)=>{b.push(w);
v.push({json:l,attachment:x})});return b},[]);p(0,()=>q(a));break;default:kb.alert(kb.error.parse(a)),m()}})}).catch(h=>{kb.alert(kb.error.parse(h));m()})}).catch(g=>{kb.loadEnd();m()})})({host:c.host.value,port:c.port.value,option:c.option.value?c.option.value:"/imap/ssl",mailbox:c.mailbox.value?c.mailbox.value:"INBOX",author:c.author.value,pwd:c.pwd.value,criteria:(()=>{var d='SINCE "'+f.filter.from.value+'" BEFORE "'+(new Date(f.filter.to.value)).calc("1 day").format("Y-m-d")+'"';f.filter.sender.value&&
(d+=' FROM "'+f.filter.sender.value+'"');return d})()});break;default:kb.alert(kb.error.parse(u)),m()}})}).catch(n=>{kb.alert(kb.error.parse(n));m()})},cancel:()=>m()})).show()})({id:"IMAP_filter",fields:{from:{code:"from",type:"DATE",label:kb.constants.imap.caption.from[kb.operator.language],required:!0,noLabel:!1},to:{code:"to",type:"DATE",label:kb.constants.imap.caption.to[kb.operator.language],required:!0,noLabel:!1},sender:{code:"sender",type:"SINGLE_LINE_TEXT",label:kb.constants.imap.caption.sender[kb.operator.language],
required:!0,noLabel:!1,format:"mail"}}},kb.create("div").addClass("kb-scope").attr("form-id","form_IMAP_filter"))});kintone.events.on(["app.record.index.show","mobile.app.record.index.show"],c=>new Promise((q,m)=>{((k,t)=>{f.mobile=k;f.type=t;kb.config[y].config.get().then(n=>{0!=Object.keys(n).length?kb.field.load(kb.config[y].app,!0).then(u=>{f.app={id:kb.config[y].app,fields:u.origin};f.fieldInfos=u;try{(d=>{if(0!=d.length){var g=h=>{(a=>{kb.filter.auth(a.user.value,a.organization.value,a.group.value).then(r=>
{r&&(a.view.value&&a.view.value!=c.viewId.toString()||kb.button.create(f.mobile,f.type,"kb-imap-button"+h.toString(),a.label.value,a.message.value,()=>{A(a).then(v=>{0!=v.length?kb.view.records.set(f.app.id,{post:v.reduce((p,b)=>{var e={};e[a.uid.value]={value:b.uid};e[a.from.value]={value:b.from};e[a.date.value]={value:(new Date(b.date)).format("ISO")};e[a.subject.value]={value:b.subject};e[a.body.value]={value:b.body};e[a.attachment.value]={value:b.attachment};a.cc&&a.cc.value&&(e[a.cc.value]={value:b.cc});
a.bcc&&a.bcc.value&&(e[a.bcc.value]={value:b.bcc});p.push(e);return p},[])},!0).then(p=>kb.alert("Done!",()=>window.location.reload(!0))).catch(p=>kb.alert(kb.error.parse(p))):kb.alert("There are no emails.")}).catch(()=>{})}));h++;h<d.length&&g(h)}).catch(r=>{h++;h<d.length&&g(h)})})(d[h])};g(0)}q(c)})(JSON.parse(n.tab).map((d,g)=>kb.extend({sIndex:{value:g.toString()}},d.setting)).reduce((d,g)=>{(f.mobile?["both","mobile"]:["both","pc"]).includes(g.device.value)&&d.push(g);return d},[]))}catch(d){kb.alert(kb.error.parse(d)),
q(c)}}).catch(u=>q(c)):q(c)}).catch(n=>q(c))})("mobile"==c.type.split(".").first(),c.type.split(".").slice(-2).first())}))})(kintone.$PLUGIN_ID);kb.constants=kb.extend({imap:{caption:{from:{en:"Since",ja:"\u4ee5\u964d",zh:"\u4ee5\u540e"},sender:{en:"Sender",ja:"\u5dee\u51fa\u4eba",zh:"\u53d1\u4ef6\u4eba"},to:{en:"Before",ja:"\u4ee5\u524d",zh:"\u4ee5\u524d"}}}},kb.constants);