/*
* FileName "plugins.fusion.js"
* Version: 1.0.0
* Copyright (c) 2023 Pandafirm LLC
* Distributed under the terms of the GNU Lesser General Public License.
* https://opensource.org/licenses/LGPL-2.1
*/
'use strict';(D=>{var b={},H=(g,u)=>new Promise((F,G)=>{var E=(r,t)=>{var c=(a,l,f)=>{var n=()=>{a++;a<r.length?c(a,l,f):(0!=g.sort.value.length&&(kb.progressStart(r.length,(()=>{var d="";switch(kb.operator.language){case "en":d="Sorting the statement details.";break;case "ja":d="\u5e33\u7968\u660e\u7d30\u306e\u30bd\u30fc\u30c8\u3092\u884c\u3063\u3066\u3044\u307e\u3059\u3002";break;case "zh":d="\u6b63\u5728\u6392\u5e8f\u8d26\u5355\u660e\u7ec6\u3002";break;case "zh-TW":d="\u6b63\u5728\u6392\u5e8f\u5e33\u55ae\u660e\u7d30\u3002"}return d})()),
r.each((d,m)=>{g.sort.value.each((h,k)=>{d[h.value.table.value].value.sort((q,y)=>{var v=0;h.value.fields.value.each((p,z)=>{switch(b.fieldInfos.parallelize[p.value.field.value].type){case "CALC":switch(b.fieldInfos.parallelize[p.value.field.value].format){case "NUMBER":case "NUMBER_DIGIT":z=q.value[p.value.field.value].value?parseFloat(q.value[p.value.field.value].value):0;var w=y.value[p.value.field.value].value?parseFloat(y.value[p.value.field.value].value):0;break;default:z=q.value[p.value.field.value].value,
w=y.value[p.value.field.value].value}break;case "CATEGORY":case "CHECK_BOX":case "CREATOR":case "FILE":case "GROUP_SELECT":case "MODIFIER":case "MULTI_SELECT":case "ORGANIZATION_SELECT":case "STATUS_ASSIGNEE":case "USER_SELECT":z=JSON.stringify(q.value[p.value.field.value].value);w=JSON.stringify(y.value[p.value.field.value].value);break;case "NUMBER":z=q.value[p.value.field.value].value?parseFloat(q.value[p.value.field.value].value):0;w=y.value[p.value.field.value].value?parseFloat(y.value[p.value.field.value].value):
0;break;default:z=q.value[p.value.field.value].value,w=y.value[p.value.field.value].value}switch(p.value.order.value){case "asc":z>w&&(v=1);z<w&&(v=-1);break;case "desc":z>w&&(v=-1),z<w&&(v=1)}if(v)return KB_BREAK});return v})});kb.progressUpdate()})),f(r))};((d,m)=>{kb.progressStart(r.length,(()=>{var h="";switch(kb.operator.language){case "en":h="Registering "+d.name+" data.";break;case "ja":h=d.name+"\u306e\u30c7\u30fc\u30bf\u3092\u767b\u9332\u3057\u3066\u3044\u307e\u3059\u3002";break;case "zh":h=
"\u6b63\u5728\u767b\u8bb0"+d.name+"\u6570\u636e\u3002";break;case "zh-TW":h="\u6b63\u5728\u767b\u9304"+d.name+"\u8cc7\u6599\u3002"}return h})());kb.view.records.get(d.id,(h=>{var k=[],q=y=>d.isTimeStamp?(y.getTime()/1E3).toString():d.isDateTime?y.toISOString():y.format("Y-m-d");k.push(d.date+(d.fieldInfos.parallelize[d.date].tableCode?' not in ("")':'!=""'));k.push(d.date+'>"'+q(h.start)+'"');k.push(d.date+'<"'+q(h.end)+'"');return k.join(" and ")})({start:(h=>d.isDateTime?h.calc("-1 second").calc(kb.timezoneOffset()+
" hour"):h.calc("-1 day"))(new Date(l?l:"1900-01-01")),end:(h=>d.isDateTime?h.calc("1 day").calc(kb.timezoneOffset()+" hour"):h.calc("1 day"))(new Date(b.preset.date))})).then(h=>{(k=>{r.each((q,y)=>{(v=>{h.each((p,z)=>{var w=kb.filter.scan({id:d.id,fields:d.fieldInfos.origin},p,(x=>{x&&(x+=" and ");return x+d.client+'="'+q[g.client.value].value+'" and '+d.date+'>"'+v.start+'" and '+d.date+'<"'+v.end+'"'})(d.filter));w&&(p=[],k?p=w[k].value.reduce((x,A)=>{for(var B in d.mapping){var C=d.mapping[B];
C in A.value||(A.value[C]={value:w[C].value})}x.push(A.value);return x},[]):p.push(w),q[m].value=(x=>{1==x.length&&(Object.values(x.first().value).some(A=>!kb.field.isEmpty(A.value))||x.pop());return x})(q[m].value),Array.prototype.push.apply(q[m].value,p.map(x=>({value:Object.entries(d.mapping).reduce((A,[B,C])=>{A[B].value=x[C].value;b.fieldInfos.parallelize[B].lookup&&(A[B].lookup=!0);return A},kb.extend({},b.preset.template.table[m]))}))))});kb.progressUpdate()})({start:(v=>d.isDateTime?v.calc("-1 second").calc(kb.timezoneOffset()+
" hour").toISOString():v.calc("-1 day").format("Y-m-d"))(new Date(q[g.client.value].value in b.preset.latest?b.preset.latest[q[g.client.value].value]:l)),end:(v=>d.isDateTime?v.calc("1 day").calc(kb.timezoneOffset()+" hour").toISOString():v.calc("1 day").format("Y-m-d"))(new Date(b.preset.date))})});n()})(Object.values(d.mapping).map(k=>d.fieldInfos.parallelize[k].tableCode).filter(k=>k).first())}).catch(h=>kb.alert(kb.error.parse(h)))})(b.appInfos[g.source.value[a].value.app.value],g.source.value[a].value.table.value)},
e=(a,l)=>{(f=>{f?kintone.api(kintone.api.url("/k/v1/records",!0),"GET",{app:b.app.id,query:g.client.value+'="'+f[g.client.value].value+'" and '+g.issueDate.value+'<"'+f[g.issueDate.value].value+'" order by '+(g.issueDate.value+" desc,$id desc limit 1 offset 0")}).then(n=>{0!=n.records.length&&(f[g.previousAmount.value]={value:n.records.first()[g.totalAmount.value].value},(n=n.records.first()[g.issueDate.value].value)&&(b.preset.latest[f[g.client.value].value]=n));kb.progressUpdate();a++;a<r.length?
e(a,l):l(r)}).catch(n=>kb.alert(kb.error.parse(n))):(a++,a<r.length?e(a,l):l(r))})(r[a])};kb.progressStart(r.length,(()=>{var a="";switch(kb.operator.language){case "en":a="Registering previous amount data.";break;case "ja":a="\u524d\u56de\u91d1\u984d\u30c7\u30fc\u30bf\u3092\u767b\u9332\u3057\u3066\u3044\u307e\u3059\u3002";break;case "zh":a="\u6b63\u5728\u767b\u8bb0\u4e0a\u6b21\u91d1\u989d\u6570\u636e\u3002";break;case "zh-TW":a="\u6b63\u5728\u767b\u9304\u4e0a\u6b21\u91d1\u984d\u8cc7\u6599\u3002"}return a})());
e(0,a=>{c(0,0!=Object.values(b.preset.latest).length?Object.values(b.preset.latest).sort().first():"1900-01-01",l=>t(l))})};b.preset.latest={};(r=>{var t=(c,e,a)=>{var l=()=>{c++;c<e.length?t(c,e,a):a(e)};(f=>{f?kintone.api(kintone.api.url("/k/v1/records",!0),"GET",{app:b.app.id,query:g.client.value+'="'+f[g.client.value].value+'" and '+g.issueDate.value+'="'+f[g.issueDate.value].value+'" order by $id desc limit 1 offset 0'}).then(n=>{0!=n.records.length&&(f.$id={value:n.records.first().$id.value});
kb.progressUpdate();l()}).catch(n=>kb.alert(kb.error.parse(n))):l()})(e[c])};kb.progressStart(0,(()=>{var c="";switch(kb.operator.language){case "en":c="Downloading client data.";break;case "ja":c="\u53d6\u5f15\u5148\u30c7\u30fc\u30bf\u3092\u30c0\u30a6\u30f3\u30ed\u30fc\u30c9\u3057\u3066\u3044\u307e\u3059\u3002";break;case "zh":c="\u6b63\u5728\u4e0b\u8f7d\u53d6\u5f15\u5148\u6570\u636e\u3002";break;case "zh-TW":c="\u6b63\u5728\u4e0b\u8f09\u53d6\u5f15\u5148\u8cc7\u6599\u3002"}return c})());(c=>{(e=>
{e.lookup?kb.view.records.get(e.lookup.relatedApp.app,(a=>{e.lookup.filterCond&&a.push("("+e.lookup.filterCond+")");return a.join(" and ")})(Object.entries(u).map(([a,l])=>a+' in ("'+l+'")')),e.lookup.sort||"$id asc").then(a=>{kb.progressStart(a.length,(()=>{var l="";switch(kb.operator.language){case "en":l="Creating records for registration.";break;case "ja":l="\u767b\u9332\u7528\u30ec\u30b3\u30fc\u30c9\u3092\u4f5c\u6210\u3057\u3066\u3044\u307e\u3059\u3002";break;case "zh":l="\u6b63\u5728\u521b\u5efa\u7528\u4e8e\u6ce8\u518c\u7684\u8bb0\u5f55\u3002";
break;case "zh-TW":l="\u6b63\u5728\u5efa\u7acb\u7528\u65bc\u8a3b\u518a\u7684\u8a18\u9304\u3002"}return l})());c(a.map(l=>{var f=kb.extend({},b.preset.template.record);f[g.client.value]={value:l[e.lookup.relatedKeyField].value,lookup:!0};f[g.issueDate.value]={value:b.preset.date};kb.progressUpdate();return f}))}).catch(a=>kb.alert(kb.error.parse(a))):kb.alert("No client field to fusion was found")})(b.fieldInfos.parallelize[g.client.value])})(c=>{kb.progressStart(c.length,(()=>{var e="";switch(kb.operator.language){case "en":e=
"Checking registered records.";break;case "ja":e="\u767b\u9332\u6e08\u30ec\u30b3\u30fc\u30c9\u3092\u8abf\u3079\u3066\u3044\u307e\u3059\u3002";break;case "zh":e="\u6b63\u5728\u68c0\u67e5\u5df2\u6ce8\u518c\u7684\u8bb0\u5f55\u3002";break;case "zh-TW":e="\u6b63\u5728\u6aa2\u67e5\u5df2\u8a3b\u518a\u7684\u8a18\u9304\u3002"}return e})());t(0,c,e=>r(e))})})(r=>{E(r,t=>{var c={},e=(a,l)=>{0!=t.length?kb.event.call("kb.action.call",{container:kb.elm("body"),record:t[a],mobile:b.mobile,pattern:"change",fields:Object.values(b.fieldInfos.parallelize).reduce((f,
n)=>{n.tableCode&&(f.includes(n.tableCode)||f.push(n.tableCode));f.push(n.code);return f},[]),stopPropagation:!0,workplace:"view"}).then(f=>{f.error||kb.event.call("kb.submit.call",{record:f.record,mobile:f.mobile,numbering:c,pattern:f.record.$id.value?"edit":"create",workplace:"view"}).then(n=>{n.error||(a++,a<t.length?e(a,l):l())}).catch(()=>{})}).catch(()=>{}):l()};e(0,()=>{F({records:{post:t.filter(a=>!a.$id.value),put:t.reduce((a,l)=>{l.$id.value&&a.push({id:l.$id.value,record:l});return a},
[])}})})})})});kintone.events.on(["app.record.index.show","mobile.app.record.index.show"],g=>new Promise((u,F)=>{((G,E)=>{b.mobile=G;b.type=E;kb.config[D].config.get().then(r=>{0!=Object.keys(r).length?kb.field.load(kb.config[D].app,!0).then(t=>{b.app={id:kb.config[D].app,fields:t.origin};b.fieldInfos=t;b.preset={date:(new Date).format("Y-m-d"),template:{record:kb.record.create(b.app),table:Object.keys(t.tables).reduce((c,e)=>{c[e]=kb.record.create(t.origin[e],!1);return c},{})}};try{(c=>{c?(()=>
{var e=[];c.source.value=c.source.value.map(a=>{a.value.fields.value=JSON.parse(a.value.fields.value);e.push(a.value.table.value);return a});c.sort.value=c.sort.value.map(a=>{a.value.fields.value=JSON.parse(a.value.fields.value);e.push(a.value.table.value);return a});return e})().some(e=>!(e in t.tables))?(kb.alert("No table to fusion was found"),u(g)):[c.client.value,c.issueDate.value,c.totalAmount.value,c.previousAmount.value,...c.source.value.map(e=>e.value.fields.value.mapping.value.map(a=>a.value.internal.value)).flat(),
...c.sort.value.map(e=>e.value.fields.value.map(a=>a.value.field.value)).flat()].some(e=>!(e in t.parallelize))?(kb.alert("No field to fusion was found"),u(g)):kb.filter.auth(c.user.value,c.organization.value,c.group.value).then(e=>{e&&(c.view.value&&c.view.value!=g.viewId.toString()||kb.apps.load().then(a=>{var l=(f,n)=>{(d=>{(m=>{m?kb.field.load(m.appId).then(h=>{(k=>[k.client.value,k.date.value,...k.mapping.value.map(q=>q.value.external.value)])(d.value.fields.value).some(k=>!(k in h.parallelize))?
(kb.alert("No field to fusion was found ["+m.name+"]"),u(g)):(b.appInfos[m.appId]={id:m.appId,name:m.name,fieldInfos:h,client:d.value.fields.value.client.value,date:d.value.fields.value.date.value,filter:d.value.fields.value.filter.value,mapping:Object.fromEntries(d.value.fields.value.mapping.value.map(k=>[k.value.internal.value,k.value.external.value])),isDateTime:!1,isTimeStamp:!1},(k=>{switch(k.type){case "CALC":switch(k.format){case "DATE":b.appInfos[m.appId].isDateTime=!1;break;case "DATETIME":b.appInfos[m.appId].isDateTime=
!0}b.appInfos[m.appId].isTimeStamp=!0;break;case "DATE":b.appInfos[m.appId].isDateTime=!1;b.appInfos[m.appId].isTimeStamp=!1;break;case "DATETIME":b.appInfos[m.appId].isDateTime=!0;b.appInfos[m.appId].isTimeStamp=!1;break;default:b.appInfos[m.appId].isDateTime=!1,b.appInfos[m.appId].isTimeStamp=!1}})(h.parallelize[d.value.fields.value.date.value]),f++,f<c.source.value.length?l(f,n):n())}).catch(h=>{kb.alert(kb.error.parse(h));u(g)}):(kb.alert("No app to fusion was found"),u(g))})(a.find(m=>m.appId==
d.value.app.value))})(c.source.value[f])};b.appInfos={};b.appInfos[b.app.id]={id:b.app.id,name:a.find(f=>f.appId==b.app.id).name,fieldInfos:t};(f=>{f?kb.field.load(f.appId).then(n=>{(d=>{d.some(m=>!(m in n.parallelize))?(kb.alert("No field to fusion was found ["+f.name+"]"),u(g)):(b.appInfos[f.appId]={id:f.appId,name:f.name,fieldInfos:n},l(0,()=>{(m=>{m.elm(".kb-fusion-operation")||(m.addClass("kb-scope").attr("form-id","form_Fusion").append(kb.create("div").addClass("kb-fusion-operation"+(b.mobile?
" kb-mobile":"")).append(kb.create("button").addClass("kb-fusion-pickup-button").on("click",h=>{(k=>{kb.pickupDate(b.preset.date,q=>{b.preset.date=q;k.html(b.preset.date)})})(h.currentTarget.nextElementSibling)})).append(kb.create("span").addClass("kb-fusion-pickup-guide").html(b.preset.date))),d.map(h=>n.parallelize[h]).each((h,k)=>{k={id:"Fusion",fields:{[h.code]:{code:h.code,type:"DROP_DOWN",label:"",required:!1,noLabel:!0,options:h.options}}};m.append(kb.create("div").addClass("kb-fusion-operation"+
(b.mobile?" kb-mobile":"")).append(kb.field.activate(kb.field.create(k.fields[h.code]).addClass("kb-"+h.code),k)))}));kb.button.create(b.mobile,b.type,"kb-fusion-button",c.label.value,c.message.value,()=>{H(c,d.reduce((h,k)=>{h[k]=m.elm(".kb-"+CSS.escape(k)).elm("select").val();return h},{})).then(h=>{kb.view.records.set(b.app.id,h.records,!0).then(k=>kb.alert("Done!",()=>window.location.reload(!0))).catch(k=>kb.alert(kb.error.parse(k)))}).catch(()=>{})})})(b.mobile?kintone.mobile.app.getHeaderSpaceElement():
kintone.app.getHeaderMenuSpaceElement())}))})(c.category.value.map(d=>d.value.field.value))}).catch(n=>{kb.alert(kb.error.parse(n));u(g)}):(kb.alert("No app to fusion was found"),u(g))})(a.find(f=>f.appId==t.parallelize[c.client.value].lookup.relatedApp.app))}));u(g)}).catch(e=>u(g)):u(g)})(JSON.parse(r.flat))}catch(c){kb.alert(kb.error.parse(c)),u(g)}}).catch(t=>u(g)):u(g)}).catch(r=>u(g))})("mobile"==g.type.split(".").first(),g.type.split(".").slice(-2).first())}))})(kintone.$PLUGIN_ID);
