'use strict';(C=>{var a={handlers:{},intervals:[],observers:[]},E=x=>new Promise((B,F)=>{var D=(m,q)=>(c=>{let z=null,v=null;const k=(h=>(t=>{t.addEventListener("change",e=>{e.target==t&&(a.mobile?q.value:q.value.elm("input")).val(e.detail.value)});(e=>{(new MutationObserver(d=>{for(const b of d)"attributes"===b.type&&"placeholder"===b.attributeName&&t.elm("input").attr("placeholder",e.attr("placeholder"))})).observe(e,{attributes:!0,attributeFilter:["placeholder"]})})(a.mobile?q.value:q.value.elm("input"));return t})(a.mobile?
new Kuc.MobileText(h):(new Kuc.Text(h)).css({boxSizing:"border-box",width:c.tableCode?"auto":q.css("width")})))({buttons:{clear:kb.create("button").css({whiteSpace:"nowrap"}).on("click",h=>{kb.confirm(kb.constants.lookup.message.confirm.clear[kb.operator.language],()=>{if(0!=m.tableCopy.value.length)k.lookupAction="CLEAR",k.lookupRecord=null,(a.mobile?q.value:q.value.elm("input")).val("");else{var t=kb.field.get(c,a.mobile,a.type),e=a.mobile?kintone.mobile.app.record:kintone.app.record,d=e.set,b=
(a.mobile?kintone.mobile.app.record:kintone.app.record).get().record,g={};c.tableCode?(g[c.tableCode]=b[c.tableCode],g[c.tableCode].value[t.indexOf(q)].value[c.code]={lookup:"CLEAR",type:c.type,value:""}):g[c.code]={lookup:"CLEAR",type:c.type,value:""};k.lookupAction="CLEAR";k.lookupRecord=null;d.call(e,{record:g})}})}).html((()=>{var h="";switch(kb.operator.language){case "en":h="Clear";break;case "ja":h="\u30af\u30ea\u30a2";break;case "zh":h="\u6e05\u9664";break;case "zh-TW":h="\u6e05\u9664"}return h})()),
lookup:kb.create("button").css({whiteSpace:"nowrap"}).on("click",h=>{((t,e)=>{var d=()=>{a.recordPicker.show({app:c.lookup.relatedApp.app,query:c.query.filter(g=>g).join(" and "),sort:c.lookup.sort||"$id asc",picker:c.picker},g=>b(g))},b=g=>{if(0!=m.tableCopy.value.length)k.lookupAction="UPDATE",k.lookupRecord=g,(a.mobile?q.value:q.value.elm("input")).val(g[c.lookup.relatedKeyField].value);else{var f=a.mobile?kintone.mobile.app.record:kintone.app.record,l=f.set,r=(a.mobile?kintone.mobile.app.record:
kintone.app.record).get().record,n={};c.tableCode?(n[c.tableCode]=r[c.tableCode],n[c.tableCode].value[t.indexOf(q)].value[c.code]={lookup:"UPDATE",type:c.type,value:g[c.lookup.relatedKeyField].value}):n[c.code]={lookup:"UPDATE",type:c.type,value:g[c.lookup.relatedKeyField].value};k.lookupAction="UPDATE";k.lookupRecord=g;l.call(f,{record:n})}};c.query=k.buildQuery();e&&c.query.push(c.lookup.relatedKeyField+(["LINK","SINGLE_LINE_TEXT"].includes(c.type)?" like ":"=")+'"'+e+'"');kintone.api(kintone.api.url("/k/v1/records",
!0),"GET",{app:c.lookup.relatedApp.app,query:c.query.filter(g=>g).join(" and ")}).then(g=>{if(0==g.records.length){g=kb;var f=g.alert,l="";switch(kb.operator.language){case "en":l="(None)";break;case "ja":l="\u30c7\u30fc\u30bf\u304c\u3042\u308a\u307e\u305b\u3093\u3002";break;case "zh":l="\u6682\u65e0\u6570\u636e\u3002";break;case "zh-TW":l="\u7121\u8cc7\u6599\u3002"}f.call(g,l)}else 1==g.records.length?b(g.records.first()):d()}).catch(g=>kb.alert(kb.error.parse(g)))})(kb.field.get(c,a.mobile,a.type),
(a.mobile?q.value:q.value.elm("input")).val())}).html((()=>{var h="";switch(kb.operator.language){case "en":h="Lookup";break;case "ja":h="\u53d6\u5f97";break;case "zh":h="\u641c\u9009";break;case "zh-TW":h="\u9078\u53d6"}return h})())},className:"control-gaia kb-lookup-field-"+c.id,label:c.noLabel||c.tableCode?"":c.label,lookupAction:"",lookupRecord:null,placeholder:(a.mobile?q.value:q.value.elm("input")).attr("placeholder"),requiredIcon:c.required});Object.defineProperty(k,"disabledOptions",{set(h){[k.buttons.lookup,
k.buttons.clear].each((t,e)=>t.css({opacity:h?"0":"1"}));0!=m.cascade.value.length&&k.elms("[class*=kb-lookup-cascade-]").each((t,e)=>{t.disabled=h})},enumerable:!0,configurable:!0});v=new MutationObserver(()=>{(h=>{kb.field.load(c.lookup.relatedApp.app).then(t=>{k.buildQuery=()=>{var e=[a.fieldInfos.parallelize[m.lookup.value].lookup.filterCond];((d,b)=>{e=m.dynamicFilter.value.reduce((g,f)=>{var l=t.parallelize[f.value.external.value],r=f.value.operator.value;f=a.fieldInfos.parallelize[f.value.internal.value];
var n=f.tableCode?b[f.tableCode].value[d.indexOf(q)].value:b;m.ignore.value.includes("ignore")&&kb.field.isEmpty(n[f.code].value)||g.push(kb.filter.query.create(l,r,n[f.code]));return g},e);0!=m.cascade.value.length&&(e=e.concat(k.buildQuery.cascade(m.cascade.value)))})(kb.field.get(c,a.mobile,a.type),(a.mobile?kintone.mobile.app.record:kintone.app.record).get().record);return e.filter(d=>d)};k.buildQuery.cascade=e=>e.reduce((d,b)=>{var g=h.parentNode.elm(".kb-lookup-cascade-"+c.code+"-"+b.value.field.value);
if(0!=g.selectedIndex)switch(t.parallelize[b.value.field.value].type){case "DROP_DOWN":case "RADIO_BUTTON":d.push(b.value.field.value+' in ("'+g.value+'")');break;default:d.push(b.value.field.value+' = "'+g.value+'"')}return d},[]).filter(d=>d);k.refreshForm=(e,d)=>{kb.event.call("kb.action.call",{container:kb.elm("body"),record:e,mobile:a.mobile,pattern:"change",fields:d,stopPropagation:!0,workplace:"record"}).then(b=>{kb.event.call("kb.style.call",{container:b.container,record:b.record,mobile:b.mobile,
pattern:"$id"in b.record?b.record.$id.value?"edit":"create":"create",workplace:b.workplace}).then(g=>{kb.event.call("kb.cascade.call",g).then(f=>{(a.mobile?kintone.mobile.app.record:kintone.app.record).set({record:f.record})}).catch(()=>{})}).catch(()=>{})}).catch(()=>{})};c.picker=(e=>{var d={};e.each((b,g)=>{b in t.parallelize&&(d[b]=kb.extend({},t.parallelize[b]))});0==Object.keys(d).length&&(d.$id={code:"$id",type:"RECORD_NUMBER",label:kb.constants.picker.caption.recordnumber[kb.operator.language],
required:!1,noLabel:!1});return d})(c.lookup.lookupPickerFields);m.cascade.value=m.cascade.value.reduce((e,d)=>{d.value.field.value in t.parallelize&&e.push(d);return e},[]);m.dynamicFilter.value=m.dynamicFilter.value.reduce((e,d)=>{d.value.external.value in t.parallelize&&d.value.internal.value in a.fieldInfos.parallelize&&e.push(d);return e},[]);m.multiCopy.value=m.multiCopy.value.reduce((e,d)=>{d.value.external.value in t.parallelize&&d.value.internal.value in a.fieldInfos.parallelize&&e.push(d);
return e},[]);m.tableCopy.value=m.tableCopy.value.reduce((e,d)=>{d.value.external.value in t.tables&&d.value.internal.value in a.fieldInfos.tables&&(b=>{d.value.fields.value=d.value.fields.value.reduce((g,f)=>{f.value.external.value in b.external.fields&&f.value.internal.value in b.internal.fields&&g.push(f);return g},[]);0!=d.value.fields.value.length&&d.value.identifier.value in b.internal.fields&&e.push(d)})({external:t.tables[d.value.external.value],internal:a.fieldInfos.tables[d.value.internal.value]});
return e},[]);(e=>{a.mobile?h.insertAdjacentElement("afterend",kb.create("div").css({display:"flex",padding:"0 0.5em"}).append(k.buttons.lookup.addClass("forms-lookup-lookup-gaia")).append(k.buttons.clear.addClass("forms-lookup-clear-gaia"))):(h.parentNode.insertAdjacentElement("beforeend",k.buttons.lookup.addClass("button-simple-cybozu input-lookup-gaia")),h.parentNode.insertAdjacentElement("beforeend",k.buttons.clear.addClass("button-simple-cybozu input-clear-gaia")));0!=m.cascade.value.length?
m.cascade.value.each((d,b)=>{(g=>{h.insertAdjacentElement("beforebegin",(f=>{a.mobile&&f.css({borderBottom:"none"});f.reload=()=>new Promise((r,n)=>{kb.view.records.get(c.lookup.relatedApp.app,q.nextSibling.buildQuery.cascade(m.cascade.value.slice(0,b)).join(" and "),d.value.field.value+" "+d.value.order.value).then(p=>{f.items=[{label:"-----",value:""}].concat(Array.from(new Set(p.map(u=>u[d.value.field.value].value))).map(u=>({label:u,value:u})));f.value="";r()}).catch(p=>{kb.alert(kb.error.parse(p));
n()})});f.addEventListener("change",r=>{r.target==f&&b<m.cascade.value.length-1&&(0!=f.selectedIndex?f.nextSibling.reload():m.cascade.value.slice(b+1).each(n=>{n=h.parentNode.elm(".kb-lookup-cascade-"+c.code+"-"+n.value.field.value);n.items=[{label:"-----",value:""}];n.value=""}))});let l=new MutationObserver(()=>{(r=>{r.each((n,p)=>n.disabled=q.nextSibling.disabled);a.mobile||c.tableCode||q.nextSibling.css({width:r.reduce((n,p)=>n+=p.outerWidth(!0),parseFloat(q.css("width"))).toString()+"px"})})(h.parentNode.elms("[class*=kb-lookup-cascade-]"));
0==b&&f.reload().then(r=>e()).catch(r=>{});l.disconnect()});l.observe(f,{childList:!0,subtree:!0});return f.css(a.mobile?{marginBottom:"0.5em"}:{marginRight:"8px"})})(a.mobile?new Kuc.MobileDropdown(g):new Kuc.Dropdown(g)))})({className:"kb-lookup-cascade-"+c.code+"-"+d.value.field.value,items:[{label:"-----",value:""}]})}):e()})(()=>{z=setInterval(()=>{q&&q.parentNode?(e=>{k.value!=e&&(k.value=e,0!=m.cascade.value.length||0!=m.tableCopy.value.length?(d=>{"CLEAR"==k.lookupAction?d():k.lookupRecord?
d(k.lookupRecord):kintone.api(kintone.api.url("/k/v1/records",!0),"GET",{app:c.lookup.relatedApp.app,query:c.lookup.relatedKeyField+'="'+e+'"'}).then(b=>{0==b.records.length?d():d(b.records.first())}).catch(b=>kb.alert(kb.error.parse(b)))})(d=>{(b=>{if(d){if(0!=m.cascade.value.length){var g=f=>{(l=>{(r=>{r.reload().then(n=>{r.value=d[l.value.field.value].value;f++;f<m.cascade.value.length&&g(f)}).catch(n=>{})})(h.parentNode.elm(".kb-lookup-cascade-"+c.code+"-"+l.value.field.value))})(m.cascade.value[f])};
g(0)}0!=m.tableCopy.value.length&&((f,l)=>{0==Object.keys(b).length?kb.alert(kb.constants.lookup.message.invalid.notfound[kb.operator.language]):k.refreshForm((r=>{kb.preset?kb.preset.files={}:kb.preset={files:{}};for(var n in b)l[n].value=(p=>{0!=p.length&&(Object.values(p.last().value).some(u=>!kb.field.isEmpty(u.value))||p.pop());return p})((l[n].value||[]).filter(p=>p.value[b[n].identifier].value!=r)),d[b[n].source].value.each((p,u)=>{l[n].value.push(((w,y)=>{b[n].fields.each((A,G)=>{w[A.value.internal.value].value=
p.value[A.value.external.value].value;a.fieldInfos.parallelize[A.value.internal.value].lookup&&(w[A.value.internal.value].lookup="UPDATE");"FILE"==a.fieldInfos.parallelize[A.value.internal.value].type&&(A.value.internal.value in kb.preset.files||(kb.preset.files[A.value.internal.value]={}),kb.preset.files[A.value.internal.value][y.toString()]=p.value[A.value.external.value].value)});w[b[n].identifier].value=r;w[b[n].identifier].disabled=!0;return{value:w}})(kb.extend({},b[n].row),l[n].value.length))});
k.lookupAction&&(c.tableCode?(p=>{p[c.code].lookup="UPDATE";p[c.code].value=d[c.lookup.relatedKeyField].value;c.lookup.fieldMappings.each((u,w)=>{p[u.field].value=d[u.relatedField].value})})(l[c.tableCode].value[f.indexOf(q)].value):(l[c.code].lookup="UPDATE",l[c.code].value=d[c.lookup.relatedKeyField].value,c.lookup.fieldMappings.each((p,u)=>{l[p.field].value=d[p.relatedField].value})));return l})(c.id+"_"+(c.tableCode?f.indexOf(q).toString().lpad("0",3):"000")),Object.keys(b).reduce((r,n)=>r=r.concat(Object.keys(a.fieldInfos.tables[n].fields)),
Object.keys(b).concat(c.lookup.triggerField)).filter(r=>r))})(kb.field.get(c,a.mobile,a.type),(a.mobile?kintone.mobile.app.record:kintone.app.record).get().record)}else 0!=m.cascade.value.length&&m.cascade.value.each((f,l)=>{f=h.parentNode.elm(".kb-lookup-cascade-"+c.code+"-"+f.value.field.value);0!=l&&(f.items=[{label:"-----",value:""}]);f.value=""}),0!=m.tableCopy.value.length&&((f,l)=>{0==Object.keys(b).length?kb.alert(kb.constants.lookup.message.invalid.notfound[kb.operator.language]):k.refreshForm((r=>
{kb.preset?kb.preset.files={}:kb.preset={files:{}};for(var n in b)l[n].value=(l[n].value||[]).filter(p=>p.value[b[n].identifier].value!=r);k.lookupAction&&(c.tableCode?(p=>{p[c.code].lookup="CLEAR";p[c.code].value="";c.lookup.fieldMappings.each((u,w)=>{w=a.fieldInfos.parallelize[u.field];switch(w.type){case "CHECK_BOX":case "CONDITION":case "FILE":case "GROUP_SELECT":case "MULTI_SELECT":case "ORGANIZATION_SELECT":case "USER_SELECT":p[u.field].value=[];break;case "RADIO_BUTTON":p[u.field].value=w.defaultValue;
break;default:p[u.field].value=""}})})(l[c.tableCode].value[f.indexOf(q)].value):(l[c.code].lookup="CLEAR",l[c.code].value="",c.lookup.fieldMappings.each((p,u)=>{u=a.fieldInfos.parallelize[p.field];switch(u.type){case "CHECK_BOX":case "CONDITION":case "FILE":case "GROUP_SELECT":case "MULTI_SELECT":case "ORGANIZATION_SELECT":case "USER_SELECT":l[p.field].value=[];break;case "RADIO_BUTTON":l[p.field].value=u.defaultValue;break;default:l[p.field].value=""}})));return l})(c.id+"_"+(c.tableCode?f.indexOf(q).toString().lpad("0",
3):"000")),Object.keys(b).concat(c.lookup.triggerField).filter(r=>r))})(kb.field.get(c,a.mobile,a.type),(a.mobile?kintone.mobile.app.record:kintone.app.record).get().record);k.lookupAction="";k.lookupRecord=null})((b=>b.reduce((g,f)=>{g[f.value.internal.value]={fields:f.value.fields.value,identifier:f.value.identifier.value,row:kb.record.create(a.fieldInfos.origin[f.value.internal.value],!1),source:f.value.external.value};return g},{}))(m.tableCopy.value))}):(k.lookupAction="",k.lookupRecord=null))})((a.mobile?
q.value:q.value.elm("input")).val()):(clearInterval(z),a.intervals=a.intervals.filter(e=>e!=z))},500)});(e=>{e.each((d,b)=>{d in a.fieldInfos.parallelize&&(g=>{(Array.isArray(g)?g:[g]).each((f,l)=>{f.elms(".disabled-cybozu").each((r,n)=>r.removeClass("disabled-cybozu"));f.elms(".disabled-field-gaia").each((r,n)=>r.removeClass("disabled-field-gaia"));f.elms("[disabled]").each((r,n)=>r.removeAttr("disabled"))})})(kb.field.get(a.fieldInfos.parallelize[d],a.mobile,a.type))})})(m.dynamicFilter.value.reduce((e,
d)=>{a.fieldInfos.disables.includes(d.value.internal.value)&&e.push(d.value.internal.value);return e},[]));(e=>{e&&e.css({boxSizing:"border-box",padding:"0 8px",width:a.mobile?"100%":"max-content"}).append(kb.create("button").addClass("kb-action-button kb-page-detail "+(a.mobile?" kb-mobile":"")).html(m.label.value).on("click",d=>{kb.confirm(m.message.value,()=>{(b=>{0==Object.keys(b).length?kb.alert(kb.constants.lookup.message.invalid.notfound[kb.operator.language]):a.recordMultiPicker.show({app:c.lookup.relatedApp.app,
query:k.buildQuery().join(" and "),sort:c.lookup.sort||"$id asc",picker:c.picker},g=>{0!=g.length&&k.refreshForm((f=>{kb.preset?kb.preset.files={}:kb.preset={files:{}};for(var l in b)0!=f[l].value.length&&(Object.values(f[l].value.last().value).some(r=>!kb.field.isEmpty(r.value))||f[l].value.pop());g.each((r,n)=>{for(var p in b)f[p].value.push(((u,w)=>{b[p].fields.each((y,A)=>{u[y.value.internal.value].value=r[y.value.external.value].value;a.fieldInfos.parallelize[y.value.internal.value].lookup&&
(u[y.value.internal.value].lookup="UPDATE");"FILE"==a.fieldInfos.parallelize[y.value.internal.value].type&&(y.value.internal.value in kb.preset.files||(kb.preset.files[y.value.internal.value]={}),kb.preset.files[y.value.internal.value][w.toString()]=r[y.value.external.value].value)});return{value:u}})(kb.extend({},b[p].row),f[p].value.length))});return f})((a.mobile?kintone.mobile.app.record:kintone.app.record).get().record),Object.keys(b).reduce((f,l)=>f=f.concat(Object.keys(a.fieldInfos.tables[l].fields)),
Object.keys(b)))})})((b=>Array.from(new Set(b.map(g=>a.fieldInfos.parallelize[g.value.internal.value].tableCode))).reduce((g,f)=>{f&&(g[f]={fields:b.filter(l=>a.fieldInfos.parallelize[l.value.internal.value].tableCode==f),row:kb.record.create(a.fieldInfos.origin[f],!1)});return g},{}))(m.multiCopy.value))})}))})((a.mobile?kintone.mobile.app.record:kintone.app.record).getSpaceElement(m.container.value));kb.event.call("kb.attachment.lookup.call",{field:q});kb.event.call("kb.style.color.call",{field:q});
kb.event.call("kb.style.display.call",{field:q});kb.event.call("kb.style.editable.call",{field:q})})})(k.elm("input").parentNode);v.disconnect()});v.observe(k,{childList:!0,subtree:!0});return k})(a.fieldInfos.parallelize[m.lookup.value]);(m=>{(Array.isArray(m)?m:[m]).each((q,c)=>{q.nextSibling&&q.nextSibling.tagName.toLowerCase().startsWith("kuc")||q.hide().insertAdjacentElement("afterend",D(x,q))})})(kb.field.get(a.fieldInfos.parallelize[x.lookup.value],a.mobile,a.type));B()});kintone.events.on(["app.record.create.show",
"app.record.edit.show","mobile.app.record.create.show","mobile.app.record.edit.show"],x=>new Promise((B,F)=>{((D,m)=>{a.mobile=D;a.type=m;for(var q in a.handlers)a.handlers[q].each((c,z)=>{kintone.events.off(q,c)});a.intervals.each((c,z)=>clearInterval(c));a.intervals=[];a.observers.each((c,z)=>c.disconnect());a.observers=[];kb.config[C].config.get().then(c=>{0!=Object.keys(c).length&&"object"===typeof Kuc?kb.field.load(kb.config[C].app,!0).then(z=>{a.app={id:kb.config[C].app,fields:z.origin};a.fieldInfos=
z;a.recordPicker=new KintoneBoosterRecordPicker("record");a.recordMultiPicker=new KintoneBoosterRecordPicker("record",!0);try{(v=>{if(0!=v.length){let k={handler:{get:h=>{(t=>{kb.elms(t).each((e,d)=>{(b=>{if(!b.hasClass("kb-table-add-button-"+h.code))b.addClass("kb-table-add-button-"+h.code).on("mousedown,touchstart",g=>{k.index.add=kb.elms(".kb-table-add-button-"+h.code).indexOf(b)+1})})(e.elm(a.mobile?".subtable-row-add-gaia":".add-row-image-gaia"));(b=>{if(!b.hasClass("kb-table-del-button-"+h.code))b.addClass("kb-table-del-button-"+
h.code).on("mousedown,touchstart",g=>{k.index.del=kb.elms(".kb-table-del-button-"+h.code).indexOf(b)})})(e.elm(a.mobile?".subtable-row-delete-gaia":".remove-row-image-gaia"))})})(".subtable-"+h.id+(a.mobile?" .subtable-row-gaia":" tbody tr"))},set:h=>{h.tableCode in k.setting&&(t=>{t.each((e,d)=>{if(kb.isNumeric(k.index.add))for(let b=h.record[e.source.tableCode].value.length-1;b>k.index.add;b--)e.fields.each((g,f)=>{g.code in a.fieldInfos.parallelize&&h.record[g.tableCode].value.each((l,r)=>{l.value[g.code].value==
e.source.id+"_"+(b-1).toString().lpad("0",3)&&(l.value[g.code].value=e.source.id+"_"+b.toString().lpad("0",3))})});if(kb.isNumeric(k.index.del)){e.fields.each((b,g)=>{b.code in a.fieldInfos.parallelize&&(h.record[b.tableCode].value=h.record[b.tableCode].value.filter(f=>f.value[b.code].value!=e.source.id+"_"+k.index.del.toString().lpad("0",3)))});for(let b=k.index.del;b<h.record[e.source.tableCode].value.length;b++)e.fields.each((g,f)=>{g.code in a.fieldInfos.parallelize&&h.record[g.tableCode].value.each((l,
r)=>{l.value[g.code].value==e.source.id+"_"+(b+1).toString().lpad("0",3)&&(l.value[g.code].value=e.source.id+"_"+b.toString().lpad("0",3))})})}})})(k.setting[h.tableCode]);k.index.add=null;k.index.del=null;return h}},index:{add:null,del:null},setting:{}};v.each((h,t)=>{(e=>{e.tableCode?(d=>{(b=>{b.observe(kb.elm(".subtable-"+d.id+(a.mobile?"":" tbody")),{childList:!0,subtree:!1});kb.elms(".subtable-"+d.id+(a.mobile?" .subtable-row-gaia":" tbody tr")).length==x.record[d.code].value.length&&(E(h),k.handler.get(d));
a.observers.push(b)})(new MutationObserver(()=>{E(h);k.handler.get(d)}));0!=h.tableCopy.value.length&&(d.code in k.setting||(k.setting[d.code]=[]),k.setting[d.code].push({fields:h.tableCopy.value.map(b=>a.fieldInfos.parallelize[b.value.identifier.value]),source:e}))})(a.fieldInfos.tables[e.tableCode]):E(h)})(a.fieldInfos.parallelize[h.lookup.value])});((h,t)=>{kintone.events.on(h,t);h.each((e,d)=>{e in a.handlers||(a.handlers[e]=[]);a.handlers[e].push(t)});kb.event.on("kb.lookup.identifier.call",
e=>k.handler.set(e))})(Object.keys(k.setting).reduce((h,t)=>{h.push("app.record.create.change."+t);h.push("app.record.edit.change."+t);h.push("mobile.app.record.create.change."+t);h.push("mobile.app.record.edit.change."+t);return h},[]),h=>{kb.event.call("kb.action.installed.change",{installed:!1,mobile:a.mobile}).then(t=>{t.installed||(h.tableCode=h.type.split(".").last(),(a.mobile?kintone.mobile.app.record:kintone.app.record).set(k.handler.set(h)))});return h});B(x)}})(JSON.parse(c.tab).map((v,
k)=>kb.extend({sIndex:{value:k.toString()}},v.setting)).reduce((v,k)=>{k.lookup.value in a.fieldInfos.parallelize&&(k.tableCopy.value.each((h,t)=>{h.value.fields.value=JSON.parse(h.value.fields.value)}),v.push(k));return v},[]))}catch(v){kb.alert(kb.error.parse(v)),B(x)}}).catch(z=>B(x)):B(x)}).catch(c=>B(x))})("mobile"==x.type.split(".").first(),x.type.split(".").slice(-2).first())}))})(kintone.$PLUGIN_ID);
kb.constants=kb.extend({lookup:{message:{confirm:{clear:{en:"Are you sure you want to clear the lookup value? All retrieved values will also be cleared.",ja:"\u53c2\u7167\u5148\u304b\u3089\u53d6\u5f97\u3057\u305f\u5024\u3082\u30af\u30ea\u30a2\u3055\u308c\u307e\u3059\u3002\u3088\u308d\u3057\u3044\u3067\u3059\u304b\uff1f",zh:"\u5df2\u83b7\u53d6\u7684\u503c\u4e5f\u4f1a\u88ab\u6e05\u9664\u3002\u662f\u5426\u7ee7\u7eed\uff1f","zh-TW":"\u78ba\u5b9a\u8981\u6e05\u9664\u5df2\u53d6\u5f97\u7684\u503c\u55ce\uff1f"}},
invalid:{notfound:{en:"No fields to be copied were found. Please check the plugin settings.",ja:"\u30b3\u30d4\u30fc\u3059\u308b\u30d5\u30a3\u30fc\u30eb\u30c9\u304c\u898b\u3064\u304b\u308a\u307e\u305b\u3093\u3002\u30d7\u30e9\u30b0\u30a4\u30f3\u306e\u8a2d\u5b9a\u3092\u78ba\u8a8d\u3057\u3066\u304f\u3060\u3055\u3044\u3002",zh:"\u672a\u627e\u5230\u8981\u590d\u5236\u7684\u5b57\u6bb5\u3002\u8bf7\u68c0\u67e5\u63d2\u4ef6\u7684\u8bbe\u5b9a\u5185\u5bb9\u3002","zh-TW":"\u627e\u4e0d\u5230\u8981\u8907\u88fd\u7684\u6b04\u4f4d\u3002\u8acb\u78ba\u8a8d\u5916\u639b\u7684\u8a2d\u5b9a\u5167\u5bb9\u3002"}}}}},
kb.constants);
