/*
* FileName "plugins.linkage.js"
* Version: 1.0.0
* Copyright (c) 2023 Pandafirm LLC
* Distributed under the terms of the GNU Lesser General Public License.
* https://opensource.org/licenses/LGPL-2.1
*/
'use strict';(K=>{var e={handlers:{}},N=(t,C)=>new Promise((L,H)=>{kb.field.load(t.app.value).then(y=>{(D=>{t.criteria.value.some(g=>!(g.value.external.value in D.external&&g.value.internal.value in D.internal))?(kb.alert("No field to linkage was found"),H()):t.mapping.value.some(g=>!(g.value.external.value in D.external))?(kb.alert("No field to linkage was found"),H()):(g=>{g.api=g.api.join(" and ");g.url=g.url.join(" and ");kb.view.records.get(t.app.value,g.api).then(u=>{0!=u.length?((p,w,z)=>{L((q=>{q.records.sort((d,
n)=>{var r=0;t.sort.value.each((b,l)=>{switch(y.parallelize[b.value.field.value].type){case "CALC":switch(y.parallelize[b.value.field.value].format){case "NUMBER":case "NUMBER_DIGIT":l=d[b.value.field.value].value?parseFloat(d[b.value.field.value].value):0;var f=n[b.value.field.value].value?parseFloat(n[b.value.field.value].value):0;break;default:l=d[b.value.field.value].value,f=n[b.value.field.value].value}break;case "CATEGORY":case "CHECK_BOX":case "CREATOR":case "FILE":case "GROUP_SELECT":case "MODIFIER":case "MULTI_SELECT":case "ORGANIZATION_SELECT":case "STATUS_ASSIGNEE":case "USER_SELECT":l=
JSON.stringify(d[b.value.field.value].value);f=JSON.stringify(n[b.value.field.value].value);break;case "NUMBER":l=d[b.value.field.value].value?parseFloat(d[b.value.field.value].value):0;f=n[b.value.field.value].value?parseFloat(n[b.value.field.value].value):0;break;default:l=d[b.value.field.value].value,f=n[b.value.field.value].value}switch(b.value.order.value){case "asc":l>f&&(r=1);l<f&&(r=-1);break;case "desc":l>f&&(r=-1),l<f&&(r=1)}if(r)return KB_BREAK});return r});return q})(p.reduce((q,d)=>{Array(z?
d[z].value.length:1).fill().map(()=>({})).each((n,r)=>{n.$id=d.$id;for(var b in y.parallelize)y.parallelize[b].tableCode?y.parallelize[b].tableCode==z&&(n[b]=d[z].value[r].value[b]):"$rowId"!=b?n[b]=d[b]:n.$rowId=z?{value:d[z].value[r].id}:{value:""};q.records.push(n)});return q},{offset:0,origin:w,query:g.url,records:[]})))})(u.reduce((p,w)=>{(w=kb.filter.scan({fields:y.origin},w,g.api))&&p.push(w);return p},[]),u,Array.from(new Set(t.mapping.value.map(p=>y.parallelize[p.value.external.value].tableCode))).join("")):
L({offset:0,records:[]})}).catch(u=>{kb.alert(kb.error.parse(u));H()})})(t.criteria.value.reduce((g,u)=>{g.api.push(kb.filter.query.create(D.external[u.value.external.value],u.value.operator.value,C[u.value.internal.value]));D.external[u.value.external.value].tableCode||g.url.push(g.api.last());return g},kb.filter.query.parse.expand({id:t.app.value,fields:y.origin},t.filter.value).reduce((g,u)=>{g.api.push(u.field+" "+u.operator+" "+u.value);D.external[u.field].tableCode||g.url.push(g.api.last());
return g},{api:[],url:[]})))})({external:y.parallelize,internal:e.fieldInfos.parallelize})}).catch(y=>{kb.alert(kb.error.parse(y));H()})});kintone.events.on("app.record.create.show app.record.detail.show app.record.edit.show app.record.index.show mobile.app.record.create.show mobile.app.record.detail.show mobile.app.record.edit.show mobile.app.record.index.show".split(" "),t=>new Promise((C,L)=>{((H,y)=>{e.mobile=H;e.type=y;for(var D in e.handlers)e.handlers[D].each((g,u)=>{kintone.events.off(D,g)});
kb.config[K].config.get().then(g=>{0!=Object.keys(g).length?kb.field.load(kb.config[K].app,!0).then(u=>{e.app={id:kb.config[K].app,fields:u.origin};e.fieldInfos=u;try{(p=>{if(0!=p.length){var w=(q,d,n)=>{var r=(b=>Array.from(new Set(b.map(l=>e.fieldInfos.parallelize[l.value.internal.value].tableCode))).reduce((l,f)=>{d[f].value=[];l[f]={fields:b.filter(h=>e.fieldInfos.parallelize[h.value.internal.value].tableCode==f),row:kb.record.create(e.fieldInfos.origin[f],!1)};return l},{}))(q.mapping.value.reduce((b,
l)=>{l.value.internal.value in e.fieldInfos.parallelize&&b.push(l);return b},[]));n.each((b,l)=>{for(var f in r)d[f].value.push((h=>{r[f].fields.each((a,A)=>{if(a.value.internal.value in e.fieldInfos.parallelize)switch(e.fieldInfos.parallelize[a.value.internal.value].type){case "lookup":A=b[a.value.external.value];h[a.value.internal.value]={lookup:!0,search:"search"in A?A.search:"",value:A.value};break;default:h[a.value.internal.value].value=b[a.value.external.value].value}});return{value:h}})(kb.extend({},
r[f].row)))});return d};e.mobile&&kb.elm("body").addClass("kb-mobile");switch(e.type){case "create":case "edit":case "detail":var z=q=>{(d=>{(n=>{n&&kb.field.load(d.app.value).then(r=>{(b=>{((l,f)=>{var h={},a={copy:kb.create("button").addClass("kb-linkage-container-button").html(d.label.value).on("click",k=>{kb.confirm(d.message.value,()=>{kb.event.call("kb.action.call",{container:kb.elm("body"),record:w(d,(e.mobile?kintone.mobile.app.record:kintone.app.record).get().record,h.records),mobile:e.mobile,
pattern:"change",fields:(c=>c.reduce((m,x)=>m=m.concat(Object.keys(e.fieldInfos.tables[x].fields)),c))(d.mapping.value.reduce((c,m)=>{m.value.internal.value in e.fieldInfos.parallelize&&c.push(e.fieldInfos.parallelize[m.value.internal.value].tableCode);return c},[])),stopPropagation:!0,workplace:"record"}).then(c=>{kb.event.call("kb.style.call",{container:c.container,record:c.record,mobile:c.mobile,pattern:"$id"in c.record?c.record.$id.value?"edit":"create":"create",workplace:c.workplace}).then(m=>
{(e.mobile?kintone.mobile.app.record:kintone.app.record).set({record:m.record})}).catch(()=>{})}).catch(()=>{})})}),edit:kb.create("button").addClass("kb-icon kb-icon-edit").on("click",k=>{[a.total,a.reload,a.open,a.edit,a.prev,a.next,a.copy].each((c,m)=>c.addClass("kb-hidden"));[a.submit,a.cancel].each((c,m)=>c.removeClass("kb-hidden"));l.elms(".kb-field").each((c,m)=>c.removeClass("kb-readonly"));(c=>{c=kb.elm(".kb_spread_style_"+CSS.escape(c));c.parentNode.removeChild(c)})("view_"+b.id+"_"+b.view.id+
"_"+location.host.split(".").first());n.parentNode.show()}),submit:kb.create("button").addClass("kb-linkage-container-button").on("click",k=>{var c=l.tr.reduce((x,v,F)=>{x.error||"unsaved"!=v.elm(".kb-scope").attr("unsaved")||(v=kb.record.get(v.elm(".kb-scope"),b),v.error?x.error=!0:x.records["row"+F.toString()]=v.record);return x},{error:!1,records:{}}),m=(x=!1)=>{[a.total,a.reload,a.open,a.edit,a.prev,a.next,a.copy].each((v,F)=>v.removeClass("kb-hidden"));[a.submit,a.cancel].each((v,F)=>v.addClass("kb-hidden"));
x?J((e.mobile?kintone.mobile.app.record:kintone.app.record).get().record):A()};c.error||0==Object.keys(c.records).length?m():kb.confirm(kb.constants.common.message.confirm.submit[kb.operator.language],x=>{if(x)m();else{var v={},F;for(F in c.records)((G,Q)=>{var I=G.$id.value,R=G.$rowId.value,M=JSON.parse(JSON.stringify(h.origin.find(B=>B.$id.value==I)||{}));0!=Object.keys(M)&&(I in v||(v[I]=(B=>{var E={id:I,record:{$id:M.$id}};B&&(E.record[B]=M[B]);return E})(Array.from(new Set(d.mapping.value.map(B=>
r.parallelize[B.value.external.value].tableCode))).join(""))),v[I].record=b.view.fields.reduce((B,E)=>{l.tr[Q].elm('[field-id="'+CSS.escape(E)+'"]').hasAttribute("edited")&&(O=>{O?B[O].value.each((P,S)=>{P.id==R&&(P.value[E]=G[E])}):B[E]=G[E]})(b.fields[E].tableCode);return B},v[I].record))})(c.records[F],F.replace(/^row/g,""));kb.view.records.set(b.id,{put:Object.values(v)},!1,!0).then(G=>{m(!0)}).catch(G=>{kb.alert(kb.error.parse(G));m()})}},!0)}).html(kb.constants.common.caption.button.submit[kb.operator.language]).addClass("kb-hidden"),
cancel:kb.create("button").addClass("kb-linkage-container-button").on("click",k=>{[a.total,a.reload,a.open,a.edit,a.prev,a.next,a.copy].each((c,m)=>c.removeClass("kb-hidden"));[a.submit,a.cancel].each((c,m)=>c.addClass("kb-hidden"));A()}).html(kb.constants.common.caption.button.cancel[kb.operator.language]).addClass("kb-hidden"),open:kb.create("button").addClass("kb-icon kb-icon-open").on("click",k=>{window.open(kb.record.page.view(e.mobile,b.id,"20",h.query))}),prev:kb.create("button").addClass("kb-icon kb-icon-arrow kb-icon-arrow-left").on("click",
k=>{h.offset-=f;A()}),next:kb.create("button").addClass("kb-icon kb-icon-arrow kb-icon-arrow-right").on("click",k=>{h.offset+=f;A()}),reload:kb.create("button").addClass("kb-icon kb-icon-reload").on("click",k=>{J((e.mobile?kintone.mobile.app.record:kintone.app.record).get().record)}),total:kb.create("span").addClass("kb-linkage-container-monitor").html("")},A=()=>{var k=h.records.slice(h.offset,h.offset+f);l.clearRows();k.each((c,m)=>{(x=>{kb.record.set(x.elm("[form-id=form_"+b.id+"]"),b,c).then(()=>
{x.elm(".kb-view-row-edit").attr("href",kb.record.page.detail(e.mobile,b.id,c.$id.value)).attr("target","_blank");m==k.length-1&&n.parentNode.show()})})(l.addRow())});switch(kb.operator.language){case "en":a.total.html(h.records.length.toString()+"records in total");break;case "ja":a.total.html("\u7dcf"+h.records.length.toString()+"\u884c");break;case "zh":a.total.html("\u5171"+h.records.length.toString()+"\u6761\u8bb0\u5f55");break;case "zh-TW":a.total.html("\u5171"+h.records.length.toString()+"\u7b46\u8a18\u9304")}0<
h.offset?a.prev.removeAttr("disabled"):a.prev.attr("disabled","disabled");h.offset+(f==k.length?f:k.length)<h.records.length?a.next.removeAttr("disabled"):a.next.attr("disabled","disabled")},J=k=>{N(d,k).then(c=>{h=c;A()}).catch(()=>{h={offset:0,records:[]};A()})};switch(e.type){case "create":case "edit":n.append(kb.create("div").addClass("kb-linkage-container-footer").append(a.total).append(a.reload).append(a.open).append(a.edit).append(a.prev).append(a.next).append(a.copy).append(a.submit).append(a.cancel));
break;case "detail":n.append(kb.create("div").addClass("kb-linkage-container-footer").append(a.total).append(a.reload).append(a.open).append(a.edit).append(a.prev).append(a.next).append(a.submit).append(a.cancel))}d.editable.value.includes("editable")||a.edit.addClass("kb-hidden");((k,c)=>{kintone.events.on(k,c);k.each((m,x)=>{m in e.handlers||(e.handlers[m]=[]);e.handlers[m].push(c)})})(d.criteria.value.reduce((k,c)=>{k.push("app.record.create.change."+c.value.internal.value);k.push("app.record.edit.change."+
c.value.internal.value);k.push("mobile.app.record.create.change."+c.value.internal.value);k.push("mobile.app.record.edit.change."+c.value.internal.value);return k},[]),k=>J(k.record));b.view.fields.each((k,c)=>{kb.event.on("kb.change."+k,m=>{m.container.elm('[field-id="'+CSS.escape(k)+'"]').attr("edited","edited");return m})});J(t.record)})(kb.view.create(n.addClass("kb-linkage-container"),b,b.view.id,e.mobile).elm(".kb-view"),parseInt(d.limit.value))})({id:d.app.value,disables:[],fields:(b=>{b.$rowId=
{code:"$rowId",type:"SINGLE_LINE_TEXT",label:"",required:!1,noLabel:!0,placeholder:""};return b})(r.parallelize),view:{id:"linkage_"+d.app.value+"_"+d.container.value,buttons:["delete"],fields:d.mapping.value.map(b=>b.value.external.value),mode:"viewer"}})}).catch(()=>{})})((e.mobile?kintone.mobile.app.record:kintone.app.record).getSpaceElement(d.container.value).css({width:"max-content"}));q++;q<p.length&&z(q)})(p[q])};"editable"in p.first()||(kb.alert(kb.error.config.update("Boost! Linkage")),p=
p.map(q=>{q.editable={value:[]};return q}));z(0);C(t);break;case "index":z=q=>{(d=>{kb.filter.auth(d.user.value,d.organization.value,d.group.value).then(n=>{n&&(d.view.value&&d.view.value!=t.viewId.toString()||kb.button.create(e.mobile,e.type,"kb-linkage-button"+q.toString(),d.label.value,d.message.value,()=>{kb.view.records.get(e.app.id,(e.mobile?kintone.mobile.app:kintone.app).getQueryCondition()).then(r=>{var b=[];let l=(f,h)=>{N(d,r[f]).then(a=>{b.push(kb.view.records.transform(w(d,r[f],a.records)));
kb.progressUpdate();f++;f<r.length?l(f,h):h()}).catch(()=>{})};0!=r.length?(kb.progressStart(r.length),l(0,()=>{kb.view.records.set(e.app.id,{put:b}).then(f=>kb.alert("Done!",()=>window.location.reload(!0))).catch(f=>kb.alert(kb.error.parse(f)))})):kb.alert("There are no records.")}).catch(r=>kb.alert(kb.error.parse(r)))}));q++;q<p.length&&z(q)}).catch(n=>{q++;q<p.length&&z(q)})})(p[q])},z(0),C(t)}}else C(t)})(JSON.parse(g.tab).map((p,w)=>kb.extend({sIndex:{value:w.toString()}},p.setting)).reduce((p,
w)=>{switch(e.type){case "index":w.bulk.value.includes("bulk")&&p.push(w);break;default:p.push(w)}return p},[]))}catch(p){kb.alert(kb.error.parse(p)),C(t)}}).catch(u=>C(t)):C(t)}).catch(g=>C(t))})("mobile"==t.type.split(".").first(),t.type.split(".").slice(-2).first())}))})(kintone.$PLUGIN_ID);
