/*
* FileName "plugins.action.js"
* Version: 1.0.0
* Copyright (c) 2023 Pandafirm LLC
* Distributed under the terms of the GNU Lesser General Public License.
* https://opensource.org/licenses/LGPL-2.1
*/
(function(K){var b={},M=function(d,l,E,L){return new Promise(function(J,t){var D=JSON.stringify(kb.record.simplify({fields:b.fieldInfos.origin},l)),m=function(k,e){var g=function(){k++;k<d.length?m(k,e):e()};(function(a){var h=kb.filter.scan(b.app,l,a.condition.value);h?kb.filter.auth(a.user.value,a.organization.value,a.group.value).then(function(A){if(A){var G={clear:function(x){try{a.clear.value.map(function(c){return c.value}).each(function(c,z){c.table.value in b.fieldInfos.tables&&(l[c.table.value].value=
l[c.table.value].value.filter(function(y){return!h[c.table.value].value.includes(y)}),h[c.table.value].value=[])}),x()}catch(c){kb.alert(kb.error.parse(c)),t()}},fill:function(x){try{a.fill.value.map(function(c){return c.value}).each(function(c,z){c.table.value in b.fieldInfos.tables&&function(y){y=kb.isNumeric(y)?parseInt(y)-h[c.table.value].value.length:0;0<y&&Array(y).fill().map(function(){return kb.record.create(b.fieldInfos.origin[c.table.value],!1)}).each(function(B,q){l[c.table.value]==h[c.table.value]?
l[c.table.value].value.push({value:B}):(l[c.table.value].value.push({value:B}),h[c.table.value].value.push({value:B}))})}(kb.formula.calculate({field:{value:Object.values(b.fieldInfos.parallelize).first().code},formula:c.range},h,h,l,b.fieldInfos.parallelize))}),x()}catch(c){kb.alert(kb.error.parse(c)),t()}},formula:function(x){try{a.formula.value.map(function(c){return c.value}).each(function(c,z){c.field.value in b.fieldInfos.parallelize&&function(y){y.tableCode?h[y.tableCode].value.each(function(B,
q){B.value[y.code].value=kb.formula.calculate(c,B.value,h,l,b.fieldInfos.parallelize);"lookup"==y.type&&(B.value[y.code].lookup=!0)}):(h[y.code].value=kb.formula.calculate(c,h,h,l,b.fieldInfos.parallelize),"lookup"==y.type&&(h[y.code].lookup=!0))}(b.fieldInfos.parallelize[c.field.value])}),x()}catch(c){kb.alert(kb.error.parse(c)),t()}},lookup:function(x){try{a.lookupApp.value?kb.field.load(a.lookupApp.value).then(function(c){(function(z){var y=[],B=[],q=function(r,u){var n=function(v,p){return v.lookup?
kb.extend({lookup:!0},p):p};kb.view.records.get(a.lookupApp.value,u.query,u.sort).then(function(v){0!=v.length?function(p){a.lookupLimited.value.includes("limited")||1==v.length?p(v.first()):b.picker.show({app:a.lookupApp.value,query:u.query,sort:u.sort,picker:y.reduce(function(w,f){w[f.external.code]=f.external;return w},{})},function(w){return p(w)})}(function(p){y.each(function(w,f){if(a.lookupOverwrite.value.includes("overwrite")||kb.field.isEmpty(u.record[w.internal.code].value))u.record[w.internal.code]=
n(w.internal,p[w.external.code])});r++;r<B.length?q(r,B[r]):(E.latest.action[a.sIndex.value].lookup=C(),x())}):(a.lookupReset.value.includes("reset")&&y.each(function(p,w){u.record[p.internal.code]=n(p.internal,kb.record.create({fields:{empty:p.internal}}).empty)}),r++,r<B.length?q(r,B[r]):(E.latest.action[a.sIndex.value].lookup=C(),x()))})["catch"](function(v){kb.alert(kb.error.parse(v));t()})},C=function(){return function(r){return JSON.stringify(B.reduce(function(u,n){u.push(n.query);u.push(kb.record.simplify({fields:r},
n.record));return u},[]))}(y.reduce(function(r,u){r[u.internal.code]=u.internal;return r},{}))};a.lookupCriteria.value.some(function(r){return!(r.value.external.value in z.external&&r.value.internal.value in z.internal)})?(kb.alert("No field to lookup was found"),t()):a.lookupMapping.value.some(function(r){return!(r.value.external.value in z.external&&r.value.internal.value in z.internal)})?(kb.alert("No field to lookup was found"),t()):(y=a.lookupMapping.value.map(function(r){return{external:z.external[r.value.external.value],
internal:z.internal[r.value.internal.value]}}),B=function(r){return r.map(function(u){return{query:a.lookupCriteria.value.reduce(function(n,v){var p=z.external[v.value.external.value],w=v.value.operator.value,f=z.internal[v.value.internal.value];var F=f.tableCode?u.value:l;a.lookupIgnore.value.includes("ignore")&&kb.field.isEmpty(F[f.code].value)||n.push(kb.filter.query.create(p,w,F[f.code]));return n},kb.filter.query.parse(a.lookupFilter.value).map(function(n){return z.external[n.field].code+" "+
n.operator+" "+n.value})).join(" and "),sort:(0!=a.lookupSort.value.length?a.lookupSort.value.map(function(n){return n.value.field.value+" "+n.value.order.value}):["$id asc"]).join(","),record:u.value}})}(function(r){return r?h[r].value:[{value:l}]}(Array.from(new Set(y.map(function(r){return r.internal.tableCode}))).first())),0!=B.length?E.latest.action[a.sIndex.value].lookup&&E.latest.action[a.sIndex.value].lookup==C()?x():q(0,B.first()):x())})({external:c.origin,internal:b.fieldInfos.parallelize})})["catch"](function(c){kb.alert(kb.error.parse(c));
t()}):x()}catch(c){kb.alert(kb.error.parse(c)),t()}},user:function(x){try{a.userSource.value?function(c){0==kb.roleSet.user.length?kb.roleSet.load().then(function(){return c()}):c()}(function(){var c=[],z=[],y=function(q,C){(function(u){c.each(function(n,v){if(n.isCustom)switch(n.field.type){case "USER_SELECT":n.value=u.reduce(function(p,w){"customItemValues"in w&&function(f){0!=f.length&&function(F){(function(H){0!=H.length&&(p.some(function(I){return I.code==H.first().info.code})||p.push({code:H.first().info.code,
name:H.first().info.name}))})(kb.roleSet.user.filter(function(H){return H.info.id==F}))}(f.first().value)}(w.customItemValues.filter(function(f){return f.code==n.item}));return Array.from(new Set(p)).filter(function(f){return f})},[]);break;default:n.value=u.reduce(function(p,w){"customItemValues"in w&&function(f){0!=f.length&&p.push(f.first().value)}(w.customItemValues.filter(function(f){return f.code==n.item}));return Array.from(new Set(p)).filter(function(f){return f})},[]).join(",")}else switch(n.item){case "groups":case "organizations":n.value=
u.map(function(p){return p.code});break;case "primaryOrganization":n.value=u.reduce(function(p,w){n.item in w&&function(f){0!=f.length&&(p.some(function(F){return F.code==f.first().info.code})||p.push({code:f.first().info.code,name:f.first().info.name}))}(kb.roleSet.organization.filter(function(f){return f.info.id==w[n.item]}));return p},[]);break;default:n.value=u.reduce(function(p,w){n.item in w&&p.push(w[n.item]);return Array.from(new Set(p)).filter(function(f){return f})},[]).join(",")}})})(C[a.userSource.value].value.reduce(function(u,
n){(function(v){0!=v.length&&u.push(v.first().info)})(kb.roleSet.user.filter(function(v){return v.info.code==n.code}));return u},[]));var r=function(u,n){(function(v,p){var w=function(f,F,H){switch(v.item){case "groups":kintone.api(kintone.api.url("/v1/user/groups",!0),"GET",{code:v.value[f]}).then(function(I){I.groups&&(F=F.concat(I.groups.map(function(N){return{code:N.code,name:N.name}})),f++,f<v.value.length?w(f,F,H):H(F))})["catch"](function(I){kb.alert(kb.error.parse(I));t()});break;case "organizations":kintone.api(kintone.api.url("/v1/user/organizations",
!0),"GET",{code:v.value[f]}).then(function(I){I.organizationTitles&&(F=F.concat(I.organizationTitles.map(function(N){return{code:N.organization.code,name:N.organization.name}})),f++,f<v.value.length?w(f,F,H):H(F))})["catch"](function(I){kb.alert(kb.error.parse(I));t()})}};a.userOverwrite.value.includes("overwrite")||kb.field.isEmpty(C[v.field.code].value)||p();switch(v.item){case "groups":case "organizations":0!=v.value.length?w(0,[],function(f){C[v.field.code].value=f;p()}):(C[v.field.code].value=
v.value,p());break;default:C[v.field.code].value=v.value,p()}})(c[u],function(){u++;u<c.length?r(u,n):n()})};r(0,function(){q++;q<z.length?y(q,z[q]):(E.latest.action[a.sIndex.value].user=B(),x())})},B=function(){return function(q){return JSON.stringify(z.map(function(C){return kb.record.simplify({fields:q},C)}))}(c.reduce(function(q,C){q[C.field.code]=C.field;return q},function(q){var C={};C[q]=b.fieldInfos.parallelize[q];return C}(a.userSource.value)))};a.userCustomItem.value.some(function(q){return!(q.value.field.value in
b.fieldInfos.parallelize)})?(kb.alert("No field to user informations was found"),t()):a.userMapping.value.some(function(q){return!(q.value.field.value in b.fieldInfos.parallelize)})?(kb.alert("No field to user informations was found"),t()):(a.userCustomItem.value.each(function(q,C){c.push({isCustom:!0,item:q.value.item.value,field:b.fieldInfos.parallelize[q.value.field.value],value:[]})}),a.userMapping.value.each(function(q,C){c.push({isCustom:!1,item:q.value.item.value,field:b.fieldInfos.parallelize[q.value.field.value],
value:[]})}),a.userPrimaryOrganization.value&&a.userPrimaryOrganization.value in b.fieldInfos.parallelize&&c.push({isCustom:!1,item:"primaryOrganization",field:b.fieldInfos.parallelize[a.userPrimaryOrganization.value],value:[]}),a.userOrganization.value&&a.userOrganization.value in b.fieldInfos.parallelize&&c.push({isCustom:!1,item:"organizations",field:b.fieldInfos.parallelize[a.userOrganization.value],value:[]}),a.userGroup.value&&a.userGroup.value in b.fieldInfos.parallelize&&c.push({isCustom:!1,
item:"groups",field:b.fieldInfos.parallelize[a.userGroup.value],value:[]}),z=function(q){return q?h[q].value:[{value:l}]}(b.fieldInfos.parallelize[a.userSource.value].tableCode).map(function(q){return q.value}),0!=z.length?E.latest.action[a.sIndex.value].user&&E.latest.action[a.sIndex.value].user==B()?x():0!=c.length?y(0,z.first()):x():x())}):x()}catch(c){kb.alert(kb.error.parse(c)),t()}}};G.clear(function(){G.fill(function(){G.formula(function(){G.lookup(function(){G.user(function(){g()})})})})})}else g()})["catch"](function(A){kb.alert(kb.error.parse(A));
t()}):g()})(function(a){E.latest?E.latest.action||(E.latest.action={}):E.latest={action:{}};a.sIndex.value in E.latest.action||(E.latest.action[a.sIndex.value]={lookup:"[]",user:"[]"});return a}(d[k]))};m(0,function(){J({record:l,performed:D!=JSON.stringify(kb.record.simplify({fields:b.fieldInfos.origin},l))})})})};kintone.events.on("app.record.create.show app.record.detail.process.proceed app.record.detail.show app.record.edit.show app.record.index.show mobile.app.record.create.show mobile.app.record.detail.process.proceed mobile.app.record.detail.show mobile.app.record.edit.show mobile.app.record.index.show".split(" "),
function(d){return new Promise(function(l,E){(function(L,J){b.mobile=L;b.type=J;kb.config[K].config.get().then(function(t){0!=Object.keys(t).length?kb.field.load(kb.config[K].app,!0).then(function(D){b.app={id:kb.config[K].app,fields:D.origin};b.fieldInfos=D;b.picker=new KintoneBoosterRecordPicker("record");try{["create","edit","reuse"].includes(b.type)&&function(m){if(0!=m.length){var k="",e=null;kintone.events.on(D.changes.reduce(function(g,a){g.push("app.record.create.change."+a);g.push("app.record.edit.change."+
a);g.push("mobile.app.record.create.change."+a);g.push("mobile.app.record.edit.change."+a);return g},[]),function(g){var a=function(){var h=m;return m.some(function(A){return!A.triggers})?(kb.alert(kb.error.config.update("Boost! Action")),[]):h=m.filter(function(A){return function(G){return!G.first()||G.includes(g.type.split(".").last())}(A.triggers.value.map(function(G){return G.value.field.value}))})}();if(function(){var h=!0;k&&(h=!1,k==JSON.stringify(kb.record.simplify({fields:D.origin},g.record))?
(k="",e=null):e<(new Date).getTime()-5E3&&(k="",e=null,h=!0));h&&["DATETIME","TIME"].includes(g.changes.field.type)&&function(A){A&&(Array.isArray(A)?A:[A]).each(function(G,x){G.elm(".control-errors-content-gaia")&&(h=!1)})}(kb.field.get(D.parallelize[g.type.split(".").last()],b.mobile,b.type));return h}()){if(0!=a.length)return M(a,g.record,kb.elm("body"),"record").then(function(h){kb.event.call("kb.style.call",{container:kb.elm("body"),record:g.record,mobile:b.mobile,pattern:"reuse"==b.type?"create":
b.type,workplace:"record"}).then(function(A){if(h.performed||A.performed)h.performed?(k=JSON.stringify(kb.record.simplify({fields:D.origin},A.record)),e=(new Date).getTime()):(k="",e=null),(b.mobile?kintone.mobile.app.record:kintone.app.record).set(g)})["catch"](function(){})})["catch"](function(){}),g;kb.event.call("kb.style.call",{container:kb.elm("body"),record:g.record,mobile:b.mobile,pattern:"reuse"==b.type?"create":b.type,workplace:"record"}).then(function(h){h.performed&&(k="",e=null,(b.mobile?
kintone.mobile.app.record:kintone.app.record).set(g))})["catch"](function(){})}});kb.event.on("kb.action.installed",function(g){return{installed:!0}})}else kb.event.on("kb.action.installed",function(g){return{installed:!1}})}(JSON.parse(t.tab).map(function(m,k){return kb.extend({sIndex:{value:k.toString()}},m.setting)}).reduce(function(m,k){(b.mobile?["both","mobile"]:["both","pc"]).includes(k.device.value)&&k.event.value.includes("change")&&m.push(k);return m},[])),function(m){if(0!=m.length)switch(b.type){case "create":case "edit":case "reuse":M(m,
d.record,kb.elm("body"),"record").then(function(e){return l(d)})["catch"](function(){});break;case "process":(function(e){0!=e.length?M(e,d.record,kb.elm("body"),"record").then(function(g){return l(d)})["catch"](function(){}):l(d)})(m.filter(function(e){return e.action.value==d.action.value+":"+d.status.value+":"+d.nextStatus.value}));break;case "detail":var k=function(e){(function(g){kb.filter.scan(b.app,d.record,g.condition.value)?kb.filter.auth(g.user.value,g.organization.value,g.group.value).then(function(a){a&&
kb.button.create(b.mobile,b.type,"kb-action-button"+e.toString(),g.label.value,g.message.value,function(){M([g],d.record,kb.elm("body"),"record").then(function(h){kb.view.records.set(b.app.id,{put:[kb.view.records.transform(h.record)]}).then(function(A){return kb.alert("Done!",function(){return window.location.reload(!0)})})["catch"](function(A){return kb.alert(kb.error.parse(A))})})["catch"](function(){})});e++;e<m.length&&k(e)})["catch"](function(a){e++;e<m.length&&k(e)}):(e++,e<m.length&&k(e))})(m[e])};
k(0);l(d);break;case "index":k=function(e){(function(g){kb.filter.auth(g.user.value,g.organization.value,g.group.value).then(function(a){a&&(g.view.value&&g.view.value!=d.viewId.toString()||kb.button.create(b.mobile,b.type,"kb-action-button"+e.toString(),g.label.value,g.message.value,function(){kb.view.records.get(b.app.id,(b.mobile?kintone.mobile.app:kintone.app).getQueryCondition()).then(function(h){var A=[],G=function(x,c){M([g],h[x],kb.create("div"),"record").then(function(z){z.performed&&A.push(kb.view.records.transform(z.record));
kb.progressUpdate();x++;x<h.length?G(x,c):c()})["catch"](function(){})};0!=h.length?(kb.progressStart(h.length),G(0,function(){kb.view.records.set(b.app.id,{put:A}).then(function(x){return kb.alert("Done!",function(){return window.location.reload(!0)})})["catch"](function(x){return kb.alert(kb.error.parse(x))})})):kb.alert("There are no records.")})["catch"](function(h){return kb.alert(kb.error.parse(h))})}));e++;e<m.length&&k(e)})["catch"](function(a){e++;e<m.length&&k(e)})})(m[e])},k(0),l(d)}else l(d)}(JSON.parse(t.tab).map(function(m,
k){return kb.extend({sIndex:{value:k.toString()}},m.setting)}).reduce(function(m,k){(b.mobile?["both","mobile"]:["both","pc"]).includes(k.device.value)&&k.event.value.includes(b.type)&&m.push(k);return m},[]))}catch(m){kb.alert(kb.error.parse(m)),l(d)}})["catch"](function(D){return l(d)}):l(d)})["catch"](function(t){return l(d)})})("mobile"==d.type.split(".").first(),d.reuse?"reuse":d.type.split(".").slice(-2).first())})});kb.event.on("kb.action.call",function(d){return new Promise(function(l,E){kb.config[K].config.get().then(function(L){0!=
Object.keys(L).length?kb.field.load(kb.config[K].app,!0).then(function(J){b.app={id:kb.config[K].app,fields:J.origin};b.fieldInfos=J;b.picker=new KintoneBoosterRecordPicker("record");try{(function(t){if(0!=t.length){var D=function(){var m=t;if("change"==d.pattern){if(t.some(function(k){return!k.triggers}))return kb.alert(kb.error.config.update("Boost! Action")),[];m=t.filter(function(k){return function(e){return!e.first()||e.includes(d.field)}(k.triggers.value.map(function(e){return e.value.field.value}))})}return m}();
0!=D.length?M(D,d.record,d.container,d.workplace?d.workplace:"record").then(function(m){d.performed=m.performed;l(d)})["catch"](function(){return l(d)}):l(d)}else l(d)})(JSON.parse(L.tab).map(function(t,D){return kb.extend({sIndex:{value:D.toString()}},t.setting)}).reduce(function(t,D){(d.mobile?["both","mobile"]:["both","pc"]).includes(D.device.value)&&D.event.value.includes(d.pattern)&&t.push(D);return t},[]))}catch(t){kb.alert(kb.error.parse(t)),l(d)}})["catch"](function(J){return l(d)}):l(d)})["catch"](function(L){return l(d)})})})})(kintone.$PLUGIN_ID);