/*
* FileName "plugins.style.config.js"
* Version: 1.0.0
* Copyright (c) 2023 Pandafirm LLC
* Distributed under the terms of the GNU Lesser General Public License.
* https://opensource.org/licenses/LGPL-2.1
*/
(function(g){var f={};kb.field.load(kintone.app.getId()).then(function(k){kb.config[g].build({submit:function(l,h){try{var c=!1;h.tab=[];h.flat={};(function(a){kb.config[g].tabbed.tabs.some(function(d){var b=kb.record.get(d.panel,a);b.error?(kb.alert(kb.constants.common.message.invalid.record[kb.operator.language]),kb.config[g].tabbed.activate(d),c=!0):(b.record.color.value=b.record.color.value.filter(function(e){return e.value.field.value}),b.record.editable.value=b.record.editable.value.filter(function(e){return e.value.field.value}),
b.record.display.value=b.record.display.value.filter(function(e){return e.value.field.value}),b.record.toggle.value=b.record.toggle.value.filter(function(e){return e.value.field.value}),h.tab.push({label:d.label.html(),setting:b.record}));return c})})({id:f.app.id,fields:f.app.fields.tab});(function(a){a=kb.record.get(l.main.elm(".kb-flat"),a);a.error?(kb.alert(kb.constants.common.message.invalid.record[kb.operator.language]),c=!0):h.flat=a.record})({id:f.app.id,fields:f.app.fields.flat});h.tab=JSON.stringify(h.tab);
h.flat=JSON.stringify(h.flat);return c?!1:h}catch(a){return kb.alert(kb.error.parse(a)),!1}}},function(l,h){try{f.app={id:g,fields:{tab:{page:{code:"page",type:"CHECK_BOX",label:"",required:!0,noLabel:!0,options:[{index:0,label:"create"},{index:1,label:"edit"},{index:2,label:"detail"},{index:3,label:"print"}]},color:{code:"color",type:"SUBTABLE",label:"",noLabel:!0,fields:{field:{code:"field",type:"DROP_DOWN",label:"",required:!1,noLabel:!0,options:[]},backcolor:{code:"backcolor",type:"COLOR",label:"",
required:!1,noLabel:!0,placeholder:kb.constants.config.prompt.color.backcolor[kb.operator.language]},forecolor:{code:"forecolor",type:"COLOR",label:"",required:!1,noLabel:!0,placeholder:kb.constants.config.prompt.color.forecolor[kb.operator.language]}}},editable:{code:"editable",type:"SUBTABLE",label:"",noLabel:!0,fields:{field:{code:"field",type:"DROP_DOWN",label:"",required:!1,noLabel:!0,options:[]},state:{code:"state",type:"DROP_DOWN",label:"",required:!1,noLabel:!0,options:[{index:0,label:"disable"},
{index:1,label:"enable"}]}}},display:{code:"display",type:"SUBTABLE",label:"",noLabel:!0,fields:{field:{code:"field",type:"DROP_DOWN",label:"",required:!1,noLabel:!0,options:[]},state:{code:"state",type:"DROP_DOWN",label:"",required:!1,noLabel:!0,options:[{index:0,label:"hide"},{index:1,label:"show"}]}}},toggle:{code:"toggle",type:"SUBTABLE",label:"",noLabel:!0,fields:{field:{code:"field",type:"DROP_DOWN",label:"",required:!1,noLabel:!0,options:[]},state:{code:"state",type:"DROP_DOWN",label:"",required:!1,
noLabel:!0,options:[{index:0,label:"open"},{index:1,label:"close"}]}}}},flat:{reusecolor:{code:"reusecolor",type:"COLOR",label:"",required:!1,noLabel:!0,placeholder:kb.constants.config.prompt.color.reusecolor[kb.operator.language]}}}},function(c){for(var a in c)f.app.fields.tab[a]=c[a]}(kb.config[g].ui.fields.conditions.get(k)),function(c){for(var a in c)f.app.fields.tab[a]=c[a]}(kb.config[g].ui.fields.users.get(k)),kb.config[g].tabbed=new KintoneBoosterConfigTabbed(l,{add:function(c){(function(a){c.tables=
{color:kb.table.activate(kb.table.create(a.fields.color),a),display:kb.table.activate(kb.table.create(a.fields.display),a),editable:kb.table.activate(kb.table.create(a.fields.editable),a),toggle:kb.table.activate(kb.table.create(a.fields.toggle),a)};c.panel.addClass("kb-scope").attr("form-id","form_"+a.id).append(kb.config[g].ui.fields.users.set(kb.config[g].ui.fields.conditions.set(kb.create("div").addClass("kb-config-tabbed-panel-block"),a),a).append(kb.create("h1").html(kb.constants.config.caption.page[kb.operator.language])).append(kb.create("section").append(kb.field.activate(function(d){d.elms("[type=checkbox]").each(function(b,
e){b.closest("label").elm("span").html(kb.constants.config.caption.page[b.val()][kb.operator.language])});return d}(kb.field.create(a.fields.page)),a)))).append(kb.create("h1").html(kb.constants.config.caption.color[kb.operator.language])).append(kb.create("section").append(function(d){d.template.elm("[field-id=field]").elm("select").empty().assignOption(kb.config[g].ui.options.fields(k,function(b,e){b.push({code:e.code,label:e.label});return b}),"label","code");d.elm("thead").hide();return d}(c.tables.color))).append(kb.create("h1").html(kb.constants.config.caption.editable[kb.operator.language])).append(kb.create("section").append(function(d){d.template.elm("[field-id=field]").elm("select").empty().assignOption(kb.config[g].ui.options.fields(k,
function(b,e){k.disables.includes(e.code)||b.push({code:e.code,label:e.label});return b}),"label","code");d.template.elm("[field-id=state]").elms("option").each(function(b,e){b.html(kb.constants.config.caption.editable[b.val()][kb.operator.language])});d.elm("thead").hide();return d}(c.tables.editable))).append(kb.create("h1").html(kb.constants.config.caption.display[kb.operator.language])).append(kb.create("section").append(function(d){d.template.elm("[field-id=field]").elm("select").empty().assignOption(kb.config[g].ui.options.fields(k,
function(b,e){b.push({code:e.code,label:e.label});return b},!0,!0),"label","code");d.template.elm("[field-id=state]").elms("option").each(function(b,e){b.html(kb.constants.config.caption.display[b.val()][kb.operator.language])});d.elm("thead").hide();return d}(c.tables.display))).append(kb.create("h1").html(kb.constants.config.caption.toggle[kb.operator.language])).append(kb.create("section").append(function(d){d.template.elm("[field-id=field]").elm("select").empty().assignOption(kb.config[g].ui.options.fields(k,
!1,!1,!0),"label","code");d.template.elm("[field-id=state]").elms("option").each(function(b,e){b.html(kb.constants.config.caption.toggle[b.val()][kb.operator.language])});d.elm("thead").hide();return d}(c.tables.toggle)));c.tables.color.addRow();c.tables.editable.addRow();c.tables.display.addRow();c.tables.toggle.addRow();c.panel.elms("input,select,textarea").each(function(d,b){return d.initialize()})})({id:f.app.id,fields:f.app.fields.tab})},copy:function(c,a){var d={id:f.app.id,fields:f.app.fields.tab},
b=kb.record.get(c.panel,d,!0).record;kb.record.set(a.panel,d,b)},del:function(c){}}),function(c){l.main.append(kb.create("div").addClass("kb-flat kb-scope").attr("form-id","form_"+c.id).append(kb.create("h1").html(kb.constants.config.caption.reuse[kb.operator.language])).append(kb.create("section").append(kb.create("p").html(kb.constants.config.description.reuse[kb.operator.language])).append(kb.field.activate(kb.field.create(c.fields.reusecolor),c))));l.main.elms("input,select,textarea").each(function(a,
d){return a.initialize()})}({id:f.app.id,fields:f.app.fields.flat}),0!=Object.keys(h).length?(function(c){c.each(function(a){var d={id:f.app.id,fields:f.app.fields.tab},b=kb.config[g].tabbed.add();kb.record.set(b.panel,d,a.setting);b.label.html(a.label)})}(JSON.parse(h.tab)),function(c){var a={id:f.app.id,fields:f.app.fields.flat};kb.record.set(l.main.elm(".kb-flat"),a,c)}(JSON.parse(h.flat))):kb.config[g].tabbed.add()}catch(c){kb.alert(kb.error.parse(c))}})})})(kintone.$PLUGIN_ID);
kb.constants=kb.extend({config:{caption:{color:{en:"Field Coloring",ja:"\u30d5\u30a3\u30fc\u30eb\u30c9\u914d\u8272",zh:"\u5b57\u6bb5\u914d\u8272"},display:{en:"Field Display Switching",ja:"\u30d5\u30a3\u30fc\u30eb\u30c9\u8868\u793a\u5207\u66ff",zh:"\u5b57\u6bb5\u663e\u793a\u5207\u6362",show:{en:"Display",ja:"\u8868\u793a\u3059\u308b",zh:"\u663e\u793a"},hide:{en:"Hide",ja:"\u8868\u793a\u3057\u306a\u3044",zh:"\u9690\u85cf"}},editable:{en:"Field Edit Restriction",ja:"\u30d5\u30a3\u30fc\u30eb\u30c9\u7de8\u96c6\u5236\u9650",
zh:"\u5b57\u6bb5\u7f16\u8f91\u9650\u5236",enable:{en:"Enabled",ja:"\u6709\u52b9",zh:"\u6709\u6548"},disable:{en:"Disabled",ja:"\u7121\u52b9",zh:"\u65e0\u6548"}},toggle:{en:"Group Toggle",ja:"\u30b0\u30eb\u30fc\u30d7\u958b\u9589",zh:"\u7ec4\u522b\u5f00\u95ed",open:{en:"Open",ja:"\u958b\u3051\u308b",zh:"\u6253\u5f00"},close:{en:"Close",ja:"\u9589\u3058\u308b",zh:"\u5173\u95ed"}},page:{en:"Allow action page",ja:"\u52d5\u4f5c\u30da\u30fc\u30b8",zh:"\u5141\u8bb8\u52a8\u4f5c",create:{en:"Record Create Page",
ja:"\u30ec\u30b3\u30fc\u30c9\u8ffd\u52a0\u753b\u9762",zh:"\u8bb0\u5f55\u521b\u5efa\u9875\u9762"},detail:{en:"Record Detail Page",ja:"\u30ec\u30b3\u30fc\u30c9\u8a73\u7d30\u753b\u9762",zh:"\u8bb0\u5f55\u8be6\u60c5\u9875"},edit:{en:"Record Edit Page",ja:"\u30ec\u30b3\u30fc\u30c9\u7de8\u96c6\u753b\u9762",zh:"\u8bb0\u5f55\u7f16\u8f91\u9875"},print:{en:"Record Print Page",ja:"\u30ec\u30b3\u30fc\u30c9\u5370\u5237\u753b\u9762",zh:"\u8bb0\u5f55\u6253\u5370\u9875"}},reuse:{en:"Highlighting during record reuse",
ja:"\u30ec\u30b3\u30fc\u30c9\u518d\u5229\u7528\u6642\u306e\u5f37\u8abf\u8868\u793a",zh:"\u8bb0\u5f55\u518d\u5229\u7528\u65f6\u7684\u9ad8\u4eae\u663e\u793a"}},description:{reuse:{en:"When reusing a record, please specify the color you want to change the background color of the button area to.",ja:"\u30ec\u30b3\u30fc\u30c9\u3092\u518d\u5229\u7528\u3057\u305f\u6642\u306b\u30dc\u30bf\u30f3\u30a8\u30ea\u30a2\u306e\u80cc\u666f\u8272\u3092\u5909\u66f4\u3057\u305f\u3044\u5834\u5408\u306f\u3001\u305d\u306e\u8272\u3092\u6307\u5b9a\u3057\u3066\u4e0b\u3055\u3044\u3002",
zh:"\u5f53\u91cd\u590d\u4f7f\u7528\u8bb0\u5f55\u65f6\uff0c\u8bf7\u6307\u5b9a\u60a8\u5e0c\u671b\u66f4\u6539\u6309\u94ae\u533a\u57df\u7684\u80cc\u666f\u989c\u8272\u3002"}},prompt:{color:{backcolor:{en:"BackColor",ja:"\u80cc\u666f\u8272",zh:"\u80cc\u666f\u989c\u8272"},forecolor:{en:"ForeColor",ja:"\u524d\u666f\u8272",zh:"\u524d\u666f\u989c\u8272"},reusecolor:{en:"Background color when reused",ja:"\u518d\u5229\u7528\u6642\u306e\u80cc\u666f\u8272",zh:"\u91cd\u65b0\u4f7f\u7528\u65f6\u7684\u80cc\u666f\u8272"}}}}},
kb.constants);