/*
* FileName "plugins.action.js"
* Version: 1.0.0
* Copyright (c) 2023 Pandafirm LLC
* Distributed under the terms of the GNU Lesser General Public License.
* https://opensource.org/licenses/LGPL-2.1
*/
(function(K){var c={},M=function(e,g,D,L){return new Promise(function(J,u){var C=JSON.stringify(kb.record.simplify({fields:c.fieldInfos.origin},g)),v=function(p,h){var f=function(){p++;p<e.length?v(p,h):h()};(function(a){if(a.lookupApp){var m=kb.filter.scan(c.app,g,a.condition.value);m?kb.filter.auth(a.user.value,a.organization.value,a.group.value).then(function(F){if(F){var I={clear:function(y){try{a.clear.value.map(function(b){return b.value}).each(function(b,z){b.table.value in c.fieldInfos.tables&&
(g[b.table.value].value=g[b.table.value].value.filter(function(x){return!m[b.table.value].value.includes(x)}),m[b.table.value].value=[])}),y()}catch(b){kb.alert(kb.error.parse(b)),u()}},fill:function(y){try{a.fill.value.map(function(b){return b.value}).each(function(b,z){b.table.value in c.fieldInfos.tables&&function(x){x=kb.isNumeric(x)?parseInt(x)-m[b.table.value].value.length:0;0<x&&Array(x).fill().map(function(){return kb.record.create(c.fieldInfos.origin[b.table.value],!1)}).each(function(A,
n){g[b.table.value]==m[b.table.value]?g[b.table.value].value.push({value:A}):(g[b.table.value].value.push({value:A}),m[b.table.value].value.push({value:A}))})}(kb.formula.calculate({field:{value:Object.values(c.fieldInfos.parallelize).first().code},formula:b.range},m,m,g,c.fieldInfos.parallelize))}),y()}catch(b){kb.alert(kb.error.parse(b)),u()}},formula:function(y){try{a.formula.value.map(function(b){return b.value}).each(function(b,z){b.field.value in c.fieldInfos.parallelize&&function(x){x.tableCode?
m[x.tableCode].value.each(function(A,n){A.value[x.code].value=kb.formula.calculate(b,A.value,m,g,c.fieldInfos.parallelize);"lookup"==x.type&&(A.value[x.code].lookup=!0)}):(m[x.code].value=kb.formula.calculate(b,m,m,g,c.fieldInfos.parallelize),"lookup"==x.type&&(m[x.code].lookup=!0))}(c.fieldInfos.parallelize[b.field.value])}),y()}catch(b){kb.alert(kb.error.parse(b)),u()}},lookup:function(y){try{a.lookupApp.value?kb.field.load(a.lookupApp.value).then(function(b){(function(z){var x=[],A=[],n=function(q,
r){var k=function(t,l){return t.lookup?kb.extend({lookup:!0},l):l};kb.view.records.get(a.lookupApp.value,r.query,r.sort).then(function(t){0!=t.length?function(l){a.lookupLimited.value.includes("limited")||1==t.length?l(t.first()):c.picker.show({app:a.lookupApp.value,query:r.query,sort:r.sort,picker:x.reduce(function(w,d){w[d.external.code]=d.external;return w},{})},function(w){return l(w)})}(function(l){x.each(function(w,d){if(a.lookupOverwrite.value.includes("overwrite")||kb.field.isEmpty(r.record[w.internal.code].value))r.record[w.internal.code]=
k(w.internal,l[w.external.code])});q++;q<A.length?n(q,A[q]):(D.latest.action[a.sIndex.value].lookup=B(),y())}):(a.lookupReset.value.includes("reset")&&x.each(function(l,w){r.record[l.internal.code]=k(l.internal,kb.record.create({fields:{empty:l.internal}}).empty)}),q++,q<A.length?n(q,A[q]):(D.latest.action[a.sIndex.value].lookup=B(),y()))})["catch"](function(t){kb.alert(kb.error.parse(t));u()})},B=function(){return function(q){return JSON.stringify(A.reduce(function(r,k){r.push(k.query);r.push(kb.record.simplify({fields:q},
k.record));return r},[]))}(x.reduce(function(q,r){q[r.internal.code]=r.internal;return q},{}))};a.lookupCriteria.value.some(function(q){return!(q.value.external.value in z.external&&q.value.internal.value in z.internal)})?(kb.alert("No field to lookup was found"),u()):a.lookupMapping.value.some(function(q){return!(q.value.external.value in z.external&&q.value.internal.value in z.internal)})?(kb.alert("No field to lookup was found"),u()):(x=a.lookupMapping.value.map(function(q){return{external:z.external[q.value.external.value],
internal:z.internal[q.value.internal.value]}}),A=function(q){return q.map(function(r){return{query:a.lookupCriteria.value.reduce(function(k,t){var l=z.external[t.value.external.value],w=t.value.operator.value,d=z.internal[t.value.internal.value];var E=d.tableCode?r.value:g;a.lookupIgnore.value.includes("ignore")&&kb.field.isEmpty(E[d.code].value)||k.push(kb.filter.query.create(l,w,E[d.code]));return k},kb.filter.query.parse(a.lookupFilter.value).map(function(k){return z.external[k.field].code+" "+
k.operator+" "+k.value})).join(" and "),sort:(0!=a.lookupSort.value.length?a.lookupSort.value.map(function(k){return k.value.field.value+" "+k.value.order.value}):["$id asc"]).join(","),record:r.value}})}(function(q){return q?m[q].value:[{value:g}]}(Array.from(new Set(x.map(function(q){return q.internal.tableCode}))).first())),0!=A.length?D.latest.action[a.sIndex.value].lookup&&D.latest.action[a.sIndex.value].lookup==B()?y():n(0,A.first()):y())})({external:b.origin,internal:c.fieldInfos.parallelize})})["catch"](function(b){kb.alert(kb.error.parse(b));
u()}):y()}catch(b){kb.alert(kb.error.parse(b)),u()}},user:function(y){try{a.userSource.value?function(b){0==kb.roleSet.user.length?kb.roleSet.load().then(function(){return b()}):b()}(function(){var b=[],z=[],x=function(n,B){(function(r){b.each(function(k,t){if(k.isCustom)switch(k.field.type){case "USER_SELECT":k.value=r.reduce(function(l,w){"customItemValues"in w&&function(d){0!=d.length&&function(E){(function(G){0!=G.length&&(l.some(function(H){return H.code==G.first().info.code})||l.push({code:G.first().info.code,
name:G.first().info.name}))})(kb.roleSet.user.filter(function(G){return G.info.id==E}))}(d.first().value)}(w.customItemValues.filter(function(d){return d.code==k.item}));return Array.from(new Set(l)).filter(function(d){return d})},[]);break;default:k.value=r.reduce(function(l,w){"customItemValues"in w&&function(d){0!=d.length&&l.push(d.first().value)}(w.customItemValues.filter(function(d){return d.code==k.item}));return Array.from(new Set(l)).filter(function(d){return d})},[]).join(",")}else switch(k.item){case "groups":case "organizations":k.value=
r.map(function(l){return l.code});break;case "primaryOrganization":k.value=r.reduce(function(l,w){k.item in w&&function(d){0!=d.length&&(l.some(function(E){return E.code==d.first().info.code})||l.push({code:d.first().info.code,name:d.first().info.name}))}(kb.roleSet.organization.filter(function(d){return d.info.id==w[k.item]}));return l},[]);break;default:k.value=r.reduce(function(l,w){k.item in w&&l.push(w[k.item]);return Array.from(new Set(l)).filter(function(d){return d})},[]).join(",")}})})(B[a.userSource.value].value.reduce(function(r,
k){(function(t){0!=t.length&&r.push(t.first().info)})(kb.roleSet.user.filter(function(t){return t.info.code==k.code}));return r},[]));var q=function(r,k){(function(t,l){var w=function(d,E,G){switch(t.item){case "groups":kintone.api(kintone.api.url("/v1/user/groups",!0),"GET",{code:t.value[d]}).then(function(H){H.groups&&(E=E.concat(H.groups.map(function(N){return{code:N.code,name:N.name}})),d++,d<t.value.length?w(d,E,G):G(E))})["catch"](function(H){kb.alert(kb.error.parse(H));u()});break;case "organizations":kintone.api(kintone.api.url("/v1/user/organizations",
!0),"GET",{code:t.value[d]}).then(function(H){H.organizationTitles&&(E=E.concat(H.organizationTitles.map(function(N){return{code:N.organization.code,name:N.organization.name}})),d++,d<t.value.length?w(d,E,G):G(E))})["catch"](function(H){kb.alert(kb.error.parse(H));u()})}};a.userOverwrite.value.includes("overwrite")||kb.field.isEmpty(B[t.field.code].value)||l();switch(t.item){case "groups":case "organizations":0!=t.value.length?w(0,[],function(d){B[t.field.code].value=d;l()}):(B[t.field.code].value=
t.value,l());break;default:B[t.field.code].value=t.value,l()}})(b[r],function(){r++;r<b.length?q(r,k):k()})};q(0,function(){n++;n<z.length?x(n,z[n]):(D.latest.action[a.sIndex.value].user=A(),y())})},A=function(){return function(n){return JSON.stringify(z.map(function(B){return kb.record.simplify({fields:n},B)}))}(b.reduce(function(n,B){n[B.field.code]=B.field;return n},function(n){var B={};B[n]=c.fieldInfos.parallelize[n];return B}(a.userSource.value)))};a.userCustomItem.value.some(function(n){return!(n.value.field.value in
c.fieldInfos.parallelize)})?(kb.alert("No field to user informations was found"),u()):a.userMapping.value.some(function(n){return!(n.value.field.value in c.fieldInfos.parallelize)})?(kb.alert("No field to user informations was found"),u()):(a.userCustomItem.value.each(function(n,B){b.push({isCustom:!0,item:n.value.item.value,field:c.fieldInfos.parallelize[n.value.field.value],value:[]})}),a.userMapping.value.each(function(n,B){b.push({isCustom:!1,item:n.value.item.value,field:c.fieldInfos.parallelize[n.value.field.value],
value:[]})}),a.userPrimaryOrganization.value&&a.userPrimaryOrganization.value in c.fieldInfos.parallelize&&b.push({isCustom:!1,item:"primaryOrganization",field:c.fieldInfos.parallelize[a.userPrimaryOrganization.value],value:[]}),a.userOrganization.value&&a.userOrganization.value in c.fieldInfos.parallelize&&b.push({isCustom:!1,item:"organizations",field:c.fieldInfos.parallelize[a.userOrganization.value],value:[]}),a.userGroup.value&&a.userGroup.value in c.fieldInfos.parallelize&&b.push({isCustom:!1,
item:"groups",field:c.fieldInfos.parallelize[a.userGroup.value],value:[]}),z=function(n){return n?m[n].value:[{value:g}]}(c.fieldInfos.parallelize[a.userSource.value].tableCode).map(function(n){return n.value}),0!=z.length?D.latest.action[a.sIndex.value].user&&D.latest.action[a.sIndex.value].user==A()?y():0!=b.length?x(0,z.first()):y():y())}):y()}catch(b){kb.alert(kb.error.parse(b)),u()}}};I.clear(function(){I.fill(function(){I.formula(function(){I.lookup(function(){I.user(function(){f()})})})})})}else f()})["catch"](function(F){kb.alert(kb.error.parse(F));
u()}):f()}else kb.alert(kb.error.config.update("Boost! Action")),J({record:g,performed:!1}),h()})(function(a){D.latest?D.latest.action||(D.latest.action={}):D.latest={action:{}};a.sIndex.value in D.latest.action||(D.latest.action[a.sIndex.value]={lookup:"[]",user:"[]"});return a}(e[p]))};v(0,function(){J({record:g,performed:C!=JSON.stringify(kb.record.simplify({fields:c.fieldInfos.origin},g))})})})};kintone.events.on("app.record.create.show app.record.detail.process.proceed app.record.detail.show app.record.edit.show app.record.index.show mobile.app.record.create.show mobile.app.record.detail.process.proceed mobile.app.record.detail.show mobile.app.record.edit.show mobile.app.record.index.show".split(" "),
function(e){return new Promise(function(g,D){(function(L,J){c.mobile=L;c.type=J;kb.config[K].config.get().then(function(u){0!=Object.keys(u).length?kb.field.load(kb.config[K].app,!0).then(function(C){c.app={id:kb.config[K].app,fields:C.origin};c.fieldInfos=C;c.picker=new KintoneBoosterRecordPicker("record");try{["create","edit","reuse"].includes(c.type)&&function(v){if(0!=v.length){var p="",h=null;kintone.events.on(C.changes.reduce(function(f,a){f.push("app.record.create.change."+a);f.push("app.record.edit.change."+
a);f.push("mobile.app.record.create.change."+a);f.push("mobile.app.record.edit.change."+a);return f},[]),function(f){if(function(){var a=!0;p&&(a=!1,p==JSON.stringify(kb.record.simplify({fields:C.origin},f.record))?(p="",h=null):h<(new Date).getTime()-5E3&&(p="",h=null,a=!0));a&&["DATETIME","TIME"].includes(f.changes.field.type)&&function(m){m&&(Array.isArray(m)?m:[m]).each(function(F,I){F.elm(".control-errors-content-gaia")&&(a=!1)})}(kb.field.get(C.parallelize[f.type.split(".").last()],c.mobile,
c.type));return a}())return M(v,f.record,kb.elm("body"),"record").then(function(a){kb.event.call("kb.style.call",{container:kb.elm("body"),record:f.record,mobile:c.mobile,pattern:"reuse"==c.type?"create":c.type,workplace:"record"}).then(function(m){if(a.performed||m.performed)a.performed?(p=JSON.stringify(kb.record.simplify({fields:C.origin},m.record)),h=(new Date).getTime()):(p="",h=null),(c.mobile?kintone.mobile.app.record:kintone.app.record).set(f)})["catch"](function(){})})["catch"](function(){}),
f});kb.event.on("kb.action.installed",function(f){return{installed:!0}})}else kb.event.on("kb.action.installed",function(f){return{installed:!1}}),g(e)}(JSON.parse(u.tab).map(function(v,p){return kb.extend({sIndex:{value:p.toString()}},v.setting)}).reduce(function(v,p){(c.mobile?["both","mobile"]:["both","pc"]).includes(p.device.value)&&p.event.value.includes("change")&&v.push(p);return v},[])),function(v){if(0!=v.length)switch(c.type){case "create":case "edit":case "reuse":M(v,e.record,kb.elm("body"),
"record").then(function(h){return g(e)})["catch"](function(){});break;case "process":(function(h){0!=h.length?M(h,e.record,kb.elm("body"),"record").then(function(f){return g(e)})["catch"](function(){}):g(e)})(v.filter(function(h){return h.action.value==e.action.value+":"+e.status.value+":"+e.nextStatus.value}));break;case "detail":var p=function(h){(function(f){kb.filter.scan(c.app,e.record,f.condition.value)?kb.filter.auth(f.user.value,f.organization.value,f.group.value).then(function(a){a&&kb.button.create(c.mobile,
c.type,"kb-action-button"+h.toString(),f.label.value,f.message.value,function(){M([f],e.record,kb.elm("body"),"record").then(function(m){kb.view.records.set(c.app.id,{put:[kb.view.records.transform(m.record)]}).then(function(F){return kb.alert("Done!",function(){return window.location.reload(!0)})})["catch"](function(F){return kb.alert(kb.error.parse(F))})})["catch"](function(){})});h++;h<v.length&&p(h)})["catch"](function(a){h++;h<v.length&&p(h)}):(h++,h<v.length&&p(h))})(v[h])};p(0);g(e);break;
case "index":p=function(h){(function(f){kb.filter.auth(f.user.value,f.organization.value,f.group.value).then(function(a){a&&(f.view.value&&f.view.value!=e.viewId.toString()||kb.button.create(c.mobile,c.type,"kb-action-button"+h.toString(),f.label.value,f.message.value,function(){kb.view.records.get(c.app.id,(c.mobile?kintone.mobile.app:kintone.app).getQueryCondition()).then(function(m){var F=[],I=function(y,b){M([f],m[y],kb.create("div"),"record").then(function(z){z.performed&&F.push(kb.view.records.transform(z.record));
kb.progressUpdate();y++;y<m.length?I(y,b):b()})["catch"](function(){})};0!=m.length?(kb.progressStart(m.length),I(0,function(){kb.view.records.set(c.app.id,{put:F}).then(function(y){return kb.alert("Done!",function(){return window.location.reload(!0)})})["catch"](function(y){return kb.alert(kb.error.parse(y))})})):kb.alert("There are no records.")})["catch"](function(m){return kb.alert(kb.error.parse(m))})}));h++;h<v.length&&p(h)})["catch"](function(a){h++;h<v.length&&p(h)})})(v[h])},p(0),g(e)}else g(e)}(JSON.parse(u.tab).map(function(v,
p){return kb.extend({sIndex:{value:p.toString()}},v.setting)}).reduce(function(v,p){(c.mobile?["both","mobile"]:["both","pc"]).includes(p.device.value)&&p.event.value.includes(c.type)&&v.push(p);return v},[]))}catch(v){kb.alert(kb.error.parse(v)),g(e)}})["catch"](function(C){return g(e)}):g(e)})["catch"](function(u){return g(e)})})("mobile"==e.type.split(".").first(),e.reuse?"reuse":e.type.split(".").slice(-2).first())})});kb.event.on("kb.action.call",function(e){return new Promise(function(g,D){kb.config[K].config.get().then(function(L){0!=
Object.keys(L).length?kb.field.load(kb.config[K].app,!0).then(function(J){c.app={id:kb.config[K].app,fields:J.origin};c.fieldInfos=J;c.picker=new KintoneBoosterRecordPicker("record");try{(function(u){0!=u.length?M(u,e.record,e.container,e.workplace?e.workplace:"record").then(function(C){e.performed=C.performed;g(e)})["catch"](function(){return g(e)}):g(e)})(JSON.parse(L.tab).map(function(u,C){return kb.extend({sIndex:{value:C.toString()}},u.setting)}).reduce(function(u,C){(e.mobile?["both","mobile"]:
["both","pc"]).includes(C.device.value)&&C.event.value.includes(e.pattern)&&u.push(C);return u},[]))}catch(u){kb.alert(kb.error.parse(u)),g(e)}})["catch"](function(J){return g(e)}):g(e)})["catch"](function(L){return g(e)})})})})(kintone.$PLUGIN_ID);