/*
* FileName "plugins.action.js"
* Version: 1.0.0
* Copyright (c) 2023 Pandafirm LLC
* Distributed under the terms of the GNU Lesser General Public License.
* https://opensource.org/licenses/LGPL-2.1
*/
(function(K){var b={},M=function(d,k,D,L){return new Promise(function(I,u){var C=JSON.stringify(kb.record.simplify({fields:b.fieldInfos.origin},k)),n=function(e,f){var h=function(){e++;e<d.length?n(e,f):f()};(function(a){var w=kb.filter.scan(b.app,k,a.condition.value);w?kb.filter.auth(a.user.value,a.organization.value,a.group.value).then(function(H){if(H){var J={clear:function(y){try{a.clear.value.map(function(c){return c.value}).each(function(c,z){c.table.value in b.fieldInfos.tables&&(k[c.table.value].value=
k[c.table.value].value.filter(function(x){return!w[c.table.value].value.includes(x)}),w[c.table.value].value=[])}),y()}catch(c){kb.alert(kb.error.parse(c)),u()}},fill:function(y){try{a.fill.value.map(function(c){return c.value}).each(function(c,z){c.table.value in b.fieldInfos.tables&&function(x){x=kb.isNumeric(x)?parseInt(x)-w[c.table.value].value.length:0;0<x&&Array(x).fill().map(function(){return kb.record.create(b.fieldInfos.origin[c.table.value],!1)}).each(function(A,p){k[c.table.value]==w[c.table.value]?
k[c.table.value].value.push({value:A}):(k[c.table.value].value.push({value:A}),w[c.table.value].value.push({value:A}))})}(kb.formula.calculate({field:{value:Object.values(b.fieldInfos.parallelize).first().code},formula:c.range},w,w,k,b.fieldInfos.parallelize))}),y()}catch(c){kb.alert(kb.error.parse(c)),u()}},formula:function(y){try{a.formula.value.map(function(c){return c.value}).each(function(c,z){c.field.value in b.fieldInfos.parallelize&&function(x){x.tableCode?w[x.tableCode].value.each(function(A,
p){A.value[x.code].value=kb.formula.calculate(c,A.value,w,k,b.fieldInfos.parallelize);"lookup"==x.type&&(A.value[x.code].lookup=!0)}):(w[x.code].value=kb.formula.calculate(c,w,w,k,b.fieldInfos.parallelize),"lookup"==x.type&&(w[x.code].lookup=!0))}(b.fieldInfos.parallelize[c.field.value])}),y()}catch(c){kb.alert(kb.error.parse(c)),u()}},lookup:function(y){try{a.lookupApp.value?kb.field.load(a.lookupApp.value).then(function(c){(function(z){var x=[],A=[],p=function(q,r){var l=function(t,m){return t.lookup?
kb.extend({lookup:!0},m):m};kb.view.records.get(a.lookupApp.value,r.query,r.sort).then(function(t){0!=t.length?function(m){a.lookupLimited.value.includes("limited")||1==t.length?m(t.first()):b.picker.show({app:a.lookupApp.value,query:r.query,sort:r.sort,picker:x.reduce(function(v,g){v[g.external.code]=g.external;return v},{})},function(v){return m(v)})}(function(m){x.each(function(v,g){if(a.lookupOverwrite.value.includes("overwrite")||kb.field.isEmpty(r.record[v.internal.code].value))r.record[v.internal.code]=
l(v.internal,m[v.external.code])});q++;q<A.length?p(q,A[q]):(D.latest.action[a.sIndex.value].lookup=B(),y())}):(a.lookupReset.value.includes("reset")&&x.each(function(m,v){r.record[m.internal.code]=l(m.internal,kb.record.create({fields:{empty:m.internal}}).empty)}),q++,q<A.length?p(q,A[q]):(D.latest.action[a.sIndex.value].lookup=B(),y()))})["catch"](function(t){kb.alert(kb.error.parse(t));u()})},B=function(){return function(q){return JSON.stringify(A.reduce(function(r,l){r.push(l.query);r.push(kb.record.simplify({fields:q},
l.record));return r},[]))}(x.reduce(function(q,r){q[r.internal.code]=r.internal;return q},{}))};a.lookupCriteria.value.some(function(q){return!(q.value.external.value in z.external&&q.value.internal.value in z.internal)})?(kb.alert("No field to lookup was found"),u()):a.lookupMapping.value.some(function(q){return!(q.value.external.value in z.external&&q.value.internal.value in z.internal)})?(kb.alert("No field to lookup was found"),u()):(x=a.lookupMapping.value.map(function(q){return{external:z.external[q.value.external.value],
internal:z.internal[q.value.internal.value]}}),A=function(q){return q.map(function(r){return{query:a.lookupCriteria.value.reduce(function(l,t){var m=z.external[t.value.external.value],v=t.value.operator.value,g=z.internal[t.value.internal.value];var E=g.tableCode?r.value:k;a.lookupIgnore.value.includes("ignore")&&kb.field.isEmpty(E[g.code].value)||l.push(kb.filter.query.create(m,v,E[g.code]));return l},kb.filter.query.parse(a.lookupFilter.value).map(function(l){return z.external[l.field].code+" "+
l.operator+" "+l.value})).join(" and "),sort:(0!=a.lookupSort.value.length?a.lookupSort.value.map(function(l){return l.value.field.value+" "+l.value.order.value}):["$id asc"]).join(","),record:r.value}})}(function(q){return q?w[q].value:[{value:k}]}(Array.from(new Set(x.map(function(q){return q.internal.tableCode}))).first())),0!=A.length?D.latest.action[a.sIndex.value].lookup&&D.latest.action[a.sIndex.value].lookup==B()?y():p(0,A.first()):y())})({external:c.origin,internal:b.fieldInfos.parallelize})})["catch"](function(c){kb.alert(kb.error.parse(c));
u()}):y()}catch(c){kb.alert(kb.error.parse(c)),u()}},user:function(y){try{a.userSource.value?function(c){0==kb.roleSet.user.length?kb.roleSet.load().then(function(){return c()}):c()}(function(){var c=[],z=[],x=function(p,B){(function(r){c.each(function(l,t){if(l.isCustom)switch(l.field.type){case "USER_SELECT":l.value=r.reduce(function(m,v){"customItemValues"in v&&function(g){0!=g.length&&function(E){(function(F){0!=F.length&&(m.some(function(G){return G.code==F.first().info.code})||m.push({code:F.first().info.code,
name:F.first().info.name}))})(kb.roleSet.user.filter(function(F){return F.info.id==E}))}(g.first().value)}(v.customItemValues.filter(function(g){return g.code==l.item}));return Array.from(new Set(m)).filter(function(g){return g})},[]);break;default:l.value=r.reduce(function(m,v){"customItemValues"in v&&function(g){0!=g.length&&m.push(g.first().value)}(v.customItemValues.filter(function(g){return g.code==l.item}));return Array.from(new Set(m)).filter(function(g){return g})},[]).join(",")}else switch(l.item){case "groups":case "organizations":l.value=
r.map(function(m){return m.code});break;case "primaryOrganization":l.value=r.reduce(function(m,v){l.item in v&&function(g){0!=g.length&&(m.some(function(E){return E.code==g.first().info.code})||m.push({code:g.first().info.code,name:g.first().info.name}))}(kb.roleSet.organization.filter(function(g){return g.info.id==v[l.item]}));return m},[]);break;default:l.value=r.reduce(function(m,v){l.item in v&&m.push(v[l.item]);return Array.from(new Set(m)).filter(function(g){return g})},[]).join(",")}})})(B[a.userSource.value].value.reduce(function(r,
l){(function(t){0!=t.length&&r.push(t.first().info)})(kb.roleSet.user.filter(function(t){return t.info.code==l.code}));return r},[]));var q=function(r,l){(function(t,m){var v=function(g,E,F){switch(t.item){case "groups":kintone.api(kintone.api.url("/v1/user/groups",!0),"GET",{code:t.value[g]}).then(function(G){G.groups&&(E=E.concat(G.groups.map(function(N){return{code:N.code,name:N.name}})),g++,g<t.value.length?v(g,E,F):F(E))})["catch"](function(G){kb.alert(kb.error.parse(G));u()});break;case "organizations":kintone.api(kintone.api.url("/v1/user/organizations",
!0),"GET",{code:t.value[g]}).then(function(G){G.organizationTitles&&(E=E.concat(G.organizationTitles.map(function(N){return{code:N.organization.code,name:N.organization.name}})),g++,g<t.value.length?v(g,E,F):F(E))})["catch"](function(G){kb.alert(kb.error.parse(G));u()})}};a.userOverwrite.value.includes("overwrite")||kb.field.isEmpty(B[t.field.code].value)||m();switch(t.item){case "groups":case "organizations":0!=t.value.length?v(0,[],function(g){B[t.field.code].value=g;m()}):(B[t.field.code].value=
t.value,m());break;default:B[t.field.code].value=t.value,m()}})(c[r],function(){r++;r<c.length?q(r,l):l()})};q(0,function(){p++;p<z.length?x(p,z[p]):(D.latest.action[a.sIndex.value].user=A(),y())})},A=function(){return function(p){return JSON.stringify(z.map(function(B){return kb.record.simplify({fields:p},B)}))}(c.reduce(function(p,B){p[B.field.code]=B.field;return p},function(p){var B={};B[p]=b.fieldInfos.parallelize[p];return B}(a.userSource.value)))};a.userCustomItem.value.some(function(p){return!(p.value.field.value in
b.fieldInfos.parallelize)})?(kb.alert("No field to user informations was found"),u()):a.userMapping.value.some(function(p){return!(p.value.field.value in b.fieldInfos.parallelize)})?(kb.alert("No field to user informations was found"),u()):(a.userCustomItem.value.each(function(p,B){c.push({isCustom:!0,item:p.value.item.value,field:b.fieldInfos.parallelize[p.value.field.value],value:[]})}),a.userMapping.value.each(function(p,B){c.push({isCustom:!1,item:p.value.item.value,field:b.fieldInfos.parallelize[p.value.field.value],
value:[]})}),a.userPrimaryOrganization.value&&a.userPrimaryOrganization.value in b.fieldInfos.parallelize&&c.push({isCustom:!1,item:"primaryOrganization",field:b.fieldInfos.parallelize[a.userPrimaryOrganization.value],value:[]}),a.userOrganization.value&&a.userOrganization.value in b.fieldInfos.parallelize&&c.push({isCustom:!1,item:"organizations",field:b.fieldInfos.parallelize[a.userOrganization.value],value:[]}),a.userGroup.value&&a.userGroup.value in b.fieldInfos.parallelize&&c.push({isCustom:!1,
item:"groups",field:b.fieldInfos.parallelize[a.userGroup.value],value:[]}),z=function(p){return p?w[p].value:[{value:k}]}(b.fieldInfos.parallelize[a.userSource.value].tableCode).map(function(p){return p.value}),0!=z.length?D.latest.action[a.sIndex.value].user&&D.latest.action[a.sIndex.value].user==A()?y():0!=c.length?x(0,z.first()):y():y())}):y()}catch(c){kb.alert(kb.error.parse(c)),u()}}};J.clear(function(){J.fill(function(){J.formula(function(){J.lookup(function(){J.user(function(){h()})})})})})}else h()})["catch"](function(H){kb.alert(kb.error.parse(H));
u()}):h()})(function(a){D.latest?D.latest.action||(D.latest.action={}):D.latest={action:{}};a.sIndex.value in D.latest.action||(D.latest.action[a.sIndex.value]={lookup:"[]",user:"[]"});return a}(d[e]))};n(0,function(){I({record:k,performed:C!=JSON.stringify(kb.record.simplify({fields:b.fieldInfos.origin},k))})})})};kintone.events.on("app.record.create.show app.record.detail.process.proceed app.record.detail.show app.record.edit.show app.record.index.show mobile.app.record.create.show mobile.app.record.detail.process.proceed mobile.app.record.detail.show mobile.app.record.edit.show mobile.app.record.index.show".split(" "),
function(d){return new Promise(function(k,D){(function(L,I){b.mobile=L;b.type=I;kb.config[K].config.get().then(function(u){0!=Object.keys(u).length?kb.field.load(kb.config[K].app,!0).then(function(C){b.app={id:kb.config[K].app,fields:C.origin};b.fieldInfos=C;b.picker=new KintoneBoosterRecordPicker("record");try{["create","edit","reuse"].includes(b.type)&&function(n){if(0!=n.length)b.latest={record:"",time:null},kintone.events.on(C.changes.reduce(function(e,f){e.push("app.record.create.change."+f);
e.push("app.record.edit.change."+f);e.push("mobile.app.record.create.change."+f);e.push("mobile.app.record.edit.change."+f);return e},[]),function(e){var f=n.filter(function(h){return function(a){return!a.first()||a.includes(e.type.split(".").last())}(h.triggers.value.map(function(a){return a.value.field.value}))});if(function(){var h=!0;b.latest.record&&(h=!1,b.latest.record==JSON.stringify(kb.record.simplify({fields:C.origin},e.record))?b.latest={record:"",time:null}:b.latest.time<(new Date).getTime()-
5E3&&(b.latest={record:"",time:null},h=!0));h&&["DATETIME","TIME"].includes(e.changes.field.type)&&function(a){a&&(Array.isArray(a)?a:[a]).each(function(w,H){w.elm(".control-errors-content-gaia")&&(h=!1)})}(kb.field.get(C.parallelize[e.type.split(".").last()],b.mobile,b.type));return h}()){if(0!=f.length)return M(f,e.record,kb.elm("body"),"record").then(function(h){kb.event.call("kb.style.call",{container:kb.elm("body"),record:e.record,mobile:b.mobile,pattern:"reuse"==b.type?"create":b.type,workplace:"record"}).then(function(a){if(h.performed||
a.performed)b.latest=h.performed?{record:JSON.stringify(kb.record.simplify({fields:C.origin},a.record)),time:(new Date).getTime()}:{record:"",time:null},(b.mobile?kintone.mobile.app.record:kintone.app.record).set(e)})["catch"](function(){})})["catch"](function(){}),e;kb.event.call("kb.style.call",{container:kb.elm("body"),record:e.record,mobile:b.mobile,pattern:"reuse"==b.type?"create":b.type,workplace:"record"}).then(function(h){h.performed&&(b.latest={record:"",time:null},(b.mobile?kintone.mobile.app.record:
kintone.app.record).set(e))})["catch"](function(){})}}),kb.event.on("kb.action.installed",function(e){return{installed:!0}});else kb.event.on("kb.action.installed",function(e){return{installed:!1}})}(JSON.parse(u.tab).map(function(n,e){return kb.extend({sIndex:{value:e.toString()}},n.setting)}).reduce(function(n,e){(b.mobile?["both","mobile"]:["both","pc"]).includes(e.device.value)&&e.event.value.includes("change")&&n.push(e);return n},[])),function(n){if(0!=n.length)switch(b.type){case "create":case "edit":case "reuse":M(n,
d.record,kb.elm("body"),"record").then(function(f){return k(d)})["catch"](function(){});break;case "process":(function(f){0!=f.length?M(f,d.record,kb.elm("body"),"record").then(function(h){return k(d)})["catch"](function(){}):k(d)})(n.filter(function(f){return f.action.value==d.action.value+":"+d.status.value+":"+d.nextStatus.value}));break;case "detail":var e=function(f){(function(h){kb.filter.scan(b.app,d.record,h.condition.value)?kb.filter.auth(h.user.value,h.organization.value,h.group.value).then(function(a){a&&
kb.button.create(b.mobile,b.type,"kb-action-button"+f.toString(),h.label.value,h.message.value,function(){M([h],d.record,kb.elm("body"),"record").then(function(w){kb.view.records.set(b.app.id,{put:[kb.view.records.transform(w.record)]}).then(function(H){return kb.alert("Done!",function(){return window.location.reload(!0)})})["catch"](function(H){return kb.alert(kb.error.parse(H))})})["catch"](function(){})});f++;f<n.length&&e(f)})["catch"](function(a){f++;f<n.length&&e(f)}):(f++,f<n.length&&e(f))})(n[f])};
e(0);k(d);break;case "index":e=function(f){(function(h){kb.filter.auth(h.user.value,h.organization.value,h.group.value).then(function(a){a&&(h.view.value&&h.view.value!=d.viewId.toString()||kb.button.create(b.mobile,b.type,"kb-action-button"+f.toString(),h.label.value,h.message.value,function(){kb.view.records.get(b.app.id,(b.mobile?kintone.mobile.app:kintone.app).getQueryCondition()).then(function(w){var H=[],J=function(y,c){M([h],w[y],kb.create("div"),"record").then(function(z){z.performed&&H.push(kb.view.records.transform(z.record));
kb.progressUpdate();y++;y<w.length?J(y,c):c()})["catch"](function(){})};0!=w.length?(kb.progressStart(w.length),J(0,function(){kb.view.records.set(b.app.id,{put:H}).then(function(y){return kb.alert("Done!",function(){return window.location.reload(!0)})})["catch"](function(y){return kb.alert(kb.error.parse(y))})})):kb.alert("There are no records.")})["catch"](function(w){return kb.alert(kb.error.parse(w))})}));f++;f<n.length&&e(f)})["catch"](function(a){f++;f<n.length&&e(f)})})(n[f])},e(0),k(d)}else k(d)}(JSON.parse(u.tab).map(function(n,
e){return kb.extend({sIndex:{value:e.toString()}},n.setting)}).reduce(function(n,e){(b.mobile?["both","mobile"]:["both","pc"]).includes(e.device.value)&&e.event.value.includes(b.type)&&n.push(e);return n},[]))}catch(n){kb.alert(kb.error.parse(n)),k(d)}})["catch"](function(C){return k(d)}):k(d)})["catch"](function(u){return k(d)})})("mobile"==d.type.split(".").first(),d.reuse?"reuse":d.type.split(".").slice(-2).first())})});kb.event.on("kb.action.call",function(d){return new Promise(function(k,D){kb.config[K].config.get().then(function(L){0!=
Object.keys(L).length?kb.field.load(kb.config[K].app,!0).then(function(I){b.app={id:kb.config[K].app,fields:I.origin};b.fieldInfos=I;b.picker=new KintoneBoosterRecordPicker("record");try{(function(u){if(0!=u.length){var C=function(){var n=u;"change"==d.pattern&&(n=u.filter(function(e){return function(f){return"fields"in d?!f.first()||d.fields.some(function(h){return f.includes(h)}):!f.first()||f.includes(d.field)}(e.triggers.value.map(function(f){return f.value.field.value}))}));return n}();0!=C.length?
M(C,d.record,d.container,d.workplace?d.workplace:"record").then(function(n){d.stopPropagation&&(b.latest={record:JSON.stringify(kb.record.simplify({fields:I.origin},d.record)),time:(new Date).getTime()});d.performed=n.performed;k(d)})["catch"](function(){return k(d)}):k(d)}else k(d)})(JSON.parse(L.tab).map(function(u,C){return kb.extend({sIndex:{value:C.toString()}},u.setting)}).reduce(function(u,C){(d.mobile?["both","mobile"]:["both","pc"]).includes(C.device.value)&&C.event.value.includes(d.pattern)&&
u.push(C);return u},[]))}catch(u){kb.alert(kb.error.parse(u)),k(d)}})["catch"](function(I){return k(d)}):k(d)})["catch"](function(L){return k(d)})})})})(kintone.$PLUGIN_ID);