/*
* FileName "plugins.gantt.js"
* Version: 1.0.0
* Copyright (c) 2023 Pandafirm LLC
* Distributed under the terms of the GNU Lesser General Public License.
* https://opensource.org/licenses/LGPL-2.1
*/
'use strict';(r=>{var f={},v=(k,c)=>{(b=>{var n=null,q=a=>{var h=[],g=[];b.subTask&&a[b.subTask].value.each((e,d)=>{e.value[c.subtaskStart.value].value&&e.value[c.subtaskEnd.value].value&&g.push({id:"task_"+a.$id.value.toString()+"_"+d.toString(),name:kb.field.stringify(f.fieldInfos.parallelize[c.subtaskTitle.value],e.value[c.subtaskTitle.value].value," / "),start:(l=>b.time.subTask.start?l:(new Date(l)).calc(kb.timezoneOffset()+" hour").toISOString())(e.value[c.subtaskStart.value].value),end:(l=>
b.time.subTask.end?l:(new Date(l)).calc(kb.timezoneOffset()+" hour").toISOString())(e.value[c.subtaskEnd.value].value),progress:c.subtaskProgress.value?e.value[c.subtaskProgress.value].value:null,dependencies:"task_"+a.$id.value.toString()+(d>0?"_"+(d-1).toString():""),group:"task_"+a.$id.value.toString(),colors:{back:e.value[c.subtaskTitle.value].backcolor,fore:e.value[c.subtaskTitle.value].forecolor},resizable:{left:b.editable.subTask.start,right:b.editable.subTask.end}})});h.push({id:"task_"+a.$id.value.toString(),
name:kb.field.stringify(f.fieldInfos.parallelize[c.taskTitle.value],a[c.taskTitle.value].value," / "),start:(e=>b.time.task.start?e:(new Date(e)).calc(kb.timezoneOffset()+" hour").toISOString())(a[c.taskStart.value].value),end:(e=>b.time.task.end?e:(new Date(e)).calc(kb.timezoneOffset()+" hour").toISOString())(a[c.taskEnd.value].value),progress:c.taskProgress.value?a[c.taskProgress.value].value:null,dependencies:"",group:"task_"+a.$id.value.toString(),colors:{back:a[c.taskTitle.value].backcolor,fore:a[c.taskTitle.value].forecolor},
resizable:{left:b.editable.task.start,right:b.editable.task.end}});h=h.concat(g);f.records[a.$id.value]=a;return h},m=(a,h)=>{kb.view.records.get(f.app.id,(g=>{var e=[];e.push((()=>{var d=[];d.push(c.taskStart.value+'!=""');d.push(c.taskStart.value+'>"'+(b.time.task.start?(new Date(a.start)).calc("-1 second").toISOString():(new Date(a.start)).calc("-1 day").format("Y-m-d"))+'"');d.push(c.taskStart.value+'<"'+(b.time.task.start?(new Date(a.end)).calc("1 second").toISOString():(new Date(a.end)).calc("1 day").format("Y-m-d"))+
'"');return"("+d.join(" and ")+")"})());e.push((()=>{var d=[];d.push(c.taskEnd.value+'!=""');d.push(c.taskEnd.value+'>"'+(b.time.task.end?(new Date(a.start)).calc("-1 second").toISOString():(new Date(a.start)).calc("-1 day").format("Y-m-d"))+'"');d.push(c.taskEnd.value+'<"'+(b.time.task.end?(new Date(a.end)).calc("1 second").toISOString():(new Date(a.end)).calc("1 day").format("Y-m-d"))+'"');return"("+d.join(" and ")+")"})());e.push((()=>{var d=[];d.push(c.taskStart.value+'!=""');d.push(c.taskEnd.value+
'!=""');d.push(c.taskStart.value+'<="'+(b.time.task.start?(new Date(a.start)).calc("-1 second").toISOString():(new Date(a.start)).calc("-1 day").format("Y-m-d"))+'"');d.push(c.taskEnd.value+'>="'+(b.time.task.end?(new Date(a.end)).calc("1 second").toISOString():(new Date(a.end)).calc("1 day").format("Y-m-d"))+'"');return"("+d.join(" and ")+")"})());b.subTask&&(e.push((()=>{var d=[];d.push(c.subtaskStart.value+' not in ("")');d.push(c.subtaskStart.value+'>"'+(b.time.subTask.start?(new Date(a.start)).calc("-1 second").toISOString():
(new Date(a.start)).calc("-1 day").format("Y-m-d"))+'"');d.push(c.subtaskStart.value+'<"'+(b.time.subTask.start?(new Date(a.end)).calc("1 second").toISOString():(new Date(a.end)).calc("1 day").format("Y-m-d"))+'"');return"("+d.join(" and ")+")"})()),e.push((()=>{var d=[];d.push(c.subtaskEnd.value+' not in ("")');d.push(c.subtaskEnd.value+'>"'+(b.time.subTask.end?(new Date(a.start)).calc("-1 second").toISOString():(new Date(a.start)).calc("-1 day").format("Y-m-d"))+'"');d.push(c.subtaskEnd.value+'<"'+
(b.time.subTask.end?(new Date(a.end)).calc("1 second").toISOString():(new Date(a.end)).calc("1 day").format("Y-m-d"))+'"');return"("+d.join(" and ")+")"})()),e.push((()=>{var d=[];d.push(c.subtaskStart.value+' not in ("")');d.push(c.subtaskEnd.value+' not in ("")');d.push(c.subtaskStart.value+'<="'+(b.time.subTask.start?(new Date(a.start)).calc("-1 second").toISOString():(new Date(a.start)).calc("-1 day").format("Y-m-d"))+'"');d.push(c.subtaskEnd.value+'>="'+(b.time.subTask.end?(new Date(a.end)).calc("1 second").toISOString():
(new Date(a.end)).calc("1 day").format("Y-m-d"))+'"');return"("+d.join(" and ")+")"})()));return(g?"("+g+") and ":"")+"("+e.join(" or ")+")"})((f.mobile?kintone.mobile.app:kintone.app).getQueryCondition()),(g=>{g=g.match(/order by/g)?g.replace(/^.*order by/g,""):"";return(g=g.replace(/limit [0-9]+/g,"").replace(/ offset [0-9]+/g,"").replace(/^[ ]+/g,"").replace(/[ ]+$/g,""))?g:"$id asc"})((f.mobile?kintone.mobile.app:kintone.app).getQuery())).then(g=>{var e=(d,l)=>{kb.event.call("kb.style.call",{container:kb.elm("body"),
record:g[d],mobile:f.mobile,pattern:"detail",workplace:"view"}).then(t=>{d++;d<g.length?e(d,l):l()}).catch(t=>{d++;d<g.length?e(d,l):l()})};f.records={};f.tasks=[];g.length!=0?e(0,()=>{g.each((d,l)=>{f.tasks=f.tasks.concat(q(d))});h()}):h()}).catch(g=>kb.alert(kb.error.parse(g)))},p=a=>{Object.keys(a.record).length!=0&&kb.view.records.set(f.app.id,{put:[a]},!0).then(h=>{var g=JSON.stringify(f.records[a.id]);kb.event.call("kb.style.call",{container:kb.elm("body"),record:f.records[a.id],mobile:f.mobile,
pattern:"detail",workplace:"view"}).then(e=>{g!=JSON.stringify(e.record)&&(d=>{f.tasks=f.tasks.filter(l=>l.group!="task_"+e.record.$id.value.toString());Array.prototype.splice.apply(f.tasks,[d,0].concat(q(e.record)));n.refresh(f.tasks)})(f.tasks.findIndex(d=>d.id=="task_"+e.record.$id.value.toString()))}).catch(e=>finish())}).catch(h=>kb.alert(kb.error.parse(h)))};k.empty().append((a=>{var h={Day:{en:"Day",ja:"\u65e5",zh:"\u65e5","zh-TW":"\u65e5"},Week:{en:"Week",ja:"\u9031",zh:"\u5468","zh-TW":"\u9031"},
Month:{en:"Month",ja:"\u6708",zh:"\u6708","zh-TW":"\u6708"},"Half Day":{en:"Half Day",ja:"12\u6642\u9593\u6bce",zh:"\u6bcf12\u5c0f\u65f6","zh-TW":"\u6bcf12\u5c0f\u6642"},"Quarter Day":{en:"Quarter Day",ja:"6\u6642\u9593\u6bce",zh:"\u6bcf6\u5c0f\u65f6","zh-TW":"\u6bcf6\u5c0f\u6642"}};a.append(kb.create("div").addClass("kb-gantt-header-filter").append(kb.create("span").addClass("kb-gantt-guide").html("From:")).append(kb.create("button").addClass("kb-gantt-button kb-gantt-pickup-button").on("click",
g=>{(e=>{kb.pickupDate(b.session.start,d=>{b.session.start=d;e.html(b.session.start)})})(g.currentTarget.nextElementSibling)})).append(kb.create("span").addClass("kb-gantt-guide").html(b.session.start)).append(kb.create("span").addClass("kb-gantt-guide").html("&nbsp;&nbsp;To:")).append(kb.create("button").addClass("kb-gantt-button kb-gantt-pickup-button").on("click",g=>{(e=>{kb.pickupDate(b.session.end,d=>{b.session.end=d;e.html(b.session.end)})})(g.currentTarget.nextElementSibling)})).append(kb.create("span").addClass("kb-gantt-guide").html(b.session.end)).append(kb.create("button").addClass("kb-gantt-button kb-gantt-search-button").on("click",
g=>{m(b.session,()=>n.refresh(f.tasks));sessionStorage.setItem("kb-gantt-"+c.view.value,JSON.stringify({start:b.session.start,end:b.session.end,initial:n.options.view_mode}))}))).append(kb.create("div").addClass("kb-gantt-header-mode"));(g=>{for(var e in h)(d=>{g.append((l=>{h[d].button=l;return l.on("click",()=>{n.change_view_mode(d);for(var t in h){var u=t;h[u].button==l?h[u].button.addClass("kb-gantt-button-active"):h[u].button.removeClass("kb-gantt-button-active")}})})(kb.create("button").addClass("kb-gantt-button"+
(b.session.initial==d?" kb-gantt-button-active":"")).html(h[d][kb.operator.language])))})(e)})(a.elm(".kb-gantt-header-mode"));return a})(kb.create("div").attr("id","kb-gantt-header"))).append(kb.create("div").attr("id","kb-gantt-main"));m(b.session,()=>{n=new Gantt("#kb-gantt-main",f.tasks,{start:b.session.start,end:b.session.end,header_height:50,column_width:30,view_modes:["Quarter Day","Half Day","Day","Week","Month"],bar_height:20,bar_corner_radius:3,arrow_curve:5,padding:18,view_mode:b.session.initial,
language:"en",custom_popup_html:null,on_click:a=>{kb.confirm(kb.constants.gantt.message.confirm.edit[kb.operator.language],()=>{var h=(c.page||{value:[]}).value.includes("detail"),g=kb.config[r].app,e=a.id.replace(/task_/g,"").split("_").first();h||sessionStorage.setItem("kb-gantt-edit",JSON.stringify({href:window.location.href}));window.location.href=h?kb.record.page.detail(f.mobile,g,e):kb.record.page.edit(f.mobile,g,e)})},on_date_change:a=>{(h=>{var g={id:h.first(),record:{}};a.each((e,d)=>{if(d==
0)b.editable.task.start&&(g.record[c.taskStart.value]=f.records[h.first()][c.taskStart.value],g.record[c.taskStart.value].value=b.time.task.start?e._start.toISOString():e._start.format("Y-m-d")),b.editable.task.end&&(g.record[c.taskEnd.value]=f.records[h.first()][c.taskEnd.value],g.record[c.taskEnd.value].value=b.time.task.end?e._end.toISOString():e._end.calc("-1 day").format("Y-m-d"));else if(b.editable.subTask.start||b.editable.subTask.end)g.record[b.subTask]=f.records[h.first()][b.subTask],b.editable.subTask.start&&
(g.record[b.subTask].value[d-1].value[c.subtaskStart.value].value=b.time.subTask.start?e._start.toISOString():e._start.format("Y-m-d")),b.editable.subTask.end&&(g.record[b.subTask].value[d-1].value[c.subtaskEnd.value].value=b.time.subTask.end?e._end.toISOString():e._end.calc("-1 day").format("Y-m-d"))});p(g)})(a.first().id.replace(/task_/g,"").split("_"))},on_progress_change:(a,h)=>{var g=a.id.replace(/task_/g,"").split("_");a=a.id==a.group;var e={id:g.first(),record:{}};a?c.taskProgress.value&&(e.record[c.taskProgress.value]=
f.records[g.first()][c.taskProgress.value],e.record[c.taskProgress.value].value=h):c.subtaskProgress.value&&(e.record[b.subTask]=f.records[g.first()][b.subTask],e.record[b.subTask].value[g.last()].value[c.subtaskProgress.value].value=h);p(e)},on_view_change:a=>{}})})})((b=>{var n=b(f.fieldInfos.parallelize[c.taskStart.value]),q=b(f.fieldInfos.parallelize[c.taskEnd.value]),m=b(c.subtaskStart.value?f.fieldInfos.parallelize[c.subtaskStart.value]:{type:""});b=b(c.subtaskEnd.value?f.fieldInfos.parallelize[c.subtaskEnd.value]:
{type:""});var p={task:{start:n.isEditable,end:q.isEditable},subTask:{start:m.isEditable,end:b.isEditable}};var a=(a=sessionStorage.getItem("kb-gantt-"+c.view.value))?JSON.parse(a):{start:(new Date).format("Y-m-d"),end:(new Date).calc("1 month,-1 day").format("Y-m-d"),initial:c.initial.value};return{editable:p,session:a,subTask:c.subtaskTitle.value?f.fieldInfos.parallelize[c.subtaskTitle.value].tableCode:"",time:{task:{start:n.isDateTime,end:q.isDateTime},subTask:{start:m.isDateTime,end:b.isDateTime}}}})(b=>
{switch(b.type){case "CALC":switch(b.format){case "DATE":b.isDateTime=!1;b.isEditable=!1;break;case "DATETIME":b.isDateTime=!0,b.isEditable=!1}break;case "CREATED_TIME":case "UPDATED_TIME":b.isDateTime=!0;b.isEditable=!1;break;case "DATE":b.isDateTime=!1;b.isEditable=!0;break;case "DATETIME":b.isDateTime=!0;b.isEditable=!0;break;default:b.isDateTime=!1,b.isEditable=!0}return b}))};kintone.events.on(["app.record.index.show","mobile.app.record.index.show"],k=>new Promise((c,b)=>{((n,q)=>{f.mobile=n;
f.type=q;kb.config[r].config.get().then(m=>{Object.keys(m).length!=0?kb.field.load(kb.config[r].app,!0).then(p=>{f.app={id:kb.config[r].app,fields:p.origin};f.fieldInfos=p;f.records={};f.tasks=[];try{(a=>{if(a){a.taskTitle.value&&(a.taskTitle.value in f.fieldInfos.parallelize||c(k));a.taskStart.value&&(a.taskStart.value in f.fieldInfos.parallelize||c(k));a.taskEnd.value&&(a.taskEnd.value in f.fieldInfos.parallelize||c(k));a.taskProgress.value&&(a.taskProgress.value in f.fieldInfos.parallelize||c(k));
a.subtaskTitle.value&&(a.subtaskTitle.value in f.fieldInfos.parallelize||c(k));a.subtaskStart.value&&(a.subtaskStart.value in f.fieldInfos.parallelize||c(k));a.subtaskEnd.value&&(a.subtaskEnd.value in f.fieldInfos.parallelize||c(k));a.subtaskProgress.value&&(a.subtaskProgress.value in f.fieldInfos.parallelize||c(k));var h=kb.elm("#kb-gantt");h&&v(h,a)}c(k)})(JSON.parse(m.tab).map((a,h)=>kb.extend({sIndex:{value:h.toString()}},a.setting)).reduce((a,h)=>{h.view.value==k.viewId.toString()&&(a=h);return a},
null))}catch(a){kb.alert(kb.error.parse(a)),c(k)}}).catch(p=>c(k)):c(k)}).catch(m=>c(k))})(k.type.split(".").first()=="mobile",k.type.split(".").slice(-2).first())}));kintone.events.on(["app.record.edit.show","mobile.app.record.edit.show"],k=>new Promise((c,b)=>{(n=>{n&&((q=>{(m=>{m.parentNode.insertBefore(m.clone().removeAttr("disabled").on("click",p=>{window.location.href=q.href}),m.hide().nextElementSibling)})(kb.elm(k.type.split(".").first()=="mobile"?".gaia-mobile-v2-app-record-edittoolbar-cancel":
".gaia-ui-actionmenu-cancel"));kintone.events.on(["app.record.edit.submit.success","mobile.app.record.edit.submit.success"],m=>new Promise((p,a)=>{m.url=q.href;p(m)}))})(JSON.parse(n)),sessionStorage.removeItem("kb-gantt-edit"));c(k)})(sessionStorage.getItem("kb-gantt-edit"))}))})(kintone.$PLUGIN_ID);
kb.constants=kb.extend({gantt:{message:{confirm:{edit:{en:"Do you want to open the record?",ja:"\u30ec\u30b3\u30fc\u30c9\u3092\u958b\u304d\u307e\u3059\u304b\uff1f",zh:"\u60a8\u8981\u6253\u5f00\u8bb0\u5f55\u5417\uff1f","zh-TW":"\u60a8\u8981\u6253\u958b\u8a18\u9304\u55ce\uff1f"}}}}},kb.constants);