/*
* FileName "plugins.style.js"
* Version: 1.0.0
* Copyright (c) 2023 Pandafirm LLC
* Distributed under the terms of the GNU Lesser General Public License.
* https://opensource.org/licenses/LGPL-2.1
*/
(function(t){var c={},y=function(e,k,p){p=void 0===p?"record":p;var r=!1,q=function(){var f={},m=0;if("record"==p)for(var h in k)h in c.fieldInfos.tables&&k[h].value.each(function(l,g){null==l.id&&(m++,l.id=m);f[l.id]=g},{});return f}(),n=function(f,m){var h=function(){f++;f<e.length?n(f,m):m()};(function(l){var g=kb.filter.scan(c.app,k,l.condition.value);g?kb.filter.auth(l.user.value,l.organization.value,l.group.value).then(function(w){w&&(l.color.value.map(function(b){return b.value}).each(function(b,
x){b.field.value in c.fieldInfos.parallelize&&function(a){switch(p){case "record":a.tableCode?a.tableCode in g&&function(d){if(c.mobile)d();else if(kb.elms(".subtable-"+c.fieldInfos.tables[a.tableCode].id+" tbody tr").length!=k[a.tableCode].value.length){var u=new MutationObserver(function(){kb.elms(".subtable-"+c.fieldInfos.tables[a.tableCode].id+" tbody tr").length==k[a.tableCode].value.length&&(d(),u.disconnect())});u.observe(kb.elm(".subtable-"+c.fieldInfos.tables[a.tableCode].id),{childList:!0,
subtree:!0})}else d()}(function(){g[a.tableCode].value.each(function(d,u){if(a.code in d.value){var v=kb.field.get(a,c.mobile,c.type);v&&(v[q[d.id]].value.css({backgroundColor:b.backcolor.value,color:b.forecolor.value}),b.backcolor.value?v[q[d.id]].value.addClass("kb-inherit-backcolor"):v[q[d.id]].value.removeClass("kb-inherit-backcolor"),b.forecolor.value?v[q[d.id]].value.addClass("kb-inherit-forecolor"):v[q[d.id]].value.removeClass("kb-inherit-forecolor"))}})}):a.code in g&&function(d){d&&(d.value.css({backgroundColor:b.backcolor.value,
color:b.forecolor.value}),b.backcolor.value?d.value.addClass("kb-inherit-backcolor"):d.value.removeClass("kb-inherit-backcolor"),b.forecolor.value?d.value.addClass("kb-inherit-forecolor"):d.value.removeClass("kb-inherit-forecolor"))}(kb.field.get(a,c.mobile,c.type));break;case "view":a.tableCode?a.tableCode in g&&g[a.tableCode].value.each(function(d,u){a.code in d.value&&(d.value[a.code].backcolor=b.backcolor.value,d.value[a.code].forecolor=b.forecolor.value)}):a.code in g&&(g[a.code].backcolor=b.backcolor.value,
g[a.code].forecolor=b.forecolor.value)}}(c.fieldInfos.parallelize[b.field.value])}),l.display.value.map(function(b){return b.value}).each(function(b,x){switch(p){case "record":(c.mobile?kintone.mobile.app.record:kintone.app.record).setFieldShown(b.field.value,"show"==b.state.value);break;case "view":b.field.value in c.fieldInfos.groups?c.fieldInfos.groups[b.field.value].fields.map(function(a){return a.code}).each(function(a,d){a in c.fieldInfos.parallelize&&a in g&&(g[a].hidden="hide"==b.state.value)}):
b.field.value in c.fieldInfos.tables?b.field.value in g&&(g[b.field.value].hidden="hide"==b.state.value):function(a){a.tableCode?a.tableCode in g&&g[a.tableCode].value.each(function(d,u){a.code in d.value&&(d.value[a.code].hidden="hide"==b.state.value)}):a.code in g&&(g[a.code].hidden="hide"==b.state.value)}(c.fieldInfos.parallelize[b.field.value])}}),l.toggle.value.map(function(b){return b.value}).each(function(b,x){switch(p){case "record":(c.mobile?kintone.mobile.app.record:kintone.app.record).setGroupFieldOpen(b.field.value,
"open"==b.state.value)}}),["create","edit"].includes(c.type)&&l.editable.value.map(function(b){return b.value}).each(function(b,x){b.field.value in c.fieldInfos.parallelize&&function(a){c.fieldInfos.disables.includes(a.code)||(a.tableCode?a.tableCode in g&&g[a.tableCode].value.each(function(d,u){a.code in d.value&&(d.value[a.code].disabled="disable"==b.state.value,"record"==p&&(r=!0))}):a.code in g&&(g[a.code].disabled="disable"==b.state.value,"record"==p&&(r=!0)))}(c.fieldInfos.parallelize[b.field.value])}));
h()})["catch"](function(w){return kb.alert(kb.error.parse(w))}):h()})(e[f])};return new Promise(function(f,m){n(0,function(){return f({performed:r})})})};kintone.events.on("app.record.create.show app.record.detail.show app.record.edit.show app.record.print.show mobile.app.record.create.show mobile.app.record.detail.show mobile.app.record.edit.show".split(" "),function(e){return new Promise(function(k,p){(function(r,q){c.mobile=r;c.type=q;kb.config[t].config.get().then(function(n){0!=Object.keys(n).length?
(e.reuse&&function(f){"reusecolor"in f&&f.reusecolor.value&&kintone.app.record.getHeaderMenuSpaceElement().nextSibling.firstElementChild.css({backgroundColor:f.reusecolor.value})}(JSON.parse(n.flat)),kb.field.load(kb.config[t].app,!0).then(function(f){c.app={id:kb.config[t].app,fields:f.origin};c.fieldInfos=f;try{(function(m){if(0!=m.length){if(["create","edit"].includes(c.type))kintone.events.on(f.changes.reduce(function(h,l){h.push("app.record.create.change."+l);h.push("app.record.edit.change."+
l);h.push("mobile.app.record.create.change."+l);h.push("mobile.app.record.edit.change."+l);return h},[]),function(h){y(m,h.record,"record").then(function(l){l.performed&&(c.mobile?kintone.mobile.app.record:kintone.app.record).set(h)});return h});y(m,e.record,"record").then(function(h){return k(e)})}else k(e)})(JSON.parse(n.tab).reduce(function(m,h){(c.mobile?["both","mobile"]:["both","pc"]).includes(h.setting.device.value)&&h.setting.page.value.includes(c.type)&&m.push(h.setting);return m},[]))}catch(m){kb.alert(kb.error.parse(m)),
k(e)}})["catch"](function(f){return k(e)})):k(e)})["catch"](function(n){return k(e)})})("mobile"==e.type.split(".").first(),e.type.split(".").slice(-2).first())})});kb.event.on("kb.style.call",function(e){return new Promise(function(k,p){kb.config[t].config.get().then(function(r){0!=Object.keys(r).length?kb.field.load(kb.config[t].app,!0).then(function(q){c.app={id:kb.config[t].app,fields:q.origin};c.fieldInfos=q;try{(function(n){0!=n.length?y(n,e.record,e.workplace?e.workplace:"record").then(function(f){return k(e)}):
k(e)})(JSON.parse(r.tab).reduce(function(n,f){(e.mobile?["both","mobile"]:["both","pc"]).includes(f.setting.device.value)&&f.setting.page.value.includes(e.pattern)&&n.push(f.setting);return n},[]))}catch(n){kb.alert(kb.error.parse(n)),k(e)}})["catch"](function(q){return k(e)}):k(e)})["catch"](function(r){return k(e)})})})})(kintone.$PLUGIN_ID);