/*
* FileName "main.js"
* Version: 1.0.0
* Copyright (c) 2023 Pandafirm LLC
* Distributed under the terms of the GNU Lesser General Public License.
* https://opensource.org/licenses/LGPL-2.1
*/
'use strict';window.KintoneBoosterInjector=class{constructor(){this.fields={}}build(m,n){try{window.kb.attachment=new KintoneBoosterAttachment,window.kb.field=new KintoneBoosterField,window.kb.filter=new KintoneBoosterFilter,window.kb.formula=new KintoneBoosterFormula,window.kb.record=new KintoneBoosterRecord,window.kb.table=new KintoneBoosterTable,kb.field.load(m).then(k=>{this.app={id:m,fields:k.origin};this.record={id:(a=>"id"in a?kb.isNumeric(a.id)?a.id:"":"")(kb.queries())};this.setting=kb.extend({ui:{}},
n);kb.elm("body").append((a=>this.setting.ui.container=a)(kb.create("div").addClass("kb-injector")).append(kb.create("div").addClass("kb-injector-main").append((a=>this.setting.ui.header=a)(kb.create("header").addClass("kb-injector-header")).append(kb.create("div").addClass("kb-injector-header-title").html(this.setting.title)).append(kb.create("div").addClass("kb-injector-header-description").html(this.setting.description?this.setting.description.replace(/\n/g,"<br>"):"")).append(kb.create("div").addClass("kb-injector-header-space"))).append((a=>
this.setting.ui.body=a)(kb.create("main").addClass("kb-injector-body"))).append((a=>{this.setting.ui.footer=a;this.setting.ui.buttons={ok:kb.create("button").addClass("kb-injector-button").html(kb.constants.injector.caption.button.submit[kb.operator.language])};return a.append(this.setting.ui.buttons.ok)})(kb.create("footer").addClass("kb-injector-footer")))));((a,e,f)=>{this.setting.fields.each((b,g)=>{b.code in this.app.fields&&((c,d)=>{switch(d.type){case "SUBTABLE":if("alter"in c){c.alter.label&&
(d.label=c.alter.label.replace(/\n/g,"<br>"));for(var h in c.alter.fields)h in d.fields&&c.alter.fields[h].label&&(d.fields[h].label=c.alter.fields[h].label.replace(/\n/g,"<br>"))}d.noLabel||a.append(kb.create("div").append(kb.create("span").addClass("kb-table-caption").html(d.label)));a.append(kb.table.activate(kb.table.create(d,!0,!1,!0,!0),this.app));break;default:"alter"in c&&c.alter.label&&(d.label=c.alter.label.replace(/\n/g,"<br>")),d.lookup&&Array.prototype.push.apply(f,d.lookup.fieldMappings.map(l=>
l.field)),a.append(kb.field.activate(kb.field.create(d,!0),this.app))}})(b,this.app.fields[b.code])});e.each((b,g)=>{b.code in this.app.fields&&(c=>{switch(c.type){case "SUBTABLE":a.append(kb.table.activate(kb.table.create(c),this.app).addClass("kb-unuse"));break;default:a.append(kb.field.activate(kb.field.create(c),this.app).addClass("kb-unuse"))}})(this.app.fields[b.code])});f.each((b,g)=>{a.elm('[field-id="'+CSS.escape(b)+'"]')&&a.elm('[field-id="'+CSS.escape(b)+'"]').addClass("kb-readonly")});
a.addClass("kb-scope").attr("form-id","form_"+this.app.id).append(kb.create("input").attr("type","hidden").attr("data-type","id")).elms("input,select,textarea").each((b,g)=>b.initialize())})(this.setting.ui.body,Object.values(this.app.fields).reduce((a,e)=>{this.setting.fields.some(f=>f.code==e.code)||a.push(e);return a},[]),[]);this.setting.ui.buttons.ok.on("click",a=>{a=kb.record.get(this.setting.ui.body,this.app);a.error||kb.event.call("kb.submit.call",{record:a.record,pattern:this.record.id?"edit":
"create"}).then(e=>{e.error?(kb.record.set(this.setting.ui.body,this.app,e.record),callback(!0)):(kb.loadStart(),kb.event.call(this.record.id?"kb.edit.submit":"kb.create.submit",{container:this.setting.ui.body,record:e.record}).then(f=>{f.error||kb.confirm(kb.constants.common.message.confirm.submit[kb.operator.language],()=>{kb.loadStart();kb.record.api.set(this.app.id,{post:this.record.id?[]:[f.record],put:this.record.id?[{id:this.record.id,record:f.record}]:[]},!0,!0).then(b=>{b&&(this.record.id=
b);kb.api(kb.api.url("/api/record"),"GET",{app:this.app.id,id:this.record.id}).then(g=>{kb.event.call(this.record.id?"kb.edit.submit.success":"kb.create.submit.success",{container:f.container,record:g.record}).then(c=>{c.error||kb.event.call("kb.upsert.call",{record:g.record,pattern:this.record.id?"edit":"create"}).then(d=>{d.error?(kb.record.set(this.setting.ui.body,this.app,d.record),callback(!0)):kb.event.call("kb.mail.call",{record:g.record,pattern:this.record.id?"edit":"create"}).then(h=>{h.error||
kb.event.call("kb.omail.call",{record:g.record,pattern:this.record.id?"edit":"create"}).then(l=>{l.error||(this.setting.ui.body.removeAttr("unsaved"),kb.alert("Done!",()=>window.location.reload(!0)))}).catch(()=>{})}).catch(()=>{})}).catch(()=>{})})}).catch(g=>kb.alert(kb.error.parse(g)))}).catch(b=>kb.alert(kb.error.parse(b)))})}))}).catch(()=>{})});window.on("beforeunload",a=>{this.setting.ui.body.hasAttribute("unsaved")&&(a.returnValue=kb.constants.injector.message.confirm.changed[kb.operator.language])});
this.record.id?kb.api(kb.api.url("/api/record"),"GET",{app:this.app.id,id:this.record.id}).then(a=>{kb.event.call("kb.edit.load",{container:this.setting.ui.body,record:a.record}).then(e=>{e.error||kb.event.call("kb.action.call",{container:this.setting.ui.body,record:e.record,pattern:"edit"}).then(f=>{kb.event.call("kb.style.call",{container:this.setting.ui.body,record:f.record,pattern:"edit"}).then(b=>{kb.record.set(this.setting.ui.body.removeAttr("unsaved"),this.app,b.record).then(()=>{kb.event.call("kb.edit.load.complete",
{container:this.setting.ui.body});this.setting.ui.body.focus()})}).catch(()=>{})}).catch(()=>{})})}).catch(a=>kb.alert(kb.error.parse(a))):kb.event.call("kb.create.load",{container:this.setting.ui.body,record:(()=>{kb.record.clear(this.setting.ui.body,this.app);return kb.record.get(this.setting.ui.body,this.app,!0).record})()}).then(a=>{a.error||kb.event.call("kb.action.call",{container:this.setting.ui.body,record:a.record,pattern:"create"}).then(e=>{kb.event.call("kb.style.call",{container:this.setting.ui.body,
record:e.record,pattern:"create"}).then(f=>{kb.record.set(this.setting.ui.body.removeAttr("unsaved"),this.app,f.record).then(()=>{kb.event.call("kb.create.load.complete",{container:this.setting.ui.body});this.setting.ui.body.focus()})}).catch(()=>{})}).catch(()=>{})})})}catch(k){kb.alert(kb.error.parse(k))}}};window.kb.injector||(window.kb.injector=new KintoneBoosterInjector);
kb.constants=kb.extend({injector:{caption:{button:{submit:{en:"Submit",ja:"\u9001\u4fe1",zh:"\u63d0\u4ea4"}}},description:{},message:{confirm:{changed:{en:"Your changes have not been saved.<br>Can I continue?",ja:"\u5909\u66f4\u304c\u4fdd\u5b58\u3055\u308c\u3066\u3044\u307e\u305b\u3093\u3002<br>\u3053\u306e\u307e\u307e\u7d9a\u884c\u3057\u307e\u3059\u304b\uff1f"}},invalid:{}}}},kb.constants);