/*
* FileName "plugin.js"
* Version: 1.0.0
* Copyright (c) 2023 Pandafirm LLC
* Distributed under the terms of the GNU Lesser General Public License.
* https://opensource.org/licenses/LGPL-2.1
*/
'use strict';kb.event.on("kb.action.call",k=>new Promise((A,Q)=>{if(Array.isArray(kb.plugin.action)&&0!=kb.plugin.action.length){var c={},P=(B,e,m)=>new Promise((N,D)=>{var L=JSON.stringify(kb.record.simplify({fields:c.fieldInfos.origin},e)),I=(E,F)=>{var r=()=>{E++;E<B.length?I(E,F):F()};(a=>{var p=kb.filter.scan(c.app,e,a.condition.value);p?kb.filter.auth(a.user.value,a.organization.value,a.group.value).then(w=>{if(w){var J={clear:f=>{try{a.clear.value.map(b=>b.value).each((b,h)=>{b.table.value in c.fieldInfos.tables&&
(e[b.table.value].value=e[b.table.value].value.filter(d=>!p[b.table.value].value.includes(d)),p[b.table.value].value=[])}),f()}catch(b){kb.alert(kb.error.parse(b)),D()}},fill:f=>{try{a.fill.value.map(b=>b.value).each((b,h)=>{b.table.value in c.fieldInfos.tables&&(d=>{d=kb.isNumeric(d)?parseInt(d)-p[b.table.value].value.length:0;0<d&&Array(d).fill().map(()=>kb.record.create(c.fieldInfos.origin[b.table.value],!1)).each((l,g)=>{e[b.table.value]==p[b.table.value]?e[b.table.value].value.push({value:l}):
(e[b.table.value].value.push({value:l}),p[b.table.value].value.push({value:l}))})})(kb.formula.calculate({field:{value:Object.values(c.fieldInfos.parallelize).first().code},formula:b.range},p,p,e,c.fieldInfos.parallelize))}),f()}catch(b){kb.alert(kb.error.parse(b)),D()}},formula:f=>{try{a.formula.value.map(b=>b.value).each((b,h)=>{b.field.value in c.fieldInfos.parallelize&&(d=>{d.tableCode?p[d.tableCode].value.each((l,g)=>{l.value[d.code].value=kb.formula.calculate(b,l.value,p,e,c.fieldInfos.parallelize);
d.lookup&&(l.value[d.code].lookup=!0)}):(p[d.code].value=kb.formula.calculate(b,p,p,e,c.fieldInfos.parallelize),d.lookup&&(p[d.code].lookup=!0))})(c.fieldInfos.parallelize[b.field.value])}),f()}catch(b){kb.alert(kb.error.parse(b)),D()}},lookup:f=>{try{a.lookupApp.value?kb.field.load(a.lookupApp.value).then(b=>{(h=>{var d=[],l=[],g=(x,q)=>{var G=(n,t)=>n.lookup?kb.extend({lookup:!0,type:n.type},t):kb.extend({type:n.type},t);kb.record.api.get(a.lookupApp.value,q.query,q.sort).then(n=>{0!=n.length?(t=>
{a.lookupLimited.value.includes("limited")||1==n.length?t(n.first()):c.picker.show({app:a.lookupApp.value,query:q.query,sort:q.sort,picker:d.reduce((H,v)=>{H[v.external.code]=v.external;return H},{})},H=>t(H))})(t=>{d.each((H,v)=>{if(a.lookupOverwrite.value.includes("overwrite")||kb.field.isEmpty(q.record[H.internal.code].value))q.record[H.internal.code]=G(H.internal,t[H.external.code])});x++;x<l.length?g(x,l[x]):(m.latest.action[a.sIndex.value].lookup=C(),f())}):(a.lookupReset.value.includes("reset")&&
d.each((t,H)=>{q.record[t.internal.code]=G(t.internal,kb.record.create({fields:{empty:t.internal}}).empty)}),x++,x<l.length?g(x,l[x]):(m.latest.action[a.sIndex.value].lookup=C(),f()))}).catch(n=>{kb.alert(kb.error.parse(n));D()})},C=()=>(x=>JSON.stringify(l.reduce((q,G)=>{q.push(G.query);q.push(kb.record.simplify({fields:x},G.record));return q},[])))(d.reduce((x,q)=>{x[q.internal.code]=q.internal;return x},{}));a.lookupCriteria.value.some(x=>!(x.value.external.value in h.external&&x.value.internal.value in
h.internal))?(kb.alert("No field to lookup was found"),D()):a.lookupMapping.value.some(x=>!(x.value.external.value in h.external&&x.value.internal.value in h.internal))?(kb.alert("No field to lookup was found"),D()):(d=a.lookupMapping.value.map(x=>({external:h.external[x.value.external.value],internal:h.internal[x.value.internal.value]})),l=(x=>x.map(q=>({query:a.lookupCriteria.value.reduce((G,n)=>{var t=h.external[n.value.external.value],H=n.value.operator.value;n=h.internal[n.value.internal.value];
var v=n.tableCode?q.value:e;a.lookupIgnore.value.includes("ignore")&&kb.field.isEmpty(v[n.code].value)||G.push(kb.filter.query.create(t,H,v[n.code]));return G},kb.filter.query.parse.expand({id:a.lookupApp.value,fields:b.origin},a.lookupFilter.value).map(G=>G.field+" "+G.operator+" "+G.value)).join(" and "),sort:(0!=a.lookupSort.value.length?a.lookupSort.value.map(G=>G.value.field.value+" "+G.value.order.value):["$id asc"]).join(","),record:q.value})))((x=>x?p[x].value:[{value:e}])(Array.from(new Set(d.map(x=>
x.internal.tableCode))).first())),0!=l.length?m.latest.action[a.sIndex.value].lookup&&m.latest.action[a.sIndex.value].lookup==C()?f():g(0,l.first()):f())})({external:b.origin,internal:c.fieldInfos.parallelize})}).catch(b=>{kb.alert(kb.error.parse(b));D()}):f()}catch(b){kb.alert(kb.error.parse(b)),D()}},user:f=>{try{if(a.userSource.value){var b=[],h=[],d=(g,C)=>{(q=>{b.each((G,n)=>{if(G.isCustom)switch(G.field.type){case "USER_SELECT":G.value=q.reduce((t,H)=>{"customItemValues"in H&&(v=>{0!=v.length&&
(u=>{(y=>{0!=y.length&&(t.some(O=>O.code==y.first().info.code)||t.push({code:y.first().info.code,name:y.first().info.name}))})(kb.roleSet.user.filter(y=>y.info.id==u))})(v.first().value)})(H.customItemValues.filter(v=>v.code==G.item));return Array.from(new Set(t)).filter(v=>v)},[]);break;default:G.value=q.reduce((t,H)=>{"customItemValues"in H&&(v=>{0!=v.length&&t.push(v.first().value)})(H.customItemValues.filter(v=>v.code==G.item));return Array.from(new Set(t)).filter(v=>v)},[]).join(",")}else switch(G.item){case "groups":case "organizations":G.value=
q.map(t=>t.code);break;case "primaryOrganization":G.value=q.reduce((t,H)=>{G.item in H&&(v=>{0!=v.length&&(t.some(u=>u.code==v.first().info.code)||t.push({code:v.first().info.code,name:v.first().info.name}))})(kb.roleSet.organization.filter(v=>v.info.id==H[G.item]));return t},[]);break;default:G.value=q.reduce((t,H)=>{G.item in H&&t.push(H[G.item]);return Array.from(new Set(t)).filter(v=>v)},[]).join(",")}})})(C[a.userSource.value].value.reduce((q,G)=>{(n=>{0!=n.length&&q.push(n.first().info)})(kb.roleSet.user.filter(n=>
n.info.code==G.code));return q},[]));var x=(q,G)=>{((n,t)=>{var H=(v,u,y)=>{kb.api(kb.api.url("/api/user/affiliations"),"GET",{code:n.value[v]}).then(O=>{switch(n.item){case "groups":O.groups&&(u=O.groups.reduce((z,K)=>{z.some(M=>M.code==K.code)||z.push({code:K.code,name:K.name});return z},u),v++,v<n.value.length?H(v,u,y):y(u));break;case "organizations":O.organizations&&(u=O.organizations.reduce((z,K)=>{z.some(M=>M.code==K.code)||z.push({code:K.code,name:K.name});return z},u),v++,v<n.value.length?
H(v,u,y):y(u))}}).catch(O=>kb.alert(kb.error.parse(O)))};a.userOverwrite.value.includes("overwrite")||kb.field.isEmpty(C[n.field.code].value)||t();switch(n.item){case "groups":case "organizations":0!=n.value.length?H(0,[],v=>{C[n.field.code].value=v;t()}):(C[n.field.code].value=n.value,t());break;default:C[n.field.code].value=n.value,t()}})(b[q],()=>{q++;q<b.length?x(q,G):G()})};x(0,()=>{g++;g<h.length?d(g,h[g]):(m.latest.action[a.sIndex.value].user=l(),f())})},l=()=>(g=>JSON.stringify(h.map(C=>kb.record.simplify({fields:g},
C))))(b.reduce((g,C)=>{g[C.field.code]=C.field;return g},(g=>{var C={};C[g]=c.fieldInfos.parallelize[g];return C})(a.userSource.value)));a.userCustomItem.value.some(g=>!(g.value.field.value in c.fieldInfos.parallelize))?(kb.alert("No field to user informations was found"),D()):a.userMapping.value.some(g=>!(g.value.field.value in c.fieldInfos.parallelize))?(kb.alert("No field to user informations was found"),D()):(a.userCustomItem.value.each((g,C)=>{b.push({isCustom:!0,item:g.value.item.value,field:c.fieldInfos.parallelize[g.value.field.value],
value:[]})}),a.userMapping.value.each((g,C)=>{b.push({isCustom:!1,item:g.value.item.value,field:c.fieldInfos.parallelize[g.value.field.value],value:[]})}),a.userPrimaryOrganization.value&&a.userPrimaryOrganization.value in c.fieldInfos.parallelize&&b.push({isCustom:!1,item:"primaryOrganization",field:c.fieldInfos.parallelize[a.userPrimaryOrganization.value],value:[]}),a.userOrganization.value&&a.userOrganization.value in c.fieldInfos.parallelize&&b.push({isCustom:!1,item:"organizations",field:c.fieldInfos.parallelize[a.userOrganization.value],
value:[]}),a.userGroup.value&&a.userGroup.value in c.fieldInfos.parallelize&&b.push({isCustom:!1,item:"groups",field:c.fieldInfos.parallelize[a.userGroup.value],value:[]}),h=(g=>g?p[g].value:[{value:e}])(c.fieldInfos.parallelize[a.userSource.value].tableCode).map(g=>g.value),0!=h.length?m.latest.action[a.sIndex.value].user&&m.latest.action[a.sIndex.value].user==l()?f():0!=b.length?d(0,h.first()):f():f())}else f()}catch(g){kb.alert(kb.error.parse(g)),D()}}};J.clear(()=>{J.fill(()=>{J.formula(()=>{J.lookup(()=>
{J.user(()=>{r()})})})})})}else r()}).catch(w=>{kb.alert(kb.error.parse(w));D()}):r()})((a=>{m.latest?m.latest.action||(m.latest.action={}):m.latest={action:{}};a.sIndex.value in m.latest.action||(m.latest.action[a.sIndex.value]={lookup:"[]",user:"[]"});return a})(B[E]))};I(0,()=>{N({record:e,performed:L!=JSON.stringify(kb.record.simplify({fields:c.fieldInfos.origin},e))})})});kb.field.load(kb.injector.app.id).then(B=>{c.app={id:kb.injector.app.id,fields:B.origin};c.fieldInfos=B;c.picker=new KintoneBoosterRecordPicker("record");
try{(e=>{if(0!=e.length){var m=(()=>{var N=e;"change"==k.pattern&&(N=e.filter(D=>(L=>"fields"in k?!L.first()||k.fields.some(I=>L.includes(I)):!L.first()||L.includes(k.field))(D.triggers.value.map(L=>L.value.field.value))));return N})();0!=m.length?P(m,k.record,k.container).then(N=>{k.stopPropagation&&(c.latest={record:JSON.stringify(kb.record.simplify({fields:B.origin},k.record)),time:(new Date).getTime()});k.performed=N.performed;A(k)}).catch(()=>A(k)):A(k)}else A(k)})(kb.plugin.action.reduce((e,
m)=>{m.event.value.includes(k.pattern)&&e.push(m);return e},[]))}catch(e){kb.alert(kb.error.parse(e)),A(k)}}).catch(B=>A(k))}else A(k)}));
kb.event.on("kb.cascade.call",k=>new Promise((A,Q)=>{if(["create","edit"].includes(k.pattern))if(Array.isArray(kb.plugin.cascade)&&0!=kb.plugin.cascade.length){var c={},P=(B,e,m)=>new Promise((N,D)=>{var L=(I,E)=>{var F=(r,a)=>{var p=Object.keys(c.fieldInfos.parallelize[r.child.value].options);if(Array.isArray(a[r.parent.value].value)?0!=a[r.parent.value].value.length:a[r.parent.value].value)p=(Array.isArray(a[r.parent.value].value)?a[r.parent.value].value:[a[r.parent.value].value]).reduce((w,J)=>
w=[...(new Set([...w,...r.relation.value[J]]))],[]);return p};(r=>{(a=>{a.parent.tableCode?a.parent.tableCode in e&&e[a.parent.tableCode].value.each((p,w)=>{a.parent.code in p.value&&(p.value[a.child.code].options=F(r,p.value))}):a.parent.code in e&&(e[a.child.code].options=F(r,e))})({parent:c.fieldInfos.parallelize[r.parent.value],child:c.fieldInfos.parallelize[r.child.value]});I++;I<B.length?L(I,E):E()})(B[I])};L(0,()=>N())});kb.field.load(kb.injector.app.id).then(B=>{c.app={id:kb.injector.app.id,
fields:B.origin};c.fieldInfos=B;try{(e=>{0!=e.length?P(e,k.record,k.container).then(m=>A(k)).catch(()=>A(k)):A(k)})(kb.plugin.cascade.reduce((e,m)=>{m.parent.value in c.fieldInfos.parallelize&&m.child.value in c.fieldInfos.parallelize&&("string"===typeof m.relation.value&&(m.relation.value=JSON.parse(m.relation.value)),e.push(m));return e},[]))}catch(e){kb.alert(kb.error.parse(e)),A(k)}}).catch(B=>A(k))}else A(k);else A(k)}));
kb.event.on("kb.mail.call",k=>new Promise((A,Q)=>{if(Array.isArray(kb.plugin.mail)&&0!=kb.plugin.mail.length){var c={},P=(B,e,m=!1)=>new Promise((N,D)=>{var L="",I=(E,F)=>{var r=()=>{E++;E<B.length?I(E,F):F()};(a=>{var p=kb.filter.scan(c.app,e,a.condition.value);p?kb.filter.auth(a.user.value,a.organization.value,a.group.value).then(w=>{if(w){var J=(f,b,h)=>{"HTML"==a.format.value&&(f=f.replace(/\r/g,"").replace(/\n/g,"<br>"));for(var d in b){var l=b[d].value;d in c.fieldInfos.parallelize&&("HTML"==
a.format.value&&"MULTI_LINE_TEXT"==c.fieldInfos.parallelize[d].type&&(l=l.replace(/\r/g,"").replace(/\n/g,"<br>")),f=f.replace(new RegExp("%"+d+"%","g"),kb.field.stringify(c.fieldInfos.parallelize[d],l," / ",!0)))}for(d in h)l=h[d].value,d in c.fieldInfos.parallelize&&("HTML"==a.format.value&&"MULTI_LINE_TEXT"==c.fieldInfos.parallelize[d].type&&(l=l.replace(/\r/g,"").replace(/\n/g,"<br>")),f=f.replace(new RegExp("%"+d+"%","g"),kb.field.stringify(c.fieldInfos.parallelize[d],l," / ",!0)));return f};
(f=>{var b=h=>{(d=>{var l=(g,C)=>{if(0!=d.attachment.length){var x=!1;window.hasOwnProperty("kb_report_temp")&&d.attachment[g].fileKey in window.kb_report_temp&&(x=!0);x?(d.attachment[g].data=window.kb_report_temp[d.attachment[g].fileKey],g++,g<d.attachment.length?l(g,C):C()):kb.file.download(d.attachment[g],!0).then(q=>{kb.field.blobToBase64(q,G=>{d.attachment[g].data=G;g++;g<d.attachment.length?l(g,C):C()})}).catch(q=>{kb.alert(kb.error.parse(q));D()})}else C()};l(0,()=>{kb.encrypt(JSON.stringify(d.data),
L).then(g=>{var C=fetch,x="https://api.kintone-booster.com/mail/"+kb.operator.language,q=JSON,G=q.stringify;d.data=g.data;d.iv=g.iv;d.tag=g.tag;C(x,{method:"POST",headers:{"X-Requested-With":"XMLHttpRequest"},body:G.call(q,d)}).then(n=>{n.json().then(t=>{switch(n.status){case 200:h++;h<f.length?b(h):r();break;default:kb.alert(kb.error.parse(t)),D()}})}).catch(n=>{kb.alert(kb.error.parse(n));D()})}).catch(g=>{D()})})})(f[h])};0!=f.length?b(0):r()})((()=>{var f=[];(c.fieldInfos.parallelize[a.to.value].tableCode?
p[c.fieldInfos.parallelize[a.to.value].tableCode].value:[{value:p}]).each((b,h)=>{if(b.value[a.to.value].value){h=f.push;var d={mail:a.mail.value,sender:a.sender.value,host:a.host.value,port:a.port.value,author:a.author.value,pwd:a.pwd.value,secure:a.secure.value,to:b.value[a.to.value].value,cc:J(a.cc.value,p,c.fieldInfos.parallelize[a.to.value].tableCode?b.value:{}),bcc:J(a.bcc.value,p,c.fieldInfos.parallelize[a.to.value].tableCode?b.value:{}),html:"HTML"==a.format.value},l=J(a.subject.value,p,c.fieldInfos.parallelize[a.to.value].tableCode?
b.value:{}),g=J(a.body.value,p,c.fieldInfos.parallelize[a.to.value].tableCode?b.value:{}),C=[];a.attachment.value&&a.attachment.value in c.fieldInfos.parallelize&&(C=(c.fieldInfos.parallelize[a.attachment.value].tableCode?b.value:p)[a.attachment.value].value);h.call(f,{data:d,subject:l,body:g,attachment:C})}});return f})())}else r()}).catch(w=>{kb.alert(kb.error.parse(w));D()}):r()})(B[E])};fetch("https://api.kintone-booster.com/mail/"+kb.operator.language,{method:"GET",headers:{"X-Requested-With":"XMLHttpRequest"}}).then(E=>
{E.json().then(F=>{switch(E.status){case 200:L=F.passphrase;m||kb.loadStart();I(0,()=>{m||kb.loadEnd();N()});break;default:kb.alert(kb.error.parse(F)),D()}})}).catch(E=>{kb.alert(kb.error.parse(E));D()})});kb.field.load(kb.injector.app.id).then(B=>{c.app={id:kb.injector.app.id,fields:B.origin};c.fieldInfos=B;try{(e=>{0!=e.length?P(e,k.record,!0).then(m=>A(k)).catch(()=>A(k)):A(k)})(kb.plugin.mail.reduce((e,m)=>{m.event.value.includes(k.pattern)&&e.push(m);return e},[]))}catch(e){kb.alert(kb.error.parse(e)),
A(k)}}).catch(B=>A(k))}else A(k)}));
kb.event.on("kb.omail.call",k=>new Promise((A,Q)=>{if(Array.isArray(kb.plugin.omail)&&0!=kb.plugin.omail.length){var c={},P=(B,e,m=!1)=>new Promise((N,D)=>{var L="",I=(E,F)=>{var r=()=>{E++;E<B.length?I(E,F):F()};(a=>{var p=kb.filter.scan(c.app,e,a.condition.value);p?kb.filter.auth(a.user.value,a.organization.value,a.group.value).then(w=>{if(w){var J=(f,b,h)=>{"HTML"==a.format.value&&(f=f.replace(/\r/g,"").replace(/\n/g,"<br>"));for(var d in b){var l=b[d].value;d in c.fieldInfos.parallelize&&("HTML"==
a.format.value&&"MULTI_LINE_TEXT"==c.fieldInfos.parallelize[d].type&&(l=l.replace(/\r/g,"").replace(/\n/g,"<br>")),f=f.replace(new RegExp("%"+d+"%","g"),kb.field.stringify(c.fieldInfos.parallelize[d],l," / ",!0)))}for(d in h)l=h[d].value,d in c.fieldInfos.parallelize&&("HTML"==a.format.value&&"MULTI_LINE_TEXT"==c.fieldInfos.parallelize[d].type&&(l=l.replace(/\r/g,"").replace(/\n/g,"<br>")),f=f.replace(new RegExp("%"+d+"%","g"),kb.field.stringify(c.fieldInfos.parallelize[d],l," / ",!0)));return f};
(f=>{var b=h=>{(d=>{var l=(g,C)=>{if(0!=d.attachment.length){var x=!1;window.hasOwnProperty("kb_report_temp")&&d.attachment[g].fileKey in window.kb_report_temp&&(x=!0);x?(d.attachment[g].data=window.kb_report_temp[d.attachment[g].fileKey],g++,g<d.attachment.length?l(g,C):C()):kb.file.download(d.attachment[g],!0).then(q=>{kb.field.blobToBase64(q,G=>{d.attachment[g].data=G;g++;g<d.attachment.length?l(g,C):C()})}).catch(q=>{kb.alert(kb.error.parse(q));D()})}else C()};l(0,()=>{kb.encrypt(JSON.stringify(d.data),
L).then(g=>{var C=fetch,x="https://api.kintone-booster.com/mail/oauth/"+kb.operator.language,q=JSON,G=q.stringify;d.data=g.data;d.iv=g.iv;d.tag=g.tag;C(x,{method:"POST",headers:{"X-Requested-With":"XMLHttpRequest"},body:G.call(q,d)}).then(n=>{n.json().then(t=>{switch(n.status){case 200:h++;h<f.length?b(h):r();break;default:kb.alert(kb.error.parse(t)),D()}})}).catch(n=>{kb.alert(kb.error.parse(n));D()})}).catch(g=>{D()})})})(f[h])};0!=f.length?b(0):r()})((()=>{var f=[];(c.fieldInfos.parallelize[a.to.value].tableCode?
p[c.fieldInfos.parallelize[a.to.value].tableCode].value:[{value:p}]).each((b,h)=>{b.value[a.to.value].value&&f.push({data:{client_id:a.client_id.value,client_secret:a.client_secret.value,author:a.author.value,sender:a.sender.value,subdomain:kb.operator.domain,provider:(d=>{d="";switch(a.provider.value){case "GMail":d="google";break;case "Exchange Online":d="microsoft"}return d})(a.provider.value),to:b.value[a.to.value].value,cc:J(a.cc.value,p,c.fieldInfos.parallelize[a.to.value].tableCode?b.value:
{}),bcc:J(a.bcc.value,p,c.fieldInfos.parallelize[a.to.value].tableCode?b.value:{}),html:"HTML"==a.format.value},subject:J(a.subject.value,p,c.fieldInfos.parallelize[a.to.value].tableCode?b.value:{}),body:J(a.body.value,p,c.fieldInfos.parallelize[a.to.value].tableCode?b.value:{}),attachment:(()=>{var d=[];a.attachment.value&&a.attachment.value in c.fieldInfos.parallelize&&(d=(c.fieldInfos.parallelize[a.attachment.value].tableCode?b.value:p)[a.attachment.value].value);return d})()})});return f})())}else r()}).catch(w=>
{kb.alert(kb.error.parse(w));D()}):r()})(B[E])};fetch("https://api.kintone-booster.com/mail/oauth/"+kb.operator.language,{method:"GET",headers:{"X-Requested-With":"XMLHttpRequest"}}).then(E=>{E.json().then(F=>{switch(E.status){case 200:L=F.passphrase;m||kb.loadStart();I(0,()=>{m||kb.loadEnd();N()});break;default:kb.alert(kb.error.parse(F)),D()}})}).catch(E=>{kb.alert(kb.error.parse(E));D()})});kb.field.load(kb.injector.app.id).then(B=>{c.app={id:kb.injector.app.id,fields:B.origin};c.fieldInfos=B;
try{(e=>{0!=e.length?P(e,k.record,!0).then(m=>A(k)).catch(()=>A(k)):A(k)})(kb.plugin.omail.reduce((e,m)=>{m.event.value.includes(k.pattern)&&e.push(m);return e},[]))}catch(e){kb.alert(kb.error.parse(e)),A(k)}}).catch(B=>A(k))}else A(k)}));
kb.event.on("kb.report.call",k=>new Promise((A,Q)=>{if(Array.isArray(kb.plugin.report)&&0!=kb.plugin.report.length){var c={},P=(B,e,m=!1)=>new Promise((N,D)=>{var L=(I,E)=>{var F=()=>{I++;I<B.length?L(I,E):E()};(r=>{kb.filter.scan(c.app,e,r.condition.value)?kb.filter.auth(r.user.value,r.organization.value,r.group.value).then(a=>{if(a)if(r.attachment.value in c.fieldInfos.origin){var p=Object.values(c.fieldInfos.tables).reduce((w,J)=>{Object.values(J.fields).each((f,b)=>{w[f.code]={index:-1,limit:e[J.code].value.length,
status:"ready",table:J.code}});return w},{});(w=>{if(0!=w.sheets.length){var J=(b,h,d)=>{(l=>{var g=!1,C=kb.extend({},l),x;for(x in c.fieldInfos.parallelize)(q=>{l.cells.each((G,n)=>{G.each((t,H)=>{if(t.value.match(new RegExp("%"+q.code+"%")))switch(q.type){case "FILE":(v=>{Array.isArray(v)?(u=>{if(u){t.type="image";var y=l.rows.slice(n,n+parseInt(t.rowSpan||"1")).reduce((z,K)=>z+=K.origin,0),O=l.cols.slice(H,H+parseInt(t.colSpan||"1")).reduce((z,K)=>z+=K.origin,0);h.push({cell:t,fileKey:u.fileKey,
size:{height:y,width:O}});g=!0}else t.value=""})(v.find(u=>u.contentType.match(/image/g))):t.value=""})((()=>{var v=null;if(q.code in p){var u=p[q.code];"complete"!=u.status&&(u.index++,u.status=u.index==u.limit-1?"complete":"processing",v=e[u.table].value[u.index].value[q.code].value)}else v=e[q.code].value;return v})());break;default:q.code in p?(v=>{"complete"!=v.status?(v.index++,v.status=v.index==v.limit-1?"complete":"processing",t.value=t.value.replace(new RegExp("%"+q.code+"%","g"),kb.field.stringify(q,
e[v.table].value[v.index].value[q.code].value," / ",!0)),g=!0):t.value=t.value.replace(new RegExp("%"+q.code+"%","g"),"")})(p[q.code]):(t.value=t.value.replace(new RegExp("%"+q.code+"%","g"),kb.field.stringify(q,e[q.code].value," / ",!0)),g=!0)}t.value.match(/^=/)&&(t.value=eval(t.value.replace(/^=/g,"kb.formula.report.")))})})})(c.fieldInfos.parallelize[x]);l.repeat&&(Object.values(p).some(q=>"processing"==q.status)?w.sheets.splice(b+1,0,C):g||(w.sheets.splice(b,1),b--));b++;b<w.sheets.length?J(b,
h,d):d(h)})(w.sheets[b])},f=(b,h,d)=>{0!=h.length?kb.file.download(h[b],!0).then(l=>{var g=new Image;g.onload=()=>{var C=Math.min(h[b].size.width/g.width,h[b].size.height/g.height),x=Math.round(g.height*C);C=Math.round(g.width*C);var q=kb.create("canvas");q.width=C;q.height=x;q.getContext("2d").drawImage(g,0,0,C,x);h[b].cell.value=q.toDataURL("image/png");b++;b<h.length?f(b,h,d):d()};g.src=URL.createObjectURL(l)}).catch(l=>kb.alert(kb.error.parse(l),()=>D())):d()};J(0,[],b=>{f(0,b,()=>{(h=>{fetch("https://api.pandafirm.jp/layup/report",
{method:"POST",headers:{"X-Requested-With":"XMLHttpRequest"},body:JSON.stringify({lang:kb.operator.language,name:h,datas:w})}).then(d=>{d.json().then(l=>{switch(d.status){case 200:kb.file.upload((g=>{var C=atob(g.binary),x=new Uint8Array(C.length);C.length.each(q=>x[q]=C.charCodeAt(q));return new File([new Blob([x.buffer],{type:g.contentType})],g.filename,{type:g.contentType})})(l.file),!0).then(g=>{window.hasOwnProperty("kb_report_temp")||(window.kb_report_temp={});window.kb_report_temp[g.fileKey]=
l.file.binary;e[r.attachment.value].value.push(g);F()}).catch(g=>{kb.alert(kb.error.parse(g),()=>D())});break;default:kb.alert(kb.error.parse(l),()=>D())}})}).catch(d=>kb.alert(kb.error.parse(d),()=>D()))})((r.name.value in c.fieldInfos.origin?e[r.name.value].value:"")||"report.pdf")})})}else F()})(r.template.value?JSON.parse(r.template.value):{sheets:[]})}else F();else F()}).catch(a=>kb.alert(kb.error.parse(a),()=>D())):F()})(B[I])};m||kb.loadStart();L(0,()=>{kb.record.api.set(c.app.id,{put:[kb.record.api.transform(B.reduce((I,
E)=>{E.attachment.value in c.fieldInfos.origin&&(I[E.attachment.value]=e[E.attachment.value]);return I},{$id:e.$id}))]},!0).then(I=>{m||kb.loadEnd();N()}).catch(I=>kb.alert(kb.error.parse(I),()=>D()))})});kb.field.load(kb.injector.app.id).then(B=>{c.app={id:kb.injector.app.id,fields:B.origin};c.fieldInfos=B;try{(e=>{0!=e.length?P(e,k.record,!0).then(m=>A(k)).catch(()=>A(k)):A(k)})(kb.plugin.report.reduce((e,m)=>{m.event.value.includes(k.pattern)&&e.push(m);return e},[]))}catch(e){kb.alert(kb.error.parse(e)),
A(k)}}).catch(B=>A(k))}else A(k)}));
kb.event.on("kb.style.call",k=>new Promise((A,Q)=>{if(Array.isArray(kb.plugin.style)&&0!=kb.plugin.style.length){var c={},P=(B,e,m)=>new Promise((N,D)=>{var L={},I=(E,F)=>{(r=>{var a=kb.filter.scan(c.app,e,r.condition.value);a?kb.filter.auth(r.user.value,r.organization.value,r.group.value).then(p=>{p&&(r.color.value.map(w=>w.value).each((w,J)=>{w.field.value in c.fieldInfos.parallelize&&(f=>{f.tableCode?f.tableCode in a&&a[f.tableCode].value.each((b,h)=>{f.code in b.value&&(b.value[f.code].backcolor=
w.backcolor.value,b.value[f.code].forecolor=w.forecolor.value)}):f.code in a&&(a[f.code].backcolor=w.backcolor.value,a[f.code].forecolor=w.forecolor.value)})(c.fieldInfos.parallelize[w.field.value])}),r.editable.value.map(w=>w.value).each((w,J)=>{w.field.value in c.fieldInfos.parallelize&&(f=>{c.fieldInfos.disables.includes(f.code)||(f.tableCode?f.tableCode in a&&(a[f.tableCode].value.each((b,h)=>{f.code in b.value&&(b.value[f.code].disabled="disable"==w.state.value)}),L[f.code]=e[f.tableCode].value.map(b=>
b.value[f.code].disabled?"disabled":"")):f.code in a&&(a[f.code].disabled="disable"==w.state.value,L[f.code]=e[f.code].disabled?"disabled":""))})(c.fieldInfos.parallelize[w.field.value])}),r.display.value.map(w=>w.value).each((w,J)=>{w.field.value in c.fieldInfos.groups?c.fieldInfos.groups[w.field.value].fields.map(f=>f.code).each((f,b)=>{f in c.fieldInfos.parallelize&&f in a&&(a[f].hidden="hide"==w.state.value)}):w.field.value in c.fieldInfos.tables?w.field.value in a&&(a[w.field.value].hidden="hide"==
w.state.value):(f=>{f.tableCode?f.tableCode in a&&a[f.tableCode].value.each((b,h)=>{f.code in b.value&&(b.value[f.code].hidden="hide"==w.state.value)}):f.code in a&&(a[f.code].hidden="hide"==w.state.value)})(c.fieldInfos.parallelize[w.field.value])}));E++;E<B.length?I(E,F):F()}).catch(p=>{kb.alert(kb.error.parse(p));D()}):(E++,E<B.length?I(E,F):F())})(B[E])};I(0,()=>{m.latest?m.latest.style||(m.latest.style="{}"):m.latest={style:"{}"};var E=JSON.stringify(L),F="{}"!=E?m.latest.style!=E:!1;F&&(m.latest.style=
E);N({performed:F})})});kb.field.load(kb.injector.app.id).then(B=>{c.app={id:kb.injector.app.id,fields:B.origin};c.fieldInfos=B;try{(e=>{0!=e.length?P(e,k.record,k.container).then(m=>{k.performed=m.performed;A(k)}).catch(()=>A(k)):A(k)})(kb.plugin.style.reduce((e,m)=>{m.page.value.includes(k.pattern)&&e.push(m);return e},[]))}catch(e){kb.alert(kb.error.parse(e)),A(k)}}).catch(B=>A(k))}else A(k)}));
kb.event.on("kb.submit.call",k=>new Promise((A,Q)=>{if(Array.isArray(kb.plugin.submit)&&0!=kb.plugin.submit.length){var c={},P=(B,e,m=!1,N={})=>new Promise((D,L)=>{var I=[],E=(F,r)=>{var a=()=>{F++;F<B.length?E(F,r):r()};(p=>{kb.filter.scan(c.app,e,p.condition.value)?kb.filter.auth(p.user.value,p.organization.value,p.group.value).then(w=>{if(w){var J={duplicate:f=>{try{p.duplicateCriteria.value.some(b=>!(b.value.external.value in c.fieldInfos.parallelize&&b.value.internal.value in c.fieldInfos.parallelize))?
(kb.alert("No field to lookup was found"),L()):(b=>{b&&I.push(b);f()})(p.duplicateCriteria.value.reduce((b,h)=>{b.push(kb.filter.query.create(c.fieldInfos.parallelize[h.value.external.value],h.value.operator.value,e[c.fieldInfos.parallelize[h.value.internal.value].code]));return b},[]).join(" and "))}catch(b){kb.alert(kb.error.parse(b)),L()}},error:f=>{try{if(p.errorMessage.value||0!=p.errorField.value.length){var b=kb.filter.scan(c.app,e,p.errorFilter.value);b?(p.errorField.value.each((h,d)=>{h.value.field.value in
c.fieldInfos.parallelize&&(l=>{l.tableCode?b[l.tableCode].value.each((g,C)=>{g.value[h.value.field.value].error=h.value.message.value}):e[h.value.field.value].error=h.value.message.value})(c.fieldInfos.parallelize[h.value.field.value])}),m||kb.loadEnd(),D({error:!0,message:p.errorMessage.value})):f()}else f()}catch(h){kb.alert(kb.error.parse(h)),L()}},numbering:f=>{try{if(p.numberingField.value in c.fieldInfos.parallelize)if(e[p.numberingField.value].value)f();else{var b="",h=p.numberingGroup.value.reduce((d,
l)=>{if(l.value.field.value in c.fieldInfos.parallelize)switch(b+=e[l.value.field.value].value,c.fieldInfos.parallelize[l.value.field.value].type){case "DROP_DOWN":case "RADIO_BUTTON":d.push(l.value.field.value+' in ("'+e[l.value.field.value].value+'")');break;default:d.push(l.value.field.value+'="'+e[l.value.field.value].value+'"')}return d},"$id"in e?['$id!="'+e.$id.value+'"']:[]);b in N?(N[b]++,e[p.numberingField.value].value=b+N[b].toString().lpad("0",parseInt(p.numberingDigits.value)),f()):kb.api(kb.api.url("/api/records"),
"GET",{app:c.app.id,query:h.join(" and ")+" order by "+p.numberingField.value+" desc limit 1 offset 0"}).then(d=>{d=d.records;var l=0;0!=d.length&&(l=parseInt((d.first()[p.numberingField.value].value||" ").replace(/[ ]+/g,"").replace(new RegExp("^"+b,"g"),"")),kb.isNumeric(l)||(l=0));l++;d=l;N[b]=d;e[p.numberingField.value].value=b+d.toString().lpad("0",parseInt(p.numberingDigits.value));f()}).catch(d=>{kb.alert(kb.error.parse(d));L()})}else f()}catch(d){kb.alert(kb.error.parse(d)),L()}},prompt:f=>
{try{(b=>{0!=b.length?(h=>{b.each((d,l)=>{h.append(kb.field.activate(kb.field.create(d).css({width:"100%"}),c.app,!1))});m||kb.loadEnd();(new KintoneBoosterPopupform(h,600,"full",{ok:()=>{var d=kb.record.get(h,c.app,!0);b.each((l,g)=>{e[l.code].value=d.record[l.code].value});m||kb.loadStart();f()},cancel:()=>{m||kb.loadStart();f()}})).show()})(kb.create("div").addClass("kb-scope").attr("form-id","form_"+c.app.id)):f()})(p.promptField.value.reduce((b,h)=>{h.value.field.value in c.fieldInfos.parallelize&&
(p.promptOverwrite.value.includes("overwrite")?b.push(c.fieldInfos.parallelize[h.value.field.value]):kb.field.isEmpty(e[h.value.field.value].value)&&b.push(c.fieldInfos.parallelize[h.value.field.value]));return b},[]))}catch(b){kb.alert(kb.error.parse(b)),L()}},verify:f=>{try{(b=>{0!=b.length?(h=>{b.each((d,l)=>{h.append(kb.field.activate(kb.field.create(d).addClass("kb-readonly").css({width:"100%"}),c.app,!1))});kb.record.set(h,c.app,e);m||kb.loadEnd();(new KintoneBoosterPopupform(h,600,"full",{ok:()=>
{m||kb.loadStart();f()},cancel:()=>{m||kb.loadEnd();D({error:!0})}})).show()})(kb.create("div").addClass("kb-scope kb-verify").attr("form-id","form_"+c.app.id).append(kb.create("p").html(p.verifyMessage.value))):f()})(p.verifyField.value.reduce((b,h)=>{h.value.field.value in c.fieldInfos.parallelize&&b.push(c.fieldInfos.parallelize[h.value.field.value]);return b},[]))}catch(b){kb.alert(kb.error.parse(b)),L()}}};J.numbering(()=>{J.prompt(()=>{J.verify(()=>{J.error(()=>{J.duplicate(()=>{a()})})})})})}else a()}).catch(w=>
{kb.alert(kb.error.parse(w));L()}):a()})(B[F])};m||kb.loadStart();E(0,()=>{m||kb.loadEnd();0!=I.length?kb.api(kb.api.url("/api/records"),"GET",{app:c.app.id,query:((F,r)=>(r?"$id!="+r+" and ("+F+")":F)+" order by $id asc limit 5 offset 0")(I.map(F=>"("+F+")").join(" or "),"$id"in e?e.$id.value:"")}).then(F=>{0!=F.records.length?kb.confirm(kb.create("div").append(kb.create("p").css({margin:"0"}).html(kb.constants.submit.message.duplicate[kb.operator.language])),r=>{D({error:r})},!0):D({error:!1})}).catch(F=>
{kb.alert(kb.error.parse(F),()=>{D({error:!1})})}):D({error:!1})})});kb.field.load(kb.injector.app.id).then(B=>{c.app={id:kb.injector.app.id,fields:B.origin};c.fieldInfos=B;try{(e=>{0!=e.length?P(e,k.record,!0,k.numbering).then(m=>{m.error?(k.error=!0,m.message?kb.alert(m.message,()=>A(k)):A(k)):A(k)}).catch(()=>{k.error=!0;A(k)}):A(k)})(kb.plugin.submit.reduce((e,m)=>{m.event.value.includes(k.pattern)&&e.push(m);return e},[]))}catch(e){kb.alert(kb.error.parse(e)),A(k)}}).catch(B=>A(k))}else A(k)}));
kb.event.on("kb.upsert.call",k=>new Promise((A,Q)=>{if(Array.isArray(kb.plugin.upsert)&&0!=kb.plugin.upsert.length){var c={},P=(B,e,m=!1)=>new Promise((N,D)=>{var L=(I,E)=>{var F=()=>{I++;I<B.length?L(I,E):E()};(r=>{var a=kb.filter.scan(c.app,e,r.condition.value);a?kb.filter.auth(r.user.value,r.organization.value,r.group.value).then(p=>{p?kb.field.load(r.app.value).then(w=>{var J={id:r.app.value,fields:w.origin};(f=>{var b=[],h=[],d=[],l={},g=1,C=1,x=0,q=0,G=()=>{var n=[],t={field:(u,y)=>{y=u.tableCode?
a[u.tableCode].value.length>y?a[u.tableCode].value[y].value[u.code]:kb.record.create({fields:{empty:mapping.internal}}).empty:a[u.code];return kb.extend({type:u.type},y)},record:u=>{C.each(y=>{var O=(z=>{var K=kb.filter.scan(J,u,z.query);if(!K&&"upsert"==r.pattern.value){for(var M in z.rows)0==kb.filter.result[M].value.length&&(u[M].value.push({value:kb.extend({},z.rows[M])}),kb.filter.result[M]={value:[u[M].value.last()]});K=kb.filter.result}return K})((()=>{var z={rows:{},query:[]};q=y;b.each((K,
M)=>{K.external.tableCode&&(K.external.tableCode in z.rows||(z.rows[K.external.tableCode]=kb.record.create(J.fields[K.external.tableCode],!1)),z.rows[K.external.tableCode][K.external.code]=H(K.external,t.field(K.internal,q)),z.query.push(kb.filter.query.create(K.external,K.operator,t.field(K.internal,q))))});h.each((K,M)=>{K.field.tableCode&&z.query.push(K.field.code+" "+K.operator+" "+K.value)});z.query=z.query.join(" and ");return z})());O&&d.each((z,K)=>{z.external.tableCode?z.external.tableCode in
l?(u[z.external.tableCode]={value:l[z.external.tableCode]},l[z.external.tableCode].each((M,R)=>{M.value[z.external.code]=H(z.external,t.field(z.internal,R));"FILE"==z.external.type&&M.value[z.external.code].value&&Array.prototype.push.apply(n,M.value[z.external.code].value)})):O[z.external.tableCode].value.each((M,R)=>{M.value[z.external.code]=H(z.external,t.field(z.internal,q));"FILE"==z.external.type&&M.value[z.external.code].value&&Array.prototype.push.apply(n,M.value[z.external.code].value)}):
(u[z.external.code]=H(z.external,t.field(z.internal,x)),"FILE"==z.external.type&&u[z.external.code].value&&Array.prototype.push.apply(n,u[z.external.code].value))})});return u}},H=(u,y)=>{switch(u.type){case "CHECK_BOX":case "FILE":case "GROUP_SELECT":case "MULTI_SELECT":case "ORGANIZATION_SELECT":case "USER_SELECT":Array.isArray(y.value)||(y.value=[y.value])}y.type=u.type;return u.lookup?kb.extend({lookup:!0},y):y},v=u=>{u.each((y,O)=>{r.formula.value.each((z,K)=>{z.value.field.value in f.external&&
(M=>{M.tableCode?y[M.tableCode].value.each((R,S)=>{R.value[M.code].value=kb.formula.calculate(z.value,R.value,y,y,f.external);M.lookup&&(R.value[M.code].lookup=!0)}):(y[M.code].value=kb.formula.calculate(z.value,y,y,y,f.external),M.lookup&&(y[M.code].lookup=!0))})(f.external[z.value.field.value])})});return u};"insert"==r.pattern.value?(u=>{kb.file.clone(n,!0).then(()=>{kb.record.api.set(r.app.value,{post:u},m).then(y=>{x++;x<g?G():F()}).catch(y=>{kb.alert(kb.error.parse(y));D()})})})(v([t.record(kb.record.create(J))])):
kb.record.api.get(r.app.value,(()=>{var u=[];b.each((y,O)=>{y.external.tableCode||u.push(kb.filter.query.create(y.external,y.operator,t.field(y.internal,x)))});h.each((y,O)=>{y.field.tableCode||u.push(y.field.code+" "+y.operator+" "+y.value)});return u.join(" and ")})()).then(u=>{u=(y=>{var O=[];0!=y.length?O=y.map(z=>t.record(z)):"upsert"==r.pattern.value&&(z=>{O.push(t.record((()=>{var K=kb.record.create(J);z.each((M,R)=>{M.external.tableCode?K[M.external.tableCode]={value:[]}:K[M.external.code]=
H(M.external,t.field(M.internal,x))});return K})()))})(b.filter(z=>!kb.field.reserved.includes(z.external.type)));return v(O)})(u);kb.file.clone(n,!0).then(()=>{kb.record.api.set(r.app.value,{post:u.filter(y=>!y.$id.value),put:u.reduce((y,O)=>{O.$id.value&&y.push(kb.record.api.transform(O));return y},[])},m).then(y=>{x++;x<g?G():F()}).catch(y=>{kb.alert(kb.error.parse(y));D()})})}).catch(u=>{kb.alert(kb.error.parse(u));D()})};r.mapping.value.some(n=>!(n.value.external.value in f.external&&n.value.internal.value in
f.internal))?(kb.alert("No field to transfer was found"),D()):r.criteria.value.some(n=>!(n.value.external.value in f.external&&n.value.internal.value in f.internal))?(kb.alert("No field to transfer was found"),D()):(r.mapping.value.each((n,t)=>{((H,v)=>{H.tableCode?l[H.tableCode]=(u=>{u=u?u.length:1;v.tableCode&&(u=u<a[v.tableCode].value.length?a[v.tableCode].value.length:u);return Array(u).fill().map(()=>({value:kb.record.create(J.fields[H.tableCode],!1)}))})(l[H.tableCode]):v.tableCode&&(g=0==a[v.tableCode].value.length?
0:g<a[v.tableCode].value.length?a[v.tableCode].value.length:g);d.push({external:H,internal:v})})(f.external[n.value.external.value],f.internal[n.value.internal.value])}),r.criteria.value.each((n,t)=>{t=f.external[n.value.external.value];var H=n.value.operator.value;n=f.internal[n.value.internal.value];t.tableCode?(t.tableCode in l&&delete l[t.tableCode],n.tableCode&&(C=C<a[n.tableCode].value.length?a[n.tableCode].value.length:C)):n.tableCode&&(g=0==a[n.tableCode].value.length?0:g<a[n.tableCode].value.length?
a[n.tableCode].value.length:g);b.push({external:t,operator:H,internal:n})}),kb.filter.query.parse.expand({id:r.app.value,fields:w.origin},r.filter.value).each((n,t)=>{h.push({field:f.external[n.field],operator:n.operator,value:n.value})}),0!=g?(q=x=0,G()):F())})({external:w.parallelize,internal:c.fieldInfos.parallelize})}).catch(w=>{kb.alert(kb.error.parse(w));D()}):F()}).catch(p=>{kb.alert(kb.error.parse(p));D()}):F()})(B[I])};m||kb.loadStart();L(0,()=>{m||kb.loadEnd();N()})});kb.field.load(kb.injector.app.id).then(B=>
{c.app={id:kb.injector.app.id,fields:B.origin};c.fieldInfos=B;try{(e=>{0!=e.length?P(e,k.record,!0).then(m=>A(k)).catch(()=>A(k)):A(k)})(kb.plugin.upsert.reduce((e,m)=>{m.event.value.includes(k.pattern)&&e.push(m);return e},[]))}catch(e){kb.alert(kb.error.parse(e)),A(k)}}).catch(B=>A(k))}else A(k)}));
kb.constants=kb.extend({submit:{message:{cancel:{process:{en:"The process action was canceled.",ja:"\u30d7\u30ed\u30bb\u30b9\u30a2\u30af\u30b7\u30e7\u30f3\u304c\u30ad\u30e3\u30f3\u30bb\u30eb\u3055\u308c\u307e\u3057\u305f\u3002",zh:"\u8fdb\u7a0b\u64cd\u4f5c\u5df2\u88ab\u53d6\u6d88\u3002","zh-TW":"\u7a0b\u5e8f\u64cd\u4f5c\u5df2\u88ab\u53d6\u6d88\u3002"},submit:{en:"The submit was canceled.",ja:"\u4fdd\u5b58\u304c\u30ad\u30e3\u30f3\u30bb\u30eb\u3055\u308c\u307e\u3057\u305f\u3002",zh:"\u4fdd\u5b58\u5df2\u88ab\u53d6\u6d88\u3002",
"zh-TW":"\u63d0\u4ea4\u5df2\u88ab\u53d6\u6d88\u3002"}},duplicate:{en:"A similar record already exists. Would you like to proceed with the registration anyway?",ja:"\u985e\u4f3c\u30ec\u30b3\u30fc\u30c9\u304c\u65e2\u306b\u767b\u9332\u3055\u308c\u3066\u3044\u307e\u3059\u304c\u3001\u3053\u306e\u307e\u307e\u767b\u9332\u3057\u3066\u3082\u5b9c\u3057\u3044\u3067\u3059\u304b\uff1f",zh:"\u5df2\u7ecf\u6709\u7c7b\u4f3c\u7684\u8bb0\u5f55\u5b58\u5728\u4e86\uff0c\u60a8\u8fd8\u8981\u7ee7\u7eed\u6ce8\u518c\u5417\uff1f",
"zh-TW":"\u5df2\u6709\u985e\u4f3c\u7684\u8a18\u9304\u5b58\u5728\uff0c\u60a8\u9084\u8981\u7e7c\u7e8c\u8a3b\u518a\u55ce\uff1f"}}}},kb.constants);
