/*
* FileName "plugin.js"
* Version: 1.0.0
* Copyright (c) 2023 Pandafirm LLC
* Distributed under the terms of the GNU Lesser General Public License.
* https://opensource.org/licenses/LGPL-2.1
*/
'use strict';kb.event.on("kb.action.call",n=>new Promise((B,R)=>{if(kb.plugin.action.length!=0){var d={},P=(C,f,m)=>new Promise((O,z)=>{var K=JSON.stringify(kb.record.simplify({fields:d.fieldInfos.origin},f)),M=(E,F)=>{var y=()=>{E++;E<C.length?M(E,F):F()};(a=>{var p=kb.filter.scan(d.app,f,a.condition.value);p?kb.filter.auth(a.user.value,a.organization.value,a.group.value).then(x=>{if(x){var L={clear:c=>{try{a.clear.value.map(b=>b.value).each((b,h)=>{b.table.value in d.fieldInfos.tables&&(f[b.table.value].value=
f[b.table.value].value.filter(e=>!p[b.table.value].value.includes(e)),p[b.table.value].value=[])}),c()}catch(b){kb.alert(kb.error.parse(b)),z()}},fill:c=>{try{a.fill.value.map(b=>b.value).each((b,h)=>{b.table.value in d.fieldInfos.tables&&(e=>{e=kb.isNumeric(e)?parseInt(e)-p[b.table.value].value.length:0;e>0&&Array(e).fill().map(()=>kb.record.create(d.fieldInfos.origin[b.table.value],!1)).each((k,l)=>{f[b.table.value]==p[b.table.value]?f[b.table.value].value.push({value:k}):(f[b.table.value].value.push({value:k}),
p[b.table.value].value.push({value:k}))})})(kb.formula.calculate({field:{value:Object.values(d.fieldInfos.parallelize).first().code},formula:b.range},p,p,f,d.fieldInfos.parallelize))}),c()}catch(b){kb.alert(kb.error.parse(b)),z()}},formula:c=>{try{a.formula.value.map(b=>b.value).each((b,h)=>{b.field.value in d.fieldInfos.parallelize&&(e=>{e.tableCode?p[e.tableCode].value.each((k,l)=>{k.value[e.code].value=kb.formula.calculate(b,k.value,p,f,d.fieldInfos.parallelize);e.lookup&&(k.value[e.code].lookup=
!0)}):(p[e.code].value=kb.formula.calculate(b,p,p,f,d.fieldInfos.parallelize),e.lookup&&(p[e.code].lookup=!0))})(d.fieldInfos.parallelize[b.field.value])}),c()}catch(b){kb.alert(kb.error.parse(b)),z()}},lookup:c=>{try{a.lookupApp.value?kb.field.load(a.lookupApp.value).then(b=>{(h=>{var e=[],k=[],l=(v,A)=>{var D=(g,r)=>g.lookup?kb.extend({lookup:!0,type:g.type},r):kb.extend({type:g.type},r);kb.record.api.get(a.lookupApp.value,A.query,A.sort).then(g=>{g.length!=0?(r=>{a.lookupLimited.value.includes("limited")||
g.length==1?r(g.first()):d.picker.show({app:a.lookupApp.value,query:A.query,sort:A.sort,picker:e.reduce((G,w)=>{G[w.external.code]=w.external;return G},{})},G=>r(G))})(r=>{e.each((G,w)=>{if(a.lookupOverwrite.value.includes("overwrite")||kb.field.isEmpty(A.record[G.internal.code].value))A.record[G.internal.code]=D(G.internal,r[G.external.code])});v++;v<k.length?l(v,k[v]):(m.latest.action[a.sIndex.value].lookup=H(),c())}):(a.lookupReset.value.includes("reset")&&e.each((r,G)=>{A.record[r.internal.code]=
D(r.internal,kb.record.create({fields:{empty:r.internal}}).empty)}),v++,v<k.length?l(v,k[v]):(m.latest.action[a.sIndex.value].lookup=H(),c()))}).catch(g=>{kb.alert(kb.error.parse(g));z()})},H=()=>(v=>JSON.stringify(k.reduce((A,D)=>{A.push(D.query);A.push(kb.record.simplify({fields:v},D.record));return A},[])))(e.reduce((v,A)=>{v[A.internal.code]=A.internal;return v},{}));a.lookupCriteria.value.some(v=>!(v.value.external.value in h.external&&v.value.internal.value in h.internal))?(kb.alert("No field to lookup was found"),
z()):a.lookupMapping.value.some(v=>!(v.value.external.value in h.external&&v.value.internal.value in h.internal))?(kb.alert("No field to lookup was found"),z()):(e=a.lookupMapping.value.map(v=>({external:h.external[v.value.external.value],internal:h.internal[v.value.internal.value]})),k=(v=>v.map(A=>({query:a.lookupCriteria.value.reduce((D,g)=>{var r=h.external[g.value.external.value],G=g.value.operator.value;g=h.internal[g.value.internal.value];var w=g.tableCode?A.value:f;a.lookupIgnore.value.includes("ignore")&&
kb.field.isEmpty(w[g.code].value)||D.push(kb.filter.query.create(r,G,w[g.code]));return D},kb.filter.query.parse.expand({id:a.lookupApp.value,fields:b.origin},a.lookupFilter.value).map(D=>D.field+" "+D.operator+" "+D.value)).join(" and "),sort:(a.lookupSort.value.length!=0?a.lookupSort.value.map(D=>D.value.field.value+" "+D.value.order.value):["$id asc"]).join(","),record:A.value})))((v=>v?p[v].value:[{value:f}])(Array.from(new Set(e.map(v=>v.internal.tableCode))).first())),k.length!=0?m.latest.action[a.sIndex.value].lookup&&
m.latest.action[a.sIndex.value].lookup==H()?c():l(0,k.first()):c())})({external:b.origin,internal:d.fieldInfos.parallelize})}).catch(b=>{kb.alert(kb.error.parse(b));z()}):c()}catch(b){kb.alert(kb.error.parse(b)),z()}},user:c=>{try{if(a.userSource.value){var b=[],h=[],e=(l,H)=>{(A=>{b.each((D,g)=>{if(D.isCustom)switch(D.field.type){case "USER_SELECT":D.value=A.reduce((r,G)=>{"customItemValues"in G&&(w=>{w.length!=0&&(t=>{(q=>{q.length!=0&&(r.some(N=>N.code==q.first().info.code)||r.push({code:q.first().info.code,
name:q.first().info.name}))})(kb.roleSet.user.filter(q=>q.info.id==t))})(w.first().value)})(G.customItemValues.filter(w=>w.code==D.item));return Array.from(new Set(r)).filter(w=>w)},[]);break;default:D.value=A.reduce((r,G)=>{"customItemValues"in G&&(w=>{w.length!=0&&r.push(w.first().value)})(G.customItemValues.filter(w=>w.code==D.item));return Array.from(new Set(r)).filter(w=>w)},[]).join(",")}else switch(D.item){case "groups":case "organizations":D.value=A.map(r=>r.code);break;case "primaryOrganization":D.value=
A.reduce((r,G)=>{D.item in G&&(w=>{w.length!=0&&(r.some(t=>t.code==w.first().info.code)||r.push({code:w.first().info.code,name:w.first().info.name}))})(kb.roleSet.organization.filter(w=>w.info.id==G[D.item]));return r},[]);break;default:D.value=A.reduce((r,G)=>{D.item in G&&r.push(G[D.item]);return Array.from(new Set(r)).filter(w=>w)},[]).join(",")}})})(H[a.userSource.value].value.reduce((A,D)=>{(g=>{g.length!=0&&A.push(g.first().info)})(kb.roleSet.user.filter(g=>g.info.code==D.code));return A},[]));
var v=(A,D)=>{((g,r)=>{var G=(w,t,q)=>{kb.api(kb.api.url("/api/user/affiliations"),"GET",{code:g.value[w]}).then(N=>{switch(g.item){case "groups":N.groups&&(t=N.groups.reduce((u,I)=>{u.some(J=>J.code==I.code)||u.push({code:I.code,name:I.name});return u},t),w++,w<g.value.length?G(w,t,q):q(t));break;case "organizations":N.organizations&&(t=N.organizations.reduce((u,I)=>{u.some(J=>J.code==I.code)||u.push({code:I.code,name:I.name});return u},t),w++,w<g.value.length?G(w,t,q):q(t))}}).catch(N=>kb.alert(kb.error.parse(N)))};
a.userOverwrite.value.includes("overwrite")||kb.field.isEmpty(H[g.field.code].value)||r();switch(g.item){case "groups":case "organizations":g.value.length!=0?G(0,[],w=>{H[g.field.code].value=w;r()}):(H[g.field.code].value=g.value,r());break;default:H[g.field.code].value=g.value,r()}})(b[A],()=>{A++;A<b.length?v(A,D):D()})};v(0,()=>{l++;l<h.length?e(l,h[l]):(m.latest.action[a.sIndex.value].user=k(),c())})},k=()=>(l=>JSON.stringify(h.map(H=>kb.record.simplify({fields:l},H))))(b.reduce((l,H)=>{l[H.field.code]=
H.field;return l},(l=>{var H={};H[l]=d.fieldInfos.parallelize[l];return H})(a.userSource.value)));a.userCustomItem.value.some(l=>!(l.value.field.value in d.fieldInfos.parallelize))?(kb.alert("No field to user informations was found"),z()):a.userMapping.value.some(l=>!(l.value.field.value in d.fieldInfos.parallelize))?(kb.alert("No field to user informations was found"),z()):(a.userCustomItem.value.each((l,H)=>{b.push({isCustom:!0,item:l.value.item.value,field:d.fieldInfos.parallelize[l.value.field.value],
value:[]})}),a.userMapping.value.each((l,H)=>{b.push({isCustom:!1,item:l.value.item.value,field:d.fieldInfos.parallelize[l.value.field.value],value:[]})}),a.userPrimaryOrganization.value&&a.userPrimaryOrganization.value in d.fieldInfos.parallelize&&b.push({isCustom:!1,item:"primaryOrganization",field:d.fieldInfos.parallelize[a.userPrimaryOrganization.value],value:[]}),a.userOrganization.value&&a.userOrganization.value in d.fieldInfos.parallelize&&b.push({isCustom:!1,item:"organizations",field:d.fieldInfos.parallelize[a.userOrganization.value],
value:[]}),a.userGroup.value&&a.userGroup.value in d.fieldInfos.parallelize&&b.push({isCustom:!1,item:"groups",field:d.fieldInfos.parallelize[a.userGroup.value],value:[]}),h=(l=>l?p[l].value:[{value:f}])(d.fieldInfos.parallelize[a.userSource.value].tableCode).map(l=>l.value),h.length!=0?m.latest.action[a.sIndex.value].user&&m.latest.action[a.sIndex.value].user==k()?c():b.length!=0?e(0,h.first()):c():c())}else c()}catch(l){kb.alert(kb.error.parse(l)),z()}}};L.clear(()=>{L.fill(()=>{L.formula(()=>{L.lookup(()=>
{L.user(()=>{y()})})})})})}else y()}).catch(x=>{kb.alert(kb.error.parse(x));z()}):y()})((a=>{m.latest?m.latest.action||(m.latest.action={}):m.latest={action:{}};a.sIndex.value in m.latest.action||(m.latest.action[a.sIndex.value]={lookup:"[]",user:"[]"});return a})(C[E]))};M(0,()=>{O({record:f,performed:K!=JSON.stringify(kb.record.simplify({fields:d.fieldInfos.origin},f))})})});kb.field.load(kb.injector.app.id).then(C=>{d.app={id:kb.injector.app.id,fields:C.origin};d.fieldInfos=C;d.picker=new KintoneBoosterRecordPicker("record");
try{(f=>{if(f.length!=0){var m=(()=>{var O=f;n.pattern=="change"&&(O=f.filter(z=>(K=>"fields"in n?!K.first()||n.fields.some(M=>K.includes(M)):!K.first()||K.includes(n.field))(z.triggers.value.map(K=>K.value.field.value))));return O})();m.length!=0?P(m,n.record,n.container).then(O=>{n.stopPropagation&&(d.latest={record:JSON.stringify(kb.record.simplify({fields:C.origin},n.record)),time:(new Date).getTime()});n.performed=O.performed;B(n)}).catch(()=>B(n)):B(n)}else B(n)})(kb.plugin.action.reduce((f,
m)=>{m.event.value.includes(n.pattern)&&f.push(m);return f},[]))}catch(f){kb.alert(kb.error.parse(f)),B(n)}}).catch(C=>B(n))}else B(n)}));
kb.event.on("kb.mail.call",n=>new Promise((B,R)=>{if(kb.plugin.mail.length!=0){var d={},P=(C,f,m=!1)=>new Promise((O,z)=>{var K="",M=(E,F)=>{var y=()=>{E++;E<C.length?M(E,F):F()};(a=>{var p=kb.filter.scan(d.app,f,a.condition.value);p?kb.filter.auth(a.user.value,a.organization.value,a.group.value).then(x=>{if(x){var L=(c,b,h)=>{a.format.value=="HTML"&&(c=c.replace(/\r/g,"").replace(/\n/g,"<br>"));for(var e in b){var k=b[e].value;e in d.fieldInfos.parallelize&&(a.format.value=="HTML"&&d.fieldInfos.parallelize[e].type==
"MULTI_LINE_TEXT"&&(k=k.replace(/\r/g,"").replace(/\n/g,"<br>")),c=c.replace(new RegExp("%"+e+"%","g"),kb.field.stringify(d.fieldInfos.parallelize[e],k," / ",!0)))}for(e in h)k=h[e].value,e in d.fieldInfos.parallelize&&(a.format.value=="HTML"&&d.fieldInfos.parallelize[e].type=="MULTI_LINE_TEXT"&&(k=k.replace(/\r/g,"").replace(/\n/g,"<br>")),c=c.replace(new RegExp("%"+e+"%","g"),kb.field.stringify(d.fieldInfos.parallelize[e],k," / ",!0)));return c};(c=>{var b=h=>{(e=>{var k=(l,H)=>{e.attachment.length!=
0?kb.file.download(e.attachment[l],!0).then(v=>{kb.field.blobToBase64(v,A=>{e.attachment[l].data=A;l++;l<e.attachment.length?k(l,H):H()})}).catch(v=>{kb.alert(kb.error.parse(v));z()}):H()};k(0,()=>{kb.encrypt(JSON.stringify(e.data),K).then(l=>{var H=fetch,v="https://api.kintone-booster.com/mail/"+kb.operator.language,A=JSON,D=A.stringify;e.data=l.data;e.iv=l.iv;e.tag=l.tag;H(v,{method:"POST",headers:{"X-Requested-With":"XMLHttpRequest"},body:D.call(A,e)}).then(g=>{g.json().then(r=>{switch(g.status){case 200:h++;
h<c.length?b(h):y();break;default:kb.alert(kb.error.parse(r)),z()}})}).catch(g=>{kb.alert(kb.error.parse(g));z()})}).catch(l=>{z()})})})(c[h])};c.length!=0?b(0):y()})((()=>{var c=[];(d.fieldInfos.parallelize[a.to.value].tableCode?p[d.fieldInfos.parallelize[a.to.value].tableCode].value:[{value:p}]).each((b,h)=>{if(b.value[a.to.value].value){h=c.push;var e={mail:a.mail.value,sender:a.sender.value,host:a.host.value,port:a.port.value,author:a.author.value,pwd:a.pwd.value,secure:a.secure.value,to:b.value[a.to.value].value,
cc:L(a.cc.value,p,d.fieldInfos.parallelize[a.to.value].tableCode?b.value:{}),bcc:L(a.bcc.value,p,d.fieldInfos.parallelize[a.to.value].tableCode?b.value:{}),html:a.format.value=="HTML"},k=L(a.subject.value,p,d.fieldInfos.parallelize[a.to.value].tableCode?b.value:{}),l=L(a.body.value,p,d.fieldInfos.parallelize[a.to.value].tableCode?b.value:{}),H=[];a.attachment.value&&a.attachment.value in d.fieldInfos.parallelize&&(H=(d.fieldInfos.parallelize[a.attachment.value].tableCode?b.value:p)[a.attachment.value].value);
h.call(c,{data:e,subject:k,body:l,attachment:H})}});return c})())}else y()}).catch(x=>{kb.alert(kb.error.parse(x));z()}):y()})(C[E])};fetch("https://api.kintone-booster.com/mail/"+kb.operator.language,{method:"GET",headers:{"X-Requested-With":"XMLHttpRequest"}}).then(E=>{E.json().then(F=>{switch(E.status){case 200:K=F.passphrase;m||kb.loadStart();M(0,()=>{m||kb.loadEnd();O()});break;default:kb.alert(kb.error.parse(F)),z()}})}).catch(E=>{kb.alert(kb.error.parse(E));z()})});kb.field.load(kb.injector.app.id).then(C=>
{d.app={id:kb.injector.app.id,fields:C.origin};d.fieldInfos=C;try{(f=>{f.length!=0?P(f,n.record,!0).then(m=>B(n)).catch(()=>B(n)):B(n)})(kb.plugin.mail.reduce((f,m)=>{m.event.value.includes(n.pattern)&&f.push(m);return f},[]))}catch(f){kb.alert(kb.error.parse(f)),B(n)}}).catch(C=>B(n))}else B(n)}));
kb.event.on("kb.omail.call",n=>new Promise((B,R)=>{if(kb.plugin.omail.length!=0){var d={},P=(C,f,m=!1)=>new Promise((O,z)=>{var K="",M=(E,F)=>{var y=()=>{E++;E<C.length?M(E,F):F()};(a=>{var p=kb.filter.scan(d.app,f,a.condition.value);p?kb.filter.auth(a.user.value,a.organization.value,a.group.value).then(x=>{if(x){var L=(c,b,h)=>{a.format.value=="HTML"&&(c=c.replace(/\r/g,"").replace(/\n/g,"<br>"));for(var e in b){var k=b[e].value;e in d.fieldInfos.parallelize&&(a.format.value=="HTML"&&d.fieldInfos.parallelize[e].type==
"MULTI_LINE_TEXT"&&(k=k.replace(/\r/g,"").replace(/\n/g,"<br>")),c=c.replace(new RegExp("%"+e+"%","g"),kb.field.stringify(d.fieldInfos.parallelize[e],k," / ",!0)))}for(e in h)k=h[e].value,e in d.fieldInfos.parallelize&&(a.format.value=="HTML"&&d.fieldInfos.parallelize[e].type=="MULTI_LINE_TEXT"&&(k=k.replace(/\r/g,"").replace(/\n/g,"<br>")),c=c.replace(new RegExp("%"+e+"%","g"),kb.field.stringify(d.fieldInfos.parallelize[e],k," / ",!0)));return c};(c=>{var b=h=>{(e=>{var k=(l,H)=>{e.attachment.length!=
0?kb.file.download(e.attachment[l],!0).then(v=>{kb.field.blobToBase64(v,A=>{e.attachment[l].data=A;l++;l<e.attachment.length?k(l,H):H()})}).catch(v=>{kb.alert(kb.error.parse(v));z()}):H()};k(0,()=>{kb.encrypt(JSON.stringify(e.data),K).then(l=>{var H=fetch,v="https://api.kintone-booster.com/mail/oauth/"+kb.operator.language,A=JSON,D=A.stringify;e.data=l.data;e.iv=l.iv;e.tag=l.tag;H(v,{method:"POST",headers:{"X-Requested-With":"XMLHttpRequest"},body:D.call(A,e)}).then(g=>{g.json().then(r=>{switch(g.status){case 200:h++;
h<c.length?b(h):y();break;default:kb.alert(kb.error.parse(r)),z()}})}).catch(g=>{kb.alert(kb.error.parse(g));z()})}).catch(l=>{z()})})})(c[h])};c.length!=0?b(0):y()})((()=>{var c=[];(d.fieldInfos.parallelize[a.to.value].tableCode?p[d.fieldInfos.parallelize[a.to.value].tableCode].value:[{value:p}]).each((b,h)=>{b.value[a.to.value].value&&c.push({data:{client_id:a.client_id.value,client_secret:a.client_secret.value,author:a.author.value,sender:a.sender.value,subdomain:kb.operator.domain,provider:(e=>
{e="";switch(a.provider.value){case "GMail":e="google";break;case "Exchange Online":e="microsoft"}return e})(a.provider.value),to:b.value[a.to.value].value,cc:L(a.cc.value,p,d.fieldInfos.parallelize[a.to.value].tableCode?b.value:{}),bcc:L(a.bcc.value,p,d.fieldInfos.parallelize[a.to.value].tableCode?b.value:{}),html:a.format.value=="HTML"},subject:L(a.subject.value,p,d.fieldInfos.parallelize[a.to.value].tableCode?b.value:{}),body:L(a.body.value,p,d.fieldInfos.parallelize[a.to.value].tableCode?b.value:
{}),attachment:(()=>{var e=[];a.attachment.value&&a.attachment.value in d.fieldInfos.parallelize&&(e=(d.fieldInfos.parallelize[a.attachment.value].tableCode?b.value:p)[a.attachment.value].value);return e})()})});return c})())}else y()}).catch(x=>{kb.alert(kb.error.parse(x));z()}):y()})(C[E])};fetch("https://api.kintone-booster.com/mail/oauth/"+kb.operator.language,{method:"GET",headers:{"X-Requested-With":"XMLHttpRequest"}}).then(E=>{E.json().then(F=>{switch(E.status){case 200:K=F.passphrase;m||kb.loadStart();
M(0,()=>{m||kb.loadEnd();O()});break;default:kb.alert(kb.error.parse(F)),z()}})}).catch(E=>{kb.alert(kb.error.parse(E));z()})});kb.field.load(kb.injector.app.id).then(C=>{d.app={id:kb.injector.app.id,fields:C.origin};d.fieldInfos=C;try{(f=>{f.length!=0?P(f,n.record,!0).then(m=>B(n)).catch(()=>B(n)):B(n)})(kb.plugin.omail.reduce((f,m)=>{m.event.value.includes(n.pattern)&&f.push(m);return f},[]))}catch(f){kb.alert(kb.error.parse(f)),B(n)}}).catch(C=>B(n))}else B(n)}));
kb.event.on("kb.style.call",n=>new Promise((B,R)=>{if(kb.plugin.style.length!=0){var d={},P=(C,f,m)=>new Promise((O,z)=>{var K={},M=(E,F)=>{(y=>{var a=kb.filter.scan(d.app,f,y.condition.value);a?kb.filter.auth(y.user.value,y.organization.value,y.group.value).then(p=>{p&&(y.color.value.map(x=>x.value).each((x,L)=>{x.field.value in d.fieldInfos.parallelize&&(c=>{c.tableCode?c.tableCode in a&&a[c.tableCode].value.each((b,h)=>{c.code in b.value&&(b.value[c.code].backcolor=x.backcolor.value,b.value[c.code].forecolor=
x.forecolor.value)}):c.code in a&&(a[c.code].backcolor=x.backcolor.value,a[c.code].forecolor=x.forecolor.value)})(d.fieldInfos.parallelize[x.field.value])}),y.editable.value.map(x=>x.value).each((x,L)=>{x.field.value in d.fieldInfos.parallelize&&(c=>{d.fieldInfos.disables.includes(c.code)||(c.tableCode?c.tableCode in a&&(a[c.tableCode].value.each((b,h)=>{c.code in b.value&&(b.value[c.code].disabled=x.state.value=="disable")}),K[c.code]=f[c.tableCode].value.map(b=>b.value[c.code].disabled?"disabled":
"")):c.code in a&&(a[c.code].disabled=x.state.value=="disable",K[c.code]=f[c.code].disabled?"disabled":""))})(d.fieldInfos.parallelize[x.field.value])}),y.display.value.map(x=>x.value).each((x,L)=>{x.field.value in d.fieldInfos.groups?d.fieldInfos.groups[x.field.value].fields.map(c=>c.code).each((c,b)=>{c in d.fieldInfos.parallelize&&c in a&&(a[c].hidden=x.state.value=="hide")}):x.field.value in d.fieldInfos.tables?x.field.value in a&&(a[x.field.value].hidden=x.state.value=="hide"):(c=>{c.tableCode?
c.tableCode in a&&a[c.tableCode].value.each((b,h)=>{c.code in b.value&&(b.value[c.code].hidden=x.state.value=="hide")}):c.code in a&&(a[c.code].hidden=x.state.value=="hide")})(d.fieldInfos.parallelize[x.field.value])}));E++;E<C.length?M(E,F):F()}).catch(p=>{kb.alert(kb.error.parse(p));z()}):(E++,E<C.length?M(E,F):F())})(C[E])};M(0,()=>{m.latest?m.latest.style||(m.latest.style="{}"):m.latest={style:"{}"};var E=JSON.stringify(K),F=E!="{}"?m.latest.style!=E:!1;F&&(m.latest.style=E);O({performed:F})})});
kb.field.load(kb.injector.app.id).then(C=>{d.app={id:kb.injector.app.id,fields:C.origin};d.fieldInfos=C;try{(f=>{f.length!=0?P(f,n.record,n.container).then(m=>{n.performed=m.performed;B(n)}).catch(()=>B(n)):B(n)})(kb.plugin.style.reduce((f,m)=>{m.page.value.includes(n.pattern)&&f.push(m);return f},[]))}catch(f){kb.alert(kb.error.parse(f)),B(n)}}).catch(C=>B(n))}else B(n)}));
kb.event.on("kb.submit.call",n=>new Promise((B,R)=>{if(kb.plugin.submit.length!=0){var d={},P=(C,f,m=!1,O={})=>new Promise((z,K)=>{var M=[],E=(F,y)=>{var a=()=>{F++;F<C.length?E(F,y):y()};(p=>{kb.filter.scan(d.app,f,p.condition.value)?kb.filter.auth(p.user.value,p.organization.value,p.group.value).then(x=>{if(x){var L={duplicate:c=>{try{p.duplicateCriteria.value.some(b=>!(b.value.external.value in d.fieldInfos.parallelize&&b.value.internal.value in d.fieldInfos.parallelize))?(kb.alert("No field to lookup was found"),
K()):(b=>{b&&M.push(b);c()})(p.duplicateCriteria.value.reduce((b,h)=>{b.push(kb.filter.query.create(d.fieldInfos.parallelize[h.value.external.value],h.value.operator.value,f[d.fieldInfos.parallelize[h.value.internal.value].code]));return b},[]).join(" and "))}catch(b){kb.alert(kb.error.parse(b)),K()}},error:c=>{try{if(p.errorMessage.value||p.errorField.value.length!=0){var b=kb.filter.scan(d.app,f,p.errorFilter.value);b?(p.errorField.value.each((h,e)=>{h.value.field.value in d.fieldInfos.parallelize&&
(k=>{k.tableCode?b[k.tableCode].value.each((l,H)=>{l.value[h.value.field.value].error=h.value.message.value}):f[h.value.field.value].error=h.value.message.value})(d.fieldInfos.parallelize[h.value.field.value])}),m||kb.loadEnd(),z({error:!0,message:p.errorMessage.value})):c()}else c()}catch(h){kb.alert(kb.error.parse(h)),K()}},numbering:c=>{try{if(p.numberingField.value in d.fieldInfos.parallelize)if(f[p.numberingField.value].value)c();else{var b="",h=p.numberingGroup.value.reduce((e,k)=>{if(k.value.field.value in
d.fieldInfos.parallelize)switch(b+=f[k.value.field.value].value,d.fieldInfos.parallelize[k.value.field.value].type){case "DROP_DOWN":case "RADIO_BUTTON":e.push(k.value.field.value+' in ("'+f[k.value.field.value].value+'")');break;default:e.push(k.value.field.value+'="'+f[k.value.field.value].value+'"')}return e},"$id"in f?['$id!="'+f.$id.value+'"']:[]);b in O?(O[b]++,f[p.numberingField.value].value=b+O[b].toString().lpad("0",parseInt(p.numberingDigits.value)),c()):kb.api(kb.api.url("/api/records"),
"GET",{app:d.app.id,query:h.join(" and ")+" order by "+p.numberingField.value+" desc limit 1 offset 0"}).then(e=>{e=e.records;var k=0;e.length!=0&&(k=parseInt((e.first()[p.numberingField.value].value||" ").replace(/[ ]+/g,"").replace(new RegExp("^"+b,"g"),"")),kb.isNumeric(k)||(k=0));k++;e=k;O[b]=e;f[p.numberingField.value].value=b+e.toString().lpad("0",parseInt(p.numberingDigits.value));c()}).catch(e=>{kb.alert(kb.error.parse(e));K()})}else c()}catch(e){kb.alert(kb.error.parse(e)),K()}},prompt:c=>
{try{(b=>{b.length!=0?(h=>{b.each((e,k)=>{h.append(kb.field.activate(kb.field.create(e).css({width:"100%"}),d.app,!1))});m||kb.loadEnd();(new KintoneBoosterPopupform(h,600,"full",{ok:()=>{var e=kb.record.get(h,d.app,!0);b.each((k,l)=>{f[k.code].value=e.record[k.code].value});m||kb.loadStart();c()},cancel:()=>{m||kb.loadStart();c()}})).show()})(kb.create("div").addClass("kb-scope").attr("form-id","form_"+d.app.id)):c()})(p.promptField.value.reduce((b,h)=>{h.value.field.value in d.fieldInfos.parallelize&&
(p.promptOverwrite.value.includes("overwrite")?b.push(d.fieldInfos.parallelize[h.value.field.value]):kb.field.isEmpty(f[h.value.field.value].value)&&b.push(d.fieldInfos.parallelize[h.value.field.value]));return b},[]))}catch(b){kb.alert(kb.error.parse(b)),K()}},verify:c=>{try{(b=>{b.length!=0?(h=>{b.each((e,k)=>{h.append(kb.field.activate(kb.field.create(e).addClass("kb-readonly").css({width:"100%"}),d.app,!1))});kb.record.set(h,d.app,f);m||kb.loadEnd();(new KintoneBoosterPopupform(h,600,"full",{ok:()=>
{m||kb.loadStart();c()},cancel:()=>{m||kb.loadEnd();z({error:!0})}})).show()})(kb.create("div").addClass("kb-scope kb-verify").attr("form-id","form_"+d.app.id).append(kb.create("p").html(p.verifyMessage.value))):c()})(p.verifyField.value.reduce((b,h)=>{h.value.field.value in d.fieldInfos.parallelize&&b.push(d.fieldInfos.parallelize[h.value.field.value]);return b},[]))}catch(b){kb.alert(kb.error.parse(b)),K()}}};L.numbering(()=>{L.prompt(()=>{L.verify(()=>{L.error(()=>{L.duplicate(()=>{a()})})})})})}else a()}).catch(x=>
{kb.alert(kb.error.parse(x));K()}):a()})(C[F])};m||kb.loadStart();E(0,()=>{m||kb.loadEnd();M.length!=0?kb.api(kb.api.url("/api/records"),"GET",{app:d.app.id,query:((F,y)=>(y?"$id!="+y+" and ("+F+")":F)+" order by $id asc limit 5 offset 0")(M.map(F=>"("+F+")").join(" or "),"$id"in f?f.$id.value:"")}).then(F=>{F.records.length!=0?kb.confirm(kb.create("div").append(kb.create("p").css({margin:"0"}).html(kb.constants.submit.message.duplicate[kb.operator.language])),y=>{z({error:y})},!0):z({error:!1})}).catch(F=>
{kb.alert(kb.error.parse(F),()=>{z({error:!1})})}):z({error:!1})})});kb.field.load(kb.injector.app.id).then(C=>{d.app={id:kb.injector.app.id,fields:C.origin};d.fieldInfos=C;try{(f=>{f.length!=0?P(f,n.record,!0,n.numbering).then(m=>{m.error?(n.error=!0,m.message?kb.alert(m.message,()=>B(n)):B(n)):B(n)}).catch(()=>{n.error=!0;B(n)}):B(n)})(kb.plugin.submit.reduce((f,m)=>{m.event.value.includes(n.pattern)&&f.push(m);return f},[]))}catch(f){kb.alert(kb.error.parse(f)),B(n)}}).catch(C=>B(n))}else B(n)}));
kb.event.on("kb.upsert.call",n=>new Promise((B,R)=>{if(kb.plugin.upsert.length!=0){var d={},P=(C,f,m=!1)=>new Promise((O,z)=>{var K=(M,E)=>{var F=()=>{M++;M<C.length?K(M,E):E()};(y=>{var a=kb.filter.scan(d.app,f,y.condition.value);a?kb.filter.auth(y.user.value,y.organization.value,y.group.value).then(p=>{p?kb.field.load(y.app.value).then(x=>{var L={id:y.app.value,fields:x.origin};(c=>{var b=[],h=[],e=[],k={},l=1,H=1,v=0,A=0,D=()=>{var g=[],r={field:(t,q)=>{q=t.tableCode?a[t.tableCode].value.length>
q?a[t.tableCode].value[q].value[t.code]:kb.record.create({fields:{empty:mapping.internal}}).empty:a[t.code];return kb.extend({type:t.type},q)},record:t=>{H.each(q=>{var N=(u=>{var I=kb.filter.scan(L,t,u.query);if(!I&&y.pattern.value=="upsert"){for(var J in u.rows)kb.filter.result[J].value.length==0&&(t[J].value.push({value:kb.extend({},u.rows[J])}),kb.filter.result[J]={value:[t[J].value.last()]});I=kb.filter.result}return I})((()=>{var u={rows:{},query:[]};A=q;b.each((I,J)=>{I.external.tableCode&&
(I.external.tableCode in u.rows||(u.rows[I.external.tableCode]=kb.record.create(L.fields[I.external.tableCode],!1)),u.rows[I.external.tableCode][I.external.code]=G(I.external,r.field(I.internal,A)),u.query.push(kb.filter.query.create(I.external,I.operator,r.field(I.internal,A))))});h.each((I,J)=>{I.field.tableCode&&u.query.push(I.field.code+" "+I.operator+" "+I.value)});u.query=u.query.join(" and ");return u})());N&&e.each((u,I)=>{u.external.tableCode?u.external.tableCode in k?(t[u.external.tableCode]=
{value:k[u.external.tableCode]},k[u.external.tableCode].each((J,Q)=>{J.value[u.external.code]=G(u.external,r.field(u.internal,Q));u.external.type=="FILE"&&J.value[u.external.code].value&&Array.prototype.push.apply(g,J.value[u.external.code].value)})):N[u.external.tableCode].value.each((J,Q)=>{J.value[u.external.code]=G(u.external,r.field(u.internal,A));u.external.type=="FILE"&&J.value[u.external.code].value&&Array.prototype.push.apply(g,J.value[u.external.code].value)}):(t[u.external.code]=G(u.external,
r.field(u.internal,v)),u.external.type=="FILE"&&t[u.external.code].value&&Array.prototype.push.apply(g,t[u.external.code].value))})});return t}},G=(t,q)=>{switch(t.type){case "CHECK_BOX":case "FILE":case "GROUP_SELECT":case "MULTI_SELECT":case "ORGANIZATION_SELECT":case "USER_SELECT":Array.isArray(q.value)||(q.value=[q.value])}q.type=t.type;return t.lookup?kb.extend({lookup:!0},q):q},w=t=>{t.each((q,N)=>{y.formula.value.each((u,I)=>{u.value.field.value in c.external&&(J=>{J.tableCode?q[J.tableCode].value.each((Q,
S)=>{Q.value[J.code].value=kb.formula.calculate(u.value,Q.value,q,q,c.external);J.lookup&&(Q.value[J.code].lookup=!0)}):(q[J.code].value=kb.formula.calculate(u.value,q,q,q,c.external),J.lookup&&(q[J.code].lookup=!0))})(c.external[u.value.field.value])})});return t};y.pattern.value=="insert"?(t=>{kb.file.clone(g,!0).then(()=>{kb.record.api.set(y.app.value,{post:t},m).then(q=>{v++;v<l?D():F()}).catch(q=>{kb.alert(kb.error.parse(q));z()})})})(w([r.record(kb.record.create(L))])):kb.record.api.get(y.app.value,
(()=>{var t=[];b.each((q,N)=>{q.external.tableCode||t.push(kb.filter.query.create(q.external,q.operator,r.field(q.internal,v)))});h.each((q,N)=>{q.field.tableCode||t.push(q.field.code+" "+q.operator+" "+q.value)});return t.join(" and ")})()).then(t=>{t=(q=>{var N=[];q.length!=0?N=q.map(u=>r.record(u)):y.pattern.value=="upsert"&&(u=>{N.push(r.record((()=>{var I=kb.record.create(L);u.each((J,Q)=>{J.external.tableCode?I[J.external.tableCode]={value:[]}:I[J.external.code]=G(J.external,r.field(J.internal,
v))});return I})()))})(b.filter(u=>!kb.field.reserved.includes(u.external.type)));return w(N)})(t);kb.file.clone(g,!0).then(()=>{kb.record.api.set(y.app.value,{post:t.filter(q=>!q.$id.value),put:t.reduce((q,N)=>{N.$id.value&&q.push(kb.record.api.transform(N));return q},[])},m).then(q=>{v++;v<l?D():F()}).catch(q=>{kb.alert(kb.error.parse(q));z()})})}).catch(t=>{kb.alert(kb.error.parse(t));z()})};y.mapping.value.some(g=>!(g.value.external.value in c.external&&g.value.internal.value in c.internal))?
(kb.alert("No field to transfer was found"),z()):y.criteria.value.some(g=>!(g.value.external.value in c.external&&g.value.internal.value in c.internal))?(kb.alert("No field to transfer was found"),z()):(y.mapping.value.each((g,r)=>{((G,w)=>{G.tableCode?k[G.tableCode]=(t=>{t=t?t.length:1;w.tableCode&&(t=t<a[w.tableCode].value.length?a[w.tableCode].value.length:t);return Array(t).fill().map(()=>({value:kb.record.create(L.fields[G.tableCode],!1)}))})(k[G.tableCode]):w.tableCode&&(l=a[w.tableCode].value.length==
0?0:l<a[w.tableCode].value.length?a[w.tableCode].value.length:l);e.push({external:G,internal:w})})(c.external[g.value.external.value],c.internal[g.value.internal.value])}),y.criteria.value.each((g,r)=>{r=c.external[g.value.external.value];var G=g.value.operator.value;g=c.internal[g.value.internal.value];r.tableCode?(r.tableCode in k&&delete k[r.tableCode],g.tableCode&&(H=H<a[g.tableCode].value.length?a[g.tableCode].value.length:H)):g.tableCode&&(l=a[g.tableCode].value.length==0?0:l<a[g.tableCode].value.length?
a[g.tableCode].value.length:l);b.push({external:r,operator:G,internal:g})}),kb.filter.query.parse.expand({id:y.app.value,fields:x.origin},y.filter.value).each((g,r)=>{h.push({field:c.external[g.field],operator:g.operator,value:g.value})}),l!=0?(A=v=0,D()):F())})({external:x.parallelize,internal:d.fieldInfos.parallelize})}).catch(x=>{kb.alert(kb.error.parse(x));z()}):F()}).catch(p=>{kb.alert(kb.error.parse(p));z()}):F()})(C[M])};m||kb.loadStart();K(0,()=>{m||kb.loadEnd();O()})});kb.field.load(kb.injector.app.id).then(C=>
{d.app={id:kb.injector.app.id,fields:C.origin};d.fieldInfos=C;try{(f=>{f.length!=0?P(f,n.record,!0).then(m=>B(n)).catch(()=>B(n)):B(n)})(kb.plugin.upsert.reduce((f,m)=>{m.event.value.includes(n.pattern)&&f.push(m);return f},[]))}catch(f){kb.alert(kb.error.parse(f)),B(n)}}).catch(C=>B(n))}else B(n)}));
kb.constants=kb.extend({submit:{message:{cancel:{process:{en:"The process action was canceled.",ja:"\u30d7\u30ed\u30bb\u30b9\u30a2\u30af\u30b7\u30e7\u30f3\u304c\u30ad\u30e3\u30f3\u30bb\u30eb\u3055\u308c\u307e\u3057\u305f\u3002",zh:"\u8fdb\u7a0b\u64cd\u4f5c\u5df2\u88ab\u53d6\u6d88\u3002","zh-TW":"\u7a0b\u5e8f\u64cd\u4f5c\u5df2\u88ab\u53d6\u6d88\u3002"},submit:{en:"The submit was canceled.",ja:"\u4fdd\u5b58\u304c\u30ad\u30e3\u30f3\u30bb\u30eb\u3055\u308c\u307e\u3057\u305f\u3002",zh:"\u4fdd\u5b58\u5df2\u88ab\u53d6\u6d88\u3002",
"zh-TW":"\u63d0\u4ea4\u5df2\u88ab\u53d6\u6d88\u3002"}},duplicate:{en:"A similar record already exists. Would you like to proceed with the registration anyway?",ja:"\u985e\u4f3c\u30ec\u30b3\u30fc\u30c9\u304c\u65e2\u306b\u767b\u9332\u3055\u308c\u3066\u3044\u307e\u3059\u304c\u3001\u3053\u306e\u307e\u307e\u767b\u9332\u3057\u3066\u3082\u5b9c\u3057\u3044\u3067\u3059\u304b\uff1f",zh:"\u5df2\u7ecf\u6709\u7c7b\u4f3c\u7684\u8bb0\u5f55\u5b58\u5728\u4e86\uff0c\u60a8\u8fd8\u8981\u7ee7\u7eed\u6ce8\u518c\u5417\uff1f",
"zh-TW":"\u5df2\u6709\u985e\u4f3c\u7684\u8a18\u9304\u5b58\u5728\uff0c\u60a8\u9084\u8981\u7e7c\u7e8c\u8a3b\u518a\u55ce\uff1f"}}}},kb.constants);