/*
* FileName "plugin.js"
* Version: 1.0.0
* Copyright (c) 2023 Pandafirm LLC
* Distributed under the terms of the GNU Lesser General Public License.
* https://opensource.org/licenses/LGPL-2.1
*/
'use strict';kb.event.on("kb.action.call",g=>new Promise((y,R)=>{if(Array.isArray(kb.plugin.action)&&0!=kb.plugin.action.length){var c={},P=(A,e,h)=>new Promise((N,B)=>{var K=JSON.stringify(kb.record.simplify({fields:c.fieldInfos.origin},e)),M=(D,E)=>{var q=()=>{D++;D<A.length?M(D,E):E()};(a=>{var m=kb.filter.scan(c.app,e,a.condition.value);m?kb.filter.auth(a.user.value,a.organization.value,a.group.value).then(w=>{if(w){var L={clear:d=>{try{a.clear.value.map(b=>b.value).each((b,l)=>{b.table.value in c.fieldInfos.tables&&
(e[b.table.value].value=e[b.table.value].value.filter(f=>!m[b.table.value].value.includes(f)),m[b.table.value].value=[])}),d()}catch(b){kb.alert(kb.error.parse(b)),B()}},fill:d=>{try{a.fill.value.map(b=>b.value).each((b,l)=>{b.table.value in c.fieldInfos.tables&&(f=>{f=kb.isNumeric(f)?parseInt(f)-m[b.table.value].value.length:0;0<f&&Array(f).fill().map(()=>kb.record.create(c.fieldInfos.origin[b.table.value],!1)).each((n,p)=>{e[b.table.value]==m[b.table.value]?e[b.table.value].value.push({value:n}):
(e[b.table.value].value.push({value:n}),m[b.table.value].value.push({value:n}))})})(kb.formula.calculate({field:{value:Object.values(c.fieldInfos.parallelize).first().code},formula:b.range},m,m,e,c.fieldInfos.parallelize))}),d()}catch(b){kb.alert(kb.error.parse(b)),B()}},formula:d=>{try{a.formula.value.map(b=>b.value).each((b,l)=>{b.field.value in c.fieldInfos.parallelize&&(f=>{f.tableCode?m[f.tableCode].value.each((n,p)=>{n.value[f.code].value=kb.formula.calculate(b,n.value,m,e,c.fieldInfos.parallelize);
f.lookup&&(n.value[f.code].lookup=!0)}):(m[f.code].value=kb.formula.calculate(b,m,m,e,c.fieldInfos.parallelize),f.lookup&&(m[f.code].lookup=!0))})(c.fieldInfos.parallelize[b.field.value])}),d()}catch(b){kb.alert(kb.error.parse(b)),B()}},lookup:d=>{try{a.lookupApp.value?kb.field.load(a.lookupApp.value).then(b=>{(l=>{var f=[],n=[],p=(x,C)=>{var F=(k,t)=>k.lookup?kb.extend({lookup:!0,type:k.type},t):kb.extend({type:k.type},t);kb.record.api.get(a.lookupApp.value,C.query,C.sort).then(k=>{0!=k.length?(t=>
{a.lookupLimited.value.includes("limited")||1==k.length?t(k.first()):c.picker.show({app:a.lookupApp.value,query:C.query,sort:C.sort,picker:f.reduce((G,z)=>{G[z.external.code]=z.external;return G},{})},G=>t(G))})(t=>{f.each((G,z)=>{if(a.lookupOverwrite.value.includes("overwrite")||kb.field.isEmpty(C.record[G.internal.code].value))C.record[G.internal.code]=F(G.internal,t[G.external.code])});x++;x<n.length?p(x,n[x]):(h.latest.action[a.sIndex.value].lookup=H(),d())}):(a.lookupReset.value.includes("reset")&&
f.each((t,G)=>{C.record[t.internal.code]=F(t.internal,kb.record.create({fields:{empty:t.internal}}).empty)}),x++,x<n.length?p(x,n[x]):(h.latest.action[a.sIndex.value].lookup=H(),d()))}).catch(k=>{kb.alert(kb.error.parse(k));B()})},H=()=>(x=>JSON.stringify(n.reduce((C,F)=>{C.push(F.query);C.push(kb.record.simplify({fields:x},F.record));return C},[])))(f.reduce((x,C)=>{x[C.internal.code]=C.internal;return x},{}));a.lookupCriteria.value.some(x=>!(x.value.external.value in l.external&&x.value.internal.value in
l.internal))?(kb.alert("No field to lookup was found"),B()):a.lookupMapping.value.some(x=>!(x.value.external.value in l.external&&x.value.internal.value in l.internal))?(kb.alert("No field to lookup was found"),B()):(f=a.lookupMapping.value.map(x=>({external:l.external[x.value.external.value],internal:l.internal[x.value.internal.value]})),n=(x=>x.map(C=>({query:a.lookupCriteria.value.reduce((F,k)=>{var t=l.external[k.value.external.value],G=k.value.operator.value;k=l.internal[k.value.internal.value];
var z=k.tableCode?C.value:e;a.lookupIgnore.value.includes("ignore")&&kb.field.isEmpty(z[k.code].value)||F.push(kb.filter.query.create(t,G,z[k.code]));return F},kb.filter.query.parse.expand({id:a.lookupApp.value,fields:b.origin},a.lookupFilter.value).map(F=>F.field+" "+F.operator+" "+F.value)).join(" and "),sort:(0!=a.lookupSort.value.length?a.lookupSort.value.map(F=>F.value.field.value+" "+F.value.order.value):["$id asc"]).join(","),record:C.value})))((x=>x?m[x].value:[{value:e}])(Array.from(new Set(f.map(x=>
x.internal.tableCode))).first())),0!=n.length?h.latest.action[a.sIndex.value].lookup&&h.latest.action[a.sIndex.value].lookup==H()?d():p(0,n.first()):d())})({external:b.origin,internal:c.fieldInfos.parallelize})}).catch(b=>{kb.alert(kb.error.parse(b));B()}):d()}catch(b){kb.alert(kb.error.parse(b)),B()}},user:d=>{try{if(a.userSource.value){var b=[],l=[],f=(p,H)=>{(C=>{b.each((F,k)=>{if(F.isCustom)switch(F.field.type){case "USER_SELECT":F.value=C.reduce((t,G)=>{"customItemValues"in G&&(z=>{0!=z.length&&
(u=>{(r=>{0!=r.length&&(t.some(O=>O.code==r.first().info.code)||t.push({code:r.first().info.code,name:r.first().info.name}))})(kb.roleSet.user.filter(r=>r.info.id==u))})(z.first().value)})(G.customItemValues.filter(z=>z.code==F.item));return Array.from(new Set(t)).filter(z=>z)},[]);break;default:F.value=C.reduce((t,G)=>{"customItemValues"in G&&(z=>{0!=z.length&&t.push(z.first().value)})(G.customItemValues.filter(z=>z.code==F.item));return Array.from(new Set(t)).filter(z=>z)},[]).join(",")}else switch(F.item){case "groups":case "organizations":F.value=
C.map(t=>t.code);break;case "primaryOrganization":F.value=C.reduce((t,G)=>{F.item in G&&(z=>{0!=z.length&&(t.some(u=>u.code==z.first().info.code)||t.push({code:z.first().info.code,name:z.first().info.name}))})(kb.roleSet.organization.filter(z=>z.info.id==G[F.item]));return t},[]);break;default:F.value=C.reduce((t,G)=>{F.item in G&&t.push(G[F.item]);return Array.from(new Set(t)).filter(z=>z)},[]).join(",")}})})(H[a.userSource.value].value.reduce((C,F)=>{(k=>{0!=k.length&&C.push(k.first().info)})(kb.roleSet.user.filter(k=>
k.info.code==F.code));return C},[]));var x=(C,F)=>{((k,t)=>{var G=(z,u,r)=>{kb.api(kb.api.url("/api/user/affiliations"),"GET",{code:k.value[z]}).then(O=>{switch(k.item){case "groups":O.groups&&(u=O.groups.reduce((v,I)=>{v.some(J=>J.code==I.code)||v.push({code:I.code,name:I.name});return v},u),z++,z<k.value.length?G(z,u,r):r(u));break;case "organizations":O.organizations&&(u=O.organizations.reduce((v,I)=>{v.some(J=>J.code==I.code)||v.push({code:I.code,name:I.name});return v},u),z++,z<k.value.length?
G(z,u,r):r(u))}}).catch(O=>kb.alert(kb.error.parse(O)))};a.userOverwrite.value.includes("overwrite")||kb.field.isEmpty(H[k.field.code].value)||t();switch(k.item){case "groups":case "organizations":0!=k.value.length?G(0,[],z=>{H[k.field.code].value=z;t()}):(H[k.field.code].value=k.value,t());break;default:H[k.field.code].value=k.value,t()}})(b[C],()=>{C++;C<b.length?x(C,F):F()})};x(0,()=>{p++;p<l.length?f(p,l[p]):(h.latest.action[a.sIndex.value].user=n(),d())})},n=()=>(p=>JSON.stringify(l.map(H=>kb.record.simplify({fields:p},
H))))(b.reduce((p,H)=>{p[H.field.code]=H.field;return p},(p=>{var H={};H[p]=c.fieldInfos.parallelize[p];return H})(a.userSource.value)));a.userCustomItem.value.some(p=>!(p.value.field.value in c.fieldInfos.parallelize))?(kb.alert("No field to user informations was found"),B()):a.userMapping.value.some(p=>!(p.value.field.value in c.fieldInfos.parallelize))?(kb.alert("No field to user informations was found"),B()):(a.userCustomItem.value.each((p,H)=>{b.push({isCustom:!0,item:p.value.item.value,field:c.fieldInfos.parallelize[p.value.field.value],
value:[]})}),a.userMapping.value.each((p,H)=>{b.push({isCustom:!1,item:p.value.item.value,field:c.fieldInfos.parallelize[p.value.field.value],value:[]})}),a.userPrimaryOrganization.value&&a.userPrimaryOrganization.value in c.fieldInfos.parallelize&&b.push({isCustom:!1,item:"primaryOrganization",field:c.fieldInfos.parallelize[a.userPrimaryOrganization.value],value:[]}),a.userOrganization.value&&a.userOrganization.value in c.fieldInfos.parallelize&&b.push({isCustom:!1,item:"organizations",field:c.fieldInfos.parallelize[a.userOrganization.value],
value:[]}),a.userGroup.value&&a.userGroup.value in c.fieldInfos.parallelize&&b.push({isCustom:!1,item:"groups",field:c.fieldInfos.parallelize[a.userGroup.value],value:[]}),l=(p=>p?m[p].value:[{value:e}])(c.fieldInfos.parallelize[a.userSource.value].tableCode).map(p=>p.value),0!=l.length?h.latest.action[a.sIndex.value].user&&h.latest.action[a.sIndex.value].user==n()?d():0!=b.length?f(0,l.first()):d():d())}else d()}catch(p){kb.alert(kb.error.parse(p)),B()}}};L.clear(()=>{L.fill(()=>{L.formula(()=>{L.lookup(()=>
{L.user(()=>{q()})})})})})}else q()}).catch(w=>{kb.alert(kb.error.parse(w));B()}):q()})((a=>{h.latest?h.latest.action||(h.latest.action={}):h.latest={action:{}};a.sIndex.value in h.latest.action||(h.latest.action[a.sIndex.value]={lookup:"[]",user:"[]"});return a})(A[D]))};M(0,()=>{N({record:e,performed:K!=JSON.stringify(kb.record.simplify({fields:c.fieldInfos.origin},e))})})});kb.field.load(kb.injector.app.id).then(A=>{c.app={id:kb.injector.app.id,fields:A.origin};c.fieldInfos=A;c.picker=new KintoneBoosterRecordPicker("record");
try{(e=>{if(0!=e.length){var h=(()=>{var N=e;"change"==g.pattern&&(N=e.filter(B=>(K=>"fields"in g?!K.first()||g.fields.some(M=>K.includes(M)):!K.first()||K.includes(g.field))(B.triggers.value.map(K=>K.value.field.value))));return N})();0!=h.length?P(h,g.record,g.container).then(N=>{g.stopPropagation&&(c.latest={record:JSON.stringify(kb.record.simplify({fields:A.origin},g.record)),time:(new Date).getTime()});g.performed=N.performed;y(g)}).catch(()=>y(g)):y(g)}else y(g)})(kb.plugin.action.reduce((e,
h)=>{h.event.value.includes(g.pattern)&&e.push(h);return e},[]))}catch(e){kb.alert(kb.error.parse(e)),y(g)}}).catch(A=>y(g))}else y(g)}));
kb.event.on("kb.cascade.call",g=>new Promise((y,R)=>{if(["create","edit"].includes(g.pattern))if(Array.isArray(kb.plugin.cascade)&&0!=kb.plugin.cascade.length){var c={},P=(A,e,h)=>new Promise((N,B)=>{var K=(M,D)=>{var E=(q,a)=>{var m=Object.keys(c.fieldInfos.parallelize[q.child.value].options);if(Array.isArray(a[q.parent.value].value)?0!=a[q.parent.value].value.length:a[q.parent.value].value)m=(Array.isArray(a[q.parent.value].value)?a[q.parent.value].value:[a[q.parent.value].value]).reduce((w,L)=>
w=[...(new Set([...w,...q.relation.value[L]]))],[]);return m};(q=>{(a=>{a.parent.tableCode?a.parent.tableCode in e&&e[a.parent.tableCode].value.each((m,w)=>{a.parent.code in m.value&&(m.value[a.child.code].options=E(q,m.value))}):a.parent.code in e&&(e[a.child.code].options=E(q,e))})({parent:c.fieldInfos.parallelize[q.parent.value],child:c.fieldInfos.parallelize[q.child.value]});M++;M<A.length?K(M,D):D()})(A[M])};K(0,()=>N())});kb.field.load(kb.injector.app.id).then(A=>{c.app={id:kb.injector.app.id,
fields:A.origin};c.fieldInfos=A;try{(e=>{0!=e.length?P(e,g.record,g.container).then(h=>y(g)).catch(()=>y(g)):y(g)})(kb.plugin.cascade.reduce((e,h)=>{h.parent.value in c.fieldInfos.parallelize&&h.child.value in c.fieldInfos.parallelize&&("string"===typeof h.relation.value&&(h.relation.value=JSON.parse(h.relation.value)),e.push(h));return e},[]))}catch(e){kb.alert(kb.error.parse(e)),y(g)}}).catch(A=>y(g))}else y(g);else y(g)}));
kb.event.on("kb.mail.call",g=>new Promise((y,R)=>{if(Array.isArray(kb.plugin.mail)&&0!=kb.plugin.mail.length){var c={},P=(A,e,h=!1)=>new Promise((N,B)=>{var K="",M=(D,E)=>{var q=()=>{D++;D<A.length?M(D,E):E()};(a=>{var m=kb.filter.scan(c.app,e,a.condition.value);m?kb.filter.auth(a.user.value,a.organization.value,a.group.value).then(w=>{if(w){var L=(d,b,l)=>{"HTML"==a.format.value&&(d=d.replace(/\r/g,"").replace(/\n/g,"<br>"));for(var f in b){var n=b[f].value;f in c.fieldInfos.parallelize&&("HTML"==
a.format.value&&"MULTI_LINE_TEXT"==c.fieldInfos.parallelize[f].type&&(n=n.replace(/\r/g,"").replace(/\n/g,"<br>")),d=d.replace(new RegExp("%"+f+"%","g"),kb.field.stringify(c.fieldInfos.parallelize[f],n," / ",!0)))}for(f in l)n=l[f].value,f in c.fieldInfos.parallelize&&("HTML"==a.format.value&&"MULTI_LINE_TEXT"==c.fieldInfos.parallelize[f].type&&(n=n.replace(/\r/g,"").replace(/\n/g,"<br>")),d=d.replace(new RegExp("%"+f+"%","g"),kb.field.stringify(c.fieldInfos.parallelize[f],n," / ",!0)));return d};
(d=>{var b=l=>{(f=>{var n=(p,H)=>{0!=f.attachment.length?kb.file.download(f.attachment[p],!0).then(x=>{kb.field.blobToBase64(x,C=>{f.attachment[p].data=C;p++;p<f.attachment.length?n(p,H):H()})}).catch(x=>{kb.alert(kb.error.parse(x));B()}):H()};n(0,()=>{kb.encrypt(JSON.stringify(f.data),K).then(p=>{var H=fetch,x="https://api.kintone-booster.com/mail/"+kb.operator.language,C=JSON,F=C.stringify;f.data=p.data;f.iv=p.iv;f.tag=p.tag;H(x,{method:"POST",headers:{"X-Requested-With":"XMLHttpRequest"},body:F.call(C,
f)}).then(k=>{k.json().then(t=>{switch(k.status){case 200:l++;l<d.length?b(l):q();break;default:kb.alert(kb.error.parse(t)),B()}})}).catch(k=>{kb.alert(kb.error.parse(k));B()})}).catch(p=>{B()})})})(d[l])};0!=d.length?b(0):q()})((()=>{var d=[];(c.fieldInfos.parallelize[a.to.value].tableCode?m[c.fieldInfos.parallelize[a.to.value].tableCode].value:[{value:m}]).each((b,l)=>{if(b.value[a.to.value].value){l=d.push;var f={mail:a.mail.value,sender:a.sender.value,host:a.host.value,port:a.port.value,author:a.author.value,
pwd:a.pwd.value,secure:a.secure.value,to:b.value[a.to.value].value,cc:L(a.cc.value,m,c.fieldInfos.parallelize[a.to.value].tableCode?b.value:{}),bcc:L(a.bcc.value,m,c.fieldInfos.parallelize[a.to.value].tableCode?b.value:{}),html:"HTML"==a.format.value},n=L(a.subject.value,m,c.fieldInfos.parallelize[a.to.value].tableCode?b.value:{}),p=L(a.body.value,m,c.fieldInfos.parallelize[a.to.value].tableCode?b.value:{}),H=[];a.attachment.value&&a.attachment.value in c.fieldInfos.parallelize&&(H=(c.fieldInfos.parallelize[a.attachment.value].tableCode?
b.value:m)[a.attachment.value].value);l.call(d,{data:f,subject:n,body:p,attachment:H})}});return d})())}else q()}).catch(w=>{kb.alert(kb.error.parse(w));B()}):q()})(A[D])};fetch("https://api.kintone-booster.com/mail/"+kb.operator.language,{method:"GET",headers:{"X-Requested-With":"XMLHttpRequest"}}).then(D=>{D.json().then(E=>{switch(D.status){case 200:K=E.passphrase;h||kb.loadStart();M(0,()=>{h||kb.loadEnd();N()});break;default:kb.alert(kb.error.parse(E)),B()}})}).catch(D=>{kb.alert(kb.error.parse(D));
B()})});kb.field.load(kb.injector.app.id).then(A=>{c.app={id:kb.injector.app.id,fields:A.origin};c.fieldInfos=A;try{(e=>{0!=e.length?P(e,g.record,!0).then(h=>y(g)).catch(()=>y(g)):y(g)})(kb.plugin.mail.reduce((e,h)=>{h.event.value.includes(g.pattern)&&e.push(h);return e},[]))}catch(e){kb.alert(kb.error.parse(e)),y(g)}}).catch(A=>y(g))}else y(g)}));
kb.event.on("kb.omail.call",g=>new Promise((y,R)=>{if(Array.isArray(kb.plugin.omail)&&0!=kb.plugin.omail.length){var c={},P=(A,e,h=!1)=>new Promise((N,B)=>{var K="",M=(D,E)=>{var q=()=>{D++;D<A.length?M(D,E):E()};(a=>{var m=kb.filter.scan(c.app,e,a.condition.value);m?kb.filter.auth(a.user.value,a.organization.value,a.group.value).then(w=>{if(w){var L=(d,b,l)=>{"HTML"==a.format.value&&(d=d.replace(/\r/g,"").replace(/\n/g,"<br>"));for(var f in b){var n=b[f].value;f in c.fieldInfos.parallelize&&("HTML"==
a.format.value&&"MULTI_LINE_TEXT"==c.fieldInfos.parallelize[f].type&&(n=n.replace(/\r/g,"").replace(/\n/g,"<br>")),d=d.replace(new RegExp("%"+f+"%","g"),kb.field.stringify(c.fieldInfos.parallelize[f],n," / ",!0)))}for(f in l)n=l[f].value,f in c.fieldInfos.parallelize&&("HTML"==a.format.value&&"MULTI_LINE_TEXT"==c.fieldInfos.parallelize[f].type&&(n=n.replace(/\r/g,"").replace(/\n/g,"<br>")),d=d.replace(new RegExp("%"+f+"%","g"),kb.field.stringify(c.fieldInfos.parallelize[f],n," / ",!0)));return d};
(d=>{var b=l=>{(f=>{var n=(p,H)=>{0!=f.attachment.length?kb.file.download(f.attachment[p],!0).then(x=>{kb.field.blobToBase64(x,C=>{f.attachment[p].data=C;p++;p<f.attachment.length?n(p,H):H()})}).catch(x=>{kb.alert(kb.error.parse(x));B()}):H()};n(0,()=>{kb.encrypt(JSON.stringify(f.data),K).then(p=>{var H=fetch,x="https://api.kintone-booster.com/mail/oauth/"+kb.operator.language,C=JSON,F=C.stringify;f.data=p.data;f.iv=p.iv;f.tag=p.tag;H(x,{method:"POST",headers:{"X-Requested-With":"XMLHttpRequest"},
body:F.call(C,f)}).then(k=>{k.json().then(t=>{switch(k.status){case 200:l++;l<d.length?b(l):q();break;default:kb.alert(kb.error.parse(t)),B()}})}).catch(k=>{kb.alert(kb.error.parse(k));B()})}).catch(p=>{B()})})})(d[l])};0!=d.length?b(0):q()})((()=>{var d=[];(c.fieldInfos.parallelize[a.to.value].tableCode?m[c.fieldInfos.parallelize[a.to.value].tableCode].value:[{value:m}]).each((b,l)=>{b.value[a.to.value].value&&d.push({data:{client_id:a.client_id.value,client_secret:a.client_secret.value,author:a.author.value,
sender:a.sender.value,subdomain:kb.operator.domain,provider:(f=>{f="";switch(a.provider.value){case "GMail":f="google";break;case "Exchange Online":f="microsoft"}return f})(a.provider.value),to:b.value[a.to.value].value,cc:L(a.cc.value,m,c.fieldInfos.parallelize[a.to.value].tableCode?b.value:{}),bcc:L(a.bcc.value,m,c.fieldInfos.parallelize[a.to.value].tableCode?b.value:{}),html:"HTML"==a.format.value},subject:L(a.subject.value,m,c.fieldInfos.parallelize[a.to.value].tableCode?b.value:{}),body:L(a.body.value,
m,c.fieldInfos.parallelize[a.to.value].tableCode?b.value:{}),attachment:(()=>{var f=[];a.attachment.value&&a.attachment.value in c.fieldInfos.parallelize&&(f=(c.fieldInfos.parallelize[a.attachment.value].tableCode?b.value:m)[a.attachment.value].value);return f})()})});return d})())}else q()}).catch(w=>{kb.alert(kb.error.parse(w));B()}):q()})(A[D])};fetch("https://api.kintone-booster.com/mail/oauth/"+kb.operator.language,{method:"GET",headers:{"X-Requested-With":"XMLHttpRequest"}}).then(D=>{D.json().then(E=>
{switch(D.status){case 200:K=E.passphrase;h||kb.loadStart();M(0,()=>{h||kb.loadEnd();N()});break;default:kb.alert(kb.error.parse(E)),B()}})}).catch(D=>{kb.alert(kb.error.parse(D));B()})});kb.field.load(kb.injector.app.id).then(A=>{c.app={id:kb.injector.app.id,fields:A.origin};c.fieldInfos=A;try{(e=>{0!=e.length?P(e,g.record,!0).then(h=>y(g)).catch(()=>y(g)):y(g)})(kb.plugin.omail.reduce((e,h)=>{h.event.value.includes(g.pattern)&&e.push(h);return e},[]))}catch(e){kb.alert(kb.error.parse(e)),y(g)}}).catch(A=>
y(g))}else y(g)}));
kb.event.on("kb.style.call",g=>new Promise((y,R)=>{if(Array.isArray(kb.plugin.style)&&0!=kb.plugin.style.length){var c={},P=(A,e,h)=>new Promise((N,B)=>{var K={},M=(D,E)=>{(q=>{var a=kb.filter.scan(c.app,e,q.condition.value);a?kb.filter.auth(q.user.value,q.organization.value,q.group.value).then(m=>{m&&(q.color.value.map(w=>w.value).each((w,L)=>{w.field.value in c.fieldInfos.parallelize&&(d=>{d.tableCode?d.tableCode in a&&a[d.tableCode].value.each((b,l)=>{d.code in b.value&&(b.value[d.code].backcolor=w.backcolor.value,
b.value[d.code].forecolor=w.forecolor.value)}):d.code in a&&(a[d.code].backcolor=w.backcolor.value,a[d.code].forecolor=w.forecolor.value)})(c.fieldInfos.parallelize[w.field.value])}),q.editable.value.map(w=>w.value).each((w,L)=>{w.field.value in c.fieldInfos.parallelize&&(d=>{c.fieldInfos.disables.includes(d.code)||(d.tableCode?d.tableCode in a&&(a[d.tableCode].value.each((b,l)=>{d.code in b.value&&(b.value[d.code].disabled="disable"==w.state.value)}),K[d.code]=e[d.tableCode].value.map(b=>b.value[d.code].disabled?
"disabled":"")):d.code in a&&(a[d.code].disabled="disable"==w.state.value,K[d.code]=e[d.code].disabled?"disabled":""))})(c.fieldInfos.parallelize[w.field.value])}),q.display.value.map(w=>w.value).each((w,L)=>{w.field.value in c.fieldInfos.groups?c.fieldInfos.groups[w.field.value].fields.map(d=>d.code).each((d,b)=>{d in c.fieldInfos.parallelize&&d in a&&(a[d].hidden="hide"==w.state.value)}):w.field.value in c.fieldInfos.tables?w.field.value in a&&(a[w.field.value].hidden="hide"==w.state.value):(d=>
{d.tableCode?d.tableCode in a&&a[d.tableCode].value.each((b,l)=>{d.code in b.value&&(b.value[d.code].hidden="hide"==w.state.value)}):d.code in a&&(a[d.code].hidden="hide"==w.state.value)})(c.fieldInfos.parallelize[w.field.value])}));D++;D<A.length?M(D,E):E()}).catch(m=>{kb.alert(kb.error.parse(m));B()}):(D++,D<A.length?M(D,E):E())})(A[D])};M(0,()=>{h.latest?h.latest.style||(h.latest.style="{}"):h.latest={style:"{}"};var D=JSON.stringify(K),E="{}"!=D?h.latest.style!=D:!1;E&&(h.latest.style=D);N({performed:E})})});
kb.field.load(kb.injector.app.id).then(A=>{c.app={id:kb.injector.app.id,fields:A.origin};c.fieldInfos=A;try{(e=>{0!=e.length?P(e,g.record,g.container).then(h=>{g.performed=h.performed;y(g)}).catch(()=>y(g)):y(g)})(kb.plugin.style.reduce((e,h)=>{h.page.value.includes(g.pattern)&&e.push(h);return e},[]))}catch(e){kb.alert(kb.error.parse(e)),y(g)}}).catch(A=>y(g))}else y(g)}));
kb.event.on("kb.submit.call",g=>new Promise((y,R)=>{if(Array.isArray(kb.plugin.submit)&&0!=kb.plugin.submit.length){var c={},P=(A,e,h=!1,N={})=>new Promise((B,K)=>{var M=[],D=(E,q)=>{var a=()=>{E++;E<A.length?D(E,q):q()};(m=>{kb.filter.scan(c.app,e,m.condition.value)?kb.filter.auth(m.user.value,m.organization.value,m.group.value).then(w=>{if(w){var L={duplicate:d=>{try{m.duplicateCriteria.value.some(b=>!(b.value.external.value in c.fieldInfos.parallelize&&b.value.internal.value in c.fieldInfos.parallelize))?
(kb.alert("No field to lookup was found"),K()):(b=>{b&&M.push(b);d()})(m.duplicateCriteria.value.reduce((b,l)=>{b.push(kb.filter.query.create(c.fieldInfos.parallelize[l.value.external.value],l.value.operator.value,e[c.fieldInfos.parallelize[l.value.internal.value].code]));return b},[]).join(" and "))}catch(b){kb.alert(kb.error.parse(b)),K()}},error:d=>{try{if(m.errorMessage.value||0!=m.errorField.value.length){var b=kb.filter.scan(c.app,e,m.errorFilter.value);b?(m.errorField.value.each((l,f)=>{l.value.field.value in
c.fieldInfos.parallelize&&(n=>{n.tableCode?b[n.tableCode].value.each((p,H)=>{p.value[l.value.field.value].error=l.value.message.value}):e[l.value.field.value].error=l.value.message.value})(c.fieldInfos.parallelize[l.value.field.value])}),h||kb.loadEnd(),B({error:!0,message:m.errorMessage.value})):d()}else d()}catch(l){kb.alert(kb.error.parse(l)),K()}},numbering:d=>{try{if(m.numberingField.value in c.fieldInfos.parallelize)if(e[m.numberingField.value].value)d();else{var b="",l=m.numberingGroup.value.reduce((f,
n)=>{if(n.value.field.value in c.fieldInfos.parallelize)switch(b+=e[n.value.field.value].value,c.fieldInfos.parallelize[n.value.field.value].type){case "DROP_DOWN":case "RADIO_BUTTON":f.push(n.value.field.value+' in ("'+e[n.value.field.value].value+'")');break;default:f.push(n.value.field.value+'="'+e[n.value.field.value].value+'"')}return f},"$id"in e?['$id!="'+e.$id.value+'"']:[]);b in N?(N[b]++,e[m.numberingField.value].value=b+N[b].toString().lpad("0",parseInt(m.numberingDigits.value)),d()):kb.api(kb.api.url("/api/records"),
"GET",{app:c.app.id,query:l.join(" and ")+" order by "+m.numberingField.value+" desc limit 1 offset 0"}).then(f=>{f=f.records;var n=0;0!=f.length&&(n=parseInt((f.first()[m.numberingField.value].value||" ").replace(/[ ]+/g,"").replace(new RegExp("^"+b,"g"),"")),kb.isNumeric(n)||(n=0));n++;f=n;N[b]=f;e[m.numberingField.value].value=b+f.toString().lpad("0",parseInt(m.numberingDigits.value));d()}).catch(f=>{kb.alert(kb.error.parse(f));K()})}else d()}catch(f){kb.alert(kb.error.parse(f)),K()}},prompt:d=>
{try{(b=>{0!=b.length?(l=>{b.each((f,n)=>{l.append(kb.field.activate(kb.field.create(f).css({width:"100%"}),c.app,!1))});h||kb.loadEnd();(new KintoneBoosterPopupform(l,600,"full",{ok:()=>{var f=kb.record.get(l,c.app,!0);b.each((n,p)=>{e[n.code].value=f.record[n.code].value});h||kb.loadStart();d()},cancel:()=>{h||kb.loadStart();d()}})).show()})(kb.create("div").addClass("kb-scope").attr("form-id","form_"+c.app.id)):d()})(m.promptField.value.reduce((b,l)=>{l.value.field.value in c.fieldInfos.parallelize&&
(m.promptOverwrite.value.includes("overwrite")?b.push(c.fieldInfos.parallelize[l.value.field.value]):kb.field.isEmpty(e[l.value.field.value].value)&&b.push(c.fieldInfos.parallelize[l.value.field.value]));return b},[]))}catch(b){kb.alert(kb.error.parse(b)),K()}},verify:d=>{try{(b=>{0!=b.length?(l=>{b.each((f,n)=>{l.append(kb.field.activate(kb.field.create(f).addClass("kb-readonly").css({width:"100%"}),c.app,!1))});kb.record.set(l,c.app,e);h||kb.loadEnd();(new KintoneBoosterPopupform(l,600,"full",{ok:()=>
{h||kb.loadStart();d()},cancel:()=>{h||kb.loadEnd();B({error:!0})}})).show()})(kb.create("div").addClass("kb-scope kb-verify").attr("form-id","form_"+c.app.id).append(kb.create("p").html(m.verifyMessage.value))):d()})(m.verifyField.value.reduce((b,l)=>{l.value.field.value in c.fieldInfos.parallelize&&b.push(c.fieldInfos.parallelize[l.value.field.value]);return b},[]))}catch(b){kb.alert(kb.error.parse(b)),K()}}};L.numbering(()=>{L.prompt(()=>{L.verify(()=>{L.error(()=>{L.duplicate(()=>{a()})})})})})}else a()}).catch(w=>
{kb.alert(kb.error.parse(w));K()}):a()})(A[E])};h||kb.loadStart();D(0,()=>{h||kb.loadEnd();0!=M.length?kb.api(kb.api.url("/api/records"),"GET",{app:c.app.id,query:((E,q)=>(q?"$id!="+q+" and ("+E+")":E)+" order by $id asc limit 5 offset 0")(M.map(E=>"("+E+")").join(" or "),"$id"in e?e.$id.value:"")}).then(E=>{0!=E.records.length?kb.confirm(kb.create("div").append(kb.create("p").css({margin:"0"}).html(kb.constants.submit.message.duplicate[kb.operator.language])),q=>{B({error:q})},!0):B({error:!1})}).catch(E=>
{kb.alert(kb.error.parse(E),()=>{B({error:!1})})}):B({error:!1})})});kb.field.load(kb.injector.app.id).then(A=>{c.app={id:kb.injector.app.id,fields:A.origin};c.fieldInfos=A;try{(e=>{0!=e.length?P(e,g.record,!0,g.numbering).then(h=>{h.error?(g.error=!0,h.message?kb.alert(h.message,()=>y(g)):y(g)):y(g)}).catch(()=>{g.error=!0;y(g)}):y(g)})(kb.plugin.submit.reduce((e,h)=>{h.event.value.includes(g.pattern)&&e.push(h);return e},[]))}catch(e){kb.alert(kb.error.parse(e)),y(g)}}).catch(A=>y(g))}else y(g)}));
kb.event.on("kb.upsert.call",g=>new Promise((y,R)=>{if(Array.isArray(kb.plugin.upsert)&&0!=kb.plugin.upsert.length){var c={},P=(A,e,h=!1)=>new Promise((N,B)=>{var K=(M,D)=>{var E=()=>{M++;M<A.length?K(M,D):D()};(q=>{var a=kb.filter.scan(c.app,e,q.condition.value);a?kb.filter.auth(q.user.value,q.organization.value,q.group.value).then(m=>{m?kb.field.load(q.app.value).then(w=>{var L={id:q.app.value,fields:w.origin};(d=>{var b=[],l=[],f=[],n={},p=1,H=1,x=0,C=0,F=()=>{var k=[],t={field:(u,r)=>{r=u.tableCode?
a[u.tableCode].value.length>r?a[u.tableCode].value[r].value[u.code]:kb.record.create({fields:{empty:mapping.internal}}).empty:a[u.code];return kb.extend({type:u.type},r)},record:u=>{H.each(r=>{var O=(v=>{var I=kb.filter.scan(L,u,v.query);if(!I&&"upsert"==q.pattern.value){for(var J in v.rows)0==kb.filter.result[J].value.length&&(u[J].value.push({value:kb.extend({},v.rows[J])}),kb.filter.result[J]={value:[u[J].value.last()]});I=kb.filter.result}return I})((()=>{var v={rows:{},query:[]};C=r;b.each((I,
J)=>{I.external.tableCode&&(I.external.tableCode in v.rows||(v.rows[I.external.tableCode]=kb.record.create(L.fields[I.external.tableCode],!1)),v.rows[I.external.tableCode][I.external.code]=G(I.external,t.field(I.internal,C)),v.query.push(kb.filter.query.create(I.external,I.operator,t.field(I.internal,C))))});l.each((I,J)=>{I.field.tableCode&&v.query.push(I.field.code+" "+I.operator+" "+I.value)});v.query=v.query.join(" and ");return v})());O&&f.each((v,I)=>{v.external.tableCode?v.external.tableCode in
n?(u[v.external.tableCode]={value:n[v.external.tableCode]},n[v.external.tableCode].each((J,Q)=>{J.value[v.external.code]=G(v.external,t.field(v.internal,Q));"FILE"==v.external.type&&J.value[v.external.code].value&&Array.prototype.push.apply(k,J.value[v.external.code].value)})):O[v.external.tableCode].value.each((J,Q)=>{J.value[v.external.code]=G(v.external,t.field(v.internal,C));"FILE"==v.external.type&&J.value[v.external.code].value&&Array.prototype.push.apply(k,J.value[v.external.code].value)}):
(u[v.external.code]=G(v.external,t.field(v.internal,x)),"FILE"==v.external.type&&u[v.external.code].value&&Array.prototype.push.apply(k,u[v.external.code].value))})});return u}},G=(u,r)=>{switch(u.type){case "CHECK_BOX":case "FILE":case "GROUP_SELECT":case "MULTI_SELECT":case "ORGANIZATION_SELECT":case "USER_SELECT":Array.isArray(r.value)||(r.value=[r.value])}r.type=u.type;return u.lookup?kb.extend({lookup:!0},r):r},z=u=>{u.each((r,O)=>{q.formula.value.each((v,I)=>{v.value.field.value in d.external&&
(J=>{J.tableCode?r[J.tableCode].value.each((Q,S)=>{Q.value[J.code].value=kb.formula.calculate(v.value,Q.value,r,r,d.external);J.lookup&&(Q.value[J.code].lookup=!0)}):(r[J.code].value=kb.formula.calculate(v.value,r,r,r,d.external),J.lookup&&(r[J.code].lookup=!0))})(d.external[v.value.field.value])})});return u};"insert"==q.pattern.value?(u=>{kb.file.clone(k,!0).then(()=>{kb.record.api.set(q.app.value,{post:u},h).then(r=>{x++;x<p?F():E()}).catch(r=>{kb.alert(kb.error.parse(r));B()})})})(z([t.record(kb.record.create(L))])):
kb.record.api.get(q.app.value,(()=>{var u=[];b.each((r,O)=>{r.external.tableCode||u.push(kb.filter.query.create(r.external,r.operator,t.field(r.internal,x)))});l.each((r,O)=>{r.field.tableCode||u.push(r.field.code+" "+r.operator+" "+r.value)});return u.join(" and ")})()).then(u=>{u=(r=>{var O=[];0!=r.length?O=r.map(v=>t.record(v)):"upsert"==q.pattern.value&&(v=>{O.push(t.record((()=>{var I=kb.record.create(L);v.each((J,Q)=>{J.external.tableCode?I[J.external.tableCode]={value:[]}:I[J.external.code]=
G(J.external,t.field(J.internal,x))});return I})()))})(b.filter(v=>!kb.field.reserved.includes(v.external.type)));return z(O)})(u);kb.file.clone(k,!0).then(()=>{kb.record.api.set(q.app.value,{post:u.filter(r=>!r.$id.value),put:u.reduce((r,O)=>{O.$id.value&&r.push(kb.record.api.transform(O));return r},[])},h).then(r=>{x++;x<p?F():E()}).catch(r=>{kb.alert(kb.error.parse(r));B()})})}).catch(u=>{kb.alert(kb.error.parse(u));B()})};q.mapping.value.some(k=>!(k.value.external.value in d.external&&k.value.internal.value in
d.internal))?(kb.alert("No field to transfer was found"),B()):q.criteria.value.some(k=>!(k.value.external.value in d.external&&k.value.internal.value in d.internal))?(kb.alert("No field to transfer was found"),B()):(q.mapping.value.each((k,t)=>{((G,z)=>{G.tableCode?n[G.tableCode]=(u=>{u=u?u.length:1;z.tableCode&&(u=u<a[z.tableCode].value.length?a[z.tableCode].value.length:u);return Array(u).fill().map(()=>({value:kb.record.create(L.fields[G.tableCode],!1)}))})(n[G.tableCode]):z.tableCode&&(p=0==a[z.tableCode].value.length?
0:p<a[z.tableCode].value.length?a[z.tableCode].value.length:p);f.push({external:G,internal:z})})(d.external[k.value.external.value],d.internal[k.value.internal.value])}),q.criteria.value.each((k,t)=>{t=d.external[k.value.external.value];var G=k.value.operator.value;k=d.internal[k.value.internal.value];t.tableCode?(t.tableCode in n&&delete n[t.tableCode],k.tableCode&&(H=H<a[k.tableCode].value.length?a[k.tableCode].value.length:H)):k.tableCode&&(p=0==a[k.tableCode].value.length?0:p<a[k.tableCode].value.length?
a[k.tableCode].value.length:p);b.push({external:t,operator:G,internal:k})}),kb.filter.query.parse.expand({id:q.app.value,fields:w.origin},q.filter.value).each((k,t)=>{l.push({field:d.external[k.field],operator:k.operator,value:k.value})}),0!=p?(C=x=0,F()):E())})({external:w.parallelize,internal:c.fieldInfos.parallelize})}).catch(w=>{kb.alert(kb.error.parse(w));B()}):E()}).catch(m=>{kb.alert(kb.error.parse(m));B()}):E()})(A[M])};h||kb.loadStart();K(0,()=>{h||kb.loadEnd();N()})});kb.field.load(kb.injector.app.id).then(A=>
{c.app={id:kb.injector.app.id,fields:A.origin};c.fieldInfos=A;try{(e=>{0!=e.length?P(e,g.record,!0).then(h=>y(g)).catch(()=>y(g)):y(g)})(kb.plugin.upsert.reduce((e,h)=>{h.event.value.includes(g.pattern)&&e.push(h);return e},[]))}catch(e){kb.alert(kb.error.parse(e)),y(g)}}).catch(A=>y(g))}else y(g)}));
kb.constants=kb.extend({submit:{message:{cancel:{process:{en:"The process action was canceled.",ja:"\u30d7\u30ed\u30bb\u30b9\u30a2\u30af\u30b7\u30e7\u30f3\u304c\u30ad\u30e3\u30f3\u30bb\u30eb\u3055\u308c\u307e\u3057\u305f\u3002",zh:"\u8fdb\u7a0b\u64cd\u4f5c\u5df2\u88ab\u53d6\u6d88\u3002","zh-TW":"\u7a0b\u5e8f\u64cd\u4f5c\u5df2\u88ab\u53d6\u6d88\u3002"},submit:{en:"The submit was canceled.",ja:"\u4fdd\u5b58\u304c\u30ad\u30e3\u30f3\u30bb\u30eb\u3055\u308c\u307e\u3057\u305f\u3002",zh:"\u4fdd\u5b58\u5df2\u88ab\u53d6\u6d88\u3002",
"zh-TW":"\u63d0\u4ea4\u5df2\u88ab\u53d6\u6d88\u3002"}},duplicate:{en:"A similar record already exists. Would you like to proceed with the registration anyway?",ja:"\u985e\u4f3c\u30ec\u30b3\u30fc\u30c9\u304c\u65e2\u306b\u767b\u9332\u3055\u308c\u3066\u3044\u307e\u3059\u304c\u3001\u3053\u306e\u307e\u307e\u767b\u9332\u3057\u3066\u3082\u5b9c\u3057\u3044\u3067\u3059\u304b\uff1f",zh:"\u5df2\u7ecf\u6709\u7c7b\u4f3c\u7684\u8bb0\u5f55\u5b58\u5728\u4e86\uff0c\u60a8\u8fd8\u8981\u7ee7\u7eed\u6ce8\u518c\u5417\uff1f",
"zh-TW":"\u5df2\u6709\u985e\u4f3c\u7684\u8a18\u9304\u5b58\u5728\uff0c\u60a8\u9084\u8981\u7e7c\u7e8c\u8a3b\u518a\u55ce\uff1f"}}}},kb.constants);
